UKGovernmentBEIS/beis-report-official-development-assistance

- .env.example
- .env.test
- README.md
- address all but 1 TODO generated by the rails-template we have used to generate this repository
- the remaining one must remain until we have live environments to point to
- use the name `roda` as it is shorter and therefore more manageable than the full name
> Address TODOs generated by rails-template

- .travis.yml
- Gemfile
- Gemfile.lock
- heroku.yml
- automatic container deployment on staging when merges to `develop` 
- automatic container deployment to production when merges to `master` - this was done to help facilitate testing as production wasn't being used
- fix Heroku container deployment problem. Containers would be built successfully but then fail during the release phase due to [some low level compiler errors similar to this](https://github.com/sass/sassc-ruby/issues/133). On investigation we tracked down a [commit that added standard.rb](https://github.com/dxw/rails-template/commit/dbc14a6e943f7f9baa3804a0d5946b0ad5c4879c) in our rails-template, this change bumped the version of the sass compiler to `2.2.1`. When reverting this change the release then succeeds so to fix the problem we lock `sassc` to the minor version …
> Deploy to staging (and production) with containers

- bin/setup
- config/application.rb
- config/cable.yml
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- config/puma.rb
- config/spring.rb
Remove the Rails 5.2 defaults that were still being used, because dxw's rails template was originally built from this version.
> (84) Application uses Rails 6 defaults

- doc/architecture/decisions/0008-use-heroku-for-hosting.md
We switched on Heroku without recording why so we are retroactively documenting this. 
Even if the choice of hosting on Heroku is intended to be short term our team doesn't have control of how long this will be the case, we are dependant on other teams within BEIS. We should record why we have done this to preserve the rationale for future teams and future questions.
> Record decision to use Heroku

- app/views/staff/organisations/show.html.haml
- config/locales/en.yml
During the demo on 12/11/2019 I noticed that the i18n strings on the Organisation
show page were not correct. Due to a clash between the `en.yml` and `iati.yml`
the labels for these fields were not being rendered correctly.
`en.yml` had `organisation.language_code` while `iati.yml` had multiple
`organisation.language_code.*` entries; as a result `organisation.language_code`
did not render correctly (the fallback to 'Language Code' was used).
> Fix: correct I18n strings

- .gitignore
- spec/spec_helper.rb
Uncomment the `config.example_status_persistence_file_path` setting in RSpec. 
This allows us to run *only* failing specs using `rspec --only-failures`.
> Allow failing specs to be run in isolation

- config/environments/test.rb
There's a bug with the way Spring interacts with Rails 6. The original workaround was to set `cache_classes = false` which causes the test suite to run a *lot* slower, particularly when using Capybara.
An alternative workaround is to use the classic autoloader rather than Zeitwerk (default in Rails 6), which allows the faster `cache_classes = true` whilst preventing the annoying reloading errors.
The issue is documented here: https://github.com/rails/spring/issues/598
> (fix) Prevent test suite 'reloading is disabled' error

- README.md
- db/seeds.rb
* A user is required to add more users. Use the Seed file to create a local copy of the information stored in Auth0 for our generic team user roda@dxw.com.
* This user is only in the development tenant and is isolated from staging and production. Sharing the identifier in plain text should be safe to do.
> Setup includes a seeded user to allow us to sign in locally

- app/views/staff/dashboards/show.html.haml
- config/locales/en.yml
- spec/features/staff/users_can_create_an_organisation_spec.rb
- spec/features/staff/users_can_view_all_organisations_spec.rb
- spec/features/staff/users_can_view_an_organisation_spec.rb
Trello: https://trello.com/c/mrW7IAqI/93-users-can-navigate-to-organisation-pages-without-changing-the-url
Add navigation to the Organisation pages without having to change the URL. Also amend the Organisation-related feature tests to use the new navigation steps.
> Add navigation to Organisations page(s) to the dashboard

- config/environments/production.rb
When viewing an activity, the locale lookups are failing with key not found. This works as intended in development and test but it turns out that this configuration overrides that made by us in application.rb. 
This configuration is not overridden in the development or test environment files, so we remove this production specific config to allow the application.rb version to take affect across all envs.
> IATI locale fallback is used in production

- app/views/layouts/application.html.haml
Because this is gov.uk service we need to include crown copyright logo in the footer.
Because this is gov.uk service we need to include crown copyright logo in the footer.
> (97) Add crown copyright logo to the footer

- app/assets/javascripts/application.js
This was being initialised in out application layout, but wasn't being loaded into the asset pipeline. This change fixes that and enables JS features that help with accessibility https://github.com/alphagov/govuk-frontend/blob/master/docs/installation/installing-with-npm.md#using-javascript.
> GOV.UK Frontend JS is enabled

- Gemfile
- Gemfile.lock
- app/controllers/staff/users_controller.rb
- app/views/staff/users/new.html.haml
- config/initializers/form_builder.rb
- config/locales/generic_validation_errors.en.yml
- config/locales/models_and_forms.en.yml
- doc/architecture/decisions/0011-use-govuk-design-system-form-builder.md
- doc/i18n.md
- spec/features/staff/users_can_invite_new_users_spec.rb
Use `govuk_design_system_formbuilder` gem to replace `simple_form` starting with the user creation form. This has been [written by DfE](https://github.com/DFE-Digital/govuk_design_system_formbuilder) to adapt the standard Rails form builder to generate markup that's 100% compliant with the [GOVUK Design System](https://design-system.service.gov.uk/)
This change should make it much easier to build forms without having to use lots of boilerplate code to make it work.
Because we are currently using the *Simple Form* form builder for the majority of our forms, the two can co-exist until we have to time to switch all forms over.
> (105) Refactor user creation form with "govuk_design_system_formbuilder" 

- app/views/staff/activities/show.html.haml
- app/views/staff/activity_forms/everything.html.haml
- app/views/staff/funds/index.html.haml
- app/views/staff/funds/new.html.haml
- app/views/staff/funds/show.html.haml
- app/views/staff/organisations/index.html.haml
- app/views/staff/organisations/new.html.haml
- app/views/staff/organisations/show.html.haml
- app/views/staff/users/index.html.haml
- app/views/staff/users/new.html.haml
- app/views/staff/users/show.html.haml
Following the design system page template back links are stand alone links and don’t need to be wrapped in paragraphs. This is removing the paragraphs. more read https://design-system.service.gov.uk/styles/page-template/
- removed paragraphs from back links
No UI changes, but here's an example from [gov.uk design system page template](https://design-system.service.gov.uk/styles/page-template/)
> Remove paragraph wrap from back links

- app/views/staff/activities/show.html.haml
- app/views/staff/funds/show.html.haml
- app/views/staff/organisations/show.html.haml
- app/views/staff/users/show.html.haml
After removing bootstrap the definition lists reverted to browser’s default styling, which didn’t look good.
Added gov.uk classes to the definition list and now they are more clear and use ‘summary-list’ component.
> Add gov.uk styles to definition lists

- config/initializers/sidekiq.rb
Looks like in the major verison bump from 5. to 6. the API for configuring logging changed https://github.com/mperham/sidekiq/wiki/Logging#api-changes - this means that our deployments are failing due to our logging config only being applied in the production environment
This new instruction documents how we would do configure sidekiq logging to avoid lots of verbose logging https://github.com/mperham/sidekiq/wiki/Logging#default-logger-and-verboseness this is a concern as our papertrail limit may quickly disappear due to retrying jobs.
> Sidekiq logging configuration updated for version 6.x

- app/services/create_user.rb
- spec/services/create_user_spec.rb
Now the `user` object is sent to the mailing service (rather than an ID) there is always an initial error from Sidekiq when the user is created.
The error happens when a user is successfully created but the mailer is called before the user record is persisted to the database, due to the use of the transaction block.
When the mailer recieves the object, it tries to call `id` on it and fails with a serialisation error. This is due to the fact no ID has been created and we are dealing with a object in memory only.
Added a missing happy path test on my way through.
> Welcome emails are only sent after the user is persisted

- CHANGELOG.md
- app/controllers/staff/users_controller.rb
- app/models/user.rb
- app/policies/user_policy.rb
- app/services/update_user.rb
- app/services/update_user_in_auth0.rb
- app/views/staff/shared/users/_table.html.haml
- app/views/staff/users/_form.html.haml
- app/views/staff/users/edit.html.haml
- app/views/staff/users/new.html.haml
- config/locales/en.yml
- spec/features/staff/users_can_edit_existing_users_spec.rb
- spec/policies/user_policy_spec.rb
- spec/services/update_user_in_auth0_spec.rb
- spec/services/update_user_spec.rb
- spec/support/auth0_helpers.rb
- Create a new 'fund manager' role, who can manage users
- Allow users to be edited (by administrators or fund managers only). Any changes to `name` or `email` are synchronised to Auth0.
> (90) Edit a user

- app/views/staff/shared/activities/_activity.html.haml
ActivityPresenter returns the i18n string for the Fund's Tied Status so there
is no need to get the internationalized string in the view
> (Fix) Correct display of a Fund's Tied Status on Fund#show

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/controllers/staff/funds_controller.rb
- app/controllers/staff/transactions_controller.rb
- app/helpers/activity_helper.rb
- app/views/staff/funds/_form.html.haml
- app/views/staff/funds/edit.html.haml
- app/views/staff/funds/index.html.haml
- app/views/staff/funds/new.html.haml
- app/views/staff/funds/show.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- config/locales/en.yml
- config/routes.rb
- spec/features/staff/users_can_create_a_transaction_spec.rb
- spec/features/staff/users_can_create_an_activity_spec.rb
- spec/features/staff/users_can_edit_a_fund_spec.rb
- spec/features/staff/users_can_view_a_fund_spec.rb
- spec/features/staff/users_can_view_an_activity_spec.rb
- spec/helpers/activity_helper_spec.rb
**Important - this change is based on https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/75 so requires that to be agreed and merged first** 
- remove fund level routing that didn't require an organisation
- refactor `simple_form` out of the form new form
- allow the `fund` record to be edited. Note this change does not include editing the associated `activity` record to keep this proposal small, however I imagine the edit journey will be very similar. The links for activity edit will go to `ActivityFormController` rather than `FundController`
> 104 Users can edit a fund

- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/notifications.css.scss
- app/views/layouts/_messages.html.haml
We know we need to give more design thought to this however we can improve the state of what we currently have since the removal drastically in a few minutes.
Dismiss button doesn't work without bootstrap styling so rather than spend more time fixing it, it's removed for now. The flashes should all disappear as they navigate away. The previous experience was a button that didn't do anything so this improves it by removing what's broken.
This style can sit as a placeholder for all types of flash until we do https://trello.com/c/mPauGcJ0
> Minimal flash message styling (temporary)

- app/controllers/staff/funds_controller.rb
- app/controllers/staff/organisations_controller.rb
- spec/features/staff/users_can_view_transactions_on_fund_page_spec.rb
Trello: https://trello.com/c/LsOoYdS6/150-only-show-transactions-for-the-given-fund-rather-than-all
On the Fund#show page we were showing all Transactions for the given _Organisation_, not just the ones for that Fund. This corrects that error.
> (150) Only show transactions for the given Fund on Fund page

- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/notifications.css.scss
- app/assets/stylesheets/partials/_alerts.css.scss
- app/views/layouts/_messages.html.haml
Introduces different alert styling based on the type of alert: success, notice or danger.
Based on research and examples of gov.uk services using alerts, links are attached in the trello card:
https://trello.com/c/mPauGcJ0
> Style alert messages, move styles into partials

- CHANGELOG.md
- app/helpers/activity_helper.rb
- app/views/staff/activities/show.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- spec/features/staff/users_can_create_an_activity_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/helpers/activity_helper_spec.rb
- spec/rails_helper.rb
- spec/support/form_helpers.rb
- each activity field has an edit link that can be used to take the user to that step in the existing activity form journey
- once on the right step of the journey, the user can update the field's value and will have to continue through the journey or press 'back' to go backwards. Using the same flow for create and edit has trade-offs that I hope to documented on the commits.
- refactor the edit URLs to be open to extension for more hierarchies to keep this as open to extension as possible. Issues were had in trying to use `url_for` for the polymorphic routes and in a way that is compatible with the routing requirements of the Wicked gem. I'd love to make this better and remove the concatonation if there are suggestions!
> 154 Edit all activity fields

- app/controllers/staff/activities_controller.rb
- app/controllers/staff/activity_forms_controller.rb
- app/views/staff/activity_forms/_wrapper.html.haml
- config/routes.rb
* Although we aren't adding programmes and other levels of the `hierarchy` yet, I was trying to consider how to implement editing an activity in a future proof way. This led me to do this refactoring which I think is useful in isolation to make it easier to extend.
* Provide comments for guidance to increase confidence when we do these extensions.
* Use routing `concerns` to avoid repeating the nested resource blocks for each hierarchy and to ensure that the right configuration is managed centrally eg. `only: [:destroy]`
Prefer:
```
concern :activity do
resources :activities, only: [:new, :create, :show] do
resources :steps, controller: "activity_forms"
end
end
concern :transactionable do
resources :transactions, only: [:new, :create, :show]
end
resources :funds, only: [], concerns: …
```
> Activity record creation is decoupled from working only with Funds

- CHANGELOG.md
- app/controllers/staff/transactions_controller.rb
- app/helpers/form_helper.rb
- app/models/organisation.rb
- app/models/transaction.rb
- app/views/staff/funds/edit.html.haml
- app/views/staff/transactions/_form.html.haml
- app/views/staff/transactions/edit.html.haml
- app/views/staff/transactions/new.html.haml
- config/environments/test.rb
- config/initializers/form_builder.rb
- config/locales/en.yml
- config/locales/models_and_forms.en.yml
- db/migrate/20191213123607_add_provider_and_receiver_org_to_transactons.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/transaction.rb
- spec/features/staff/users_can_edit_a_transaction_spec.rb
- spec/helpers/form_helper_spec.rb
- spec/models/organisation_spec.rb
- spec/support/form_helpers.rb
- transactions require 2 new fields: provider and receiver
- these fields are currently required and we can make it optional if the users are unable to succeed. This ensures we have a chance of having pristine data from the start given that this data will help us score well on transparency
- this proposal includes a tricky patch for the govuk form builder to ensure error messages are shown ontop of association fields. I wonder if there is an easier way to do this? If not, I hope it is extendable for when we have to add more associations for participating organisations in future. More info on the commit
- there is no room to put this new information in the transactions table as a new horizontal column. Until we have redesigned this page or implemented an individual transaction#show page we …
> 151 Transactions capture provider and reciever organisation

- .travis.yml
- Dockerfile
See https://dashboard.heroku.com/apps/beis-roda-production release v69 and below
> Lock Rake to v13.0.1 to fix Heroku deployment issue

- CHANGELOG.md
- app/controllers/staff/activities_controller.rb
- app/controllers/staff/activity_forms_controller.rb
- app/helpers/activity_helper.rb
- app/helpers/codelist_helper.rb
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/views/staff/activity_forms/aid_type.html.haml
- app/views/staff/activity_forms/country.html.haml
- app/views/staff/activity_forms/finance.html.haml
- app/views/staff/activity_forms/flow.html.haml
- app/views/staff/activity_forms/sector.html.haml
- app/views/staff/activity_forms/status.html.haml
- app/views/staff/activity_forms/tied_status.html.haml
- app/views/staff/organisations/_form.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- app/views/staff/transactions/_form.html.haml
- config/locales/en.yml
- db/migrate/20191217160336_add_wizard_status_to_activity.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/factories/fund.rb
- spec/features/staff/users_can_create_an_activity_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/helpers/activity_helper_spec.rb
- spec/helpers/codelist_helper_spec.rb
- spec/models/activity_spec.rb
- spec/presenters/activity_presenter_spec.rb
Trello: https://trello.com/c/GiHeA5QU/122-add-validations-to-activity-multi-step-form
* Implement validations on the Activity form. All fields are required (except dates) but the user can add them in their own time, but only in one order.
* Add a helper which hides the "Edit" links for fields on the fund#show page which have not been filled in yet, *unless* those fields form part of the next Wizard step. This encourages the user to fill the form out from start to finish. 
* If a field has not been filled out yet, the CTA is "Add". If it's been filled in before, the CTA is "Edit", so the user knows the attributes can be edited.
* Default attributes are presented in the select boxes but are no longer automatically saved onto the record. We found that a consequence of this prior design that …
> (122) Add validations to Activity multi-step form

- app/views/staff/shared/transactions/_table.html.haml
- config/locales/models_and_forms.en.yml
- spec/features/staff/users_can_view_transactions_on_fund_page_spec.rb
- spec/support/form_helpers.rb
Trello: https://trello.com/c/VqODQmSn/171-add-receiver-and-provider-org-to-the-transaction-table
* Add the Provider org and Receiver org names to the Transaction table on fund#show
> (171) Add receiver and provider organisation to the transaction table

- app/controllers/auth0_controller.rb
- app/views/auth0/failure.html.haml
- config/locales/en.yml
- spec/features/staff/users_can_sign_in_spec.rb
* When Oauth redirects the user to the standard /failure endpoint we now give the user a styled page that has an error message and a prompt as to what to do next.
* We don't have a support contact yet so omit it. We will need this before going live.
> (136) Users see a styled and informative sign in error message

- spec/features/staff/users_can_view_all_organisations_spec.rb
Removing this skipped test as, from looking at `OrganisationPolicy`, we are not
restricting any Organisations from being viewed by users.
> Remove skipped test

- lib/tasks/default.rake
This is a tiny quality of life improvement that makes the default rake task run in the order specified.
By default the rspec configuration always loads the specs first so the`spec` task here is ignored.
By clearing the default task prerequisites and then adding (enhancing) in order we get the expected behaviour.
As someone who often slips up with formatting, this means I don't have to wait for all the specs to run before finding out I have a formatting issue, which saves time.
> Chore to run default rake tasks in expected order

- app/assets/stylesheets/partials/_forms.css.scss
The checkbox ovewriting styles where probably added when the app was using bootstrap to compensate for inconsistent look. Removing them fixes this and allows the app to use default gov.uk styling for checkboxes.
> Remove old styling to keep gov.uk defults

- app/helpers/activity_helper.rb
- spec/factories/activity.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/helpers/activity_helper_spec.rb
- spec/presenters/activity_presenter_spec.rb
Trello comment which alerted us to this: https://trello.com/c/J9fiyVbh/143-add-transaction-information-an-activity-xml#comment-5dfcf58bdad0708e3adc8425
Some Activities in the staging db have a nil Wizard Status as they were added
before we added the `wizard_status` field. Handle this in the code - show all
fields in the Fund#show page if the `wizard_status` is nil
Raised by this error on staging:
```
Dec 23 09:26:39 beis-roda-staging app/web.1: F, [2019-12-23T09:26:39.234730 #8] FATAL -- : [e04e1584-e2fc-41b6-9799-c5532736f449]   
Dec 23 09:26:39 beis-roda-staging app/web.1: [e04e1584-e2fc-41b6-9799-c5532736f449] ActionView::Template::Error (undefined method `to_sym' for nil:NilClass):
Dec 23 09:26:39 beis-roda-staging app/web.1: [e04e1584-e2fc-41b6-9799-c5532736f449]     20: …
```
> Bugfix - Show all steps if Activity has a nil `wizard_status`

- Gemfile
- Gemfile.lock
Swap the plain 'pry' gem for 'pry-rails', so it's used instead of IRB for the Rails console by default, which makes debugging much nicer.
> Use 'pry' when debugging on the rails console

- CHANGELOG.md
- config/environments/production.rb
NB: This redirects non-SSL requests to their SSL equivalents, forces secure cookies and enables HSTS (which means browsers will *never* visit the non-SSL version of the site after the first visit).
> (113) Force SSL in production environments

- CHANGELOG.md
- app/controllers/staff/users_controller.rb
- app/helpers/form_helper.rb
- app/models/user.rb
- app/views/staff/shared/users/_table.html.haml
- app/views/staff/users/_form.html.haml
- app/views/staff/users/show.html.haml
- config/locales/en.yml
- config/locales/models_and_forms.en.yml
- spec/features/staff/users_can_edit_a_user_spec.rb
- spec/features/staff/users_can_invite_new_users_spec.rb
- spec/features/staff/users_can_view_other_users_spec.rb
- spec/models/user_spec.rb
- Shows the users role on the index and show pages
- Allows a user with the correct permission to choose the users role when creating or updating a user
https://trello.com/c/UoCQvLew
> (81) Admins can assign roles to users

- .github/pull_request_template.md
`- [ ] Is a changelog entry required? An entry should always be made in `CHANGELOG.md`, unless this PR is a small tweak which has` __NO__ ` impact outside the development team.`
> Fix a typo in the PR template which was annoying me

- doc/architecture/decisions/0006-use-auth0-for-authentication.md
To cover the decision to use the 'Classic' login views from Auth0 which
offer the best balance between user experience and technical debt in the
service.
> Chore/Update Auth0 ADR to include Classic views

- CHANGELOG.md
- app/controllers/staff/funds_controller.rb
- app/controllers/staff/programmes_controller.rb
- app/models/fund.rb
- app/models/organisation.rb
- app/models/programme.rb
- app/policies/programme_policy.rb
- app/views/staff/funds/show.html.haml
- app/views/staff/organisations/show.html.haml
- app/views/staff/programmes/new.html.haml
- app/views/staff/programmes/show.html.haml
- config/locales/en.yml
- config/locales/models_and_forms.en.yml
- config/routes.rb
- db/migrate/20200115114151_create_programme.rb
- db/schema.rb
- spec/factories/programme.rb
- spec/features/staff/fund_managers_can_create_a_programme_spec.rb
- spec/features/staff/fund_managers_can_view_a_programme_spec.rb
- spec/models/fund_spec.rb
- spec/models/programme_spec.rb
- spec/policies/programme_policy_spec.rb
Trello: https://trello.com/c/s1HLTajb/201-fund-managers-can-create-a-basic-programme
Fund managers can create a basic Programme with a name and Fund & Organisation associations.
The list of Programmes is shown on the Fund page.
> Fund managers can create a basic programme

- spec/spec_helper.rb
Run the simplecov test coverage locally, in addition to it being run on CI. This will allow us to observe coverage drops before raising a PR.
I've configured it so in most everyday scenarios, you shouldn't get a test coverage report when only running a small number of specs/files.
Additionally, it writes an HTML version of the coverage report into `coverage/index.html` for reference. NB: this directory has already been added to `.gitignore`.
**NB: We've historically been calling simplecov with its default profile rather than the Rails one. I've done the same here as it changes the coverage result considerably, but might be something we want to consider using**
> (218) Developers see test coverage warnings locally

- CHANGELOG.md
- app/models/user.rb
- spec/features/staff/fund_managers_can_invite_new_users_spec.rb
Co-authored-by: Lorna <lorna@dxw.com>
- user email addresses are validated before being sent to Auth0, this handles an unexpected error since Auth0 requires emails to be in a valid format
> The user form validates if an email looks real

- CHANGELOG.md
- app/controllers/staff/activities_controller.rb
- app/helpers/activity_helper.rb
- app/models/programme.rb
- app/policies/activity_policy.rb
- app/views/staff/programmes/show.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- config/routes.rb
- spec/features/staff/fund_managers_can_create_a_programme_spec.rb
- spec/features/staff/users_can_create_an_activity_spec.rb
- spec/helpers/activity_helper_spec.rb
- spec/models/programme_spec.rb
- spec/policies/activity_policy_spec.rb
- spec/policies/programme_policy_spec.rb
Trello: https://trello.com/c/Y2x07ws7/202-fund-managers-can-create-a-programme-activity
Allow Fund Managers to add additional information to a Programme via an attached Activity (and activity form)
The activity form journey for a Programme is exactly the same as that for a Fund. This will need to be looked at in future, as some of the form defaults for Programmes may not be the same as for Funds.
Additionally, there are some TODOs in this PR around how we handle polymorphic links between Funds -> Organisations, and Programmes -> Funds, for example in `activity_helper.rb`
> Fund managers can create a programme activity

- app/presenters/activity_presenter.rb
- app/views/staff/shared/activities/_activity.html.haml
- config/locales/en.yml
- spec/features/staff/users_can_view_an_activity_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/support/time_helpers.rb
We have set  a default date format in translation locale. Added presenters for all the fund activity dates and included tests checking if those specific dates are in a human readable format.
We used ruby travel_to helper method in our tests to ensure that they will continue to pass without being dependent on a current date.  Especially becaue we know that activity dates are validated to be within a certain time frame.
We thought about using strftime in our helper, but then we realised it would’ve been duplicated in a lot of places. Therefore setting the date format in locale file means we don’t need to worry about using locale in the views for an activity and it will be easier to change our time formats in the future.
Co-authored-by: Tom <tomhipkin@gmail.com>
> Dates updated to have human readable format as default

- db/migrate/20200116172705_add_service_owner_to_organisations.rb
- db/schema.rb
- spec/models/organisation_spec.rb
This change re-adds a feature that has already been merged into develop once before https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/141. During the [refactor of the activity hierarchy](https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/154) the original work was deliberately force pushed away.
This original work has been rebased on top of the new develop so it is now compatible with the new architecture.
cture.
> Provide a way to flag an organisation as BEIS

- app/models/user.rb
- spec/features/staff/fund_managers_can_invite_new_users_spec.rb
Re-adding the changes that have previously been merged in #143 but were knowingly removed during a recent refactor that had to force develop back in time.
> Re-add the user form validates if an email looks real

- app/views/staff/organisations/show.html.haml
- spec/features/staff/users_can_view_an_organisation_spec.rb
https://trello.com/c/S1w9OyXP/214-all-user-roles-are-taken-to-the-organisation-show-page-rather-than-a-dashboard#comment-5e3453bb0232ed133ea28d48
Adding the word "Organisation" from the organisation page title was confusing -
two people on product have pointed out that it's unnecessary. Just show the name
of the organisation as the page title.
> Remove the word "Organisation" from the organisation show page title

- CHANGELOG.md
- app/controllers/staff/activities_controller.rb
- app/controllers/staff/organisations_controller.rb
- app/controllers/staff/programmes_controller.rb
- app/helpers/activity_helper.rb
- app/models/activity.rb
- app/views/staff/activities/show.html.haml
- app/views/staff/organisations/show.html.haml
- config/locales/en.yml
- config/routes.rb
- db/migrate/20200130144115_add_activity_reference_to_activity.rb
- db/schema.rb
- spec/features/staff/fund_managers_can_create_a_programme_level_activity_spec.rb
- spec/features/staff/fund_managers_can_view_fund_level_activities_spec.rb
- spec/features/staff/fund_managers_can_view_programme_level_activity_spec.rb
- spec/helpers/activity_helper_spec.rb
- spec/models/activity_spec.rb
Programme level activities can be added to a fund level activity. The programme level activities are only shown on the fund level activity show page to which they belong.
All Activities are still shown on their `orgnaisation/:id/activity/:id` paths.
The back link used on the activity show pages now knows on which level it is used and can provide the 'parent' activity – this feels like a bit of a quick fix – but I didn't want to go down a rabbit hole of how the system will work in the future - the back links work for this scope of work!
I've added a foriegn key constraint to the activity association to stop 'parent' activities being deleted when they still have 'children' – I wasn't 100% that this is:
- the behaviour we want in the model
- the right way to declare and test this
so please …
> Fund managers can add and view programme level actvities

- CHANGELOG.md
- app/controllers/staff/activities_controller.rb
- app/controllers/staff/budgets_controller.rb
- app/helpers/form_helper.rb
- app/models/budget.rb
- app/policies/budget_policy.rb
- app/presenters/budget_presenter.rb
- app/views/staff/activities/show.html.haml
- app/views/staff/budgets/_form.html.haml
- app/views/staff/budgets/new.html.haml
- app/views/staff/shared/budgets/_table.html.haml
- config/locales/en.yml
- config/locales/models_and_forms.en.yml
- config/routes.rb
- db/migrate/20200122150646_create_budgets.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/factories/budget.rb
- spec/features/staff/users_can_create_a_budget_spec.rb
- spec/features/staff/users_can_view_budgets_on_an_activity_page_spec.rb
- spec/models/budget_spec.rb
- spec/policies/budget_policy_spec.rb
- spec/presenters/budget_presenter_spec.rb
Trello: https://trello.com/c/GcJI6seX/142-add-budgets-to-a-programme
Fund managers can create Budgets on an Activity.
Budgets can only be created against Programme Activities. Budgets are not listed on Fund Activity show pages, and if the user tries to create a Budget against a fund, they will see an error message.
> (142) Add Budgets

- app/controllers/staff/activity_forms_controller.rb
- app/helpers/activity_helper.rb
- app/models/activity.rb
- config/locales/en.yml
- spec/factories/activity.rb
- spec/features/staff/fund_managers_can_edit_an_activity_spec.rb
- spec/features/staff/fund_managers_can_view_fund_level_activities_spec.rb
- spec/helpers/activity_helper_spec.rb
- spec/models/activity_spec.rb
- spec/presenters/activity_presenter_spec.rb
@mec says:
I've picked this up whilst @leeky was on a support sprint.
The work changed once we refactored the model and was only about returning the user to the appropriate place when editing an activity.
- when the activity is complete, the user edits an attribute and returns to the activity summary view
- when the activity is incomplete, the user edits or adds an attribute they continue the stepped form flow.
I also found some of the Actvity factory traits weren't reflecting the behaviour of the model so took the opportunity to update them:
Becuase an Activity can now have a nil identifier attribute when the `wizard_step` is 'identifier' some specs were updated to use the 'purpose' step as this better reflects the state of the activity under test i.e. has a 'identifier' value set.
I've …
> (204) Editing a complete activity form returns to the activity

- app/presenters/transaction_presenter.rb
- spec/presenters/transaction_presenter_spec.rb
- spec/support/form_helpers.rb
Added a presenter for a transaction that turns the date into a readable format.
Renamed the spec form helper date method to be more specific and used the local translation inside the method to remove the repetition.
> Transactions have human readable dates

- CHANGELOG.md
- app/controllers/staff/funds_controller.rb
- app/controllers/staff/programmes_controller.rb
- app/services/create_fund_activity.rb
- app/services/create_programme_activity.rb
- app/views/staff/shared/xml/_activity.xml.haml
- db/migrate/20200203140136_add_funding_organisation_details_to_activities.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/features/staff/fund_managers_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/fund_managers_can_create_a_programme_level_activity_spec.rb
- spec/features/staff/fund_managers_can_view_an_activity_as_xml_spec.rb
- spec/services/create_fund_activity_spec.rb
- spec/services/create_programme_activity_spec.rb
Trello: https://trello.com/c/LZjMGZPu/227-activities-collect-information-about-the-participating-organisations-that-provides-the-funds-funder
Add the Funding Organisation information to an Activity. For now, this is a hard-coded set of information, which differs depending on whether the Activity is a programme or fund activity. 
Eventually we will make this information something the Fund managers can choose, but for now it is static.
> (227) Activities collect information about participating organisations that provide the funds

- CHANGELOG.md
- app/services/create_fund_activity.rb
- app/services/create_programme_activity.rb
- app/views/staff/shared/xml/_activity.xml.haml
- db/migrate/20200204115513_add_accountable_organisation_details_to_activities.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/features/staff/fund_managers_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/fund_managers_can_create_a_programme_level_activity_spec.rb
- spec/features/staff/fund_managers_can_view_an_activity_as_xml_spec.rb
- spec/services/create_fund_activity_spec.rb
- spec/services/create_programme_activity_spec.rb
Trello: https://trello.com/c/9gobZxRi/261-activities-collect-information-about-the-participating-organisations-that-are-accountable
Add Accountable Organisation details to Activity records. These are `participating-org` organisations with a `@role` of 2, according to IATI.
Currently these values are hardcoded for MVP, but eventually they will be selectable.
> (261) Activities collect information about accountable participating organisations

- CHANGELOG.md
- app/services/create_fund_activity.rb
- app/views/staff/shared/xml/_activity.xml.haml
- db/migrate/20200205105914_add_extending_organisation_details_to_activities.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/features/staff/fund_managers_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/fund_managers_can_view_an_activity_as_xml_spec.rb
Trello: https://trello.com/c/Isi8Hlay/262-fund-activities-share-their-extending-organisation-in-iati-xml
Add extending organisation details to fund activities in much the same way as #175 and #173. However in this PR we are only adding default extending organisation details to _funds_, not _programmes_, as the extending organisation for a programme is a little more involved. This will follow in a future PR.
I have also refactored the XML feature test as it was getting unwieldy. I think in this new format it will be easier to add "unhappy" paths if we need them.
> (262) Fund activities share their extending organisation in IATI XML

- .github/pull_request_template.md
- app/models/activity.rb
- app/views/staff/activities/show.xml.haml
- app/views/staff/shared/xml/_activity.xml.haml
- doc/xml-validation.md
- spec/features/staff/fund_managers_can_view_an_activity_as_xml_spec.rb
- spec/models/activity_spec.rb
Trello: https://trello.com/c/f0sswz5n/275-validate-the-activity-records-with-the-iati-validator-and-put-necessary-changes-into-sprint-backlog
We have run the existing Activity XML through the new validator (https://test-validator.iatistandard.org/) and as a result:
* Empty elements are now self-closing
* `provider-org` elements do not show if they are empty
* Required attributes have been added (with one exception - see below)
* Elements have been re-ordered as per the IATI standard
The `reporting-org` element requires a `@ref` attribute but we don't currently collect that on the Organisation model. We have opened https://trello.com/c/pJaaUq1B/295-organisations-must-have-their-iati-reference-number to address this.
Also we have added a new check to the pull request template, to prompt …
> (275) Validate the activity records with the IATI validator

- CHANGELOG.md
- config/locales/models_and_forms.en.yml
Added hint text to date form fields for an activity, budget and a transaction.
During our testing the date form fields turned out to be not clear on what values are expected for the month part. It wasn’t clear that the date input expects a number and not a month name.
Now with a hint text this should be more descriptive.
Next todo’s:
There should be more hint text work around dates added to include guidance around planned and actual dates
> Add hint text to date form fields

- app/helpers/user_helper.rb
- spec/helpers/user_helper_spec.rb
This spec failed a couple of times but mostly passes so I took a look
over it.
As we cannot guarantee the order entities from an `all` query the match
could fail if the order came back differently, which we have no control
over.
We could've used `match_array` if the order didn't matter, but I think
it makes sense that, where this is used, the organisations are listed in
alphabetical order.
I've changed the implementation to use the existing `sorted_by_name`
scope, which gives us the organisations in alphabetical order.
I also tweaked the spec now that the order matters.
> Fix flakey user helper

- CHANGELOG.md
- app/controllers/staff/transactions_controller.rb
- app/models/transaction.rb
- app/views/staff/shared/transactions/_table.html.haml
- app/views/staff/shared/xml/_transaction.xml.haml
- app/views/staff/transactions/_form.html.haml
- config/locales/en.yml
- config/locales/models_and_forms.en.yml
- db/migrate/20200213150213_add_provider_and_receiver_fields_to_transaction.rb
- db/migrate/20200213152249_remove_association_between_transaction_and_organisation.rb
- db/migrate/20200213161657_add_references_to_transaction_providers_and_receivers.rb
- db/schema.rb
- spec/factories/transaction.rb
- spec/features/staff/users_can_create_a_transaction_spec.rb
- spec/features/staff/users_can_edit_a_transaction_spec.rb
- spec/features/staff/users_can_view_an_activity_as_xml_spec.rb
- spec/features/staff/users_can_view_transactions_on_an_activity_page_spec.rb
- spec/models/transaction_spec.rb
- spec/support/form_helpers.rb
- Refactor how users add providing and receiving organisation details when creating transactions
- Ask the user for the organisational references for use in IATI and output the result of this value into IATI if present
- Organisation `references` for providers and receivers are optional. IATI requires either `name` or `ref` and our hypothesis is that of the 2, our users should be able to more easily provide a name of the company they are sending money to rather than their full IATI reference which is a challenging thing to work out. This was confirmed with users when we tested it on our google prototype.
- The `(optional)` string is included in the form headers in line with the [GDS design system guidance  that suggests instead of marking mandatory fields, mark the ones that are not …
> (245) transactions can store arbitrary reciever and providing orgs

- CHANGELOG.md
- app/controllers/staff/budgets_controller.rb
- app/controllers/staff/projects_controller.rb
- app/helpers/activity_helper.rb
- app/models/activity.rb
- app/services/create_project_activity.rb
- app/views/staff/activities/show.html.haml
- app/views/staff/shared/projects/_table.html.haml
- config/locales/en.yml
- config/routes.rb
- spec/factories/activity.rb
- spec/features/staff/users_can_create_a_budget_spec.rb
- spec/features/staff/users_can_create_a_project_spec.rb
- spec/features/staff/users_can_edit_an_actviity_spec.rb
- spec/features/staff/users_can_view_a_project_spec.rb
- spec/models/activity_spec.rb
- spec/services/create_project_activity_spec.rb
In #184 although @lozette amazing work and determination got us a working feature, the team were concerned about the debt we were building up around user roles and authorisation.
In order to deliver a this feature we decided to re-scope the work and remove the authorisation altogether. By doing so any user signed in to the service can be thought of as an 'Administator' for the moment and can perform create, update and edit actions on all activity levels.
We know we have work to do to authorise users and activities, but we can deliver this feature in a managable chunk of work that raises little debt and can be reviewed easily.
All the work here is taken from @lozette previous work.
This PR enables users to:
- create any number of projects as children of a programme
- view the details of …
> (270) Users can report project level activities

- CHANGELOG.md
- app/presenters/budget_xml_presenter.rb
- app/views/staff/activities/show.xml.haml
- app/views/staff/shared/xml/_activity.xml.haml
- app/views/staff/shared/xml/_budget.xml.haml
- config/locales/en.yml
- spec/factories/activity.rb
- spec/features/staff/users_can_view_an_activity_as_xml_spec.rb
- spec/presenters/budget_presenter_spec.rb
- spec/presenters/budget_xml_presenter_spec.rb
- spec/support/shared_examples/behaves_like_valid_activity_xml_spec.rb
Trello: https://trello.com/c/o0YNJlMt/281-add-budgets-to-xml
Budgets are added to the Activity XML as per the IATI standard: http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/budget/
The budget XML passes validation (see https://test-validator.iatistandard.org/view/dqf/files/ba982acc-8187-4885-989c-50bff12c4fd6?isTestfiles=true) but there are some errors in the Activity XML which are not related to budgets.
See also https://trello.com/c/anTHm0iW/301-budget-periods-cannot-be-more-than-1-year
> (281) Add Budgets to XML

- .github/pull_request_template.md
Before this change, when clicking the link from a GitHub pull request it broke.
The link path was:
https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/doc/xml-validation.md
Notice the `/pull/doc/`? I assume the relative syntax we've got works from the context of the app but doesn't work from the context of a pull request?
Here's an old pull request where you can test the bug https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/189
An absolute link is prone to breaking if we change our master branch or move the file. In which case a pointer to documentation that exists is still useful even if the link breaks.
> Pull request links to IATI validator documentation

- CHANGELOG.md
- config/locales/en.yml
- spec/features/staff/users_can_create_a_budget_spec.rb
- spec/features/staff/users_can_view_budgets_on_an_activity_page_spec.rb
Trello: https://trello.com/c/RsLTbcF2/280-users-can-add-a-budget-to-a-fund
Previously we believed a budget could not be directly attached to a fund. This
turned out not to be true, so we have removed the restrictions which stopped
a budget from being created on a fund.
> (280) Remove restrictions that stopped a budget from being attached to a fund

- Dockerfile
On the PaaS when puma attempts to start it will try to write a pid to
`tmp/pids/server.pid` if it can't it will error and stop.
```
2020-02-20T15:05:47.77+0000 [APP/PROC/WEB/0] ERR bundler: failed to load command: puma (/usr/local/bundle/ruby/2.6.0/bin/puma)
2020-02-20T15:05:47.77+0000 [APP/PROC/WEB/0] ERR Errno::ENOENT: No such file or directory @ rb_sysopen - tmp/pids/server.pid
```
> Create tmp/pids so that puma can start

- CHANGELOG.md
- app/controllers/staff/budgets_controller.rb
- app/models/budget.rb
- app/presenters/budget_presenter.rb
- app/views/staff/budgets/_form.html.haml
- app/views/staff/shared/budgets/_table.html.haml
- app/views/staff/shared/xml/_budget.xml.haml
- config/locales/en.yml
- db/migrate/20200224141519_add_currency_to_budgets.rb
- db/schema.rb
- spec/factories/budget.rb
- spec/features/staff/users_can_create_a_budget_spec.rb
- spec/features/staff/users_can_view_budgets_on_an_activity_page_spec.rb
- spec/models/budget_spec.rb
- spec/presenters/budget_presenter_spec.rb
- spec/support/shared_examples/behaves_like_valid_activity_xml.rb
Trello: https://trello.com/c/hVAX9Jrc/319-budgets-should-collect-a-currency-like-transactions
Collect the currency information for a Budget using the generic currency
codelist.
Output the budget currency in the XML.
> (319) Budgets collect currency information much like Transactions

- app/models/transaction.rb
- app/presenters/transaction_presenter.rb
- app/validators/date_not_in_future_validator.rb
- config/locales/models_and_forms.en.yml
- spec/factories/activity.rb
- spec/features/staff/users_can_create_a_transaction_spec.rb
- spec/features/staff/users_can_edit_a_transaction_spec.rb
- spec/models/transaction_spec.rb
- spec/presenters/transaction_presenter_spec.rb
- spec/support/form_helpers.rb
- spec/validators/date_not_in_future_validator_spec.rb
Trello: https://trello.com/c/6XaRLaol/316-transactions-cannot-be-set-to-a-future-date
When testing with the IATI validator we realised that Transactions with a date in the future are not valid according to the IATI standard. This PR adds validations to the Transaction model which means a transaction cannot be saved if its date is in the future.
> (316) Transactions cannot be set to a future date

- CHANGELOG.md
- app/controllers/staff/activities_controller.rb
- app/controllers/staff/implementing_organisations_controller.rb
- app/models/activity.rb
- app/models/implementing_organisation.rb
- app/presenters/implementing_organisation_presenter.rb
- app/views/staff/activities/show.html.haml
- app/views/staff/implementing_organisations/edit.html.haml
- app/views/staff/implementing_organisations/new.html.haml
- app/views/staff/shared/activities/_implementing_organisations.html.haml
- app/views/staff/shared/implementing_organisations/_table.html.haml
- app/views/staff/shared/xml/_activity.xml.haml
- config/locales/en.yml
- config/locales/models_and_forms.en.yml
- config/routes.rb
- db/migrate/20200213143837_create_implementing_organisations.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/factories/implementing_organisation.rb
- spec/features/staff/users_can_manage_implementing_organisations_spec.rb
- spec/features/staff/users_can_view_an_activity_as_xml_spec.rb
- spec/models/activity_spec.rb
- spec/models/implementing_organisation_spec.rb
- spec/presenters/implementing_organisation_presenter_spec.rb
- spec/support/shared_examples/behaves_like_valid_activity_xml.rb
Trello: https://trello.com/c/VwXXIspE/269-activities-collect-one-or-more-implementing-organisations
@mec did 99% of this PR, I'm just finishing it for him!
Project-level activities can now have multiple implementing organisations. These are expressed in the IATI XML as `participating-org[@role='4']`
Implementing organisations attributes are free-text fields. Because implementers can be any organisation anywhere in the world (not necessarily registered on this platform) we rely on the delivery partners filling in these details themselves.
Validated here: https://test-validator.iatistandard.org/view/dqf/files/4e82520b-38b5-462f-86d8-f020af58c1e2?isTestfiles=true
> (269) Activities collect one or more implementing organisations

- config/initializers/vcap_services.rb
- lib/vcap_parser.rb
- spec/lib/vcap_parser_spec.rb
GPaaS provides a VCAP_SERVICES environment variable which contains JSON
with information about services bound to the application.
From the JSON we need to extract the REDIS_URL and any other environment
variables we have put into a user provided service.
This is based on the work we had done for CCS RMI
https://github.com/dxw/DataSubmissionServiceAPI/pull/376 and others
> Extract env vars from VCAP_SERVICES

- Gemfile
- Gemfile.lock
GPaaS currently only provides redis 3.2 which is not supported by
sidekiq 6 therefore we should use a version of sidekiq 5.
Sidekiq 5.2.8 is the latest released version but that downgrades rack to
2.0.9. We decided that for the week that we need to use sidekiq 5 we
don't need the patches provided by 5.2.8 and would prefer not to use an
old version of rack therefore we are pinning to 5.2.7
> Pin sidekiq to 5.2.7

- CHANGELOG.md
- app/controllers/staff/activities_controller.rb
- app/models/activity.rb
- app/presenters/activity_xml_presenter.rb
- app/services/create_fund_activity.rb
- app/services/create_programme_activity.rb
- app/services/create_project_activity.rb
- app/views/staff/activities/show.xml.haml
- app/views/staff/shared/xml/_activity.xml.haml
- db/migrate/20200225155754_add_reporter_reference_to_activity.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/factories/organisation.rb
- spec/features/staff/users_can_view_an_activity_as_xml_spec.rb
- spec/models/activity_spec.rb
- spec/presenters/activity_xml_presenter_spec.rb
- spec/services/create_fund_activity_spec.rb
- spec/services/create_programme_activity_spec.rb
- spec/services/create_project_activity_spec.rb
- spec/support/shared_examples/behaves_like_valid_activity_xml.rb
The `iati-identifier` field that is output in the Activity XML has had 2 updates.
1. It now includes the reporting organisation reference to that it passes the validator. This change involved an important decision on how we deal with changes to organisation iati references against the requirement by IATI for these to always remain unchanged. Feedback would be great on this, more info in the commit!
2. It can include up 2 to more prefixes to the activity identifier part itself. This maps our internal hierarchy and how we ask for identifiers at the different levels back to what BEIS currently publish to IATI. This change is more controversial as it's not required to produce valid IATI but it is required to keep it consistent with BEIS publishing. I've left more info on the commit that added …
> (318) Activitity XML includes reporting org in identifier

- config/application.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
ActiveStorage in default configuration created valid routes that allowed files to be uploaded. We do not intend for files to be uploaded to the application as local files so this can be removed.
If we do want to add file upload in the future we may add this back however it will very likely use a third party document store given the ephemeral nature of Docker containers.
This change also removes action_mailbox routes with allows the application to recieve incoming emails. https://guides.rubyonrails.org/action_mailbox_basics.html This is not appropriate now and I cannot imagine when this would be appropriate.
> Reduce the attack footprint by removing unused rails ties

- .travis.yml
- travis-docker-push.sh
We will be deploying to the PaaS using docker images so push an image for
each branch that gets tested in travis and a unique docker tag consisting
of branch, build number and commit.
> Push docker images to docker hub for every branch

- travis-docker-push.sh
You can not have a '/' in a docker tag because it uses it to separate org
and repo
```
invalid argument "thedxw/beis-report-official-development-assistance:feature/287-create-ability-to-make-a-user-eg-delivery-partner-inactive-in-the-application" for "-t, --tag" flag: invalid reference format
```
We often use '/' in branch names which causes this error.
We are using this tag to make sure we have a unique tag for deployments
so TRAVIS_BUILD_NUMBER and TRAVIS_COMMIT will suffice.
> Remove TRAVIS_BRANCH from docker tag

- travis-docker-push.sh
Only tag the built image with $TAG created from $TRAVIS_BUILD_NUMBER and
$TRAVIS_COMMIT
You can not have a '/' in a docker tag because it uses it to separate org
and repo
```
invalid argument "thedxw/beis-report-official-development-assistance:feature/287-create-ability-to-make-a-user-eg-delivery-partner-inactive-in-the-application" for "-t, --tag" flag: invalid reference format
```
We often use '/' in branch names which causes this error.
We are using this tag to make sure we have a unique tag for deployments
so TRAVIS_BUILD_NUMBER and TRAVIS_COMMIT will suffice.
> Build and Push just an image tagged $TAG

- CHANGELOG.md
- app/controllers/auth0_controller.rb
- app/controllers/staff/users_controller.rb
- app/helpers/form_helper.rb
- app/views/staff/shared/users/_table.html.haml
- app/views/staff/users/_form.html.haml
- app/views/staff/users/show.html.haml
- config/locales/en.yml
- db/migrate/20200303120754_add_active_status_to_users.rb
- db/schema.rb
- spec/factories/user.rb
- spec/features/staff/beis_users_can_edit_a_user_spec.rb
- spec/features/staff/beis_users_can_view_other_users_spec.rb
- spec/features/staff/users_can_sign_in_spec.rb
Trello: https://trello.com/c/L6bIzPW7/287-create-ability-to-make-a-user-eg-delivery-partner-inactive-in-the-application
BEIS users can mark other users as active or inactive. The GOVUK design system prefers yes/no type options to be presented as radio buttons as opposed to a single checkbox, for clarity (see https://govuk-form-builder.netlify.com/form-elements/checkboxes/#generating-a-single-checkbox )
An inactive user will still have an Auth0 account, they just cannot access the RODA service.
> (287) BEIS users can mark other users (i.e. delivery partner users) as active or inactive

- CHANGELOG.md
- app/models/budget.rb
- app/validators/budget_dates_validator.rb
- config/locales/models_and_forms.en.yml
- spec/features/staff/users_can_create_a_budget_spec.rb
- spec/models/budget_spec.rb
- spec/validators/budget_date_validator_spec.rb
The IATI standard requires that budget start and end dates be validated
as follows:
- start date must not be after end date
- end date not more than one year after start date
http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/budget/
We spent some time attempting to make a generic validator for these two
validations but in the end decided that a validator specifically for
budget was the simplest and most elegant solution until we need to reuse
this validation criteria.
We decided that as the validation requirements are clearly defined by
IATI, by wrapping them up in a validator we keep all of the elements to
carry out the validation together in one place.
The interface and associated challenges that went with a generic solution felt quite messy to us and …
> (301) Budget dates are validated

- db/seeds.rb
- db/seeds/activity.rb
- db/seeds/organisations.rb
- db/seeds/organisations.yml
- db/seeds/users.rb
Trello: https://trello.com/c/pcdbxmEM/320-seed-the-database-with-known-delivery-partners-and-beis-itself
- Reorganise the seeds into individual files for organisation/users/activities
- Run the seeds in order (organisations first, as users & activities depend on them)
- Create the organisations from a YAML file
- Add a second generic delivery partner user (login details in the 1password vault as usual)
One deficiency here is that if we wish to update an organisation's IATI identifier in
the `organisations.yml` file we will have to drop all the organisations and re-seed them.
But I'm not sure of a better attribute to `find_or_create_by` than iati_reference?
> (231) Seed the database with delivery partner organisations & BEIS, and common user accounts

- config/locales/en.yml
- spec/features/staff/users_can_edit_an_activity_spec.rb
Small fix that I noticed in previous work that I didn't want to push into the same pull request. 
We could probably refactor these flash messages to reuse the same locale by allowing variables to be passed in but that felt improvement like like a rabbit hole and a step too far.
> Fix update activity message not working for projects

- .travis.yml
- deploy-terraform.sh
Add a script to run terraform which will deploy the app to staging and production
The script will also set up a PaaS space to run the app.
This PR also adds linting of our shell scripts.
This PR relies on https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/233 being merged.
> Deploy to the PaaS from travis

- app/controllers/staff/users_controller.rb
- app/views/staff/shared/users/_table.html.haml
- spec/features/staff/beis_users_can_view_other_users_spec.rb
Trello: https://trello.com/c/nD7e6PG9/415-add-organisation-name-to-the-user-list
Show the user's organisation name in the user list. Group the users by their organisation name.
> Show the user's organisation name in the users#index page

- CHANGELOG.md
- app/controllers/staff/activities_controller.rb
- app/policies/project_policy.rb
- app/views/staff/activities/show.html.haml
- app/views/staff/shared/activities/_projects.html.haml
- config/locales/en.yml
- spec/features/staff/users_can_view_a_project_spec.rb
- spec/policies/project_policy_spec.rb
Trello: https://trello.com/c/AEowjwGK/417-add-a-button-to-make-it-easier-for-beis-users-ie-dan-sparks-to-export-xml-data-on-a-per-project-basis
Allow BEIS users to download a project activity XML via the click of a button.
Because previously BEIS users were not able to view projects, we have allowed them to access projects on a read-only basis (they can view but not create/update them). BEIS users can navigate to the project page and click "Download as XML" to download the IATI XML for the project.
Non-BEIS users cannot see the "Download as XML" button.
> (417) Allow BEIS users to download projects as XML

- .travis.yml
Remove CI error caused by running `rake db:setup` when a database already exists. Whilst it doesn't seem to exit the testing process it does produce noise so when something does go wrong we see this error and aren't confident what's related and what's not.
It seems that the docker-entrypoint was already running prepare and these 2 invocations of the same command were treading on each others toes!
> CI runs don't error when a database already exists

- CHANGELOG.md
- app/helpers/codelist_helper.rb
- spec/fixtures/codelist_with_withdrawn_items.yml
- spec/helpers/codelist_helper_spec.rb
- vendor/data/codelists/IATI/2_03/activity/sector.yml
Trello: https://trello.com/c/ozGnGd0z/297-choosing-a-sector-for-an-activity-presents-the-user-with-duplicate-options
When creating an activity, we noticed that some of the Sector options were duplicated.
It soon became apparent that some of the codelist items from IATI are marked as "status: withdrawn". IATI marks items as withdrawn to indicate they are deprecated: https://support.iatistandard.org/hc/en-us/articles/214390846-Add-a-withdrawn-flag-to-code-names-to-indicate-deprecation
First, we amended the CodelistHelper to only put codelist items into the dropdowns if they are not marked as withdrawn. 
However, we still had two duplicates - two entries for "Rural development" which were marked as "status: active". Following discussion with the service owner, we decided to amend one of the …
> (297) Choosing a Sector for an Activity presents the user with duplicate options

- app/controllers/staff/users_controller.rb
- app/models/result.rb
- app/services/create_user.rb
- config/locales/en.yml
- spec/features/staff/beis_users_can_invite_new_users_spec.rb
- spec/services/create_user_spec.rb
- spec/support/auth0_helpers.rb
Trello: https://trello.com/c/falHEEs2/286-address-bug-when-email-address-has-already-been-used-to-create-a-user-in-auth0
Previously, we were showing a generic error message when user creation failed in
Auth0. Now, we will attempt to parse the error message received from Auth0 and
show it to the user. If the error message is unparseable, a generic error will
be shown.
> (286) Show actual Auth0 error when user creation fails

- .travis.yml
Using `set -e` at the top of the script ensures that if one of the
following commands errors the script will stop and return an exit code
of not zero which will let CI know that something has failed.
Otherwise a command will fail during the script but Travis thinks
everything is green.
Also set `u` so if a variable is unbound it will also error out.
> Stop running the test script when a command errors

- app/views/staff/activity_forms/purpose.html.haml
- config/locales/en.yml
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_create_a_programme_level_activity_spec.rb
- spec/features/staff/users_can_create_a_project_spec.rb
- spec/support/form_helpers.rb
Trello: https://trello.com/c/OWw5dOUE
Addressing the feedback from user research, during the creation of an activity the form step for 'Purpose' needed to be dynamically populated with the level of the activity. That would work as a reminder for users that what they are creating is either a fund, a programme or a project.
In order to achieve this, I have added that activity level to the yaml file so it could be displayed in the view for the purpose step. After doing that and checking all the tests were passing and the view on the browser was actually what I wanted to be, I realised that the page title on the browser tab was displaying
`Purpose of %{level}` (see image attached at the bottom of this section) instead of being dynamically populated. I believe this page title comes from a meta …
> Purpose of activity is now dynamic

- .travis.yml
- deploy-terraform.sh
- install-terraform-provider-for-cf.sh
- use our own script to download the cloud foundry terraform provider
- do terraform testing in the terraform directory
- remove the heroku deploys
> make terraform testing more reliable

- CHANGELOG.md
- Activity status is now shown as radio buttons with hints
- Activity XML includes 'iati-identifier' which is includes the reporting organisation
- Activity XML includes 'iati-identifier' with an identifier that consists of all present levels of hierarchy: fund and/or programme
- BEIS users (administrators) can mark other users as active or inactive
- Budget start and end dates are validated according to IATI standard
- BEIS users can view projects (read-only) and download them as XML via a button
- Codelist dropdowns do not contain values which have been marked as "status: withdrawn" by IATI
- Redis version increased from 3.x to 4.x now that GPaaS supports it
I will be replacing the old redis instance manually when this is merged since automatica replacement was not possible.
We need to …
> Production release #2

- app/controllers/staff/activity_forms_controller.rb
- app/controllers/staff/budgets_controller.rb
- app/controllers/staff/transactions_controller.rb
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/helpers/date_helper_spec.rb
Trello: https://trello.com/c/c9DkwHY9/296-bug-dates-accept-0
We noticed Papertrail recording ActiveRecord::MultiparameterAssignmentErrors when a user input 0 into any of the three inputs on any date field (generated via govuk_date_field)
Rails will attempt to coerce any values from a date_field view helper into a date. If any of those values are 0, the coercion will fail with ActiveRecord::MultiparameterAssignmentErrors
Unfortunately, because this coercion happens before the values are assigned to the model, we cannot catch them with a validator on the model and return errors on the attributes in question.
After trying several solutions, we have extended DateHelper (which was being included in several controllers but not actually being used!) to catch and reject any dates which contain a …
> (296) Date fields accept 0

- CHANGELOG.md
- app/controllers/staff/activities_controller.rb
- app/controllers/staff/organisations_controller.rb
- app/views/staff/organisations/show.html.haml
- app/views/staff/shared/budgets/_table.html.haml
- spec/features/staff/users_can_view_an_organisation_spec.rb
- spec/features/staff/users_can_view_budgets_on_an_activity_page_spec.rb
- spec/features/staff/users_can_view_transactions_on_an_activity_page_spec.rb
Trello: https://trello.com/c/VgXDUp9B/436-lists-of-activities-transactions-and-budgets-do-not-change-based-on-the-last-updated-time
During user testing, users noticed that the lists of budgets & transactions shown on the activity pages changed their order after being edited. The transactions & budgets were being sorted by `last_updated` which is going to change whenever a record is updated. 
Also, activities themselves are listed on the organisation page and "parent" activity pages in order of `last_updated`
This PR orders these entities in different ways:
- Activities are ordered oldest first (`created_at ASC`)
- Budgets are ordered by `period_start_date`, newest first (`period_start_date DESC`)
- Transactions are ordered by `date`, newest first (`date DESC`)
> (436) Lists of Activities, Transactions and Budgets do not change based on the last updated time

- config/initializers/rollbar.rb
- terraform/app.tf
- terraform/variables.tf
- terraform/worker.tf
Add the ability to turn off reporting as the pen test is raising so many errors that we are going to hit our account limit.
I haven't allowed this flag to be send to production or staging by Travis as I think it will be very rare we ever want to do this. If we did we should probably change this environment variable manually with a manual deploy whilst we fix the root cause. Once a fix is made we can use the normal release process to flip rollbar back on.
This hotfix has already been applied onto the pentest environment so this change is to sync it into our mainstream.
> Disable rollbar through a new environment variable

- doc/deployment-process.md
We tried using a hyrid of these instructions and it went wrong.
The release commit that was merged into master wasn't pushed back downstream into develop. When we came to release again our changelog was in the state as if the first release hadn't happened - not ideal.
We like pull requests because they protect us from accidentally doing git merges to the wrong environment which we use for development. That said, having a pull request to deplo and another to push the change back to the downstream involves a frustrating amount of overhead. Getting 2 pull requests, merged in the right order, with 2 reviews. It's complicated and things are likely to go wrong too.
We're going to keep exactly to the deployment process of RMI instead of using a hyrbid …
> Update deployment instructions to include the same manual merge step

- CHANGELOG.md
- app/views/staff/shared/transactions/_table.html.haml
- spec/features/staff/users_can_view_transactions_on_an_activity_page_spec.rb
- spec/support/form_helpers.rb
Trello: https://trello.com/c/YqtDTWv2/435-transaction-descriptions-are-not-included-in-the-table
To improve the look of the activity page, we have decided to remove the
transaction description from the transaction display table, as it can be very
long and disrupt the activity page UI.
> (435) Remove transaction description from the display table

- app/helpers/codelist_helper.rb
- app/views/staff/activity_forms/tied_status.html.haml
- spec/helpers/codelist_helper_spec.rb
- spec/support/form_helpers.rb
Trello: https://trello.com/c/mibiNC05/353-create-activity-tied-status-change-to-radio-btn-with-hints
As per a discussion with the service owner, as we cannot have a default selected
optino with radio buttons, we are putting "Untied" first in the tied_status
options to help users realise it is the preferred option for ODA.
> Make sure "Untied" is first in the list of tied_status options

- CHANGELOG.md
- app/views/staff/activity_forms/aid_type.html.haml
- config/locales/models_and_forms.en.yml
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/support/form_helpers.rb
Trello: https://trello.com/c/Uw6dKrtm/352-create-activity-aid-type
In line with other steps on the Create Activity flow, we have switched Aid type in Activity form from a dropdown to a set of radio buttons with hints.
The hint texts are quite long, so there is a further ticket to iterate over the content and make them smaller & in "plain English" https://trello.com/c/fysX1dKR/497-make-aid-type-descriptions-smaller-in-plain-english
> (352) Change activity Aid type into radio buttons with descriptions

- app/controllers/auth0_controller.rb
- config/locales/en.yml
- spec/features/staff/users_can_sign_in_spec.rb
This work came out of the Pentest which was performed on the service in
March 2020.
An attacker could inject their own error message into a fake
Auth0 response and get the user to inteact with a bogus service.
By checking the error message is something we know and understand and
then displaying our own error message instead we prevent this attack.
If we see a unknown error message, we log to Rollbar so we can learn
what errors we are seeing and display a generic error message.
As ever, I struggled to find a good home for the locales that display
the errors, I went for a location that already had 'errors' and 'auth0'
over creating more separation.
I reworded some of the specs to better reflect what is under test.
> (471) Unknown Auth0 error messages are not displayed

- spec/factories/organisation.rb
- spec/factory_spec.rb
This change fixes a known interimittent test failure and potential others we aren't currently aware of.
The test that we know fails: `spec/services/create_project_activity_spec.rb:42`
After a number of refactorings the final change we're proposing to fix this is problem is one to the Organisation Factory as a whole. It should ensure that only 1 BEIS organisation can ever be created within the context of any one test. The main advantage of this approach is that fewer tests have to repeat the precise setup steps required to create an activity with valid parent activities. More information is attached on the commit.
> (496) Organisation factory only create one BEIS

- app/assets/stylesheets/partials/_definition_list.scss
- app/views/staff/activities/show.html.haml
- app/views/staff/shared/activities/_activity.html.haml
Trello: https://trello.com/c/oQ88bfcT
We change the activity detail to take full page width, so that if the description is very long it takes less vertical space. 
Also we reduced the width of action links, to help manage the horizontal space better.
We should be striving towards separating information that is less used and important into smaller chunks (perhaps into a side navigation link or a tab) and move up the most used and important information to the top.
> Activity details take full page width

- CHANGELOG.md
- config/environments/production.rb
- config/environments/test.rb
- spec/rails_helper.rb
- spec/requests/host_urls_are_whitelisted_spec.rb
- spec/requests/users_can_sign_out_spec.rb
- spec/support/capybara.rb
Trello: https://trello.com/c/fKK1MwEE/473-http-host-header-poisoning-id-web-l3
During a recent pen test, our application was found to be vulnerable to a Host
header poisoning attack, in which a "bad" hostname can be injected into the
request headers and passed back to the client, where it may be used to redirect
users (or in any scenario where `url_for` is used or the `location` is passed
back to the client)
Using a built-in feature in Rails 6 https://github.com/rails/rails/pull/33145
we are able to only allow known hostnames to be passed on from a request header
into the application.
> Enable Rails 6 hosts whitelisting to counteract host header poisoning

- config/environments/production.rb
In https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/286
we enabled Rails 6 host whitelisting. Unfortunately in that PR we used the
ENV["DOMAIN"] variable as the host, but this contains a full URI and not just
the host name. This PR parses the DOMAIN variable to extract only the host for
use in `config.host`
> (Fix) Parse ENV["DOMAIN"] to retrieve host name for use in config.hosts

- CHANGELOG.md
- app/controllers/staff/activities_controller.rb
- app/controllers/staff/budgets_controller.rb
- app/controllers/staff/transactions_controller.rb
- app/policies/budget_policy.rb
- app/policies/transaction_policy.rb
- app/views/staff/activities/show.html.haml
- app/views/staff/shared/activities/_budgets.html.haml
- app/views/staff/shared/activities/_transactions.html.haml
- app/views/staff/shared/budgets/_table.html.haml
- app/views/staff/shared/transactions/_table.html.haml
- spec/features/staff/users_can_view_an_activity_as_xml_spec.rb
- spec/features/staff/users_can_view_budgets_on_an_activity_page_spec.rb
- spec/features/staff/users_can_view_transactions_on_an_activity_page_spec.rb
- spec/policies/budget_policy_spec.rb
- spec/policies/transaction_policy_spec.rb
Trello: https://trello.com/c/Xnef9CW2/466-bug-beis-users-do-not-see-transations-or-budgets-that-are-not-associated-with-their-organisation
Regardless of which organisation the Budgets or Transactions belong to, BEIS users
should be able to see them.
This ticket was raised because BEIS users could not see Budgets and Transactions
in the downloaded IATI XML, because the Budgets/Transactions did not belong to the
user's organisation.
Now, in the Activity XML BEIS users can see all budgets and transactions that belong to
the Activity.
> (466) Enable BEIS users to see all Budgets and Transactions that belong to an Activity

- CHANGELOG.md
- vendor/data/codelists/IATI/2_03/activity/recipient_country.yml
Trello: https://trello.com/c/R1sH0nhV
When creating an activity, in the recipient country step there was a list including all the countries on the ISO list.
Following advice from users regarding this list being too extensive and including countries that ODA do not consider recipients, I have reduced the list of countries leaving only the ones that ODA report as recipients.
> Recipient country list reduced

- CHANGELOG.md
- app/views/layouts/application.html.haml
- config/locales/en.yml
- spec/features/public/visitors/users_can_provide_feedback_spec.rb
To allow users of the service to provide feedback. Following the GOVUK
pattern, of a link in the phase banned at the top of the site.
> (465) Add link to feedback form

- CHANGELOG.md
- app/controllers/staff/activities_controller.rb
- app/models/activity.rb
- app/services/create_programme_activity.rb
- app/services/create_project_activity.rb
- spec/features/staff/users_can_create_a_project_spec.rb
- spec/features/staff/users_can_view_a_project_spec.rb
- spec/features/staff/users_can_view_fund_level_activities_spec.rb
- spec/models/activity_spec.rb
Related to: https://trello.com/c/jEaQCbZp/434-user-actions-are-auditable
While implementing `public_activity` gem, we found a name clash with `Activities`
When public_activity records a change against a model, it adds PublicActivity::Activity
records in an association called `activities`. We already had an association
on Activity called `activities`, so this resulted in a naming clash.
In order to move forward with public_activity, we have decided to rename the
Activity -> Activity association to `child_activities`, i.e.
`has_many :child_activities, foreign_key: "activity_id", class_name: "Activity"`
> Change Activity -> Activity association to `child_activities`

- db/migrate/20200326173005_add_uniqueness_to_organisation_iati_reference.rb
- db/schema.rb
During the production database restore to the pentest environment I noticed that if you skip activerecord you can have as many organisations with GB-GOV-13 as you like. This is a pretty important field to be unique for publishing to IATI purposes to lets validate at the database level as well as ActiveRecord.
> Ensure that organisation iati_references are unique at the database level

- app/models/organisation.rb
- config/locales/models_and_forms.en.yml
- spec/models/organisation_spec.rb
I noticed this bug when restoring production data to the pentest environment. UKSA have an invalid identifier of 1234. This makes publishing their data to IATI invalid.
Following the IATI guidance on organisation identifiers: http://reference.iatistandard.org/203/organisation-identifiers/#two-components-of-iati-organisation-identifiers. This change validates that the "namespace" code exists as a prefix and is separated by a hyphen.
Whilst IATI do say that each component of the namespace code MAY also include a hyphen the real world examples we have seen for BEIS do not. It feels like we can layer on this logic later if required.
> Validate that iati references are prefixed with the correct structure

- doc/deployment-process.md
During release 3 it was noted that some of the documented steps would
error.
It was also felt that tagging the commit that merges the release into
develop would be a more accurate reflection of the release code.
The example link also had the release the wrong way around which had the
potential to confuse developers or result in an incorrect link being
pasted to the change log.
> (chore) Update deployment docs

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/views/staff/activity_forms/finance.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- config/locales/codelists/2_03/iati.en.yml
- config/locales/en.yml
- config/locales/models_and_forms.en.yml
- db/migrate/20200330145039_remove_finance_from_activities.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/helpers/activity_helper_spec.rb
- spec/models/activity_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/support/activity_helpers.rb
- spec/support/form_helpers.rb
- spec/support/shared_examples/behaves_like_valid_activity_xml.rb
Trello: https://trello.com/c/yfr1eiz2
Feedback from user research when creating an activity showed that the Finance step could possibly be omitted as the users always document the activities' finance under the "Standard grant" category. After discussion with them and knowing is highly likely they will keep using the same category in the future, we decided to default the finance category to "Standard grant" for every activity in every level and omit this step from the form the user needs to fill in when they create activities. This would reduce the time users take to complete this task too.
I have deleted the Finance step from the controller and the views. I have deleted the references to this step on the Spec files and the yaml files that are not needed anymore. I have also removed the …
> Finance value defaulted and step removed from Create Activity journey

- .env.test
- .travis.yml
- spec/requests/users_can_sign_out_spec.rb
This work came out of seeing the tests fail in CI with seed 10466,
running the same seed locally, the tests passed.
Trying to figure out what was different it became apparent that in CI
the `.env.example` variables are loaded and locally the `.env.test`
variables are loaded.
One of the differences was that REDIS_URL is not defined in .env.test
whereas it is in .env.example.
Adding the REDIS_URL to the .env.test file results in seed 10466 failing
locally, which confirms the issue.
This could be fixed two ways but the decision was made to change CI to
use the .env.test variables and add the REDIS_URL in. This means
developers will need to run redis locally now in order to run the test
suite, but also means CI and the local tests run in the same environment
- this feels like a good …
> (fix) CI and local tests use the same env vars

- Gemfile
- Gemfile.lock
- app/controllers/staff/activity_forms_controller.rb
- app/models/activity.rb
- app/services/create_fund_activity.rb
- app/services/create_programme_activity.rb
- app/services/create_project_activity.rb
- db/data/20200402172606_change_wizard_step_for_all_activities_without_identifier_to_blank.rb
- db/data_schema.rb
- spec/models/activity_spec.rb
- spec/services/create_fund_activity_spec.rb
- spec/services/create_programme_activity_spec.rb
- spec/services/create_project_activity_spec.rb
This change has been driven by the review of this [pull request](https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/303) that was seeking to use `save(validate: false)` to solve a problem where data couldn't be saved normally. 
On investigation we found activities that existed on the `identifier` step but did not have a value. When `save` was called on these records to correct data that was set during the initial creation (see changes to the services) it would fail due to the `identifier` field validations being run even though the value was still `nil`. We were unable to update fields set by the system.
I think the `identifier` step is used since it's the first 'real' step to the form.
I've added a new form step to capture the state where an activity is …
> Activities at the identification step but without an identifier can be updated again

- db/data/20200402180246_add_geography_data.rb
- db/data_schema.rb
Based on https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/310 which installs the data-migrate gem. Please merge that first.
When we added the `geography` field we didn't set values on our environments. None of our 35 activities on production have a value for geography. https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/249/files
An impact of this is that activities that are at the country step or beyond can no longer be edited.
Using a rake script we update the geography to `recipient_region` for all actiivty records that have a region but not a country.
Whilst no activities currently have a country on production. This is not guaranteed to be the case by the time this task is run, so there is a guard to ignore those …
> Old activities that are beyond the country/region step can be updated again.

- CHANGELOG.md
- app/assets/stylesheets/partials/_address.css.scss
- app/controllers/public/privacy_policy_controller.rb
- app/views/layouts/application.html.haml
- app/views/public/privacy_policy/index.html.haml
- config/locales/en.yml
- config/routes.rb
- spec/features/user_can_view_privacy_policy_spec.rb
The content has been through reviews with BEIS colleagues.
Uses the `<address>` element for better page semantics, which meant adding
a stylesheet.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/address
> (461) Add privacy policy

- CHANGELOG.md
- app/views/staff/shared/xml/_activity.xml.haml
- spec/features/staff/users_can_view_an_activity_as_xml_spec.rb
Trello: https://trello.com/c/2LJYjzhh
This PR fixes a bug we detected while validating XMLs of activities on the IATI validator. When a user creates an activity, they're prompted to input start dates and end dates as part of the journey. The `planned dates` are mandatory, but the `actual dates` are optional. 
Before this change, the XML file would include the fields for the optional dates (`actual_start_date` and `actual_end_date`) even when these dates have been left blank by the user. This situation would case the IATI validator to throw an error on validation of this XML file, as it would encounter two fields with not data on them. Now, the optional dates fields that are left blank by the user will not be included on the XML and the validation will not fail as a result. 
I added tests …
> Empty optional dates are not included in XML

- CHANGELOG.md
- app/models/activity.rb
- app/models/organisation.rb
- app/presenters/activity_xml_presenter.rb
- app/services/create_fund_activity.rb
- app/services/create_programme_activity.rb
- app/services/create_project_activity.rb
- app/views/staff/shared/xml/_activity.xml.haml
- db/migrate/20200331111947_add_reporting_org_association_to_activity.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/models/activity_spec.rb
- spec/models/organisation_spec.rb
- spec/presenters/activity_xml_presenter_spec.rb
- spec/services/create_fund_activity_spec.rb
- spec/services/create_programme_activity_spec.rb
- spec/services/create_project_activity_spec.rb
- spec/support/shared_examples/behaves_like_valid_activity_xml.rb
Trello: https://trello.com/c/CfLUXjCa/459-iati-reporting-org-should-be-beis-regardless-of-the-users-organisation
Funds and programmes should have their reporting org set as BEIS
Projects created by UKSA (our current only delivery partner, and a government organisation) should have their reporting org set as BEIS
Other future DPs will have themselves set as their reporting org (for now).
**NOTE** This PR includes a rake task (can be added as a data migration) to be run on deployment to production.
> (459) IATI reporting org should be BEIS regardless of the user's organisation

- db/migrate/20200408173214_add_foreign_key_constraints.rb
- db/schema.rb
TL;DR Data integrity is a good thing and protects us from accidents
and unexpected consequences of future logic we may add. Rails 
doesn't steer us as clearly as it could. We should add database level 
constraints **alongside** the Rails model logic to all existing 
associations, rather than removing existing associations and relying 
solely on Rails Model logic.
---
We reached a point where we noticed we had created foreign key
constraints for only 2 relationships. This problem came to the
surface during our work to practice restoring production data
to other environments[1]. We ended up taking a different approach
to copying the database across to complete the work. We left this
issue to one side.
Soon after we noticed we were adding a new association and were
choosing to add a foreign …
> Add database constraints to ensure data integrity

- db/migrate/20200331111947_add_reporting_org_association_to_activity.rb
This was fine locally, and on staging but luckily I was testing this against my local database that has production data in and it blew up!
```
== 20200331111947 AddReportingOrgAssociationToActivity: migrating =============
-- add_reference(:activities, :reporting_organisation, {:type=>:uuid, :foreign_key=>{:to_table=>:organisations}})
-> 0.0220s
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:
Validation failed: Your unique identifier Your unique identifier has already been taken
/Users/tomhipkin/sites/beis/beis-report-overseas-development-assistance/db/migrate/20200331111947_add_reporting_org_association_to_activity.rb:15:in `block (2 levels) in up'
```
This was happening as I had 2 activities with an identifier of `nil`.
Before this change is …
> Migration does not fail by trying to update blank activity records on production

- README.md
- doc/architecture/decisions/0019-use-data-migrations-to-update-live-data.md
- docker-entrypoint.sh
Doing this automatically will ensure we don't forget to run these data:migrate tasks by hand. Something we did on the first try - oops.
Using the docker entrypoint ensures the command will be run automatically on all environments.
When we deploy we bring up 2 new applications in the form of docker containers. This sometimes causes a race condition. The first container to call the `rake db:migrate` will block the second and a concurrent migration can error. I think this error will prevent the new data:migrate step from being executed and will remove the change of a data migration being run before the database migration has been applied.
This can be applied by using rake db:migrate:with_data to do both in one. Our use of prepare which improved the reliability of our database set up. Before …
> Run data migrations automatically after migrating the database

- db/migrate/20200408173215_rename_budget_activity_id_to_parent_activity_id.rb
- db/migrate/20200409133152_rename_transaction_activity_id_to_parent_activity_id.rb
Rollbar: https://rollbar.com/dxw/beis-roda/items/139/
```
StandardError: An error has occurred, this and all later migrations canceled:
undefined method `activity' for #<Budget:0x000055f690cb3270>
Did you mean? activity_id
```
Refer to the Activity association in Budgets & Transactions by the id, not the object.
> Reference Transaction & Budget Activity association by id, not object

- config/locales/en.yml
Added '2020' to the transaction description.
Before:  For example, Quarter one spend on the Early Career Research Network project.
After: For example, 2020 quarter one spend on the Early Career Research Network project.
> Content update to transaction description in en.yml

- CHANGELOG.md
- app/views/staff/shared/xml/_activity.xml.haml
- db/migrate/20200414101829_add_previous_identifier_to_activities.rb
- db/schema.rb
- spec/features/staff/users_can_view_an_activity_as_xml_spec.rb
When an activity has already been published to IATI the identifier must
not change. As we are now standardising the identifier we may have to
use two identifiers for some activities.
As existing activities will be imported, do not expose the previous
identifier attribute to users.
Where an activity has a previous identifier use it as the
`iati-identifier` in the xml and output the new identifier using the
`other-identifier` attribute, see:
http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/other-identifier/
I did wonder if we should include the `owner-org` for the `other-identifier` and set it to BEIS, but I won't let that block this work.
http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/other-identifier/owner-org/ …
> (549) Activities can have a previous identifier

- CHANGELOG.md
- app/controllers/staff/organisations_controller.rb
- app/models/organisation.rb
- spec/features/staff/beis_users_can_create_an_organisation_spec.rb
- spec/features/staff/users_can_edit_an_organisation_spec.rb
Trello: https://trello.com/c/XVTv8mOR/577-record-when-an-organisation-is-created-updated-auditing
In https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/309
we added public_activity tracking to Users, Activities, Budgets and Transaction
but missed out Organisations. This PR adds tracking to Organisations.
In `beis_users_can_create_an_organisation_spec.rb` there were two identical copis
of the test `successfully creating an organisation` so we have repurposed one of
these to track the creation of the Organisation.
> Use public_activity to record when an Organisation is created/edited

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_create_a_programme_level_activity_spec.rb
- spec/features/staff/users_can_create_a_project_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
Trello: https://trello.com/c/ZQlLq4nF/551-record-when-users-go-through-each-step-of-the-activity-form
Users update an Activity via a multi-step form, a step for each attribute. The
previous implementation of public_activity meant we had an `activity.update`
event for each step. This change changes the event keys to be more obvious
*what* is being created or updated.
We decide if an activity attribute is being created or updated by the `wizard_complete?`
method on Activities - if the wizard is complete, we can assume an attribute is being
updated; if not, we can assume the attribute is being created.
So the event keys will now be `activity.action.attribute`, e.g. activity.create
for the initial Activity creation; activity.create.identifier for the identifier
creaton, and …
> public_activity update events on Activities are more granular

- app/views/staff/activity_forms/geography.html.haml
Trello: https://trello.com/c/6PnGREFR
We found a typo on the heading of the geography step of activities. It should be a `h1` but it was `hq` instead. As a result, screen readers were struggling to determine the layout of the page and the accessibility of the app was compromised.
This PR fixes that typo on the heading making the geography page accessible for people with vision impairment.
> (567) Heading error fixed on Geography step

- terraform/README.md
When deploying manually to `pentest` we discovered that our terrafiles are not
backwards-compatible with Terraform `0.11.x`. Make it explicit in the docs that
you will need Terraform `0.12.x` to use our terrafiles, along with how to install
& use `tfenv`
> Make Terraform version explicit in manual deployment docs

- CHANGELOG.md
- config/locales/en.yml
- config/locales/models_and_forms.en.yml
- spec/support/form_helpers.rb
Trello: https://trello.com/c/NCFXpJED
The Accessibility Audit report stated that links that open in new windows should have a message informing the user of this action. Visual impaired users could find confusing when a new window opens without informing them (they would not be able to click on the `Back` button, for example).
In line with the suggestion given by the Accessibility report, I have amended the messages on the links that open in new windows. Now, all these messages inform the user they will have a new window/tab opened as a result when clicking the link.
> (572) Message on links that open in new window

- CHANGELOG.md
- app/controllers/staff/organisations_controller.rb
- app/services/find_fund_activities.rb
- app/services/find_programme_activities.rb
- app/services/find_project_activities.rb
- spec/features/staff/users_can_view_an_organisation_spec.rb
- spec/services/find_fund_activities_spec.rb
- spec/services/find_programme_activities_spec.rb
- spec/services/find_project_activities_spec.rb
Trello: https://trello.com/c/XhZ45G6F/520-beis-users-only-see-an-organisations-activities-on-the-organisation-show-page
BEIS users have the right to view all activities, no matter which organisation they belong to.
The can also view any organisation's show page.
However, because of a bug, BEIS user's would see *all* activities on any organisation's
show page, because the list of activities is not filtered by organisation.
Now, when a BEIS user views an organisation's show page, they will only see activities
which belong to that organisation. That is, fund and projects which belong to the organisation,
and programmes which have the organisation as its extending organisation.
When a BEIS user views the BEIS organisation, they will see *all* activities belonging
to all organisations. …
> (520) BEIS users only see an organisation's activities on that organisation's show page

- app/controllers/staff/activity_forms_controller.rb
In a previous commit https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/336 we added more granular event auditing to Activities, but
a line tracking the default "update" auditable event was accidentally left in place.
> Remove default `activity.update` key that was accidentally left in tracking

- config/locales/en.yml
Soz, forgot to change the branch when making a second update...
Spelling out acronyms:
International Aid Transparency Initiative (IATI) reference
Change of sector question as per the content review to 'What area of the economy or society is your %{level} helping?' 
Changed 'create transaction' button to 'Add a transaction' to align with previous content design change. 
[Acronyms in RODA - accessibility.pdf](https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/files/4521571/Acronyms.in.RODA.-.accessibility.pdf)
> Update en.yml to spell out acronyms

- CHANGELOG.md
- app/views/staff/shared/xml/_activity.xml.haml
- spec/features/staff/users_can_view_an_activity_as_xml_spec.rb
- spec/services/create_project_activity_spec.rb
Trello: https://trello.com/c/fMOwz0lj
IATI gives the possibility of publishing the level of hierarchy of an activity by including the parent activities. This PR modifies the XML template for activities to include a new field called `related-activity` which will contain the identifiers of the parent activities of a project (fund and
programme). For now, we are only including parent activities for projects as they are the only ones that are published to IATI at the moment.
On a separate commit, there is an error fixed in one of the test descriptions.
https://stage.dataworkbench.io/validate/e4fc6e24-ced2-417d-8c05-95854cb624aa
> (374) XML for projects contain related parent activities

- config/locales/en.yml
- config/locales/models_and_forms.en.yml
- spec/support/form_helpers.rb
Spelling out acronyms:
- International Aid Transparency Initiative (IATI) reference
- Small and medium-sized enterprise (SME)
- Common reporting standard (CRS)
Small change to sector hint text based on the content review - move 'What area of the economy or society is your %{level} helping?' from the hint text to the h1. 
Small change to the transaction date based on the content review - move 'Date the transaction was made' from hint text to the h1. 
Change of sector question as per the content review to 'What area of the economy or society is your %{level} helping?'
Changed 'create transaction' button to 'Add a transaction' to align with previous content design change.
Changed service title from 'Report Official Development Assistance' to 'Report your official development assistance'. …
> (582) Implement - spell out acronyms (AAA)

- CHANGELOG.md
- app/views/staff/shared/budgets/_table.html.haml
- app/views/staff/shared/transactions/_table.html.haml
- app/views/staff/shared/users/_table.html.haml
- config/locales/en.yml
- spec/features/staff/users_can_edit_a_budget_spec.rb
The April 2020 accessibility audit identified these 'edit' links as
problematic as they have no context for assistive technology users.
We already have our `a11y_action_link` helper, so use it to give the
links more context.
- for users, the name of the user to show
- for transactions 'Edit transaction {transaction reference}'
- for budgets 'Edit budget'
I could not see a better way of identifying budgets.
> (569) Fix descriptive label issues

- CHANGELOG.md
- app/models/transaction.rb
- app/views/staff/shared/transactions/_table.html.haml
- app/views/staff/shared/xml/_transaction.xml.haml
- app/views/staff/transactions/_form.html.haml
- config/locales/en.yml
- config/locales/models_and_forms.en.yml
- db/migrate/20200427130408_remove_reference_from_transaction.rb
- db/schema.rb
- spec/factories/implementing_organisation.rb
- spec/factories/transaction.rb
- spec/features/staff/users_can_create_a_transaction_spec.rb
- spec/features/staff/users_can_edit_a_transaction_spec.rb
- spec/features/staff/users_can_view_transactions_on_an_activity_page_spec.rb
- spec/models/transaction_spec.rb
- spec/services/create_transaction_spec.rb
- spec/services/update_transaction_spec.rb
- spec/support/form_helpers.rb
- spec/support/shared_examples/behaves_like_valid_activity_xml.rb
Trello: https://trello.com/c/Azapqja1/554-remove-reference-from-create-a-transaction
In user testing, the Transaction reference was found to be confusing for users.
It is also not required by IATI.
Remove the reference entirely.
> Remove Transaction reference

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
The April 2020 accessibility audit showed that the skip link was not
working as expected.
After triaging the issue, it looks like Turbolinks was causing the
issue. As we do not rely on Turbolinks behaviour in the application it
has been turned off.
Further information on Turbolinks:
https://github.com/turbolinks/turbolinks
> (568) Fix skip link

- docker-entrypoint.sh
We use the data migrate gem to manage data migrations.
https://github.com/ilyakatz/data-migrate
Previously we ran the data migrations in all environments which caused
an issue when the name of a column in the database was later changed.
Because the test environment destroys and re-creates the database from
the schema, not the migrations, when the data migrations run the
database has a different column name and so fails.
We shouldn't run data migrations in the test environment anyway as there
is no data to migrate.
I would have solved this issue much quicker if we could see the container output in the Travis log - is there someway to do that?
> (fix) Only run data migrations in production

- .travis.yml
There is no need to push an image of a branch that will never be
deployed, not doing so will save time getting PR work to green and into
review.
> (fix) Only deploy docker images from develop and master

- CHANGELOG.md
- app/models/budget.rb
- app/presenters/budget_xml_presenter.rb
- config/locales/en.yml
- db/data/20200504145224_update_budget_status_and_type.rb
- db/data_schema.rb
- spec/factories/budget.rb
- spec/features/staff/users_can_create_a_budget_spec.rb
- spec/features/staff/users_can_edit_a_budget_spec.rb
- spec/features/staff/users_can_view_an_activity_as_xml_spec.rb
- spec/presenters/budget_xml_presenter_spec.rb
Trello: https://trello.com/c/jaDO9y6C/599-budgets-should-store-code-values-for-type-and-status-rather-than-the-human-readable-version-which-is-subject-to-change
We were previously storing the Budget type and status as word strings. This is potentially fragile in case IATI decide to change the wording; plus we were having to translate the word strings into numbers for the Activity XML using a presenter. It makes more sense to store them as numbers in the first place.
> Store Budget.status and Budget.type as numbers, not word strings

- CHANGELOG.md
- app/views/staff/activities/show.html.haml
- spec/features/staff/users_can_create_a_budget_spec.rb
- spec/features/staff/users_can_view_budgets_on_an_activity_page_spec.rb
Trello: https://trello.com/c/GU3pfrad/474-delivery-partners-can-see-level-b-budgets
Previously, Delivery partner users could view Level B (programme) activities
but not see their budgets. This meant the DP didn't have visibility of what
the total of their Level C (project) budgets should be.
Now, DPs can view budgets on a programme, but not edit or create them.
> (474) Delivery partners can see Level B budgets

- CHANGELOG.md
- app/views/staff/shared/activities/_programmes.html.haml
As with the rest of the application a funds programmes are best shown as a table.
> Show programmes in a table on fund show view

- CHANGELOG.md
- app/models/budget.rb
- app/models/transaction.rb
- spec/models/budget_spec.rb
- spec/models/transaction_spec.rb
The value attribute for both budgets and transactions accepted a
minimum value of 1 (one pound in sterling), looking at existing data
revealed transactions with a value of less that 1 (0.57).
> (618) Validate values down to 1 pence

- app/controllers/staff/activity_forms_controller.rb
- app/controllers/staff/funds_controller.rb
- app/controllers/staff/programmes_controller.rb
- app/controllers/staff/projects_controller.rb
- app/controllers/staff/third_party_projects_controller.rb
- app/helpers/activity_helper.rb
- app/models/activity.rb
- app/services/create_fund_activity.rb
- app/services/create_programme_activity.rb
- app/services/create_project_activity.rb
- app/services/create_third_party_project_activity.rb
- db/migrate/20200505093232_change_wizard_status_to_form_state.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/features/staff/users_can_manage_activity_geography_spec.rb
- spec/helpers/activity_helper_spec.rb
- spec/models/activity_spec.rb
- spec/services/create_fund_activity_spec.rb
- spec/services/create_programme_activity_spec.rb
- spec/services/create_project_activity_spec.rb
- spec/services/create_third_party_project_activity_spec.rb
The goal of this work is to to simplify the stepped form and related Activity creation:
- stop skipping validation when creating a new activity
- use validations contexts to run validation during the form steps
- when all form steps are completed by the user, run all the validations
With the refactor in-place the form steps work as expect when one question depends on the answer to another, by resetting the value to nil the activity is no longer valid so the reset step is shown as the user expects - you can see this in 3ec5514 where the `recipient_country` or `recipient_region` is rest and the spec needed to be updated to reflect the working behaviour. This relates to https://trello.com/c/GwGnh3N1
The use of the word 'wizard' has been minimised to only methods from the gem to try and make …
> (598) Refactor activity validations

- .travis.yml
Don't run the test container inside a daemon so any errors are written
to STDOUT, rather than causing the build to fail silently. The tests
will now within the `docker run` command, and the container will exit on
completion.
NB: Including `set -eu` before running the tests means that the exit
code gets reported correctly. Without this, the specs will fail *BUT*
the container will exit successfully, causing the build to pass whilst
broken.
> Expose test-container runtime errors

- app/views/staff/shared/activities/_programmes.html.haml
The new Programme table on the activity show view had the wrong css
class name so was outside the boundaries of the page layout.
> (fix) Activity show programme container class

- CHANGELOG.md
- app/views/staff/shared/activities/_activity.html.haml
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/features/staff/users_can_manage_activity_geography_spec.rb
After discussion with out interaction designer, remove the geography
response from the activity summary view.
When a user clicks on edit for country or region they are taken to the
geography question and then asked about the specific region or country.
> (521) Recipient region/country edit flow change

- CHANGELOG.md
- app/validators/budget_dates_validator.rb
- db/migrate/20200507151949_add_ingested_to_budgets.rb
- db/schema.rb
- spec/factories/budget.rb
- spec/validators/budget_date_validator_spec.rb
We have found that legacy budgets from IATI do not follow the rule of spanning
no more than a year in their start & end dates. So in order to skip date
validation on these records, we are marking them as `ingested`.
In a future commit, we will use this `ingested` flag to skip validations on
budgets when ingesting them from IATI
Spun off from https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/362
> Do not validate dates for "ingested" budgets

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/helpers/codelist_helper.rb
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/services/ingest_iati_activities.rb
- app/views/staff/activity_forms/sector.html.haml
- app/views/staff/activity_forms/sector_category.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- config/locales/codelists/2_03/iati.en.yml
- config/locales/en.yml
- config/locales/models_and_forms.en.yml
- db/data/20200507142459_add_sector_category_to_activities.rb
- db/data_schema.rb
- db/migrate/20200415134754_add_sector_category_to_activities.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/features/staff/users_can_manage_activity_sector_spec.rb
- spec/helpers/codelist_helper_spec.rb
- spec/models/activity_spec.rb
- spec/support/form_helpers.rb
- vendor/data/codelists/IATI/2_03/activity/sector_category.yml
The goal of this work is to split the sector quesiton in two. It turns out we had all the sectors lumped together in one, very long, list when in-fact they each fall into a categories.
Research showed that users liked choosing a 'sector category' first and then seeing a more refined list of sectors to choose from.
The category list is still quite long - but this is defined by IATI.
- make the sector question use radio buttons
- make the list of sector able to accept a catgory and show only sectors in that cateogry
- make the flow dynamic based on the answer to the sector category question
- backfill exisiting activities with the correct sector category
Activity show view, we do not show the sector category as it is not a real questions, just the means to aid the user to answer the sector …
> (462) Sector step uses categories

- app/controllers/auth0_controller.rb
Only replicatable on staging so we have to push to develop.
On our initial debugging 048c0fd2ffde499a483ed78f7d08ac1b4f6afa43 we learnt that the user does have a session, keys are present but not the userinfo key. Let's verify if the callback endpoint recieves this data when auth0 sends a callback.
> Debugging to check why userinfo isn't always set in the session

- CHANGELOG.md
- app/services/ingest_iati_activities.rb
- db/migrate/20200512144535_add_ingested_boolean_to_transactions.rb
- db/schema.rb
- spec/factories/transaction.rb
- spec/services/ingest_iati_activities_spec.rb
Related to https://trello.com/c/Nbh9Taqp/615-how-do-we-address-the-fact-that-dates-in-budgets-published-to-iati-are-not-valid
Similar to https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/382 this change adds the concept of `ingested` (true/false) to Transactions. This way we can mark them as records in the application that may not pass our validations, and may not be edited within the application. 
These use-cases are not implemented yet but this PR lays the groundwork for them.
> Add a boolean flag to Transactions to indicate if they've been ingested

- CHANGELOG.md
- app/models/transaction.rb
- app/services/ingest_iati_activities.rb
- app/views/staff/shared/xml/_transaction.xml.haml
- config/locales/models_and_forms.en.yml
- spec/features/staff/users_can_create_a_transaction_spec.rb
- spec/fixtures/activities/uksa/with_transactions.xml
- spec/models/transaction_spec.rb
- spec/services/ingest_iati_activities_spec.rb
https://trello.com/c/iDDYOe9j/632-transaction-disbursement-channel-field-to-become-an-optional-field
While working on UKSA data exported from IATI we discovered that many
Transactions do not have a disbursement channel set. This field is not mandatory
in IATI, so it should not be mandatory in our application.
> Transaction disbursement channel is no longer mandatory

- config/locales/models_and_forms.en.yml
- spec/features/staff/users_can_create_a_budget_spec.rb
- spec/features/staff/users_can_create_a_transaction_spec.rb
The validation on the value attribute for transactions was changed to
include values from 0.01 but the locale was not updated to reflect the
change.
Budgets have the same attribute with the same validation but never had the
nice error message applied in the locales.
> (fix) Budget and transaction value error message

- Dockerfile
- config/environments/production.rb
- config/initializers/session_store.rb
- config/initializers/vcap_services.rb
- spec/lib/vcap_parser_spec.rb
This change comes about [investigating odd sign-in behaviour](https://trello.com/c/bS7zZIBq) on staging where sometimes users are sent back to the start page. On attempting to wipe the redis store for active sessions to rule out any bad state I found the CookieStore was being used instead. This is not expected and means I cannot flush the redis state in order to continue the ingestigation.
- require a REDIS_URL environment variable to be present during application start so we are alerted early when it's missing to avoid this type of problem again
- fix the core issue which was vcap being called very late in the Rails initialisation process on app boot. It is now called before the session_store.rb initialiser which means REDIS_URL is present
- take a different approach of allowing the …
> Fix session store so that it uses RedisStore on live environments

- config/locales/models_and_forms.en.yml
Something in the locales file is providing a set of keys as the value
for this error. By explicitly setting the value we avoid the issue.
> (fix) Planned disbursement budget type error message

- CHANGELOG.md
- app/controllers/staff/planned_disbursements_controller.rb
- app/models/activity.rb
- app/models/planned_disbursement.rb
- app/presenters/planned_disbursement_xml_presenter.rb
- app/services/ingest_iati_activities.rb
- app/views/staff/activities/show.xml.haml
- app/views/staff/shared/xml/_activity.xml.haml
- app/views/staff/shared/xml/_planned_disbursement.xml.haml
- spec/features/staff/users_can_create_a_planned_disbursement_spec.rb
- spec/features/staff/users_can_view_an_activity_as_xml_spec.rb
- spec/fixtures/activities/uksa/fake_with_complete_planned_disbursement.xml
- spec/models/activity_spec.rb
- spec/models/planned_disbursement_spec.rb
- spec/presenters/planned_disbursement_presenter_spec.rb
- spec/presenters/planned_disbursement_xml_presenter_spec.rb
- spec/services/ingest_iati_activities_spec.rb
- spec/support/shared_examples/behaves_like_valid_activity_xml.rb
This work introduces the addiitonal features to Planned disbursments.
Valid IATI XML is produced that includes planned disbursements.
https://test-validator.iatistandard.org/view/dqf/files/292a5e17-6e8d-4bb7-86af-7d0464954145?isTestfiles=true
Although the ingest work is not yet finalised it was a good oportunity for me to look at the ingest code. There is a great deal of complexity around ingested legacy data that is not well-formed in RODA's world so this is just the basics in-line with the rest of the ingest code.
When we ingest and there is no IATI reference for the receiving organisation, we don't export the XML attributes, this keeps the IATI XML valid.
This was picked up in user research so I stretched to complete this.  The providing organisation can be derived from the Activity …
> (594) Additional planned disbursement features

- CHANGELOG.md
- app/controllers/staff/organisations_controller.rb
- app/models/activity.rb
- app/policies/organisation_policy.rb
- app/views/pages/errors/not_authorised.xml.haml
- app/views/staff/organisations/show.html.haml
- app/views/staff/organisations/show.xml.haml
- config/locales/en.yml
- spec/features/staff/users_can_view_an_organisation_as_xml_spec.rb
- spec/models/activity_spec.rb
- spec/policies/organisation_policy_spec.rb
Trello: https://trello.com/c/XpXfmNXM/636-a-beis-transparency-user-can-download-the-xml-all-activities-for-each-delivery-partner-in-a-single-file
A BEIS user needs to be able to download all the (project C or third-party project D, whichever is lowest) activities for an organisation as a single file. Currently the BEIS transparency user has to go to each Activity show page to download each Activity individually. 
In this PR I have added `has_many` association to Activities linking to Budgets and Transactions. This is after a lot of thought about the simplest way to get all budgets/transactions for each Activity. 
In Organisation#show we are getting all the project & third-party activities for that organisation. Without these associations, we would have to iterate over each activity in the …
> (636) A BEIS transparency user can download all activities for each delivery partner in a single XML file

- spec/support/omniauth.rb
* This problem is especially noticeable when the local rspec output is configured to output in dots rather than cascading vertically with the verbose descriptions
* I could have added this logging config to each test that was causing a failure however I couldn't think of a case when any omniauth output to the logs would be valuable when running the test suite. I've turned it off across the test suite to solve the immediate issue and prevent it popping up again in future in any new tests
The 2 tests that cause these messages are: 
- features/staff/users_can_sign_in_spec:90
- features/staff/users_can_sign_in_spec:109
> Omniauth failures don't log to stdout in test

- config/locales/models_and_forms.en.yml
- spec/support/form_helpers.rb
Updated or deleted hint text for some stages of the create fund journey
Removed a full stop after hint text for the flow question
Changed the unique identifier hint text
Changed the purpose of fund hint text
Deleted the hint text for stage of fund as the title has been changed to a question
Deleted the hint text for region as the title has been changed to a question
Deleted the hint text for country as the title has been changed to a question
Changed the hint text for the flow question
> Updated hint text for "create fund"

- CHANGELOG.md
- app/helpers/form_helper.rb
- app/models/planned_disbursement.rb
- app/validators/date_within_boundaries_validator.rb
- config/locales/en.yml
- config/locales/models_and_forms.en.yml
- spec/features/staff/users_can_create_a_planned_disbursement_spec.rb
- spec/helpers/form_helper_spec.rb
- spec/models/planned_disbursement_spec.rb
We already have a custom validator to keep dates within boundaries.
The custom validator has been updated to underscore the class name when
deriving the error message keys, we haven't had a class with an
underscore in yet and `planneddisbursement` feels a but odd in the locales file.
Added some validation coverage for planned disbursements and sorted the
locales.
> (fix) Validate boundaries of planned_disbursement dates

- CHANGELOG.md
- app/services/ingest_iati_activities.rb
- db/data/20200521165254_add_iati_ids_to_existing_uksa_data.rb
- spec/services/ingest_iati_activities_spec.rb
- Update existing UKSA production data with the associated IATI identifiers to provide a reliable way to update existing records
- Never ingest the same activity twice to avoid double entry
- If the ingest finds an existing activity that matches the IATI activity, it will do a smaller set of actions. Namely creating transactions, budgets and planned descriptions, as well as saving the XML onto the record for future updates
- if the ingest cannot find a matching record (as is the case for 11 activities) then it will seek to create new records
> (665) Ingesting updates existing projects before creating new ones

- CHANGELOG.md
- app/controllers/staff/transactions_controller.rb
- app/models/activity.rb
- spec/features/staff/users_can_create_a_transaction_spec.rb
- spec/models/activity_spec.rb
The providing organisation of a transaction can be derived from the activity level and the delivery partner organisation type.
- For government orgs all providing organisation at all levels is BEIS
- For non-governement orgs all proviging organisation at all level is BEIS, excpet Level D (Third-party projects) where it is the delivery partner.
This work builds on previous work done on planned disbursements which follows the same set of rules.
We could remove the providing org altogether and not ask the user at all, but it was felt we can build our confidence that this is a good call be testing with users before we remove it entirely, there may be edge cases we are not aware of and keeping the form means a user can override the values if needed.
> (672) Provider organisation pre filled for transactions

- db/data/20200521165254_add_iati_ids_to_existing_uksa_data.rb
Previously this was querying activities by their `id` rather than their `previous_identifier`. This was noticed when running the task by hand due to other complications when setting up the pentest environment.
> Data migration can be rolled back

- .standard.yml
- CHANGELOG.md
We cannot affect the syntax the gem produces each time we run `data:migrate` or any other command. 
Instead of running `rake standard:fix` every time we create and run one of these migrations, let's switch to ignore this file from any linting rules.
I stubmled across this when trying to add a new migration to capture the ingesting of UKSA IATI data. I can't commit that work yet as a data migration needs to be run first, but this work can still be proposed now.
There's no linting error to screenshot.
> Allow the data_migrate gem to modify it's schema without linting errors

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- app/views/staff/activity_forms/aid_type.html.haml
- app/views/staff/activity_forms/flow.html.haml
- config/initializers/form_builder.rb
- config/locales/models_and_forms.en.yml
- doc/i18n.md
- During a separate piece of work we have been trying to take advantage
of a new feature of this gem.
- Since we were using a dxw fork, we were unable to do this, so had to
either switch away from it or update our fork. Given that it looked like
the gem was now providing the feature that caused us to originally fork,
we think that it is safe to switch back.
- On updating the gem we found that there were able to remove the monkey
patching for Internationalisation and replace it with gem configuration
https://govuk-form-builder.netlify.app/building-blocks/localisation/#customising-locale-structure
- We found that we needed to continue to provide an override so that we
could continue to use a single set of local values rather than have it
duplicated. This is consist with the initial approach …
> Switch our version of the form builder gem to the latest

- app/policies/organisation_policy.rb
- app/views/staff/organisations/show.html.haml
- spec/features/staff/users_can_view_an_organisation_as_xml_spec.rb
Trello: https://trello.com/c/XpXfmNXM/636-a-beis-transparency-user-can-download-the-xml-for-all-activities-for-each-delivery-partner-in-a-single-file#comment-5ecf7d2bbc620c0aaac7a273
During testing we discovered that the "Download XML" buttons were appearing
on the BEIS home page which they should not do. Only delivery partner organisations
should have downloadable activity XML.
> (fix) Do not show download buttons on BEIS home page

- CHANGELOG.md
- app/controllers/staff/planned_disbursements_controller.rb
- app/models/planned_disbursement.rb
- spec/features/staff/users_can_create_a_planned_disbursement_spec.rb
- spec/features/staff/users_can_edit_an_planned_disbursement_spec.rb
- spec/support/form_helpers.rb
Record planned disbursement create and update actions with public
activity.
> (680) Planned disbursement activity is recorded

- app/services/ingest_iati_activities.rb
The value-date element is different to the transaction-date element.
Whilst they are likely to be the same, we export the transaction-date as
the value-date ourselves, we should ingest from the correct xml element.
Transaction reference docs:
http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/transaction/
> (fix) Transaction date ingest element

- CHANGELOG.md
- config/locales/models_and_forms.en.yml
This one is old,  the view has changed alot, but is now resolved.
Now we are not using the fork of the GOVUK form builder, we can use the
hint text on the user > role field.
> (194) Fix user role hint text

- config/locales/models_and_forms.en.yml
Saw this bad translation key whilst looking for IATI reference fields.
> (fix) Implementing organisation reference hint

- db/data/20200529093419_add_reporting_org_to_activities_where_missing.rb
- db/data_schema.rb
Trello: https://trello.com/c/VAjGDwZs/671-practice-ingesting-uksa-iati-data-ontop-of-production-data#comment-5ecfc215edfc381404373ecd
While working on the pentest environment we discovered some Activities with a nil
reporting_organisation. These records are old and we are no longer able to create
activities without a reporting organisation.
This data migration ensures there are no old records without a reporting organisation.
It follows the same rules as those in the Create[Level]Activity services.
It is irreversible because Activities are not valid without a reporting organisation.
> (fix) Tidy up old Activities which may not have a reporting_organisation

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- app/models/activity.rb
- app/models/implementing_organisation.rb
- app/models/organisation.rb
- app/models/planned_disbursement.rb
- app/models/transaction.rb
- spec/factories/implementing_organisation.rb
- spec/models/activity_spec.rb
- spec/models/implementing_organisation_spec.rb
- spec/models/organisation_spec.rb
- spec/models/planned_disbursement_spec.rb
- spec/models/transaction_spec.rb
- spec/rails_helper.rb
We have seen an instance where leading whitespace in the IATI
Identifier value caused the XML to fail the IATI validator.
The IATI spec states 'The iati-identifier should have no leading or
trailing whitespace.' therefore we should strip the whitespace before we
save the value.
http://reference.iatistandard.org/203/activity-standard/overview/iati-identifier/
The strip_attributes gem was chosen:
https://github.com/rmm5t/strip_attributes
This was after much discussion around the various approaches could
take. We felt the gem was simple enough and gave us the functionality we
wanted without a large overhead. Under the hood, it uses the before_save
callback, which was one of the preferred approaches, but the gem has a
nice interface to allow targeting the attributes to act upon.
Configure …
> (581) strip whitespace from iati identifier

- CHANGELOG.md
- app/models/transaction.rb
- spec/features/staff/users_can_create_a_transaction_spec.rb
- spec/models/transaction_spec.rb
We have seen instances of users inputting unlikely, but valid years,
0202 for example.
We have a date_within_boundaries custom validator already that will help
here.
The validator will stop future dates being more than 25 years in the
future from the current date, but this feels reasonable.
> (682) Fix transaction date boundaries

- CHANGELOG.md
- app/services/ingest_iati_activities.rb
- spec/fixtures/activities/uksa/fake_with_transaction.xml
- spec/services/ingest_iati_activities_spec.rb
Trello: https://trello.com/c/pvFOkc7c/692-infer-transaction-receiver-org-type-from-activity-implementing-org-type
On ingesting the UKSA data we noticed that all transactions had a receiving organisation
type of 0.
This is due to all the transaction receiver-org elements in the exported IATI XML
having no `@type` elements.
After discussion with BEIS, we have decided to try to infer the transaction
receiving organisation type from the transaction's parent activity. The parent
activity will have implementing organisations of type 4, which is the same as
the child transaction's receiving organisation.
We can infer the same logic for planned disbursements.
Activities can potentially have multiple implementing organisations. However a transaction can only have one receiving organisation. After …
> Infer transaction & planned disbursement receiver-org type from parent activity

- CHANGELOG.md
- app/services/ingest_iati_activities.rb
- spec/fixtures/activities/uksa/invalid_activity.xml
- spec/services/ingest_iati_activities_spec.rb
* Whilst for UKSA we have been able to ingest every activity without issue, there is a risk that future ingests will fail to create new activities silently. The more activities we ingest, the harder it will be to review these within the service by eye.
* Fail the ingest loudly if for any reason an activity fails to save
* If there is a failure the script should be able to run idempotently with the check for existing records on ID and never ingesting a file already marked as ingested
* This approach completes the fail loudly strategy used already with: `Transaction.save!`, `Budget.save!` and `PlannedDisbursement.save!`
* I've tested this locally on production data and fortunantly there were no activities failing silently and not creating
> Ingest tool fails loudly if it was unable to save for any reason

- CHANGELOG.md
- app/models/transaction.rb
- config/locales/models_and_forms.en.yml
- spec/features/staff/users_can_create_a_transaction_spec.rb
- spec/models/transaction_spec.rb
Trello: https://trello.com/c/ubB87WqW/690-change-validations-to-accept-negative-values-but-not-zero
When doing a test ingest of AMS Netwon Fund data we discovered some transactions
with negative values, which break our validations.
Transactions should be able to have a negative value when a DP sends a refund to
a fund.
However transactions cannot have a value of zero.
> (690) Allow negative transaction values

- .env.test
- Dockerfile
- config/initializers/dotenv.rb
We noticed that as a result of change to session_store.rb which rqeuired REDIS_URL to be present. This change was order to make sure our session storage was consistent across environments and to fail loudly if it wasn't, removing the chance of obscure errors that were inconsistent to debug. Eg, cookie overflows.
After rolling this change out we found out that existing members of the dev team and new joiners got tripped up by this new requirement.
This change moves to make `rails s` produce a meaninful error to developers so that they can quickly establish that they are missing environment variables. Rather than hunting through the errors that occur when an expected value was missing further down the line.
Since we are using Dotenv to load our environment variables I've used their …
> Booting the app with missing env variables will give a meaningful error

- CHANGELOG.md
- app/models/activity.rb
- app/services/ingest_iati_activities.rb
- config/locales/models_and_forms.en.yml
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/fixtures/activities/ams/newt/fake_activity_with_dates.xml
- spec/models/activity_spec.rb
- spec/services/ingest_iati_activities_spec.rb
Trello: https://trello.com/c/bHOqDiH7/691-address-activities-with-missing-mandatory-dates
This PR is in two parts, and only the second commit is strictly necessary to address the issue in the trello card.
When ingesting AMS Newton fund activities locally, we found that 17 of the activities in the IATI XML file had only `activity-date` elements of type 1 (planned start date) and 3 (planned end date). According to the ingest script, types 1 & 2 are expected, so these activities were not ingested successfully.
This change is addressed in 44aaff9652e72401ffcd4f05276ccfab706b0abb
However while fixing this, we noticed that according to the IATI standard, activity dates 1 and 2 are the mandatory ones - and *either* 1 (planned start) *or* 2 (actual start) are expected …
> (691) Address ingested activities with missing mandatory dates

- CHANGELOG.md
- app/controllers/staff/organisations_controller.rb
- app/models/activity.rb
- spec/features/staff/users_can_view_an_organisation_as_xml_spec.rb
- spec/models/activity_spec.rb
Trello: https://trello.com/c/vpHhfQ1D/442-users-can-only-download-complete-activities
When a user clicks Download as XML on an Organisation page, the resulting XML
file should only contain complete activities which will meet IATI standards, not
any which are missing any of the required fields.
> (442) Users can only download complete activities

- CHANGELOG.md
- app/assets/stylesheets/partials/_tag.scss
- app/views/staff/shared/funds/_table.html.haml
- app/views/staff/shared/programmes/_table.html.haml
- app/views/staff/shared/projects/_table.html.haml
- app/views/staff/shared/third_party_projects/_table.html.haml
- config/locales/default.en.yml
- config/locales/models/activity.en.yml
- spec/features/staff/organisation_show_page_spec.rb
Trello: https://trello.com/c/2hbGT0GG/643-user-can-see-the-reporting-status-of-an-activity-in-all-tables
To ensure a user can quickly see which Activities are missing required attributes,
we have added a complete/incomplete flag to the Activity tables on organisation & activity
views.
I have used the Gov.uk tag pattern here https://design-system.service.gov.uk/components/tag/
but have had to add CSS overrides t get the colours working correctly (after pairing with @deberny )
> (643) Flag incomplete activities in the activity table views

- db/data/20200615105812_delete_unwanted_activities.rb
- db/data_schema.rb
Trello: https://trello.com/c/0F5WFmSV/714-delete-2-production-activities-as-a-result-of-dans-ingest-review
Delete three activities in production which were identified as unnecessary after a content review.
> Data migration to remove 3 unwanted Activities from the production database

- CHANGELOG.md
- app/helpers/codelist_helper.rb
- app/views/staff/shared/xml/_activity.xml.haml
- spec/features/staff/users_can_view_an_activity_as_xml_spec.rb
- spec/helpers/codelist_helper_spec.rb
Trello: https://trello.com/c/c2twcAzs/725-expose-the-country-region-name-as-a-narrative-element-in-the-xml
The `recipient-region` and `recipient-country` elements in the Activity XML
should contain the region/country name in a nested `narrative` element like so:
```
<recipient-region code="589" vocabulary="1">
<narrative>Middle East, regional<narrative>
</recipient-region>
```
> (725) Activity region & country names are exposed in a `narrative` element in the XML

- CHANGELOG.md
- app/controllers/staff/extending_organisations_controller.rb
- db/data/20200615144002_add_implementing_organisations_to_programmes.rb
- db/data_schema.rb
- spec/features/staff/users_can_manage_extending_organisation_spec.rb
Trello: https://trello.com/c/usZXtaXu/501-programmes-have-an-implementing-organisation
When a programme has its extending organisation set, the same organisation is set
as the implementing organisation.
Previously we were not requiring an implementing organisation for programmes, but
if we are going to publish programmes to IATI we will need them to have an
implementing organisation set. This will always be the same as their extending
organisation.
The second commit contains a data migration to add the implementing organisations to existing programmes on staging/production.
> A programme's implementing organisation is the same as its extending organisation

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- config/environments/production.rb
- doc/architecture/decisions/0021-use-lograge-gem.md
Trello: https://trello.com/c/5uzKx5du/726-turn-off-debug-mode-in-production-to-reduce-logging-use
This PR:
- Reduces the default logging output level in production to `info`
- Adds the lograge gem, which turns Rails' default multiline logs into a single line, e.g. 
```
method=GET path=/organisations/f1584f98-aa3b-4158-9bf9-fd1ea4af7b67/activities/3e71cf8d-7f7a-4a72-8504-958da0712469 format=html controller=Staff::ActivitiesController action=show status=200 duration=54.78 view=41.16 db=3.41
```
> (726) Reduce logging in production to reduce Papertrail usage

- config/locales/models/user.en.yml
Removed "Choose an organisation" title
Replaced it with the hint text "What organisation does this user belong to?"
Deleted hint text
> Swapped hint text for title in "choose an organisation" field

- app/views/staff/activity_forms/status.html.haml
- config/locales/models/activity.en.yml
- spec/features/staff/users_can_view_a_project_spec.rb
- spec/features/staff/users_can_view_fund_level_activities_spec.rb
- spec/features/staff/users_can_view_programme_level_activity_spec.rb
- spec/features/staff/users_can_view_third_party_projects_spec.rb
Changed title from "Status" to "What is the development status?" for consistency with other titles
Removed the hint text as the title is more descriptive
> Update status title and removed hint text

- app/views/staff/activity_forms/purpose.html.haml
- app/views/staff/activity_forms/status.html.haml
- config/locales/models/activity.en.yml
- spec/features/staff/users_can_choose_recipient_country_spec.rb
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/helpers/codelist_helper_spec.rb
- spec/support/form_helpers.rb
- vendor/data/codelists/IATI/2_03/activity/status.yml
https://trello.com/c/4bIfITjU
https://trello.com/c/lJ2WeJYc
https://trello.com/c/rR0rbCSQ
https://trello.com/c/db3pSCgg
These are the cards that drove a refactoring of the locales. Now this is complete we can redo this work on the more structured locale files.
You can view more detaills on the Trello cards. All of the changes are around the activity form steps.
> (669, 666, 668, 670) Update create activity journey content

- CHANGELOG.md
- app/helpers/codelist_helper.rb
- app/views/staff/activity_forms/aid_type.html.haml
- spec/helpers/codelist_helper_spec.rb
Trello: https://trello.com/c/2xrjDcXk/477-delivery-partners-can-see-codes-when-selecting-aid-type
When selecting an aid type for an Activity, the aid type code is displayed
alongside the Aid Type name for clarity.
> Users can see codes when selecting aid type

- app/views/staff/activity_forms/purpose.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- config/locales/models/activity.en.yml
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
Changed "Purpose of programme" to "What is the purpose of the programme?"
Changed "Title" to "Programme name"
Changed hint text "A short title that explains the fund's activity" to "A short title that explains the purpose of the programme"
> Changes to purpose of programme heading, title, and hint text

- CHANGELOG.md
- app/assets/stylesheets/partials/_tag.scss
- app/controllers/staff/activity_redactions_controller.rb
- app/controllers/staff/organisations_controller.rb
- app/models/activity.rb
- app/policies/activity_policy.rb
- app/policies/project_policy.rb
- app/views/staff/activity_redactions/edit.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- app/views/staff/shared/projects/_table.html.haml
- app/views/staff/shared/third_party_projects/_table.html.haml
- config/locales/models/activity.en.yml
- config/routes.rb
- db/migrate/20200623132105_add_publish_to_iati_field_to_activity.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/features/staff/organisation_show_page_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/features/staff/users_can_view_an_organisation_as_xml_spec.rb
- spec/models/activity_spec.rb
- spec/policies/project_policy_spec.rb
- spec/policies/third_party_project_policy_spec.rb
Trello: https://trello.com/c/e8GbGaHP/715-redact-selected-activities-from-the-xml-file
In order for BEIS users to redact certain activities from the IATI XML file, we have introduced a boolean field onto the Activity table which enables complete activities to be left out of the XML download. Activities are set to be published to IATI by default, the option has to be manually turned off. 
This option is only available to BEIS users.
Additionally, the list view of Activities on the Organisation show page now has a label to clearly show which activities are redacted or not.
> (715) Redact selected activities from the XML file

- app/controllers/staff/activity_redactions_controller.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
A missed part of https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/501
Trello: https://trello.com/c/e8GbGaHP/715-redact-selected-activities-from-the-xml-file
When redacting an activity, all its children activities are redacted as well.
In theory this will only happen for level C activities at the moment, as only
level C & D can be redacted, and only level C can have children. But if we
begin publishing level B to IATI, this will be useful for redacting any children
that level B activities have.
> Redacted activities redact their children

- CHANGELOG.md
- app/models/activity.rb
- spec/models/activity_spec.rb
Activities can now have the same identifier, but only when they belong to different parent activities.
We are loosening up the uniqueness validation on activity identifiers because we believe it is likely that the project and third-party project identifiers currently used by delivery partners have the possibility of being the same.
When using this reference to publish to IATI we think this approach would continue to work. The fund, programme and project identifiers are all combined which should guarantee uniqueness across all activities.
*NB: We originally added this because we found in practice that programme identifiers were being reused by BEIS. However, because they would still share a common fund activity, this change wouldn't actual have fixed this issue. In that specific case, we …
> (760) Activity identifiers are only unique between sibling activities

- CHANGELOG.md
- app/views/staff/shared/xml/_activity.xml.haml
- spec/features/staff/users_can_view_an_activity_as_xml_spec.rb
The IATI activity standard specifies that `<recipient-region/>` and `<recipient-country/>` should be mutually exclusive, unless we are providing the percentage splits amongst them.
For now, we'll only include the recipient region when the country is not available.
> (780) XML contains ONLY recipient country OR region

- CHANGELOG.md
- app/controllers/staff/activities_controller.rb
- app/models/user.rb
- app/views/shared/_navigation.html.haml
- app/views/staff/activities/index.html.haml
- app/views/staff/shared/activities/_table.html.haml
- config/locales/models/activity.en.yml
- config/routes.rb
- spec/features/staff/users_can_view_activities_spec.rb
- spec/models/user_spec.rb
This is a simple view of an organisations activities.
The view takes a organisation_id and displays all the activities that
are associated with that organisation through the `organisation`
association.
BEIS users can supply a delivery partners organisation id and see those
activities. This functionality is not exposed in the UI as yet, but is
supported by the view, we expect later work to add this UI.
Delivery partners cannot use another organisation id.
The view can be augmented later with additional filters as we learn what
users want to see.
When an unexpected organisation_id is encountered we try to show the
current users own organisation activities instead, those instances might
be:
- no organisation id parameter
- an unknown organisation id
- an empty organisation id
- another …
> (752) Add activities index page

- CHANGELOG.md
- app/helpers/activity_helper.rb
- app/views/staff/activities/details.html.haml
- app/views/staff/activities/financials.html.haml
- app/views/staff/activities/show.html.haml
- app/views/staff/activity_forms/_wrapper.html.haml
- app/views/staff/activity_redactions/edit.html.haml
- app/views/staff/budgets/edit.html.haml
- app/views/staff/budgets/new.html.haml
- app/views/staff/extending_organisations/edit.html.haml
- app/views/staff/implementing_organisations/edit.html.haml
- app/views/staff/implementing_organisations/new.html.haml
- app/views/staff/organisations/edit.html.haml
- app/views/staff/organisations/new.html.haml
- app/views/staff/planned_disbursements/edit.html.haml
- app/views/staff/planned_disbursements/new.html.haml
- app/views/staff/transactions/edit.html.haml
- app/views/staff/transactions/new.html.haml
- app/views/staff/users/edit.html.haml
- app/views/staff/users/new.html.haml
- app/views/staff/users/show.html.haml
- config/locales/models/activity.en.yml
- spec/features/staff/beis_users_can_invite_new_users_spec.rb
- spec/features/staff/beis_users_can_view_other_users_spec.rb
- spec/features/staff/users_can_choose_recipient_country_spec.rb
- spec/features/staff/users_can_edit_a_transaction_spec.rb
- spec/features/staff/users_can_view_activities_spec.rb
- spec/features/staff/users_can_view_an_activity_spec.rb
- spec/features/staff/users_can_view_fund_level_activities_spec.rb
- spec/helpers/activity_helper_spec.rb
The back links are trying to mimic the action of the Back button in the browser
but are increasingly confusing as many pages can be accessed in different ways.
This commit removes them, except for the Back links on the activity create/edit
form as there is no other quick way to get back to the activity details page
without a back link. The back link on the Activity form has been amended to
point at the `details` view of the Activity.
**Suggestion for discussion:** on the Activity Form, would it make sense to replace the Back link with a secondary button? E.g. https://design-system.service.gov.uk/components/button/secondary-combo/index.html
> Remove back links, except on Activity form

- CHANGELOG.md
- app/assets/stylesheets/partials/_page_actions.css.scss
- app/controllers/staff/activities_controller.rb
- app/views/staff/activities/index.html.haml
- app/views/staff/shared/activities/_filter.html.haml
- app/views/staff/shared/activities/_table.html.haml
- config/locales/models/activity.en.yml
- spec/features/staff/users_can_filter_activities_spec.rb
This PR is part of the larger work to refactor how users view activities. To keep the PRs small and concise this one will come first.
We have the new activities view that shows a user the acitvities associated to their organisation, for BEIS users we introduce a filter that allows them to switch this view to show activities of any other delivery partner organisation.
As this activities view is becoming the single place for managing activities, it make sense to also move the new 'create activity' button to this page.
The activities view was not using the presenter so incomplete activities where not shown correctly, this has been resolved.
With this work in-place we will move on to make further refinements.
> (824) BEIS users can filter activities by organisation

- CHANGELOG.md
- app/helpers/form_helper.rb
- app/views/staff/activity_forms/level.html.haml
- config/locales/models/activity.en.yml
- spec/helpers/form_helper_spec.rb
- spec/support/form_helpers.rb
- refactor the way the previous content was displayed to free up the `description` field
- refactor a test so it was decoupled enough to not need a change for this feature
- add new content onto each radio button on the activity level step. Depending on which user you are, you will continue to see the options available to you. The new change adds more explanation/hint text to help the user make the correct choice
Content was taken from the Trello comments Louise left: https://trello.com/c/qHVAHCHx/789-add-hierarchy-definitions-to-roda. We also discussed the labels and decided to start by leaving it as "Fund" rather than "Fund (Level A)" for now.
> (789) Add hierarchy explanations to the level step of the activity form

- CHANGELOG.md
- app/controllers/staff/activity_children_controller.rb
- app/helpers/activity_helper.rb
- app/views/staff/activities/children.html.haml
- app/views/staff/activities/details.html.haml
- app/views/staff/activities/financials.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- app/views/staff/shared/activities/_table.html.haml
- config/locales/models/activity.en.yml
- config/routes.rb
- spec/factories/activity.rb
- spec/features/staff/users_can_create_a_budget_spec.rb
- spec/features/staff/users_can_create_a_programme_level_activity_spec.rb
- spec/features/staff/users_can_create_a_project_spec.rb
- spec/features/staff/users_can_create_a_third_party_project_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/features/staff/users_can_view_a_project_spec.rb
- spec/features/staff/users_can_view_an_activity_spec.rb
- spec/features/staff/users_can_view_budgets_on_an_activity_page_spec.rb
- spec/features/staff/users_can_view_fund_level_activities_spec.rb
- spec/features/staff/users_can_view_transactions_on_an_activity_page_spec.rb
- spec/helpers/activity_helper_spec.rb
Moving child activities to their own tab allows users to view and navigate the activity hierarchy without having to hunt around the interface.
For this work, what is displayed in the tab remains as before, we may want to change this in future work, removing the level titles and 'create activity' buttons, for example.
I've intentionally avoided the language issue by labelling the tab as generic as possible, we still don't know how or when we will have to bring the 'level' language into the interface and I feel like 'Child activities' is actually clearer than 'Level C activities', etc
Whilst delivery partners cannot edit programme level activities, they may want to use them as a way of understanding the hierarchy of activities.
As we already show the parent activity in the details tab, we …
> (825) Child activities are shown in their own tab

- CHANGELOG.md
- app/controllers/staff/organisations_controller.rb
- app/models/submission.rb
- app/policies/submission_policy.rb
- app/presenters/submission_presenter.rb
- app/views/staff/organisations/show.html.haml
- app/views/staff/shared/submissions/_table.html.haml
- config/locales/models/submission.en.yml
- db/data/20200716142425_add_submissions_for_all_organisations_and_funds.rb
- db/data_schema.rb
- db/migrate/20200716130243_create_submissions.rb
- db/schema.rb
- spec/factories/submission.rb
- spec/features/staff/organisation_show_page_spec.rb
- spec/models/submission_spec.rb
- spec/policies/submission_policy_spec.rb
- spec/presenters/submission_presenter_spec.rb
- vendor/data/dp_to_fund_mappings/dp_mappings_072020.csv
Trello: https://trello.com/c/4qRgkMw5/792-every-delivery-partner-organisation-has-a-submission-created-for-each-fund-they-are-associated-with
In this PR:
- Create a Submission model and associated tests & test fixtures
- Constrain Submissions by Fund and Organisation. At this point, we should not have more than one Submission per Fund/Organisation pair. This may change in future as we add more Submissions for each pair, on a quarterly basis.
- A data migration to seed the database with a Submission per Organisation/Fund pair
- A Pundit policy to control access to Submissions
- A SubmissionPresenter to style the Submission for the front end
- Show Submissions on the organisation home pages. For BEIS users, they will see all Submissions for all Organisation/Fund pairs. Delivery partner …
> (792) Every delivery partner Organisation has a Submission created for each Fund they are associated with

- db/seeds/activity.rb
The data migration `AddSubmissionsForAllOrganisationsAndFunds` added in
https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/527
will fail if the environment doesn't have both GCRF and Newton Fund activities
present. This update ot the seeds ensures everyone will have both Funds in their
local db.
> Add Newton fund activity to seeds

- CHANGELOG.md
- app/controllers/staff/submissions_controller.rb
- app/models/submission.rb
- app/presenters/submission_presenter.rb
- app/validators/date_not_in_past_validator.rb
- app/views/staff/shared/submissions/_table.html.haml
- app/views/staff/submissions/_form.html.haml
- app/views/staff/submissions/edit.html.haml
- config/locales/models/submission.en.yml
- config/routes.rb
- db/migrate/20200722081543_add_deadline_field_to_submissions.rb
- db/schema.rb
- spec/factories/submission.rb
- spec/features/staff/beis_users_can_edit_a_submission_spec.rb
- spec/models/submission_spec.rb
- spec/presenters/submission_presenter_spec.rb
- spec/validators/date_not_in_past_validator_spec.rb
Trello: https://trello.com/c/QfCsh56Z/793-a-beis-user-can-edit-submissions-to-set-or-change-a-deadline
A Deadline date attributes has been added to the Submission model. This attribute is not required but when set, it can only be set to a future date. 
Setting a deadline to a future date moves the Submission from the "Inactive" state to "Active"
Only BEIS users can edit Submissions, Delivery Partner users do not see the Edit link against their submissions.
> (793) a BEIS user can edit Submissions to set or change a deadline

- db/data/20200722154738_migrate_uksa_gcrf_mappings.rb
When running this migration on pentest & staging, we encountered issues where
if a programme is missing, the migration could not run. This is a problem
because we cannot expect each environment to contain exactly the same data.
This fix makes the migration more tolerant of missing programmes & therefore
less likely to break the build on staging.
> Make MigrateUksaGcrfMappings more tolerant of missing data

- config/locales/models/activity.en.yml
The content review recommended that we use the hint text as the title so the new title is "What area of the economy or society is the fund helping?" I also removed these words from the hint text.
> Changed focus area category title and hint text

- spec/features/staff/beis_users_can_edit_a_submission_spec.rb
When activating a Submission, a PublicActivity record with the string
`submission.activate` is created. This test is checking for the existence of
this record. However, as part of the test setup, another PublicActivity with the
string `submission.update` is created. Sometimes, when using `.find_by` to
retrieve the PublicActivity records associated with the Submission, the `activate`
record appears first, other times the `update` record appears first and causes
the test to fail.
This change makes the test consistent by retrieving both PublicActivity records
and testing for the existence of the `submission.activate` records in them, not
just relying on the one returned first.
> Address a flaky test with Submissions

- CHANGELOG.md
- app/models/budget.rb
- config/locales/models/budget.en.yml
- spec/features/staff/users_can_create_a_budget_spec.rb
- spec/models/budget_spec.rb
Trello: https://trello.com/c/0OZq4dRU/843-users-can-report-negative-budget-values
BEIS have a requirement to allow negative budget values. This has occurred
due to multi-year budget splitting.
Allow Budgets to have a negative value, but NOT a value of zero.
> (843) Allow Budgets to have a negative value

- app/services/ingest_iati_activities.rb
- db/data/20200730095019_restore_negative_budget_value.rb
- db/data_schema.rb
- spec/services/ingest_iati_activities_spec.rb
Previously, we decided to set these rare occurrences to a penny and then correct their values through the UI. Now we're permitting negative budget values, this is no longer necessary.
> (854) Ingest allows negative budgets

- CHANGELOG.md
- config/locales/models/activity.en.yml
- config/locales/models/budget.en.yml
- config/locales/models/transaction.en.yml
- config/locales/models/user.en.yml
- spec/features/staff/beis_users_can_invite_new_users_spec.rb
- spec/features/staff/users_can_create_a_budget_spec.rb
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_create_a_transaction_spec.rb
- spec/features/staff/users_can_edit_a_budget_spec.rb
- spec/features/staff/users_can_manage_extending_organisation_spec.rb
- spec/services/update_activity_as_project_spec.rb
- spec/services/update_activity_as_third_party_project_spec.rb
- spec/services/update_programme_activity_spec.rb
Trello: https://trello.com/c/JsC9J8lr/840-change-error-messages
The content review required many of the standard ActiveRecord validation error messages to be changed. These required new keys to be added to the translation files. Some of the messages cannot be fully customised - for example, if an Activity title is blank, we say "Enter a title" instead of "Enter a fund/programme/project title" as these error messages are generic across Activity levels.
> (840) Customise validation error messages according to the content review

- CHANGELOG.md
- app/controllers/staff/submissions_controller.rb
- app/views/staff/organisations/show.html.haml
- app/views/staff/shared/submissions/_table.html.haml
- app/views/staff/submissions/show.csv.haml
- app/views/staff/submissions/show.html.haml
- config/locales/default.en.yml
- config/locales/models/submission.en.yml
- spec/features/staff/users_can_view_a_submission_spec.rb
Trello: https://trello.com/c/Ad9Tp69Y/795-delivery-partners-can-view-individual-submissions-and-download-the-data-as-a-single-csv
This ticket was originally to fill the CSV with all the submission data, but we have split it up so that this PR contains the work to add a show page for the Submissions, and a downloadable skeleton of the CSV (headers only).
The next stage is to decide what data goes into the CSV and add that data (future ticket)
> (795) Users can view individual submissions and download a skeleton of the Submission CSV

- config/locales/models/organisation.en.yml
- spec/features/staff/beis_users_can_create_an_organisation_spec.rb
- spec/features/staff/users_can_edit_an_organisation_spec.rb
Trello: https://trello.com/c/JsC9J8lr/840-change-error-messages
Additional error messages related to the content review & missed in https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/550
The Gov.uk style guide requires error messages to be in the format "Enter a(n) {attribute name}" instead of "{attribute name} can't be blank"
> Update Organisation-related error messages according to content review

- terraform/app.tf
During a recent production deploy, the app instances took too long to
spin up which resulting in the deploy being terminated.
The worker instance was already given 120 seconds to start, so let's do
the same for the app instances.
> (869) Get Terraform to wait longer for app to boot

- CHANGELOG.md
- app/controllers/staff/transactions_controller.rb
- app/models/activity.rb
- app/models/submission.rb
- app/models/transaction.rb
- app/policies/transaction_policy.rb
- app/services/create_transaction.rb
- app/services/ingest_iati_activities.rb
- db/migrate/20200803141156_add_associations_between_transactions_and_submissions.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/factories/transaction.rb
- spec/features/staff/users_can_create_a_transaction_spec.rb
- spec/features/staff/users_can_edit_a_transaction_spec.rb
- spec/models/activity_spec.rb
- spec/models/transaction_spec.rb
- spec/policies/transaction_policy_spec.rb
- spec/services/ingest_iati_activities_spec.rb
Trello: https://trello.com/c/Lasw3YS4/836-associate-transactions-to-a-submission
Associate Transactions to Submissions. A Transaction can have one Submission; a Submission can have many Transactions.
When a Transaction is created, associate it with the current Submission for that Delivery Partner & Fund.
Do not allow Transactions to be created if there is no Submission in existence.
> (836) Associate Transactions to a Submission

- .travis.yml
- Gemfile
- Gemfile.lock
- config/initializers/redis.rb
- spec/rails_helper.rb
In the past we set up `mock_redis` to stand in for Redis in the test environment. Unfortunately, when we added the JavaScript tests, Redis gets used once more because the headless browser uses the session store that is connecting to Redis directly, skipping the mocked version.
Because the Redis session store only accepts a list of servers, rather than already-instantiated Redis instances, we can't use `mock_redis` here.
I've replaced `mock_redis` with `fakeredis` gem.  When required in `rails_helper.rb` it replaces `Redis.new` with a fake version, so this works everywhere including the session store.
**To test locally: stop Redis on your local development environment, and the test suite will continue to pass**
> (873) Prevent tests connecting to Redis

- CHANGELOG.md
- app/controllers/staff/submissions_controller.rb
- app/models/activity.rb
- app/policies/submission_policy.rb
- app/presenters/activity_presenter.rb
- app/services/export_activity_to_csv.rb
- app/views/staff/submissions/show.csv.haml
- app/views/staff/submissions/show.html.haml
- spec/features/staff/users_can_view_a_submission_spec.rb
- spec/policies/submission_policy_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/services/export_activity_to_csv_spec.rb
Trello: https://trello.com/c/QLknCpWs/859-the-report-csv-contains-activity-details
In a previous PR we added a basic CSV skeleton for the Submissions (Reports). This PR adds Activity data to this CSV download. Currently all level C & D activities in a Submission are included in the CSV. 
There is also a small refactor here, I have changed the CSV export from HAML to a CSV object sent with event streaming
Note that this should be merged after https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/555 and https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/559 because there is some overlap with functionality (`Activity#associated_fund`) and some changes of names will need to be refactored in.
> (859) The Report CSV contains Activity details

- CHANGELOG.md
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/services/export_activity_to_csv.rb
- spec/features/staff/beis_users_can_edit_a_report_spec.rb
- spec/models/activity_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/services/export_activity_to_csv_spec.rb
Trello: https://trello.com/c/fp8pacDC/864-transaction-actuals-totals-are-included-in-the-csv-download
Add a `transactions_total` method to the Activity model to calculate the sum of all transactions associated to that Activity (thank you @mec for the spike)
Style the total using the ActivityPresenter.
Add the total to the Submission CSV download per Activity line.
> (864) Transaction actuals totals are included in the CSV download

- app/controllers/staff/reports_controller.rb
- spec/features/staff/users_can_view_reports_spec.rb
Trello: https://trello.com/c/PcSYrR3E/891-the-csv-attachment-filename-is-truncated
URL encode the CSV attachment filename so it does not get truncated. Tested on a Mac in Chrome, Safari & FF; hopefully this covers most bases.
> (891) URL encode report CSV filename so it is not truncated

- app/presenters/activity_presenter.rb
- spec/presenters/activity_presenter_spec.rb
Trello: https://trello.com/c/px9jVQ5v/897-report-csv-actuals-value-contains-odd-characters
The data in the CSV output should be as formatting-free as possible. Also the
£ symbol was not being interpreted correctly in all spreadsheet programmes.
Instead of using `number_to_currency`, use simple number formatting to show the
value to two decimal places
> Remove currency symbol from `ActivityPresenter#transactions_total`

- CHANGELOG.md
- app/controllers/staff/reports_controller.rb
- app/models/activity.rb
- app/models/report.rb
- app/presenters/report_presenter.rb
- app/services/export_activity_to_csv.rb
- app/views/staff/shared/reports/_table.html.haml
- config/locales/models/report.en.yml
- db/migrate/20200813102824_add_financial_quarter_and_financial_year_to_reports.rb
- db/schema.rb
- spec/features/staff/users_can_view_reports_spec.rb
- spec/models/report_spec.rb
- spec/presenters/report_presenter_spec.rb
- spec/services/export_activity_to_csv_spec.rb
I've found the resons for storing the financial quarter and year on a report really hard to articulate, and discussion have taken place to drive this work.
To try and summerise:
- In order to label the actuals column with the FQ for the report
- In order to show the relevent forecasts for the report (these will not have been recorded (associated) in the report as they are from the past)
- in order to show the relevent future forecasts we need to know from where to begin
- in order to display data in ways users find meaningful, users ❤️ financial quarters
We are in a odd place at the moment where we are backfilling data into RODA with many quarters worth of data  – I feel like we know this case is an exception and the fact that the 'current report' has no FQ is alright and something we can …
> (890) Reports store their financial quarter and financial year

- app/models/report.rb
- db/data/20200814135953_report_states_are_strings.rb
- db/data_schema.rb
- db/migrate/20200814134116_report_state_stored_as_string.rb
- db/schema.rb
Defining the enum as an array has two drawbacks:
1. the values in the DB have no context for developers as they are
simply numbers
2. less flexibility to allow change as the order of the array matters
By switching to a hash we get around both these drawbacks.
This work also adds an index to state as it is likely the application
will need to sort and display Reports by their state.
We currently have reports in production but they are all 'inactive' so
this work contains a simple data migration to map the stored 0s to
"inactive". Doing this work any later would be far more difficult.
> (refactor) Change the way Report state is stored

- CHANGELOG.md
- app/models/planned_disbursement.rb
- app/models/report.rb
- app/policies/planned_disbursement_policy.rb
- app/services/create_planned_disbursement.rb
- app/services/ingest_iati_activities.rb
- db/migrate/20200812151612_add_association_between_report_and_planned_disbursements.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/factories/planned_disbursement.rb
- spec/features/staff/users_can_create_a_planned_disbursement_spec.rb
- spec/features/staff/users_can_create_a_transaction_spec.rb
- spec/features/staff/users_can_edit_an_planned_disbursement_spec.rb
- spec/models/planned_disbursement_spec.rb
- spec/policies/planned_disbursement_policy_spec.rb
- spec/services/ingest_iati_activities_spec.rb
Trello: https://trello.com/c/GiEQQVOZ/889-associate-planned-disbursements-to-reports
Create an association between Planned Disbursements and Reports, much like we did for Transactions and Reports in https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/555
We assume an `active` Report always exists, in order to associate with Planned Disbursements on create and ingest. 
Add a `:with_report` trait to the `project_activity` factory, to create an associated Report after the Project Activity is created.
> (889) Associate PlannedDisbursements to Reports

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/services/ingest_iati_activities.rb
- app/services/programme_to_iati_status.rb
- app/views/staff/activity_forms/programme_status.html.haml
- app/views/staff/activity_forms/status.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- config/locales/codelists/2_03/iati.en.yml
- config/locales/models/activity.en.yml
- db/migrate/20200803104010_add_programme_status_to_activities.rb
- db/migrate/20200817144853_change_status_to_programme_status_on_form_state.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/helpers/activity_helper_spec.rb
- spec/lib/programme_to_iati_status_spec.rb
- spec/models/activity_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/support/activity_helpers.rb
- spec/support/form_helpers.rb
- vendor/data/codelists/IATI/2_03/activity/programme_status.yml
Trello: https://trello.com/c/jj2Dju4x
After a user research session, users feedback that they are missing some important fields in the activity form in RODA. It was then identified as a priority for them to have the field `programme status` added to the activity form so they can track the status of each activity. Users preferred this status to the previously used `IATI status`, as they are more familiar with the terminology of Programme status. Since IATI status is a requirement for IATI, we will still keep it in the background to ensure the reports follow the IATI standards and pass the IATI validator, but we will not ask the user to introduce an IATI status anymore when they create activities (the form step `status` has been removed and now they are asked for a `programme status` …
> (845) Add `programme status` field to activity form

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/views/staff/shared/activities/_activity.html.haml
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/support/activity_helpers.rb
- spec/support/form_helpers.rb
Trello: https://trello.com/c/vHswa3bj
Now that `programme status` field has been added to the create activity form, the next step was to remove this form step when users create a level A activity (Fund). Users are only required to add a programme status for levels B, C and D. However, despite not asking the user for a `programme status` on Funds we are still setting a default value of `Spend in progress` in the background, as agreed with the client. This will help us avoid potential errors with validations. As a result, the old IATI `status` also gets set in the background, but the user will not see any of those as they are not relevant for them when handling Funds.
To improve the user experience, only for Funds we have removed the `programme status` step form, the field in the view of …
> (895) Programme status form step removed for Funds

- db/migrate/20200819081212_add_programme_status_to_existing_funds.rb
- db/schema.rb
Trello: https://trello.com/c/87YhiGTG
Existing Funds will not have a `programme_status` value, as this field has been introduced just recently. To avoid potential errors, we have agreed to backfill this field on existing Funds to the value `Decided` (code `06`).
This PR contains the schema migration that changes the value from `nil` to `06` for existing Funds.
> (920) Schema migration to backfill `programme_status`

- app/models/report.rb
- app/policies/report_policy.rb
- spec/policies/report_policy_spec.rb
We already have a good understanding of the what state transitions are
valid and which user can make them.
This work updates the report policy and related spec to make it possible
to enforce this understanding and support future work to allow users to
move a report though its state inside the application.
This Miro board speaks to how the state and permission works:
https://miro.com/app/board/o9J_knq_KVg=/
> Update the Report policy

- config/locales/models/planned_disbursement.en.yml
Updated all mentions of "planned disbursement" to "forecasted spend" based on the service language definitions doc
Changed the following:
Title on financials tab
Button on financials tab
"Value" to "Forecasted spend amount" on the page and the financials tab
Both confirmation messages should say "Forecasted spend has been successfully xx"
I think all of these updates still make sense - happy to change if not.
> Changed "planned disbursement" to "forecasted spend"

- CHANGELOG.md
- app/controllers/staff/reports_controller.rb
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/services/export_activity_to_csv.rb
- spec/models/activity_spec.rb
- spec/models/report_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/services/export_activity_to_csv_spec.rb
Trello: https://trello.com/c/n3371hcO/875-aggregated-forecasts-planned-disbursements-are-included-in-the-csv-download
The Report CSV will always contain all Activities associated with a Fund/Organisation pair, whether they had transactions or planned disbursements in the report period or not. But the transaction/planned disburement totals must be scoped to a single Report and its date range, not be the totals for that Activity for all time.
1) Scope the `transactions_total` to a Report & that Report's date range
The new method is called `actual_total_for_report_financial_quarter` for clarity
2) Calculate the total of all Planned Disbursements in a Report's date range
Planned Disbursements scoped to a single Report and that Report's date range are summed and returned in …
> (875) The CSV download contains aggregated forecasts

- CHANGELOG.md
- app/controllers/staff/reports_controller.rb
- app/controllers/staff/reports_state_controller.rb
- app/views/staff/reports/index.html.haml
- app/views/staff/reports/show.html.haml
- app/views/staff/reports_state/activate/complete.html.haml
- app/views/staff/reports_state/activate/confirm.html.haml
- app/views/staff/reports_state/submit/complete.html.haml
- app/views/staff/reports_state/submit/confirm.html.haml
- app/views/staff/shared/reports/_table_inactive.html.haml
- config/locales/models/report.en.yml
- spec/features/staff/beis_users_can_edit_a_report_spec.rb
- spec/features/staff/users_can_activate_reports_spec.rb
- spec/features/staff/users_can_submit_a_report_spec.rb
Previously BEIS users had to fill in the deadline and the application would activate a report, although nice, it was felt we needed a more explicit approach.
This works follow the take action > confirm action > complete action pattern to activate a report and uses the new `reportsStateController` to do so.
As an inactive report can only become active we simply add that case to the controller and update the report, we have the Report policy to manage for who and when this is allowed.
We haven't come up with our first go at the content for this flow yet so none is included beyond the basics - this is by desgin.
If we want to get the content into this PR on there is a mockup of this flow here:
https://miro.com/app/board/o9J_kpe1v2k=/?moveToWidget=3074457348997454374&cot=6
> (912) User can activate reports

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/views/staff/activity_forms/call_dates.html.haml
- app/views/staff/activity_forms/call_present.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- config/locales/codelists/2_03/iati.en.yml
- config/locales/models/activity.en.yml
- db/migrate/20200819131932_add_call_dates_to_activities.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/models/activity_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/services/ingest_iati_activities_spec.rb
- spec/support/form_helpers.rb
Trello: https://trello.com/c/AQTkUKy7
As part of the additional fields needed in RODA, and having identified this one as a priority for the users, we have now added `call open date` and `call close date` to the service. These dates are only present in level C and D activities,
and they relate to the timeline to apply for grants (note that they are not the same as IATI activity dates). As requested by the client, this new field comes in two different steps. On a first step, the DP user will select whether an activity has any calls. If they do have calls, then the second step will be displayed on the form, in which the DP can add both `call open date` and `call close date`. If there are no calls for that activity, the second step will be ignored and the form will move on to the next step. …
> (848) Add `call open` and `call close` dates to activity form

- spec/presenters/activity_presenter_spec.rb
There was a `p result.call_present` on one of the test files that was accidentally
left on the file. This was printing `Yes` when running the tests. This commit
removes the printing line.
> (Fix) `p` statement removed from spec file

- CHANGELOG.md
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/services/export_activity_to_csv.rb
- spec/models/activity_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/services/export_activity_to_csv_spec.rb
Trello: https://trello.com/c/1i9BekH8/877-variance-between-the-actual-and-forecasted-totals-is-included-in-the-csv
Calculate the variance between the actual total (transactions) for an Activity in a Report's date range, and the forecasted total (planned disbursements) for that same Activity in the Report's date range. The method is named `variance_for_report_financial_quarter`. Express this number in the CSV as "Variance".
I have attempted to memoize `variance_for_report_financial_quarter` for performance.
> (877) Variance between the actual and forecasted totals is included in the CSV

- CHANGELOG.md
- app/models/activity.rb
- app/models/report.rb
- app/presenters/activity_presenter.rb
- app/presenters/report_presenter.rb
- app/services/export_activity_to_csv.rb
- spec/models/activity_spec.rb
- spec/models/report_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/presenters/report_presenter_spec.rb
- spec/services/export_activity_to_csv_spec.rb
Trello: https://trello.com/c/Ee0f5VTG/903-a-number-of-future-aggregated-forecast-amounts-are-included-in-the-csv-file
A report has a financial quarter & year, e.g. Q1 2020.
Find the next 4 quarters after this report's quarter, e.g. Q2 2020, Q3 2020, Q4 2020 and Q1 2021
Calculate the forecast totals (planned disbursement totals) for those 4 quarters per Activity. Output these values to the report CSV as future forecast totals.
> (903) The next 4 quarters' forecast totals are included in a report's CSV

- CHANGELOG.md
- config/locales/models/organisation.en.yml
Trello: https://trello.com/c/dm6oA18s
On a previously merged PR we intended to replace all `Create activity` buttons for `Add activity` buttons, as recommended by the content review. Some of the buttons still appeared as `Create activity` due to an unchanged field on a yml
file. This PR is to fix that problem.
> Fix for `Add activity` buttons

- CHANGELOG.md
- app/controllers/staff/reports_controller.rb
- app/controllers/staff/reports_state_controller.rb
- app/views/staff/reports/index.html.haml
- app/views/staff/reports/show.html.haml
- app/views/staff/reports_state/review/complete.html.haml
- app/views/staff/reports_state/review/confirm.html.haml
- app/views/staff/shared/reports/_table_in_review.html.haml
- config/locales/models/report.en.yml
- spec/features/staff/users_can_mark_a_report_in_review_spec.rb
Trello: https://trello.com/c/K6tgKNZv/914-a-beis-user-can-mark-a-report-as-in-review
This is a basic first pass at moving Reports from "submitted" to "in review"
When a Delivery Partner submits a report, it appears on the BEIS user's
dashboard. The BEIS user can then mark as it being "in review" to indicate to
other BEIS users that the report is being looked at.
The UI is very basic and will be iterated upon.
> (914) Enable a BEIS user to mark a submitted report as "in review"

- CHANGELOG.md
- app/controllers/staff/reports_controller.rb
- app/controllers/staff/reports_state_controller.rb
- app/views/staff/reports/index.html.haml
- app/views/staff/reports/show.html.haml
- app/views/staff/reports_state/request_changes/complete.html.haml
- app/views/staff/reports_state/request_changes/confirm.html.haml
- app/views/staff/shared/reports/_table_awaiting_changes.html.haml
- config/locales/models/report.en.yml
- spec/features/staff/users_can_mark_a_report_as_awaiting_changes_spec.rb
- spec/features/staff/users_can_view_reports_spec.rb
Trello: https://trello.com/c/cqMSIb5w/915-a-beis-user-can-mark-a-report-as-awaiting-changes
#601 Must be merged before this PR.
A BEIS user can move a report from "in review" to "awaiting changes". The DP
user will then see their reports awaiting changes on their dashboard.
Because a report can be moved from "in review" to either "awaiting changes" or
"approved", we have used a parameter in ReportsStateController to indicate
which state the report should be moved to.
The UI for this is still very basic and will be iterated upon.
> (915) a BEIS user can mark a report as awaiting changes

- db/data/20200827120801_update_ams_gcrf_programme_parents.rb
- db/data_schema.rb
During the previous data migration we moved activities from projects to programmes to reflect mapping changes.
Unfortunately, we didn't change the parent mappings, which lead to programmes being the parent of other programmes, which shouldn't be possible.
This data migration updates the affected activities to link them directly to the GCRF fund activity instead.
> (941) Fix AMS GCRF programmes hierarchy

- CHANGELOG.md
- app/controllers/staff/reports_controller.rb
- app/controllers/staff/reports_state_controller.rb
- app/policies/planned_disbursement_policy.rb
- app/policies/transaction_policy.rb
- app/views/staff/reports/index.html.haml
- app/views/staff/reports/show.html.haml
- app/views/staff/reports_state/approve/complete.html.haml
- app/views/staff/reports_state/approve/confirm.html.haml
- app/views/staff/shared/reports/_table_approved.html.haml
- config/locales/models/report.en.yml
- spec/factories/report.rb
- spec/features/staff/users_can_approve_a_report_spec.rb
- spec/features/staff/users_can_view_reports_spec.rb
- spec/policies/planned_disbursement_policy_spec.rb
- spec/policies/transaction_policy_spec.rb
Trello: https://trello.com/c/ax4ldF7H/910-a-beis-user-can-approve-a-report
Note: #603 must be merged before this PR
A report in the `in_review` state can be moved into the `approved` state by
BEIS users. Delivery partners can see their approved reports but not edit them
or move them into the approved state.
Transactions and Planned Disbursements associated to an approved report cannot be edited.
> (910) a BEIS user can approve a report

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/models/activity.rb
- app/validators/roda_identifier_validator.rb
- app/views/staff/activity_forms/roda_identifier.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- config/locales/models/activity.en.yml
- db/migrate/20200826090103_add_roda_identifier.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_create_a_project_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/helpers/activity_helper_spec.rb
- spec/models/activity_spec.rb
- spec/support/form_helpers.rb
This set of changes adds the ability to store RODA Identifiers for activities. RODA Identifiers are defined hierarchically, so the ID of a fund becomes a prefix for the IDs of its programmes, and so on down the tree. The complete RODA ID schema is:
{A}-{B}-{C}{D}
where, `{A}`, `{B}`, `{C}`, and `{D}` are the Identifier _fragments_ belonging to level-A, B, C and D activities. These fragments may contain letters, digits, dashes, underscores, and slashes. The combined length of `{A}-{B}` is 18 characters maximum, and `{C}{D}` is at most 21 characters, giving a maximum total length of 40.
Users can add RODA IDs to activities starting with funds, then moving to programmes and so on down the tree. Since validation relies on the length of parent's ID fragment, we only allow an ID to be added …
> (924) Store partner and RODA IDs

- CHANGELOG.md
- app/controllers/staff/reports_state_controller.rb
- spec/features/staff/users_can_submit_a_report_spec.rb
When we introduced the awaiting changes state we missed handling the
transition from `awaiting_changes` to `submitted` in the report state
controller.
Also removes a redundant expectation in the users can submit a
report spec.
> Reports that are awaiting changes can be submitted

- CHANGELOG.md
- app/controllers/staff/reports_controller.rb
- app/views/staff/reports/show.html.haml
- app/views/staff/shared/reports/_table_variance.html.haml
- config/locales/models/activity.en.yml
- spec/features/staff/users_can_view_reports_spec.rb
As a first step towards showing all the changes made in a report in the application itself (rather than just the csv download) we want to show the total forecasted and actual spend and the variance for the reporting financial quarter.
This is also the place where we will allow users to add comments at the activity level in future work.
As we already calculate all the values for the csv this is a small change.
> (927) Show the actual vs forecast variance on the report show page

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/models/activity.rb
- app/views/staff/shared/activities/_activity.html.haml
- app/views/staff/shared/xml/_activity.xml.haml
- config/locales/models/activity.en.yml
- db/data/20200903140938_correct_transparency_identifiers.rb
- db/data_schema.rb
- db/migrate/20200901150652_add_unique_index_on_transparency_identifier.rb
- db/schema.rb
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_create_a_programme_level_activity_spec.rb
- spec/features/staff/users_can_create_a_project_spec.rb
- spec/features/staff/users_can_create_a_third_party_project_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/models/activity_spec.rb
These commits replace our existing method of generating the transparency identifier so that it's generated from the RODA identifier, not from the Delivery Partner identifier. With that change in place, we can make it possible to edit Delivery Partner identifiers again.
When viewing an activity, it is possible to edit its delivery partner identifier.
After setting the RODA identifier, the Transparency identifier is generated.
> (924) Allow Delivery Partner Identifier to be edited

- CHANGELOG.md
- app/controllers/staff/reports_controller.rb
- app/controllers/staff/reports_state_controller.rb
- app/models/report.rb
- app/views/staff/reports/_form.html.haml
- app/views/staff/reports/edit.html.haml
- app/views/staff/reports/index.html.haml
- app/views/staff/shared/reports/_table_active.html.haml
- app/views/staff/shared/reports/_table_approved.html.haml
- app/views/staff/shared/reports/_table_awaiting_changes.html.haml
- app/views/staff/shared/reports/_table_empty.html.haml
- app/views/staff/shared/reports/_table_in_review.html.haml
- app/views/staff/shared/reports/_table_inactive.html.haml
- app/views/staff/shared/reports/_table_submitted.html.haml
- config/locales/models/report.en.yml
- spec/features/staff/beis_users_can_edit_a_report_spec.rb
- spec/features/staff/users_can_activate_reports_spec.rb
- spec/features/staff/users_can_view_reports_spec.rb
- spec/models/report_spec.rb
Whilst working to create the next report automatically (https://trello.com/c/kllPs5cG) I came accross a few issues I felt needed addressing first:
- We had a constraint on Report that meant reports had to be unique for the level A activity in each organisation, this is incorrect and would stop new reports being created an organisation has many reports for the same level A activity.
- Once you get a few reports in different states the report index page becomes visually cluttered, adding empty states to the tables eases this (hopefully)
- When editing a report (adding the description and/or deadline) it is super helpful for BEIS users to also see the organisation, Level A actvity (fund) and financial quarter.
- Because of the way reports work a BEIS user can try to activate an invalid one …
> Fixes to the report journey

- app/controllers/staff/reports_state_controller.rb
- config/locales/models/report.en.yml
- spec/features/staff/users_can_submit_a_report_spec.rb
There was quite a bit of duplication in this controller.
I really like having the policy name and the report state different, I
think it makes things nice and clear. Not wanting to change this meant
having some kind of mapping from state names to policy names – I went
with a hash.
I've renamed the confirm_<state> method to try and better describe the
behaviour and align it with the argument that is passed in (a policy
action name)
I've also changed the key for the Public Activity record, I am confident
this is not an issue as we do not expose public activity records as yet
and we have no report state changes in production either (they are all
inactive).
I added all the state change failure messages to the report.yml locale
file, due to the linear nature of the state change I can't see how …
> Refactor reports state controller

- config/locales/models/report.en.yml
I just noticed this typo in one of the `Report` validation messages while testing something else.
> Correct typo in Report copy

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/views/staff/activity_forms/oda_eligibility.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- config/locales/codelists/2_03/iati.en.yml
- config/locales/models/activity.en.yml
- db/migrate/20200907094528_add_oda_eligibility_to_activities.rb
- db/schema.rb
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/models/activity_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/support/form_helpers.rb
Trello: https://trello.com/c/Kt1vrYSS
As part of the new fields on create activity journey requested by the client, the ODA eligibility has been added to every level activity. Worth noting that `ODA eligibility` is a requirement only for levels C and D activities, but the client suggested we implemented this on all levels for now. They are happy with refining this later if needed.
This new field has two options: `Eligible` and `No longer eligible`. A defaulted to `Eligible` has been implemented, as requested by the client. This field does not get reported to IATI or included in any XML.
This commit introduces the new form step, as well as tests to assert we achieve the desired behaviour.
> (898)`ODA eligibility` form step added to activity

- CHANGELOG.md
- db/data/20200907144609_update_organisation_on_all_programme_activities.rb
- db/data_schema.rb
Trello: https://trello.com/c/2bPBRojL/970-all-level-b-activities-should-have-the-organisation-association-set-to-beis
During a recent data migration, some ingested activities were moved from
"Level C" to "Level B". However their organisation_id was not updated to reflect
the fact that Level B activities always belong to the BEIS organisation, not a
Delivery Partner organisation.
This data migration corrects that oversight; all Level B activities now have
the BEIS organisation as their owning organisation.
> (970) Update the organisation_id of programmes to be the BEIS organisation ID

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/helpers/codelist_helper.rb
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/services/ingest_iati_activities.rb
- app/views/staff/activity_forms/gdi.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- config/locales/codelists/2_03/iati.en.yml
- config/locales/models/activity.en.yml
- db/migrate/20200907141532_add_gdi_to_activities.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/features/staff/users_can_add_benefitting_countries_spec.rb
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/models/activity_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/services/ingest_iati_activities_spec.rb
- spec/support/form_helpers.rb
- vendor/data/codelists/IATI/2_03/activity/gdi.yml
Trello: https://trello.com/c/sjNZ0W6D
`Global Development Impact (GDI)` policy is one of the new fields to be added to the create activity journey. This policy refocuses ODA funding when partnering with certain countries, such as China and India. This is a form step for internal BEIS use. It does not get reported to IATI.
This PR introduces the new form step, along with validations and tests, and a short-term solution for the ingest of this field in the existing data from the trackers.
> (932) Add GDI form step to activity form

- CHANGELOG.md
- app/policies/activity_policy.rb
- app/policies/budget_policy.rb
- spec/features/staff/users_can_create_a_budget_spec.rb
- spec/features/staff/users_can_create_a_project_spec.rb
- spec/features/staff/users_can_create_a_third_party_project_spec.rb
- spec/features/staff/users_can_edit_a_budget_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/features/staff/users_can_manage_implementing_organisations_spec.rb
- spec/features/staff/users_can_view_a_project_spec.rb
- spec/features/staff/users_can_view_activities_spec.rb
- spec/features/staff/users_can_view_an_activity_spec.rb
- spec/features/staff/users_can_view_budgets_on_an_activity_page_spec.rb
- spec/features/staff/users_can_view_third_party_projects_spec.rb
- spec/policies/activity_policy_spec.rb
This work started as trying to update the transaction policy but I soon realised it makes more sense to do the Activity policy first as Budgets, Transactions and PlannedDisbursments are all 'added to' an Activity.
The idea is to set out to make the policy spec document what actions a given user can perform on a given Activity under certain conditions.  The new condition here is the state of the 'current active report' but it turned out we have others that I hope have now been covered.
Activities are a bit wierd because they can be created without a level or parent activity, without which we have limited options for calculating the permissions, ultimately though, users should only edit activities that are 'owned' by their own organisation (through the `organisation` association) so this is …
> (906) Update activity policy

- CHANGELOG.md
- app/controllers/staff/reports_state_controller.rb
- app/models/report.rb
- spec/features/staff/users_can_approve_a_report_spec.rb
- spec/models/report_spec.rb
When the current report is approved we go ahead and create the next report
in the inactive state, ready for BEIS to activate.
The application relies on there only ever being one active report for a
given delivery partner organisation and level A activity so we want the
application to handle the creation of the new one to avoid error.
We also know that due to the nature of the service a report will have to
be approved either in the financial quarter in which it was created or
the following one - in both cases creating the new report upon approval
means that the new report has the correct financial year.
> (964) New reports are created automatically

- app/policies/planned_disbursement_policy.rb
- app/policies/transaction_policy.rb
When there are more than one reports for an organisation and fund we can
be in the position that the policies for transactions and planned
disbursements stop them from being created.
We have work planned to refactor both of these policies, but we also
have a need to add some today for a training session.
To fix the issue short term we make the associated_report only return
reports that are in the editable state of either active or awaiting
changes and not any state that has potential to return reports in other
states that would stop the transactions being added.
This work does not replace the refactor, merely enables us to run
training session today (10 Sep 2020)
> (fix) Transaction and Planned disbursements can be added

- CHANGELOG.md
- app/controllers/staff/reports_controller.rb
- app/views/staff/reports/_form.html.haml
- app/views/staff/reports/edit.html.haml
- spec/features/staff/beis_users_can_edit_a_report_spec.rb
When the financial year and quarter were added to the edit form as
read-only values we had to use a presenter rather than the report
itself.
Something about doing so stops the value of the deadline field showing
in the form. If we switch to the report object itself,everything works
as expected so we instead pass in the report presenter as a local to the
form partial and use that to render the financial quarter and year.
> (1002) Show the deadline on the report edit form

- CHANGELOG.md
- app/helpers/activity_helper.rb
- app/helpers/form_helper.rb
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/views/staff/activity_forms/purpose.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- config/locales/models/activity.en.yml
- config/locales/models/fund.en.yml
- config/locales/models/organisation.en.yml
- config/locales/models/programme.en.yml
- config/locales/models/project.en.yml
- config/locales/models/report.en.yml
- config/locales/models/third_party_project.en.yml
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_manage_activity_sector_spec.rb
- spec/helpers/activity_helper_spec.rb
- spec/helpers/form_helper_spec.rb
- spec/models/activity_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/support/activity_helpers.rb
- spec/support/form_helpers.rb
Trello: https://trello.com/c/09vlNklC
As a request from the client, in order to ensure consistency in how people view the service, we have updated the terminology for activity levels. They now show both the former terminology (`Fund`, `Programme`, `Project`, and `Third-party project`) along with their respective levels (A, B, C, and D), which the users are more familiar with.
This is only a change on the UI, mainly in the translation files, so we can still keep our code without causing much disruption at this moment.
This PR includes changes on the translation files, amendments on the specs, and a custom method for capitalisation when presenting the activity levels in some of the views. It also introduces the updated definitions for each activity level that will be displayed when users …
> (994) Activity hierarchy levels displayed on UI

- CHANGELOG.md
- app/models/report.rb
- app/policies/activity_policy.rb
- app/policies/transaction_policy.rb
- app/views/staff/shared/activities/_transactions.html.haml
- app/views/staff/shared/transactions/_table.html.haml
- spec/features/staff/users_can_create_a_transaction_spec.rb
- spec/features/staff/users_can_edit_a_transaction_spec.rb
- spec/policies/transaction_policy_spec.rb
Inline with the report and activity policy this PR updates the Transaction policy. We take the same approach where we test the policy thoroughly and try to use the spec to document to developers under which conditions a transation can be added or edited.
The UI is then updated to reflect the new policy by showning add and edit UI elements only when they can be used.
I added `EDITABLE_STATES` to the Report model as we have started to use this in multiple places and it feels safer and neater to define which states are considered editable in the Report model instead of when they get used.
> (982) Update transaction policy

- CHANGELOG.md
- app/policies/planned_disbursement_policy.rb
- app/views/staff/shared/activities/_planned_disbursements.html.haml
- app/views/staff/shared/planned_disbursements/_table.html.haml
- spec/features/staff/users_can_create_a_planned_disbursement_spec.rb
- spec/features/staff/users_can_edit_an_planned_disbursement_spec.rb
- spec/policies/planned_disbursement_policy_spec.rb
Hot on the heals of the Transaction policy update, this updates the planned disbursement policy – it's functionally identical right now.
> (1008) Update planned disbursement policy

- CHANGELOG.md
- app/models/planned_disbursement.rb
- app/models/transaction.rb
- app/services/create_planned_disbursement.rb
- app/services/create_transaction.rb
- spec/models/planned_disbursement_spec.rb
- spec/models/transaction_spec.rb
- spec/services/create_planned_disbursement_spec.rb
- spec/services/create_transaction_spec.rb
BEIS users should be able to add transactions and planned disbursements
to an activity when there is no editable report for the activity. Because the report
association is required they cannot as the object is considered invalid.
Make the association optional but validate the presence of the value if
the activity is for a delivery partner.
This change removes the shoulda spec for the report association as it
is now covered by the validations spec i.e. we check that the
association is set or not based on the activity organisation.
> (1010) BEIS users can add entities to activities without a report

- CHANGELOG.md
- app/views/staff/activities/financials.html.haml
- spec/features/staff/users_can_create_a_transaction_spec.rb
- spec/features/staff/users_can_edit_a_transaction_spec.rb
- spec/features/staff/users_can_view_an_activity_spec.rb
- spec/features/staff/users_can_view_transactions_on_an_activity_page_spec.rb
Programmes, Projects and Third-party projects (levels B, C and D) all
have Budgets, Forecasts and Actuals (planned disbursements and
transactions).
Funds (Level A) only have budgets.
The UI should reflect this.
Please note you won't be able to add transactions or planned disbursements unless there is an editabe report or #640 is merged for BEIS users.
> (996) Update activity financials view

- CHANGELOG.md
- app/controllers/staff/activity_comments_controller.rb
- app/controllers/staff/comments_controller.rb
- app/models/activity.rb
- app/models/comment.rb
- app/policies/comment_policy.rb
- app/services/export_activity_to_csv.rb
- app/views/staff/activities/children.html.haml
- app/views/staff/activities/comments.html.haml
- app/views/staff/activities/details.html.haml
- app/views/staff/activities/financials.html.haml
- app/views/staff/comments/edit.html.haml
- app/views/staff/comments/index.html.haml
- app/views/staff/comments/new.html.haml
- app/views/staff/reports/show.html.haml
- app/views/staff/shared/reports/_table_variance.html.haml
- config/locales/models/activity.en.yml
- config/locales/models/comment.en.yml
- config/locales/models/report.en.yml
- config/routes.rb
- db/migrate/20200909131047_create_comments.rb
- db/schema.rb
- spec/factories/comment.rb
- spec/features/staff/users_can_create_a_comment_spec.rb
- spec/features/staff/users_can_edit_a_comment_spec.rb
- spec/features/staff/users_can_view_comments_spec.rb
- spec/models/activity_spec.rb
- spec/models/comment_spec.rb
- spec/policies/comment_policy_spec.rb
- spec/services/export_activity_to_csv_spec.rb
Trello: https://trello.com/c/bgddnlzg/847-delivery-partners-can-add-a-comment-to-an-activity-for-a-report
Miro: https://miro.com/app/board/o9J_knm3rBk=/
Comments are new entity which are associated to an activity and a report. An activity can have many comments, but each comment can only belong to one report.
Delivery partners can add and edit comments. BEIS users can never add or edit comments, although they can view them.
Comments are exported to the Report CSV on the same line as the activity they are related to.
Comments can be added from the report view page. They can also be edited from the report view page.
They can be edited from the activity view page, but not added from there. 
The activity view page showing a list of comments
Adding a comment from the report view page
Creating …
> (847) Delivery Partners can add a comment to an activity for a report

- CHANGELOG.md
- app/controllers/staff/report_budgets_controller.rb
- app/controllers/staff/report_variance_controller.rb
- app/controllers/staff/reports_controller.rb
- app/models/activity.rb
- app/models/budget.rb
- app/policies/budget_policy.rb
- app/services/create_budget.rb
- app/services/ingest_iati_activities.rb
- app/views/staff/reports/_actions.html.haml
- app/views/staff/reports/budgets.html.haml
- app/views/staff/reports/variance.html.haml
- app/views/staff/shared/reports/_table_budgets.html.haml
- config/locales/models/report.en.yml
- config/routes.rb
- db/migrate/20200915101558_add_report_reference_to_budgets.rb
- db/schema.rb
- spec/factories/budget.rb
- spec/features/staff/users_can_edit_a_budget_spec.rb
- spec/features/staff/users_can_view_reports_spec.rb
- spec/models/activity_spec.rb
- spec/models/budget_spec.rb
- spec/policies/budget_policy_spec.rb
- spec/services/create_budget_spec.rb
- spec/services/ingest_iati_activities_spec.rb
As budgets do not appear in the report CSV download (or the trackers) we need a way to review the budgets that have been added in a report.
I've added a tabbed view to the report show page so the variance and budgets can live alongside each other, as per this mockup:
https://miro.com/app/board/o9J_kpLoc7Y=/?moveToWidget=3074457349383556686&cot=12
The Budget policy is an exact copy of the transaction one, I have kept the duplication as I can live with it right now, there are changes that will makes these diverge to come.
I've added a new scope to Activity with a super long name! This is used accross the two tab views so made sense to have it in a single place and as it returns Activities, this felt right.
Like the tabs on Activities, I've kept things really simple so there is some …
> (911) Users can view budgets added in a report

- app/controllers/staff/reports_state_controller.rb
- app/views/staff/reports_state/activate/confirm.html.haml
- app/views/staff/reports_state/approve/confirm.html.haml
- app/views/staff/reports_state/request_changes/confirm.html.haml
- app/views/staff/reports_state/review/confirm.html.haml
- app/views/staff/reports_state/submit/confirm.html.haml
While thinking through some consistency problems in relation to how identifiers and bulk actions are handled, it occurred to me that the `ReportsStateController` is vulnerable to a couple of race conditions that coule occur if two or more people are working on the same report. Descriptions of those conditions are in the commit messages.
> Pass report state as a parameter

- app/controllers/staff/reports_controller.rb
- spec/features/staff/users_can_view_reports_spec.rb
Trello: https://trello.com/c/D4NFGkAA/1015-bug-report-csv-filename-is-empty-if-the-report-has-no-description
While testing, we found that some reports did not have descriptions, and
therefore when downloaded did not have a filename (other than `.csv`).
This commit adds the report financial quarter & year to the filename, so if the
report description is empty there is still *something* in the filename.
> (1015) Add the report financial quarter & year to the CSV filename

- .gitignore
- Gemfile
- app/services/ingest_csv.rb
- app/services/ingest_csv_row.rb
- spec/fixtures/csv/additional_fields.csv
- spec/services/ingest_csv_row_spec.rb
- spec/services/ingest_csv_spec.rb
Given a CSV with the following columns, update the relevant activities with additional information:
- delivery_partner_identifier
- programme_status
- call_open_date
- call_close_date
- gdi
- oda_eligibility
- intended_beneficiaries (containing a `|`-separated list of country names)
- total_applications
- total_awards
**NB: The CSV dataset is *NOT* included in this PR as it contains some data that shouldn't be publicly accessible. Instead, this will be manually copied onto the server before it is manually run.**
This code exists *ONLY* for the purposes of preparing production for real users and will likely be removed once this work is completed.
> (987) Ingest additional fields from CSV

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/helpers/codelist_helper.rb
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/views/staff/activity_forms/collaboration_type.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- app/views/staff/shared/xml/_activity.xml.haml
- config/locales/codelists/2_03/iati.en.yml
- config/locales/models/activity.en.yml
- db/migrate/20200915124739_add_collaboration_type_to_activities.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/features/staff/users_can_manage_collaboration_type_for_activities_spec.rb
- spec/features/staff/users_can_view_an_activity_as_xml_spec.rb
- spec/helpers/codelist_helper_spec.rb
- spec/models/activity_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/support/form_helpers.rb
- vendor/data/codelists/IATI/2_03/activity/collaboration_type.yml
Trello: https://trello.com/c/E95quVyI
`Collaboration type` is a new field required when users create new activities through RODA. It is required for levels B, C, and D. It is optional for ingested activities. The client requested to have this option as radio buttons with a pre-selected
value of `Bilateral`, since it is the most common value for this field on the existing activities. Form builder seems not to allow pre-selected radio buttons (we use pre-selected dropdown menus in RODA, but not radio buttons). To work around this, avoiding having to default a value on the database that could affect level A activities, we are assigning a default value through the `activity_forms_controller`, and only at the moment when we display the `collaboration_type` form step, whenever the value for …
> (851) Add `collaboration type` to create activity form

- db/data/20200916151130_associate_all_ingested_entities_with_reports.rb
Trello: https://trello.com/c/122KiJmo/1009-should-we-associate-all-the-ingested-entities-with-the-current-reports
All ingested Transactions, Budgets and Planned Disbursements need to be associated
with a report in order for them to be editable by Delivery Partners.
This data migration finds all ingested entities, then finds the "Historic data
tracker" report associated with those entities (via their associated activity)
and then assigns them to the correct report.
> (1009) Associate all ingested Transactions, Budgets and Planned Disbursements with a report

- CHANGELOG.md
- app/controllers/staff/report_variance_controller.rb
- app/controllers/staff/transaction_uploads_controller.rb
- app/models/activity.rb
- app/models/report.rb
- app/services/create_planned_disbursement.rb
- app/services/create_transaction.rb
- app/services/import_transactions.rb
- app/views/staff/reports/_actions.html.haml
- app/views/staff/transaction_uploads/_error_table.html.haml
- app/views/staff/transaction_uploads/_upload_form.html.haml
- app/views/staff/transaction_uploads/new.html.haml
- app/views/staff/transaction_uploads/update.html.haml
- config/locales/models/transaction.en.yml
- config/routes.rb
- spec/features/staff/users_can_upload_transactions.rb
- spec/models/report_spec.rb
- spec/services/import_transactions_spec.rb
This allows delivery partner users to upload transactions for a report by uploading a CSV. They work by filling out a template we give them, which contains the required column headings, and the IDs of all the activities they need to report on. The RODA ID is used to identify activities on upload, while the Delivery Partner ID and Name are there for the user's information and are ignored on upload.
This is quite a large PR but the code is mostly fairly boring validation and translation of CSV fields onto database columns, plus a little glue at the end to expose the functionality via the service. I'd recommend reading each commit rather than all the changes at once.
I'd like to check that all the logic for validation and translation the fields is correct, that the right associations between …
> (876) Upload transactions as CSV

- CHANGELOG.md
- app/views/staff/activity_forms/roda_identifier.html.haml
- config/locales/models/activity.en.yml
When entering a RODA Identifier, there's nothing to tell the user where
they are, and the data they enter here is final, so it's both easy and
very costly to make a mistake and enter the wrong thing.
As a quick improvement, we can add the parent activity's RODA identifier
to the page, if the activity has a parent. You can only enter a RODA ID
if the parent activity has one completed, so this is guaranteed to
always have a value to display.
> (998) Display the parent activity's RODA Identifier

- CHANGELOG.md
- config/locales/codelists/2_03/iati.en.yml
- vendor/data/codelists/BEIS/country_to_region_mapping.yml
- vendor/data/codelists/IATI/2_03/activity/recipient_country.yml
Trello: https://trello.com/c/AtIOH9nE
When the client provided us with an up-to-date list of countries and regions to be included in RODA, we updated the existing lists for both, as well as the `country_to_region_mapping` yml file. We missed to include `West Bank and Gaza
Strip` on the list, probably due to ambiguity on the naming, as it appears as `Palestine` in the IATI list, under the same country code.
We are now amending the `recipient_country` list to include this country, under the name `West Bank and Gaza Strip (Palestinian territory)`. This is the name the client wants us to use on the app. In order to be consistent on the changes,
I have modified the IATI country codelist to match this name, as we use this list on the `activity_presenter` to show the info in the activity …
> (1018) `recipient_country` list amended

- CHANGELOG.md
- app/views/staff/reports_state/activate/complete.html.haml
- app/views/staff/reports_state/activate/confirm.html.haml
- app/views/staff/reports_state/approve/complete.html.haml
- app/views/staff/reports_state/approve/confirm.html.haml
- app/views/staff/reports_state/request_changes/complete.html.haml
- app/views/staff/reports_state/request_changes/confirm.html.haml
- app/views/staff/reports_state/review/complete.html.haml
- app/views/staff/reports_state/review/confirm.html.haml
- app/views/staff/reports_state/submit/complete.html.haml
- app/views/staff/reports_state/submit/confirm.html.haml
- config/locales/default.en.yml
- config/locales/models/report.en.yml
- spec/features/staff/users_can_submit_a_report_spec.rb
Trello: https://trello.com/c/6A0C6a5U
The content on the text provided to the users when they are about to change the state of a report or they have just changed it has been updated following the content guidance provided by the client. This gives all users a clear indication
of what will happen and what happens next when changing the state of a report.
At each report state change we have a confirmation page and then a complete page. In order to deliver the functionality, at first we went ahead and built the feature before we had final content for the mini journeys. We are now adding the content. Some examples of final content can be found on the screenshots below.
There is a couple of test examples that needed amendment after the changes in the content. Those changes are also included in …
> (981) Update report state content

- db/data/20200916151130_associate_all_ingested_entities_with_reports.rb
Error: https://rollbar.com/dxw/beis-roda/items/194/?utm_campaign=new_item_message&utm_medium=slack&utm_source=rollbar-notification
The previous iteration of this data migration failed to run on production.
It appeared to run correctly on staging but either failed silently or did
not run because staging did not have any of the correct activity types.
> Amend erroring data migration to associate entities with reports

- app/services/ingest_csv.rb
- app/services/ingest_csv_row.rb
- spec/fixtures/csv/existing_activity.csv
- spec/fixtures/csv/new_activities.csv
- spec/services/ingest_csv_row_spec.rb
- spec/services/ingest_csv_spec.rb
Given a CSV, which includes a `delivery_partner_identifier` and `parent_roda_indentifier_compound` column, ingest activities.
In addition to the above, the following data columns should be provided:
- title
- description
- sector
- programme_status
- planned_start_date
- planned_end_date
- actual_start_date
- actual_end_date
- recipient_country
- flow
- aid_type
- call_open_date
- call_close_date
- gdi
- oda_eligibility
- intended_beneficiaries
- total_applications
- total_awards
NB: The existence of the `parent_roda_identifier_compound` column in the CSV causes us to create activities associated with a parent vs. the existing 'update existing activities with non-IATI fields' behaviour.
> (988) Ingest new activity data from CSV

- CHANGELOG.md
- app/services/convert_financial_value.rb
- app/services/import_transactions.rb
- config/locales/models/transaction.en.yml
- spec/services/convert_financial_value_spec.rb
- spec/services/import_transactions_spec.rb
Monetary values entered in the `Value` column in bulk upload are passed
through the `CreateTransaction` service, which uses `Monetize.parse` to
interpret them. This is much more permissive than we want; it allows
various currency symbols and many different kinds of formatting, whereas
we want to specifically allow this format:
- an optional `£` symbol, followed by
- an optional minus (`-`) symbol, followed by
- at least 1 digit, with comma (`,`) allowed for readability
- an optional decimal point followed by 2 digits
We also cannot just remove the Monetize call, as passing the string
directly through to ActiveRecord results in truncation; a string like
"3a45" is truncated to the value 3.0. We would like any non-numeric
characters in the input treated as an error, as they may represent a …
> Reject non-numeric values in bulk transaction import

- CHANGELOG.md
- app/services/convert_financial_value.rb
- app/services/create_budget.rb
- app/services/create_planned_disbursement.rb
- app/services/create_transaction.rb
- app/services/update_budget.rb
- app/services/update_planned_disbursement.rb
- app/services/update_transaction.rb
- config/locales/models/budget.en.yml
- config/locales/models/planned_disbursement.en.yml
- config/locales/models/transaction.en.yml
- spec/features/staff/users_can_create_a_budget_spec.rb
- spec/features/staff/users_can_create_a_transaction_spec.rb
- spec/services/convert_financial_value_spec.rb
- spec/support/shared_examples/sanitises_monetary_fields.rb
Trello: https://trello.com/c/ZU0SW2pm/1014-when-a-monetary-value-is-supplied-with-letters-in-it-do-not-strip-lettters-and-accept-the-numbers-fail
Previously, letters accidentally entered in the `value` fields for budgets,
transactions and planned disbursements were being stripped and the numbers
accepted.
We would prefer these entries to be rejected as an error instead of silently
stripped and passed through.
Use the `ConvertFinancialValue` to sanitize the values before they are added
to their parent entities, and show a relevant error message if any letters are
present.
> (1014) Do not strip alphabetical characters from values, reject the value instead

- Gemfile
- Gemfile.lock
- app/controllers/staff/activity_forms_controller.rb
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
Trello: https://trello.com/c/KdWvWhzX/872-bug-no-error-message-shown-when-you-dont-select-a-country
Previously we were not showing an error message if the user did not select a
recipient country. Instead a 500 error would be thrown.
If no country was selected, we were attempting to find the associated recipient
region despite the country being blank. This was causing the error.
How, if the country is blank, we assign it to the activity, thereby forcing a
validation error to be shown. We do not try to associate the blank country value
to a region.
> (872) Show an error message if the user does not select a recipient country

- app/controllers/staff/activity_forms_controller.rb
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
This is a repeat of #667, which I removed from `develop` after messing up the history during a `dependabot` merge.
> Show an error message if the user does not select a recipient country

- app/controllers/staff/activity_forms_controller.rb
- config/locales/models/activity.en.yml
https://trello.com/c/ualvREql/1004-locale-string-for-activity-start-and-end-dates-is-missing-an-level-argument
https://trello.com/c/Kj0muayQ/866-wizard-date-steps-optional-fields-dont-match-validation-rules
Update the label on `Actual start date` field to reflect that it is optional only if the Planned start date is present.
Fix the page title on this page to add a missing label attribute.
> (1004) (866) Fix two bugs on dates page

- CHANGELOG.md
- app/views/layouts/application.html.haml
- app/views/public/privacy_policy/index.html.haml
- app/views/shared/_google_tag_manager_service_owner.html.haml
The team want to use Google Analytics and understand which users are
doing what actions to help better understand how users are interacting
with the service.
As we use Google tag manager, the first step is to add the which type of
user is signed in (BEIS or non-BEIS) to the dataLayer so the tag manager
can pick it up and pass it to Google Analytics as a 'dimension'.
The principal is to create a dataLayer object before the tag manager
code is fired and add the data to that.
Although we are adding further identifiers to the tracking, I don't
believe it to be personally identifiable, I have however, made it clear
that BEIS must understand this change and any associated risk.
I originally had this as a boolean 'service_owner` but once in GA it
just would not segment the data the way the team …
> (1013) Report the user type to analytics

- CHANGELOG.md
- app/controllers/staff/organisations_controller.rb
- app/services/find_programme_activities.rb
- app/views/staff/organisations/show.html.haml
- config/locales/models/organisation.en.yml
- spec/features/staff/users_can_view_an_organisation_as_xml_spec.rb
- spec/services/find_programme_activities_spec.rb
The service needs to publish Programme (Level B) activities to IATI.
I first allowed the `FindProgrammeService` to optionally take a fund id and if provided, returns only the programmes for that fund and organisation - I also tidied up this class a little as it felt like it was working harder than  it needed to.
I ended up with quite a 🧙 magaical bit of code to my eye, so I am on the fence about it, the commit message explains, but basically `where` can take nothing as it's condition and not be run (TIL a 'no-op'), so we provide the fund id in a hash or nil and let Rails figure it all out. The method was pretty tough to name so I am wondering if something more approachable would be better - love to hear your views.
Then we move on to the super odd 'organisation controller that returns …
> (1036) BEIS Users can download Programme (Level B) xml

- spec/factories/activity.rb
Trello: https://trello.com/c/2jy2pVG2/1041-activity-factory-sets-incorrect-value-for-gdi
In https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/627
we added the GDI step to the Activity forms. The Activity factory had the
incorrect value of "No" for GDI, when it should be 1-4.
We have amended this to be "4", the equivalent of "No".
> Correct GDI value in Activity factory

- app/views/staff/reports_state/activate/complete.html.haml
- app/views/staff/reports_state/activate/confirm.html.haml
- config/locales/models/report.en.yml
Trello: https://trello.com/c/CvKV2afG/1037-add-content-to-confirm-activation-of-report-beis
Add content to the report activation page. Also change the page layout to be full width.
> (1037) Add content to confirm activation of report

- CHANGELOG.md
- app/services/import_transactions.rb
- spec/services/import_transactions_spec.rb
Trello: https://trello.com/c/R5mTxhrD
While testing transactions uploads, one of the devs realised that the `providing_organisation_reference` value was not getting set on the transaction. We know this is always BEIS, and their IATI reference is `GB-GOV-13`.
We have now amended the code to include this reference when a user uploads transactions on RODA.
I have also changed the way the currency is set in the attributes. It was previously set as a constant for `GBP`, but I noticed that the organisation model gives us `default_currency` as an option, so I thought it would be more appropriate to get the value from the model than from a default constant.
> BEIS reference is set when uploading transactions

- app/policies/planned_disbursement_policy.rb
- app/policies/transaction_policy.rb
- spec/policies/planned_disbursement_policy_spec.rb
- spec/policies/transaction_policy_spec.rb
Trello: https://trello.com/c/t13Un49w/1012-update-transaction-and-planned-disbursement-policies-for-funds
BEIS users are already prevented from creating Transactions and Planned Disbursements on funds via the UI. This PR reinforces those restrictions in the TransactionPolicy and PlannedDisbursementPolicy.
> (1012) Update transaction and planned disbursement policies for funds

- CHANGELOG.md
- app/presenters/activity_csv_presenter.rb
- app/services/export_activity_to_csv.rb
- spec/presenters/activity_csv_presenter_spec.rb
- spec/services/export_activity_to_csv_spec.rb
Trello: https://trello.com/c/ACZgsbLv/1052-in-report-csv-separate-intended-beneficiary-countries-with-a-semicolon
The Intended Beneficiaries on an activity are stored as an array. In the UI we
display the countries as "Country, Country and Country". However in the Report
CSV these need to be expressed as "Country; Country; Country".
This commit introduces an ActivityCsvPresenter which inherits from ActivityPresenter
and overrides `#intended_beneficiaries` to generate the list of countries
separated by a semicolon.
> (1052) Intended Beneficiaries should be separated by a semicolon in report CSV

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
Trello: https://trello.com/c/VCBQEBMr
Updating activities through the wizard should behave in the same way as creation - only validating attributes relevant to the current form step. Currently the wizard behaves differently when creating and updating activities:
- When creating a brand new activity, the wizard validates only the attributes that appear on the current form step, which makes sense
- When updating an activity, we validate against all validation rules, rather than those relevant to the current step.
This was fine when activities could only be entered through the wizard, as each step required the previous steps to all validate before moving on. Now, we have incomplete/invalid activities - so you can be on one page of the wizard, fix the data, and will receive an error message …
> Users can edit invalid activities

- Gemfile.lock
There is a bug in better_errors 2.8.2, where it uses its VERSION
constant without having loaded it first [1]. This is preventing our app
from booting so I'm reverting this version bump until that issue is
fixed.
This reverts commit a6e2172a42abefaf4e2cf5f50762d0d52999def2, reversing
changes made to ce4f953ada4ef1b01db0289f9a161bfe6b20706b.
[1]: https://github.com/BetterErrors/better_errors/issues/483
> Downgrade better_errors to 2.8.1

- CHANGELOG.md
- app/assets/stylesheets/partials/_alerts.css.scss
- app/controllers/staff/reports_controller.rb
- app/controllers/staff/reports_state_controller.rb
- app/models/report.rb
- app/views/layouts/_messages.html.haml
- config/locales/models/report.en.yml
- spec/models/report_spec.rb
- spec/views/staff/shared/message_spec.rb
Our Report objects can only change state if they are vaild and they were only vaild when the deadlne was not in the past. This meant after 12:00 on the day of the deadline, delivery partners could not submit their reports.
This has been fixed here by only validating the deadline when submtted the edit form.
The PR also passes a validation context based on the report state changing, this lets us keep the behaviour that a report must have a description in order to be activated without causes validation issues later.
The second commit adds a way to show Rails flashes as GOVUK error summarys - which in turns allows us to give the user the reason a report could not be activated, see the screen shots.
> (1070) Fix: report object is valid when deadline passed

- doc/architecture/decisions/0008-use-heroku-for-hosting.md
- doc/architecture/decisions/0022-use-govuk-paas-for-hosting.md
- doc/architecture/decisions/0023-use-docker-hub-in-deployments.md
Updates the ADRs for hostig (Heroku > GOVUK PaaS) and adds one to address concerns around using open docker images in deployment.
> (815) Update ADRs for hosting and deployment

- config/environments/test.rb
- doc/utilities.md
- lib/tasks/invalid_activities.rake
- spec/lib/tasks/invalid_activities_spec.rb
- spec/services/find_programme_activities_spec.rb
- spec/services/find_project_activities_spec.rb
- spec/services/find_third_party_project_activities_spec.rb
Trello: https://trello.com/c/kJRwvB56
**Update at 22/10/2020**
We have decided to take a different approach and avoid the changes on the UI (see explanation in commit message). We are now doing a rake task that will get us the list of invalid activities we need to provide the client with. We think this is less risky as it doesn't involve changing the codebase for the UI, and less time-consuming, as we won't need to come back to revert those UI changes.
--------------------------------------------------------------------------------------------------------------------
After adding new fields to the create activity journey, and given the fact that some of these fields were mandatory, we found that there are some activities on production that were created through RODA before these fields …
> (1066) Users can see a list of invalid activities in the index page

- CHANGELOG.md
- app/controllers/staff/planned_disbursements_controller.rb
- app/helpers/form_helper.rb
- app/models/planned_disbursement.rb
- app/presenters/planned_disbursement_xml_presenter.rb
- app/services/create_planned_disbursement.rb
- app/views/staff/planned_disbursements/_form.html.haml
- app/views/staff/shared/xml/_planned_disbursement.xml.haml
- config/locales/models/planned_disbursement.en.yml
- spec/features/staff/users_can_create_a_planned_disbursement_spec.rb
- spec/features/staff/users_can_edit_an_planned_disbursement_spec.rb
- spec/helpers/form_helper_spec.rb
- spec/models/planned_disbursement_spec.rb
- spec/presenters/planned_disbursement_xml_presenter_spec.rb
- spec/services/create_planned_disbursement_spec.rb
- spec/services/ingest_iati_activities_spec.rb
- spec/support/form_helpers.rb
- spec/support/shared_examples/behaves_like_valid_activity_xml.rb
Following on from #692, we remove the fields from the form that collects values we can infer ourselves:
- planned disbursement type is always original (when creating an new one)
- currency is always GBP
- providing organisation is always BEIS
-  we do not collect a recieving organisation
There is a refactor here to store the planned_disbursement_type as an enum, this gives us nice helper methods to use with planned disbursements like `original?` that makes the code a little more readable.
The general principal here is to not remove the columns of data we are now infering, the main reason being we might have values for them in production and it seems wise to keep those for moment.
> (1056) New forecasts only collect the required information

- CHANGELOG.md
- config/locales/codelists/2_03/iati.en.yml
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/services/ingest_csv_row_spec.rb
- spec/support/form_helpers.rb
- vendor/data/codelists/IATI/2_03/activity/gdi.yml
Trello: https://trello.com/c/IidBaA1Y
This PR follows a request from the client. They needed to include one option on GDI for activities that benefit either India or China (or both) but that were created before the GDI policy existed.
Likewise, the option `No` is now presented as `GDI not applicable` as requested by the client. This will be the option users can select for activities benefitting any of the other countries (no China or India).
Specs and factories have also been modified to reflect these changes. There is one spec related to the ingest work, which modification I decided to add on a separate commit. The reason for this is that this work was done by another developer from the team, and now I have introduced an option for `GDI not applicable`, which could conflict with the …
> (1099) GDI options have been modified

- CHANGELOG.md
- app/services/create_user_in_auth0.rb
- spec/support/auth0_helpers.rb
We recently updated the Auth0 gem and I missed a breaking change.
The signature of the `create_user` method has changed; the connection
name, which is just a string that matches the default database
connection in Auth0, comes first and is required and the name of the
user is passed in the options as `name`.
Without this change the application cannot create new users in Auth0.
The application handles the error gracefully as the API simply returns
an error code 'connection not found' that we display to the user.
I settled on not creating a test for this case as I should have spotted the change in the API when I was looking at the dependabot update, I feel the system responded correctly as we were passing the wrong value as the connection. If folks feel differently, please shout and I'll …
> (1180) Fix Auth0 create_user call

- CHANGELOG.md
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/services/ingest_csv_row.rb
- app/views/staff/activity_forms/oda_eligibility.html.haml
- config/locales/codelists/2_03/iati.en.yml
- config/locales/models/activity.en.yml
- db/migrate/20201102105419_change_oda_eligibility_type.rb
- db/schema.rb
- spec/presenters/activity_presenter_spec.rb
- spec/services/ingest_csv_row_spec.rb
- spec/support/form_helpers.rb
- vendor/data/codelists/IATI/2_03/activity/oda_eligibility.yml
https://trello.com/c/a0PhOuZx
We already had `oda_eligibility` as one of the fields in the activity form. On the codebase, this used to be a boolean since we only handled two types of values( `Eligible` and `No longer eligible`). Recently, the client requested to add a new option for this field (`No - was never eligible`), since this allows them to report activities that were never ODA eligible. 
For this we have had to change the type of column `oda_eligibility` is on the database. We have chosen to make it an integer, so we can make this field an enum, which allows us to include the three different options and it also gives us helper methods that could simplify future queries on the database. 
Please, note that the presence of existing data in this column prior to convert it into an …
> (1103) Add `No` to ODA eligibility

- lib/tasks/invalid_activities.rake
- spec/lib/tasks/invalid_activities_spec.rb
Trello: https://trello.com/c/r1Tn9w2s
After supplying the client with a list of invalid activities, we were asked to add the RODA ID of each activity, so the users could group them up and make it easier for them to work on them.
This PR adds this RODA ID for each activity on the csv file, and adds the expectation on the spec file.
> (1192) Adding RODA IDs to invalid activities list

- CHANGELOG.md
- app/models/planned_disbursement.rb
- app/views/staff/planned_disbursements/_form.html.haml
- config/locales/models/planned_disbursement.en.yml
- spec/models/activity_spec.rb
- spec/models/planned_disbursement_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/services/export_activity_to_csv_spec.rb
There should only ever be one original planned disbursement for a given
activity, financial quarter and year. This commit enforces that with a
validation on planned disbursement type that only apples when creating a
new planned disbursement.
This also meant updating a number of specs that are creating multiple
planned disbursements in the same financial quarter.
As there is no field in the UI to link an error to we add the error to
the base and use the GOVUK form builders link_base_errors_to option to
make the link the financial quarter, however there seems to be a bug
with this that the id for the link is not generated correctly, it is
missing the `--error` part- I don't feel that this should block this
work however.
> (1147) Only allow one original planned disbursement

- CHANGELOG.md
- app/models/activity.rb
- app/views/staff/shared/xml/_activity.xml.haml
- spec/models/activity_spec.rb
- spec/support/shared_examples/behaves_like_valid_activity_xml.rb
All activities that BEIS publish have no capital spend on them, however
publishing this fact awards them publish what you fund points – a good
thing.
I added the capital-spend to the Activity model as I feel that it is an attribute, just a static one so I want to document it for developers, as opposed to hiding it away in the view layer.
> (1114) Set capital spend on Activity and export to IATI xml

- app/services/activities/import_from_csv.rb
- config/locales/models/activity.en.yml
- spec/services/activities/import_from_csv_spec.rb
This adds a couple of classes that start to build out the code that will eventually backfill missing activity data. It's heavily influenced by work already done by @jcoglan 
So far it accepts an array of hashes (which will eventually come from a CSV) to update an existing Activity (which is fetched by its RODA ID). 
If a field is blank, it is ignored. If any activities in the array of attribute hashes are missing, then the entire operation fails and the main classes error array is populated.
> (1195) Start building out the Activity import machinery

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/helpers/codelist_helper.rb
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/views/staff/activity_forms/policy_markers.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- app/views/staff/shared/xml/_activity.xml.haml
- config/locales/codelists/2_03/iati.en.yml
- config/locales/models/activity.en.yml
- db/migrate/20201109113715_add_policy_markers_to_activities.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/features/staff/users_can_view_an_activity_as_xml_spec.rb
- spec/helpers/codelist_helper_spec.rb
- spec/models/activity_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/services/ingest_iati_activities_spec.rb
- spec/support/form_helpers.rb
- vendor/data/codelists/IATI/2_03/activity/policy_markers.yml
Trello: https://trello.com/c/hKQ5j2uG
Policy markers are a new field on the activity form requested by the client. IATI considers 12 different policy markers, but BEIS only use 8 of them. These 8 have been added to the form. They share the same 5 answers/values so I have decided to make them `enum` so we can get helper methods that can come handy for future queries. In order to be able to share the enum methods among multiple database columns I am using prefixes as recommended in the [ActiveRecord documentation](https://api.rubyonrails.org/v5.2.3/classes/ActiveRecord/Enum.html)
These markers get reported to IATI, so they have been included on the activity XML and I have checked them against the IATI validator and they pass. Please note, there is only one value we do not report to IATI …
> (1105) Add policy markers to activity form

- app/helpers/codelist_helper.rb
- config/locales/models/activity.en.yml
- spec/helpers/codelist_helper_spec.rb
@MariluzHerrera noticed a bug where hints on some questions were being overridden accidentally (introduced in #706). I've moved the location of hints that override descriptions given in the codelist to somewhere that better describes what they do.
> Change location of overriden hints

- CHANGELOG.md
- app/models/activity.rb
- app/views/staff/activity_forms/parent.html.haml
- spec/models/activity_spec.rb
- Fix parent level strings to return enum values for `level`.
- Fix form hint to use the page content translation string for parent level.
> (1179) Fix activity parent level mapping

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/helpers/activity_helper.rb
- app/helpers/codelist_helper.rb
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/views/staff/activity_forms/sustainable_development_goals.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- config/locales/models/activity.en.yml
- db/migrate/20201029113135_add_sustainable_development_goals_to_activities.rb
- db/migrate/20201111160247_add_sdgs_apply_to_activity.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_create_a_programme_level_activity_spec.rb
- spec/features/staff/users_can_manage_sdgs_for_activities_spec.rb
- spec/features/staff/users_can_view_activities_spec.rb
- spec/helpers/codelist_helper_spec.rb
- spec/models/activity_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/support/form_helpers.rb
Users can report up to 3 Sustainable Development Goals (SDG) for Level B-D activities, in order of relevance.
> (1101) I can report Sustainable Development Goals (SDG) where applicable

- app/services/activities/import_from_csv.rb
- lib/tasks/import_activities.rake
- spec/lib/tasks/import_activities_spec.rb
- spec/lib/tasks/invalid_activities_spec.rb
- spec/services/activities/import_from_csv_spec.rb
- spec/support/rake_helpers.rb
This adds a Rake task to run an Activity import with the command:
```
rake activites:import CSV=path/to/file.csv ORGANISATION_ID=8c3b69ec-1e9c-49ae-8e04-7c5d3826b253
```
This parses the CSV from the path and runs the importer. If the import is successful, the number of added / updated Activities is presented to the user. If there are any errors, these are played back to the user.
I've kept the tests pretty light touch, and only testing the code that gets introduced in the Rake task, as we don't want a whole bunch of CSV files clogging up the test suite, and we'd only be repeating ourselves anyway, as the everything is already tested in the `ImportFromCsv` class.
> (1202) Add a Rake task to run the CSV importer

- spec/lib/tasks/import_activities_spec.rb
- spec/spec_helper.rb
Move the `ClimateControl.modify` from the `around` block and inline them into the relevant tests.
I believe this is interfering with hooks that database_cleaner sets up in order to ensure that the database is cleared between test runs, as I found this also fixed things:
```
config.before(:each, type: :task) do
DatabaseCleaner.strategy = :truncation
end
```
NB: I tried using `--bisect` to find the smallest number of tests needed to recreate the failure and it kept locking up after the first pass. I've fixed this by adding the `shell` bisect runner rather than the default `fork` runner.
> (1247) Fix intermittent test failures

- config/spring.rb
- spec/spec_helper.rb
I recently noticed that my tests were always using the same seed, instead of running in a different order each time, as per the RSpec configuration.
This fix ensures the seed is always regenerated every time, unless the `--seed` switch is passed.
Source: https://github.com/rails/spring/issues/113
> (1246) Ensure tests run in a random order each time

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/helpers/codelist_helper.rb
- app/models/activity.rb
- app/views/staff/shared/activities/_activity.html.haml
- config/locales/models/activity.en.yml
- spec/features/staff/users_can_add_benefitting_countries_spec.rb
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_create_a_programme_level_activity_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/features/staff/users_can_manage_activity_geography_spec.rb
- spec/helpers/codelist_helper_spec.rb
- spec/support/form_helpers.rb
- vendor/data/codelists/IATI/2_03/activity/intended_beneficiaries.yml
- vendor/data/codelists/IATI/2_03/activity/recipient_region.yml
Trello: https://trello.com/c/M9FaDIxY
A decision has been made with the client that in order to facilitate Q3 reporting we are going to try replicate the behaviour we have seen on the trackers for the geography/intended beneficiaries step. For this we are now making `intended_beneficiaries` an optional step on all cases (included when user selects `recipient_region`) and we will now display a full list of all countries approved by OECD-DAC regardless of the region the user has selected. This is to reflect what we have seen on the trackers where users will select countries from different regions even if they have selected a specific region.
We are keeping the limit to 10 countries as this is the expectation we have set with BEIS.
We are also adding the missing regions back into the …
> (1135) Fix intended beneficiaries for q3

- CHANGELOG.md
- app/models/activity.rb
- app/services/activities/import_from_csv.rb
- config/locales/models/activity.en.yml
- lib/tasks/import_activities.rake
- spec/lib/tasks/import_activities_spec.rb
- spec/services/activities/import_from_csv_spec.rb
This adds the remaining missing fields to the activity importer. I've added each field (or group of fields) on a commit by 
commit basis, so there's a lot of commits, but should hopefully make things easier to follow.
> (1203) Add missing fields to the activity importer

- db/data/20201125123809_approve_historic_reports.rb
We have a set of reports with no financial quarter; these represent the
sets of "historic" data we imported for an organisation during
onboarding, before they began using RODA. They are considered to predate
all quarterly reports, for the purposes of recording the history of our
data.
New data entered via RODA should _never_ be assigned to these reports.
Many objects like transactions and forecasts are automatically linked to
the current "editable" (active or awaiting_changes) report for that
organisation, and having these "historic" reports in an editable state
allows data entered via RODA to be linked to them.
By marking them as approved, we prevent the RODA service linking new
data to them, so we can only add data to them by explicitly choosing to
do so via an ingest process.
> Mark all "historic" reports as approved

- CHANGELOG.md
- app/services/activities/import_from_csv.rb
- app/services/export_activity_to_csv.rb
- app/services/programme_to_iati_status.rb
- config/locales/codelists/2_03/iati.en.yml
- config/locales/models/activity.en.yml
- spec/lib/programme_to_iati_status_spec.rb
- spec/services/activities/import_from_csv_spec.rb
- spec/services/export_activity_to_csv_spec.rb
- vendor/data/codelists/IATI/2_03/activity/programme_status.yml
- Add a new activity status: "Paused"
- Fix typos in the hint text
- Ensure we're using "Activity status" and not "Programme status" across any user-facing pages
> (1044) Activity status options and UI

- CHANGELOG.md
- app/services/activities/import_from_csv.rb
- spec/services/activities/import_from_csv_spec.rb
This contains a couple of changes to the Activity importer after it came into contact with reality:
- Changed the accepted date format to DD/MM/YYYY
- Separated intended beneficiaries by `|`, rather than `;`
> (1259) Importer format tweaks

- app/models/activity.rb
- db/seeds/activity.rb
- spec/factories/activity.rb
- spec/models/activity_spec.rb
Adds the following methods on Activity:
- `is_gcrf_funded?`
- `is_newton_funded?`
These assume that GCRF and Newton fund activities have RODA IDs "GCRF" and "NF" respectively, which is how they are set up in production. I've also updated `db/seeds/activity.rb` to reflect this.
Additionally, I've added two new FactoryBot traits to create GCRF and Newton fund activities with the correct attributes to make these methods work, e.g.
- `create(:fund_activity, :gcrf)`
- `create(:fund_activity, :newton)`
**NB: This was extracted out of https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/760 to unblock further work which relied on these methods.**
> (1100) Add methods to determine if activity is funded by GCRF or Newton

- CHANGELOG.md
- app/presenters/planned_disbursement_presenter.rb
- app/views/staff/shared/planned_disbursements/_table.html.haml
- config/locales/models/planned_disbursement.en.yml
- spec/presenters/planned_disbursement_presenter_spec.rb
This simplifies the view of forecasts, to show the quarter rather than start and end dates, the value, and no other columns.
> (1055) show forecast quarter and value

- db/migrate/20201125160306_prevent_null_planned_disbursement_scope.rb
- db/schema.rb
The "scope" of a forecast (planned disbursement) is the thing it relates
to: the object you plan to spend money on. A forecast is a plan to spent
money on a certain activity in a certain quarter, and so the fields
describing that object should not be nullable.
This migration prevents the parent_activity_id, financial_quarter, and
financial_year from being NULL. No records have NULL in these columns in
production, so this migration should deploy successfully.
> Prevent forecast scopes from being NULL

- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_create_a_programme_level_activity_spec.rb
Since the calendar ticked over to 2020-12-01, the dates we enter in the tests are now over 10 years ago and therefore invalid, so any time we run the test suite, the tests will break 🤦
> Fix tests in dates

- CHANGELOG.md
- app/models/activity.rb
- app/models/report.rb
- app/presenters/activity_presenter.rb
- app/presenters/report_presenter.rb
- app/services/export_activity_to_csv.rb
- app/services/planned_disbursement_overview.rb
- spec/features/staff/users_can_view_reports_spec.rb
- spec/models/activity_spec.rb
- spec/models/report_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/presenters/report_presenter_spec.rb
- spec/services/export_activity_to_csv_spec.rb
- spec/services/planned_disbursement_overview_spec.rb
- spec/support/reporting_cycle.rb
This PR changes how `Activity#forecasted_total_for_report_financial_quarter` and therefore `Activity#variance_for_report_financial_quarter` work. Previously they were summing all the `planned_disbursements` values for the given activity and date range, by generating a date range from the given `Report`'s `created_at` field, and then calling `Activity#forecasted_total_for_date_range` with that date range.
Now, we use the `Report`'s `financial_{quarter,year}` fields, not `created_at`, to determine which forecasts we're interested in, and we use the version of that forecast that was current at the time of the given report. As we're now storing multiple versions of a forecast for a given activity and quarter, we need to grab the latest version as of the given report, not sum the value over …
> (1055) calculate variance by report history

- db/migrate/20201127105312_restrict_report_states.rb
- db/schema.rb
The state machine that reports operate looks like this:
+-- awaiting_changes <--+
|                       |
|                       |
V                       |
inactive ------> active ------> submitted ------> in_review
|
|
V
approved
During the `active` and `awaiting_changes` states, the delivery partner
is allowed to change the report's contents -- these states are
"editable".
We added an index to allow only one report to exist in this state at a
time, for each set of reports scoped by (fund_id, organisation_id). The
purpose of this is to ensure the report sequence represents a totally
ordered history, because you can't have two editable reports open
concurrently that partner-entered data could be assigned to.
The problem is that this doesn't fully ensure the history is totally
ordered. …
> Restrict all potentially concurrent report states to one per series

- CHANGELOG.md
- app/services/activities/import_from_csv.rb
Before, we were validating country codes from the recipient_country and intended_benificiaries codelists, which have the countries that are _currently_ valid. As we are importing historic data, we want to validate against **all** country codes, not just countries that are currently allowed to be added.
> (1264) Validate countries from complete country list

- app/models/planned_disbursement.rb
- app/services/planned_disbursement_history.rb
- app/services/planned_disbursement_overview.rb
- spec/services/planned_disbursement_history_spec.rb
- spec/services/planned_disbursement_overview_spec.rb
These changes are required in order to unblock #773, and they also improve how forecast entry works for end users. The commits go into more detail on the implementation, but the gist is:
When we see a value of `0` in an imported CSV, or when the user enters this value on the site, we should interpret this as saying there is no spending planned for that quarter. In general, we don't want to delete history, and so we handle this by storing the `0` so that it supersedes previous historical values. We avoid displaying zero-valued forecasts on the site, so from the user's point of view they're effectively deleted.
There are some exceptions to this behaviour:
- If there are no existing forecast records stored for that activity and quarter, then we ignore the input rather than storing a record …
> Handle zero values in planned disbursement history

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/helpers/activity_helper.rb
- app/services/activities/import_from_csv.rb
- spec/services/activities/import_from_csv_spec.rb
This adds the policy marker fields for import. We want to treat blank fields as “not_assessed”, but the way the convertor works at the moment, we skip any blank fields. 
I’ve got round this by adding a constant called `ALLOWED_BLANK_FIELDS`. Rather than just checking a field is present before converting it, we additionally check is a field is in the `ALLOWED_BLANK_FIELDS` constant too. This way we can convert any fields that are left blank to read as `not_assessed`
> (1261) Importer can import policy markers

- CHANGELOG.md
- app/services/activities/import_from_csv.rb
- spec/services/activities/import_from_csv_spec.rb
This was missed off #754. Just adding the ODA Eligibility Lead to the importer.
> (1298) Import ODA Eligibility Lead

- app/services/import_planned_disbursements.rb
- app/services/planned_disbursement_history.rb
- script/import_forecasts.rb
- spec/services/import_planned_disbursements_spec.rb
- spec/services/planned_disbursement_history_spec.rb
This PR adds a script that lets us import forecast data into the Q2 reports using a command-line script and CSV files. The behaviour of the import is described in detail in the commits. We plan to split the input data into one file per fund per delivery partner, so that each file's data can be assigned to a specific report. The interface for specifying which report to use is given in the last commit.
> (1213) developers can import forecasts

- lib/tasks/shellcheck.rake
Currently, import_forecasts.rb is causing Shellcheck to fail when run via `script/test`. I've updated the Rake task to ignore any Ruby files that are in the `script` directory.
> Ignore Ruby files when running Shellcheck

- CHANGELOG.md
- app/models/activity.rb
- app/models/implementing_organisation.rb
- app/services/activities/import_from_csv.rb
- config/initializers/active_support_deprecation_fix.rb
- config/locales/models/implementing_organisation.en.yml
- doc/activity-csv-importer.md
- spec/factories/activity.rb
- spec/models/activity_spec.rb
- spec/models/implementing_organisation_spec.rb
- spec/services/activities/import_from_csv_spec.rb
Add the implementing organisation fields to `Activities::ImportFromCsv`:
- Implementing organisation name
- Implementing organisation reference
- Implementing organisation sector (aka organisation type)
If all of the above are blank, we don't create an associated `ImplementingOrganisation`. However, if either "Implementing organisation name" or "Implementing organisation sector" are provided, these BOTH need to be present and valid to import the row correctly.
**NB: If an activity has more than one associated `ImplementingOrganisation`, these are all deleted and replaced with a single one when imported, which is by design. Obviously, this will need to work differently once end-users are able to use the importer directly.**
> (1268) Import can create an activity implementing organisation

- spec/lib/tasks/invalid_activities_spec.rb
This previously assumed that the first row of the generated CSV always referenced the first activity the spec created, but this was often not the case.
Now, we pull out specific rows to have expectations against.
> (1307) Fix intermittent test failure on invalid activities rake task

- CHANGELOG.md
- app/services/activities/import_from_csv.rb
- spec/services/activities/import_from_csv_spec.rb
Adds the following fields that were missing from the activity importer:
- BEIS ID (`beis_id`)
- UK DP Named Contact (NF) (`uk_dp_named_contact`)
- NF Partner Country DP (`country_delivery_partners`)
> (1250) Add new fields to the activity importer

- CHANGELOG.md
- app/views/layouts/application.html.haml
- config/locales/views/footer.en.yml
- spec/features/user_can_view_static_pages_spec.rb
- Add link to the support site in footer
- Fix minor typos in specs
> (1306) Add link to the support site in footer

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/helpers/codelist_helper.rb
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/services/activities/import_from_csv.rb
- app/services/programme_to_iati_status.rb
- app/views/staff/activity_forms/programme_status.html.haml
- config/locales/codelists/2_03/iati.en.yml
- config/locales/codelists/BEIS/activity.en.yml
- db/migrate/20201208093803_change_activity_programme_status_to_enum.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_create_a_programme_level_activity_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/lib/programme_to_iati_status_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/services/activities/import_from_csv_spec.rb
- spec/support/form_helpers.rb
- vendor/data/codelists/BEIS/programme_status.yml
This updates the Programme Status field to be an enum, rather than a string. I've also tweaked the codelists to be in the BEIS folders, as these codes are actually BEIS, not IATI.
I've dispensed with my usual mantra of making sure all the tests pass for each commit, as there are quite a few changes here, and I wanted to make sure I explained everything I'd done, instead of lumping everything in as one commit, which would make it tricky to explain everything in a neat and tidy narrative.
> (1305) Change Programme Status field to an enum

- db/migrate/20201208093803_change_activity_programme_status_to_enum.rb
When this migration ran, some of the programme statuses were ending up being `nil` unexpectedly.
This is because calling `Integer` with a zero-prefixed number is treated as octal, so "08" and "09" are invalid, and `exception: false` was causing them to be set to `nil`
> (1305) Fix programme status enum migration

- db/data/20201209164802_link_project_forecasts_to_reports.rb
In the most recent deployment, part of the logic of the data migration
`20201124145240_link_forecasts_to_reports` failed to run, specifically
this section:
level_c_or_d_forecasts.where(report_id: nil).each do |planned_disbursement|
reports = historic_reports_for_activity(planned_disbursement.parent_activity)
if reports.count == 1
planned_disbursement.update!(report: reports.first)
end
end
The problem with this is the call to `update!` did not work, because
this migration ended up in a deployment where the PlannedDisbursement
model gained a new restriction on updates:
attr_readonly :report_id
This makes the call to `update!` fail silently: it is not an error to
update a read-only column, the request is simply ignored. The main
instance-level alternative is `update_column`, which raises an …
> Link level C/D forecasts to reports

- CHANGELOG.md
- Dockerfile
- Bundler version used by Docker locked to 2.1.4
Travis builds started failing on 10 Dec 2020.
The failure occurs when installing the gem `libv8`: `Failed to build gem native extension.`
This coincided with bundler version 2.2.0 becoming the default, instead of 2.1.4.
Our Dockerfile didn’t specify a version.
I propose to resolve this in the first instance by locking bundler to 2.1.4, known to work with libv8.
N/A
> (1316) Lock bundler version to 2.1.4

- CHANGELOG.md
- app/services/export_activity_to_csv.rb
- spec/services/export_activity_to_csv_spec.rb
Change the order of the CSV report file to match the data migration template and add the following columns which were previously missing:
- Free Standing Technical Cooperation (`fstc_applies`)
- SDG 1 (`sdg_1`)
- SDG 2 (`sdg_2`)
- SDG 3 (`sdg_3`)
- GCRF Challenge Area (`gcrf_challenge_area`)
> (1200) Add missing fields to the CSV export

- CHANGELOG.md
- app/presenters/transaction_presenter.rb
- app/views/staff/shared/transactions/_table.html.haml
- config/locales/models/transaction.en.yml
- spec/features/staff/users_can_view_planned_disbursements_spec.rb
- spec/features/staff/users_can_view_transactions_on_an_activity_page_spec.rb
- spec/models/planned_disbursement_spec.rb
- spec/presenters/planned_disbursement_presenter_spec.rb
- spec/presenters/transaction_presenter_spec.rb
- spec/support/form_helpers.rb
Display changes to the Financials tab of an activity:
- Remove currency, transaction type, disbursement channel, and providing organisation name from the transactions table
- Replace transaction date with the financial quarter and year computed from the date
Incidental changes:
- Add missing spec for the method that displays the financial quarter and year of forecasts
> (1299) Actuals/transactions summary similar to forecast summary

- CHANGELOG.md
- app/controllers/staff/transactions_controller.rb
- app/models/transaction.rb
- app/presenters/transaction_presenter.rb
- app/views/staff/transactions/_form.html.haml
- config/locales/models/transaction.en.yml
- spec/features/staff/users_can_create_a_transaction_spec.rb
- spec/features/staff/users_can_edit_a_transaction_spec.rb
- spec/models/transaction_spec.rb
- spec/presenters/transaction_presenter_spec.rb
- spec/support/form_helpers.rb
Trello: https://trello.com/c/cPiODeqP
The current flow for reporting a transaction asks users to complete lots of fields, not all of which are needed. We can save users time and effort by streamlining the form.
Our proposed approach is to remove a number of fields that can be autopopulated by RODA in case they are needed. This PR removes the fields that are not necessary in both the `Add a transaction` form and the transaction details page, but retaining them in the data model. 
I have also modified the specs to reflect these changes.
> (1300) Simplify transactions form

- db/data/20201209112603_transactions_reflect_actual_disbursements.rb
The definition of actuals/transactions has changed over time and we need
to update production data to reflect this. There are two parts to this
problem:
- Some transactions are included in the data which do not fit our
definition, and they need to be removed.
- Some transactions are labelled incorrectly, and they need to be
relabelled to fit our definition.
Any transactions of type 'incoming commitments' (code `11`) and
'outgoing commitments' (code `2`) should be deleted
All transactions in the database should be of type 'disbursement' code
`3`. To achieve this we need to change the type for 'expenditure' (code
`4`) and 'credit guarantee' (code `10`) to code `3`.
> (1297) Update transactions to reflect actual disbursements

- app/models/report.rb
- app/services/export_activity_to_csv.rb
- spec/models/report_spec.rb
- spec/services/export_activity_to_csv_spec.rb
The changes are covered by the commit messages, but to summarise them: we are changing the forecast data included in exported activity CSV.
Before this change, the export includes forecasts for the _four_ quarters following _today's date_.
After this change the export includes forecasts for the _twelve_ quarters following _the date of the report_.
> (1318) export next twelve quarters forecasts

- CHANGELOG.md
- app/controllers/staff/transaction_uploads_controller.rb
- spec/features/staff/users_can_upload_transactions.rb
Trello: https://trello.com/c/V0k57Ky5
On the CSV report, we were showing the activity description for the column `activity name`. The activity title would be more appropiate in this case. The activity title is only shown here to help guide users, we do not use this column from the template during import.
Specs have been modified accordingly.
> (1098) CSV template now shows activity title

- app/controllers/staff/activities_controller.rb
- app/controllers/staff/activity_financials_controller.rb
- app/models/activity.rb
- app/views/staff/organisations/show.xml.haml
- spec/features/staff/users_can_view_an_activity_as_xml_spec.rb
- spec/models/activity_spec.rb
The intent of this PR is to amend all places in the application that display planned disbursements so that they only display the latest value for each quarter, rather than all the records linked to an activity. Some of those records will represent old historical data that has been superseded by newer entries.
I have amended the instances of this that I have found but I would like to know if there are others I've missed. I have removed the `Activity#planned_disbursements` association to discourage people from accidentally rendering all the historical records -- we should use `Activity#latest_planned_disbursements` instead.
> Update planned disbursement usage

- CHANGELOG.md
- app/services/activities/import_from_csv.rb
- spec/services/activities/import_from_csv_spec.rb
I'll be honest and say I am struggling to follow how the
ImplementingOrganisationBuilder is working, but I do know that when
trying to import real data to production we have some issues.
I've written the tests to reproduce the issues and get around them,
although I feel like there is probably a better approach than this, with
time in short supply to get these imports done I think this potential
work-around is good enough.
I believe the issues are:
When the importer is creating an activity it assumes the import row will
have the details to make an implementing organisation and this is not
always the case.
When the importer is updating an existing activity it assumes the
activity has an existing implementing organisation or that the import
row has the details to create one, again this is …
> Importer handles no implementing organisation

- CHANGELOG.md
- config/locales/codelists/BEIS/activity.en.yml
Trello: https://trello.com/c/qg4g3Xyd
One of the options for programme status (`Stopped`) was not displaying correctly on the activity details page. We were getting an error that the translation was missing from the file. This was caused by a typo on the key for this option.
> (1311) Fix bug on `programme_status` translation file

- CHANGELOG.md
- app/models/activity.rb
- app/validators/end_date_after_start_date_validator.rb
- config/locales/models/activity.en.yml
- spec/models/activity_spec.rb
- spec/validators/end_date_after_start_date_validator_spec.rb
Trello: https://trello.com/c/MYdDqivE
The service currently allows users to enter planned end date which is earlier than planned start date. We need to introduce validation to prevent this from happening, since it is more likely that users will accidentally introduce incorrect information when creating or updating an activity. 
The validator in this PR makes sure that `planned_end_date` is after, or at least the same, than `planned_start_date`
> (1093) Planned end date cannot be earlier than planned start date

- .github/workflows/ci.yml
- .travis.yml
- CHANGELOG.md
- Dockerfile
- docker-compose.test.yml
- script/cibuild
- script/setup
- script/terraform_test
This moves the CI to Github Actions. This should hopefully speed up build times, as well as starting the process of moving away from Travis (and paying them money), as well as keeping the CI closer to the code.
I've made a couple of tiny tweaks to the Docker config, mainly removing volumes from the docker-compose config, and adding a dependency to the test layer of the Dockerfile. This shouldn't have any impact on the project, as I don't think the docker-compose config is being used by anyone locally (shout if it is!).
I've added a couple of secrets to the Github config - namely the Coveralls Token and the AWS config (so we can get the Terraform testing working). 
Next stage is to get the deploy working, but I think it'll be better to do this in a seperate PR, once we're happy with this.
> Move CI to Github Actions

- CHANGELOG.md
- app/models/organisation.rb
- spec/factories/organisation.rb
- spec/models/organisation_spec.rb
Trello: https://trello.com/c/gfrNbdqZ
To prevent BEIS users from accidentally duplicate an organisation, we are now introducing validation on the Organisation model to make the name field unique, regardless of case sensitivity.
> (1090) Organisation names must be unique

- spec/features/staff/users_can_upload_transactions_spec.rb
While I was investigating something else, I noticed that this spec was not named correctly, and actually failing. I've fixed the test to not worry about the order of the array, and also renamed the file, so it runs as part of the main test suite. I think this code is already touched in other specs, so I don't think it'll improve the coverage
> Fix spec that wasn't running

- app/helpers/codelist_helper.rb
- app/services/activities/import_from_csv.rb
- app/views/staff/activity_forms/oda_eligibility.html.haml
- spec/helpers/codelist_helper_spec.rb
- spec/services/activities/import_from_csv_spec.rb
- vendor/data/codelists/BEIS/oda_eligibility.yml
Trello: https://trello.com/c/hXMGMMGf
For consistency throughout the service, we are now going to codify the options for `oda_eligibility`, using numbers instead of strings. This field is already an enum on the DB, so the changes on this PR are small modifications of the data in the yaml file and how we use this file to display the different options in the UI.
Likewise, we want to be consistent and ask users to provide codes when we can, instead of strings. Until now, `oda_eligibility` on the CSV import work was taken as a string. We are now collecting the numeric values instead. This carries a few changes on the importer tool, along with amendments to the specs.
I believe a DB migration is not needed since we already did one when we changed `oda_eligibility` column in the DB from a …
> (1248) Codify ODA Eligibility

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/helpers/date_helper.rb
- config/locales/models/activity.en.yml
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_create_a_programme_level_activity_spec.rb
- spec/features/staff/users_can_create_a_project_level_activity_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/helpers/date_helper_spec.rb
- Show error message when the user tries to enter an invalid date on the `dates` step. Covers `planned_start_date`, `planned_end_date`, `actual_start_date`, `actual_end_date`
We are not able to reflect to the user what it was that they typed in. We are already swimming against Rails a bit, so it would take more effort and possibly make a more brittle feature if we tried to do that.
No feedback was given to the user.
> (1048) Show error message when user enters invalid dates

- CHANGELOG.md
- app/services/import_transactions.rb
- config/locales/models/transaction.en.yml
- spec/features/staff/users_can_upload_transactions_spec.rb
At the moment, if a cell contains an invalid (i.e. non-UTF-8) character, we get a 500 error, because the template code attempts to show the value of the cell, and this raises an `Encoding::CompatibilityError`. We can get around this by catching that specific error and forcing the encoding of the cell. We can also display a slightly more friendly error back to the user. The wording is up for debate - it can proably be improved!
> Show error when cell contains invalid characters

- CHANGELOG.md
- app/services/import_transactions.rb
- spec/features/staff/users_can_upload_transactions_spec.rb
- spec/services/import_transactions_spec.rb
- Transaction importer sets description from attributes
- Transaction importer does not process disbursement channel
N/A
> (1320) Update the transaction importer

- .github/workflows/ci.yml
- .rspec
This adds the Gemfile.lock and package-lock.json files to calculate the validity of the cache. At the moment, the cache is only refreshed if the Dockerfile changes, meaning that if a Ruby / JS dependency changes, we have to run the whole bundle install again when building the container. 
Now when a new dependency is added / updated (usually on Dependabot PRs), we do a fresh build of the container and upload the cache. This shaves a good 3 - 4 minutes off subsequent builds.
> Cache against dependencies

- CHANGELOG.md
- app/controllers/staff/planned_disbursements_controller.rb
- config/locales/models/planned_disbursement.en.yml
- spec/features/staff/users_can_create_a_planned_disbursement_spec.rb
- spec/features/staff/users_can_edit_a_planned_disbursement_spec.rb
- Show error messages when the user tries to enter invalid values for a forecasted spend. Covers financial quarter being in the past and forecast value being an invalid number.
Server error
> (1335) Handle forecasted spend errors

- CHANGELOG.md
- app/services/import_transactions.rb
- spec/features/staff/users_can_upload_transactions_spec.rb
- spec/services/import_transactions_spec.rb
Update `ImportTransactions` so it expects dates in the `dd/mm/yyyy` format that
Excel uses when exporting a CSV.
> (1157) Transaction uploader expects dates in `dd/mm/yyyy` format

- spec/features/staff/beis_users_can_edit_a_report_spec.rb
- spec/features/staff/users_can_create_a_planned_disbursement_spec.rb
- spec/models/activity_spec.rb
A couple of specs have started failing because we're now in another financial quarter, I've fixed these by using Rails's built in `travel_to` functionality to travel to a date where the tests will pass.
@CristinaRO also pointed out another test that will fail in the [Trello card](https://trello.com/c/rbYJza9l/1342-some-specs-are-written-in-a-time-brittle-way?menu=filter&filter=email), so I've fixed that too.
> Fix time sensitive specs

- CHANGELOG.md
- app/models/activity.rb
- app/services/activities/import_from_csv.rb
- app/services/export_activity_to_csv.rb
- app/services/update_activity_as_fund.rb
- app/services/update_activity_as_programme.rb
- app/services/update_activity_as_project.rb
- app/services/update_activity_as_third_party_project.rb
- app/views/staff/shared/xml/_activity.xml.haml
- db/migrate/20210105131930_remove_funding_organisation_fields.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_create_a_programme_level_activity_spec.rb
- spec/models/activity_spec.rb
- spec/services/activities/import_from_csv_spec.rb
- spec/services/update_activity_as_fund_spec.rb
- spec/services/update_activity_as_project_spec.rb
- spec/services/update_activity_as_third_party_project_spec.rb
- spec/services/update_programme_activity_spec.rb
- spec/support/shared_examples/behaves_like_valid_activity_xml.rb
This PR removes the `funding_organisation_*` fields, because all Activities are funded by BEIS, and all level A funds are not reported to IATI anyway. Now we just return the Service Owner (which in our case will always be BEIS)
> (1313) Refactor away `funding organisation`

- CHANGELOG.md
- lib/financial_period.rb
- spec/features/staff/users_can_create_a_planned_disbursement_spec.rb
- spec/lib/financial_period_spec.rb
- Forecasted spend form always includes the current financial year
> (1347) Include current financial year in the list of the “next ten years”

- CHANGELOG.md
- app/views/staff/shared/programmes/_table.html.haml
- app/views/staff/shared/projects/_table.html.haml
- app/views/staff/shared/third_party_projects/_table.html.haml
- spec/features/staff/users_can_view_an_activity_spec.rb
Trello: https://trello.com/c/h6QNiHF6
This is an old feature that shows if a user has completed all the form steps of an activity or not, which used to be an indicator of an activity being valid. This is no longer the case and this information has no value for the users anymore, so we are now removing this column from the child activities view. This applies to programmes, projects and third-party projects.
I have also removed the specs related to this feature.
> (1314) Remove form steps label from child activities view

- CHANGELOG.md
- app/helpers/codelist_helper.rb
- spec/helpers/codelist_helper_spec.rb
Refactor the codelist helper to standardise the way we load BEIS codes. IATI is still the default source.
Code lists referred originally only to IATI codes.
However, practice has shown that there are a lot of BEIS-specific codes that we are attempting to group and load in a consistent way. Having a recognised, common pattern to load BEIS codes would make it easier to add new ones in the future by decreasing the cognitive load of figuring it out from first principles.
N/A
> Refactor helper to use `load_yaml` for BEIS codes

- CHANGELOG.md
- app/services/activities/import_from_csv.rb
- config/locales/models/activity.en.yml
- spec/services/activities/import_from_csv_spec.rb
On production, we have several activities in an incomplete state, which meant that `Activity.by_roda_identifier` would return a result, instead of `nil`, so the expected `parent_not_found` was not raised. This would lead to these activities being imported and incorrectly parented to a random activity.
> (1359) Importer stops activities being associated to an incomplete parent

- CHANGELOG.md
- app/models/user.rb
- app/views/staff/users/_form.html.haml
- config/locales/models/user.en.yml
- spec/features/staff/beis_users_can_edit_a_user_spec.rb
- spec/models/user_spec.rb
When carrying out user testing, we found out that if an administrator created an account with the wrong email address and the email address was subsequently changed, the new user would not recieve a confirmation email for them to activate their account. 
We did initially consider sending a new confirmation email if an email is changed, but on further investigation / discussion, we discovered that Auth0 does not allow a user's email to be changed, and in any case, we should treat the email of a user as the primary identifier. 
With this in mind, I've changed the system to not allow emails to be changed, both via a validation, and by disabling the email field on the edit page. If a user has been created with the wrong email address, they should be deactivated. We don't currently allow …
> (1087) Prevent admnistrators from changing an email address

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/helpers/codelist_helper.rb
- app/views/staff/shared/activities/_activity.html.haml
- spec/features/staff/users_can_create_a_project_level_activity_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/helpers/codelist_helper_spec.rb
- spec/support/form_helpers.rb
- Infer the answer to the "FSTC applies" question from the value of the aid type, where possible
- Do not link to edit FSTC if it is inferred from aid type
> (1140) Automatically fill in FSTC question where applicable

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/models/activity.rb
- app/views/staff/shared/activities/_activity.html.haml
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/models/activity_spec.rb
- spec/support/form_helpers.rb
- Require UK Delivery partner named contact for all projects and third-party projects
> (1295) Require UK named contact for all projects

- CHANGELOG.md
- spec/features/staff/users_can_view_budgets_on_an_activity_page_spec.rb
The spec is exercising the ordering of the budgets, so the period of time that the budgets are for isn’t relevant.
The spec would fail when there was a leap year involved, because the validator intentionally checks for 365 days, not the variable duration of “a year”. (This was a choice, well documented in the commit message 6a9d56e44.)
Remove the brittle spec arrangement and replace with a time period that would always be less than 365 days.
N/A
> Fix spec that would fail for the wrong reason

- CHANGELOG.md
- app/controllers/staff/extending_organisations_controller.rb
- spec/features/staff/users_can_manage_extending_organisation_spec.rb
Whilst looking at if this was even possible I noticed it was broken.
The reason is that the activity model is not valid by default without
all required attributes. We often see activities being completed over
time and so cannot always rely on the object being valid.
It turns out we even have a validation context that was used for these
reasons to test the validity but it was no called on the `save` so the
save never completed.
This was compounded by the fact the UI gives the impression that the
save was completed when it had not.
The fix is to simply validation in the `update_extending_organisation`
context which will only validate the extending organisation attribute
and not the entire Activity object.
> (1379) Fix: Users can change the extending organisation

- app/controllers/staff/planned_disbursements_controller.rb
- app/policies/planned_disbursement_policy.rb
- app/services/planned_disbursement_history.rb
- app/views/staff/planned_disbursements/edit.html.haml
- app/views/staff/planned_disbursements/new.html.haml
- config/locales/default.en.yml
- config/locales/models/planned_disbursement.en.yml
- config/routes.rb
- spec/features/staff/users_can_create_a_planned_disbursement_spec.rb
- spec/features/staff/users_can_delete_a_planned_disbursement_spec.rb
- spec/policies/planned_disbursement_policy_spec.rb
- spec/services/planned_disbursement_history_spec.rb
This allows users to delete forecasts that may have been added by mistake. After a bit of back and forth and discussion, we decided that when a user wants to "delete" a forecast, it'll be because they've erroneously created one, either for the wrong reporting period, or the wrong activity, rather than they've just entered the wrong amount. With this in mind, I decided that the expected behaviour would be to delete all the Planned Disbursements for that activity / period, and remove all history. We did discuss just setting the latest value to zero, which would behave as if the forecast was deleted, but this would still keep the erroneously created value as the "original", which may not be the intent.
> Users can delete a forecast added by mistake

- CHANGELOG.md
- app/controllers/staff/transactions_controller.rb
- app/policies/transaction_policy.rb
- app/views/staff/transactions/_form.html.haml
- config/locales/models/transaction.en.yml
- config/routes.rb
- spec/features/staff/users_can_create_a_transaction_spec.rb
- spec/features/staff/users_can_delete_a_transaction_spec.rb
- spec/policies/transaction_policy_spec.rb
This allows BEIS and Delivery Partner users to delete transactions, which may have been added by mistake. It also adds a "Cancel" button to allow users to go back if they have accidentally tried to add a transaction.
> (1366) Users can delete a transaction added by mistake

- CHANGELOG.md
- app/models/activity.rb
- spec/services/export_activity_to_csv_spec.rb
During Q3 reporting we realised that the report CSV was showing the wrong values for the previous quarter’s actuals. It was showing the same values as for the current quarter. (The values were not overwritten, it was only a computation/display bug.)
The reason was that the service object was memoising all the actuals values for the current report, so when the code attempted to calculate the actuals for the previous report, it was using the already computed values.
The reason the spec didn’t catch this is that it was not set up with a full real-life scenario.
We have now enriched the spec’s setup to replicate the conditions under which the bug occurs.
None of the other methods which memoise values are being called for a different report, so we didn’t see a reason to preemptively change …
> Fix display of previous actuals in the report CSV

- CHANGELOG.md
- app/controllers/staff/users_controller.rb
- app/views/staff/users/_form.html.haml
- spec/features/staff/beis_users_can_invite_new_users_spec.rb
Trello: https://trello.com/c/iEz6socI
When a user wants to add a new user, they have to select what organisation this user belongs to. There is a radio button list for this, with organisations sorted alphabetically. However, there was no distinction between BEIS and the Delivery Partners on this list. BEIS could appear in the middle of the list, which made easier for users to accidentally assign a new user to BEIS when they don't belong to this organisation. This would give that user higher privileges than they should have. To avoid this, we have now separated BEIS org from the rest of organisations on display, adding a divider in the radio button list.
> (1370) Separate BEIS from other organisations

- CHANGELOG.md
- app/helpers/form_helper.rb
- spec/features/staff/users_can_create_a_programme_level_activity_spec.rb
- spec/helpers/form_helper_spec.rb
Previously when prompting for a parent activity, all parent activities were shown on the form. This resulted in a bunch of incomplete or erroneously created activities showing up. This adds a filter to the `scoped_parent_activities` method that makes sure only activities with a `form_state` of `complete` are shown.
> (1416) Parent step only shows complete parent activities

- CHANGELOG.md
- app/views/staff/reports/_actions.html.haml
- app/views/staff/reports/_download.haml
- app/views/staff/reports/budgets.html.haml
- app/views/staff/reports/variance.html.haml
Moves the link to the report CSV download out of the actions, and removes the button styling so it's a plain link.
I’ve reused the `.page-actions` class because all it currently does is right-align. Open to making its own class if we think it's worth it.
> (1450) Make report CSV download link a tertiary link

- config/locales/views/not_authorised.en.yml
- spec/features/staff/organisation_show_page_spec.rb
- spec/features/staff/users_can_activate_reports_spec.rb
- spec/features/staff/users_can_choose_recipient_country_spec.rb
- spec/features/staff/users_can_create_a_transaction_spec.rb
- spec/features/staff/users_can_manage_extending_organisation_spec.rb
- spec/features/staff/users_can_view_an_organisation_as_xml_spec.rb
- spec/policies/activity_policy_spec.rb
- spec/policies/budget_policy_spec.rb
- spec/policies/planned_disbursement_policy_spec.rb
- spec/policies/transaction_policy_spec.rb
- spec/services/activities/import_from_csv_spec.rb
- Fix typos in spec descriptions
Typos in spec descriptions do not affect the code in any way! They only affect me, as I watch the test suite go by and a typo lodges in my brain. It's like seeing a loose hair on someone's otherwise immaculate lapel, and being constantly distracted by that instead of paying full attention to what they're saying. 😅 
N/A
> Fix typos in spec descriptions

- app/models/transfer.rb
- db/migrate/20210126124531_create_transfer.rb
- db/schema.rb
- spec/factories/transfer.rb
- spec/models/activity_spec.rb
- spec/models/budget_spec.rb
- spec/models/transaction_spec.rb
- spec/models/transfer_spec.rb
- spec/support/matchers/validate_attribute_matcher.rb
Add a `Transfer` model for storing the transfers of money between activities.
I've added a foreign key constraint on `source_id` and `destination_id`, that will prevent those activities being deleted whilst transfers exist that reference them. 
NB: I didn't name the associations `source_activity` and `destination_activity` both to save typing and in case we need to have a source that isn't an activity in the future (e.g. external funding).
> (1423) Add a transfer model

- CHANGELOG.md
- app/controllers/staff/activities_controller.rb
- app/models/activity.rb
- app/views/staff/activities/historic.html.haml
- app/views/staff/shared/activities/_current.html.haml
- app/views/staff/shared/activities/_filter.html.haml
- app/views/staff/shared/activities/_table.html.haml
- config/locales/models/activity.en.yml
- config/routes.rb
- spec/features/staff/users_can_filter_activities_spec.rb
- spec/features/staff/users_can_view_activities_spec.rb
Trello: https://trello.com/c/NyH0BprF
This new feature separates the activities view page into two different tabs. One containing the `Current` activities, which are more relevant for users, and the other containing the `Historic` activities, which are the ones where users are unlikely to add any financials, information, etc to them. These `historic activities` are the ones in which `programme_status` is set to either `completed`, `cancelled` or `stopped`. These activities cannot have any financial data added or modified and the users are unlikely to have to use them in the future. However, we still want to keep them in RODA.
The activities view will display two tabs `Current` and `Historic`, and the user will be able to select which ones they want to see.
> (1418) Users can see Current and Historic activities separately

- CHANGELOG.md
- app/views/staff/reports/index.html.haml
- app/views/staff/shared/reports/_table_active.html.haml
- app/views/staff/shared/reports/_table_approved.html.haml
- app/views/staff/shared/reports/_table_awaiting_changes.html.haml
- app/views/staff/shared/reports/_table_in_review.html.haml
- app/views/staff/shared/reports/_table_inactive.html.haml
- app/views/staff/shared/reports/_table_submitted.html.haml
- Reports awaiting changes are the most important to emphasise, while inactive reports (only visible to service owners) are the least. Reorder them according to design.
> (1449) Reorder reports in a more helpful order

- CHANGELOG.md
- app/assets/stylesheets/partials/_reports.scss
- app/controllers/staff/report_variance_controller.rb
- app/models/activity.rb
- app/views/staff/shared/reports/_table_variance.html.haml
- config/locales/models/activity.en.yml
- db/seeds/activity.rb
- spec/models/activity_spec.rb
- Group activities by hierarchy on the view of a single report page
> (1448) Group activities by hierarchy on single report view

- doc/activity-identifiers.md
This imports the [document](https://gist.github.com/jcoglan/e525c9059e38f0c812069f6171c37652) I wrote a while ago about the different types of activity identifier we use in RODA, as I need to keep referring people to it. I believe we've added one more type since this was written so it may need updating?
> Document all the types of identifiers we use for activities

- app/models/codelist.rb
- spec/models/codelist_spec.rb
While it's potentially useful to reload codelists in dev, it's less useful in test, and almost doubles the time it takes our tests to run (from c. 3 minutes to c. 6 minutes on my local machine!). I have had to update the Codelist tests to reset the class's instance variable (fact fans: a variable starting with an `@` is still called an instance variable when it's being used inside a class, not a class variable)
> Memoize codelists in tests

- app/helpers/codelist_helper.rb
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/services/activities/import_from_csv.rb
- app/views/staff/activity_forms/flow.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- config/locales/models/activity.en.yml
- db/migrate/20210202192712_remove_flow_from_activities.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
- spec/features/staff/users_can_create_a_programme_level_activity_spec.rb
- spec/features/staff/users_can_create_a_project_level_activity_spec.rb
- spec/features/staff/users_can_create_a_third_party_project_level_activity_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/features/staff/users_can_upload_activities_spec.rb
- spec/features/staff/users_can_view_activities_spec.rb
- spec/features/staff/users_can_view_an_activity_spec.rb
- spec/helpers/activity_helper_spec.rb
- spec/helpers/codelist_helper_spec.rb
- spec/models/activity_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/services/activities/import_from_csv_spec.rb
- spec/support/activity_helpers.rb
- spec/support/form_helpers.rb
- spec/support/shared_examples/behaves_like_valid_activity_xml.rb
- We don't ask the users for the Flow type, because it is always going to be ODA ("10"). We don't import it from CSV. When exporting to CSV and to XML, the flow is added and hardcoded to "10".
> (1461) Flow is always "10" ("ODA")

- app/models/activity.rb
We have some limited situations where a RODA ID is nil, this causes the sorting to break, which is less than ideal. I've fixed this so we now cast all RODA IDs to a string when sorting.
> (1477) Handle nil RODA fragments when sorting

- doc/deployment-process.md
Now there's an "official" badger emoji, the announcements in Slack are much less celebratory (and a bit baffling!). Let's fix this.
Much better!
> Update deployment process docs to the new emoji

- CHANGELOG.md
- app/controllers/concerns/stream_csv_download.rb
- app/controllers/staff/activity_uploads_controller.rb
- app/controllers/staff/planned_disbursement_uploads_controller.rb
- app/controllers/staff/reports_controller.rb
- app/controllers/staff/transaction_uploads_controller.rb
- app/services/export_activity_to_csv.rb
- spec/features/staff/users_can_upload_activities_spec.rb
- spec/features/staff/users_can_upload_planned_disbursements_spec.rb
- spec/features/staff/users_can_upload_transactions_spec.rb
- spec/services/export_activity_to_csv_spec.rb
This PR addresses a problem that happens when people use Excel to open a CSV downloaded from RODA. All the data stored in RODA is UTF-8, and does not contain any _encoding_ errors; that is, all text stored in RODA is a valid UTF-8 byte sequence. The CSVs served by RODA are also valid UTF-8 encoded CSV, but when opened in Excel some of their content is mis-interpreted.
We ran some experiments where we encoded a CSV file containing text from a variety of Unicode blocks. We encoded this file as UTF-8, UTF-16BE and UTF-16LE, and made copies of each of these with and without a byte order mark (BOM) at the start.
We found that Excel is able to read UTF-8 successfully if it's prefixed with a BOM. If this is missing, Excel will mis-read many of the characters in the file, including …
> (1475) Encode CSV downloads for Excel

- README.md
- backing-services-docker-compose.yml
I prefer to run the two backing services (Postgres and Redis) with
Docker as I find managing version with Homebrew can effect my entire
system and I often find I update the backing services without meaning to
when updating my own tooling, which can cause horrible problems.
For those that prefer it, a simple docker compose file allows one to
start and stop the backing services via docker and not effect their
system at all. This has an added benefit of having the option to pin the
versions of the backing services to that of the ones used in production.
Whilst I am loathe to add alternatives to the one-script-to-rule-them-all,
I much prefer this approach personally and have real technical
reasons to avoid the Homebrew path, therefore I am adding this compose
file and a small section in the …
> (chore) Backing services can be run with Docker

- app/controllers/concerns/stream_csv_download.rb
We recently made some changes to how downloadable CSV responses are
generated, introducing the `StreamCsvDownload` module to share a single
implementation of this functionality. On deplying this to staging, we
found that requesting any CSV, for example a forecast bulk upload
template, contained the column headings but no data. Copying the request
as a cURL command from the browser, I found that the app returns this
response:
HTTP/1.1 200 OK
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: strict-origin-when-cross-origin
Content-Type: text/csv
Content-Disposition: attachment; filename=forecasts.csv
ETag: W/"3d2f8c0a0126c1ac6b2719b54a42ff18"
Cache-Control: …
> Serve complete CSV downloads using chunked transfer encoding

- CHANGELOG.md
- app/views/staff/shared/activities/_activity.html.haml
Now descriptions and objectives that be presented with the line breaks as HTML
> (1476) Show textarea content with wrapper HTML on the Activity details page

- app/models/fund.rb
- spec/models/fund_spec.rb
Whilst looking at the recently-added Fund model, I noticed that the `Fund.all` method was always erroring.
This commit fixes that error and adds a couple of unit tests.
> Fix bug with `Fund.all`

- .github/workflows/rebase.yml
Now, adding `/rebase` as a comment rebases a PR, saving us from having to rebase manually when a PR gets out of date.
> Add an action to automatically rebase

- .github/workflows/rebase.yml
The action can't trigger an action from another action without using a personal access token. I thought the access token we had by default was enough, but apparently not
> Fix rebase action

- README.md
Even though the repo is private, I think it is best to document everything we can, imagine being on support and not knowing where the dns is or who manages it?
> (chore) Update readme to include a link to the DNS repo

- .github/workflows/deploy.yml
- doc/architecture/decisions/0028-add-cdn-route.md
- terraform/app.tf
- terraform/cdn-route.tf
- terraform/domains.tf
- terraform/routes.tf
- terraform/variables.tf
Creates a cdn-route, and maps it to the app using the custom domain
This introduces 2 new tfvars:
```
custom_domain (the apex domain of where the app will be hosted)
custom_hostname (the subdomain, eg. www or staging)
```
> Add cdn-route

- Gemfile.lock
6.6.1 has introduced a new bug, documented here https://github.com/ilyakatz/data-migrate/issues/170
> Revert "Bump data_migrate from 6.6.0 to 6.6.1"

- CHANGELOG.md
- app/controllers/staff/reports_controller.rb
- app/views/staff/reports/index.html.haml
- config/environments/test.rb
- config/locales/models/report.en.yml
- spec/features/staff/users_can_view_reports_spec.rb
Trello: https://trello.com/c/PuEeSnuJ
With this new feature, BEIS users can download all relevant reports in just one click. The reports they will get are those which are subject to changes or additions on the financial data (active, submitted, in_review and awaiting_changes). Reports that are inactive or approved will not be included on this CSV file.
The Reports CSV file contains all the activities from the relevant reports. These are sorted by Delivery Partner first, and then by hierarchy level, by recommendation from our user researcher team. They include the same data than the individual reports.
To avoid BEIS users getting incorrect information due to some reports being from a different quarter (and hence having a different set of financial_quarters information) I'm guarding against …
> (1419) BEIS users can download a reports CSV file for all delivery partners

- README.md
- doc/manage-environment-variables.md
- Update documentation to replace Travis-specific instructions with those required when using GitHub Actions
We switched from Travis to GitHub Actions to run our deployments.
Most of the documentation was updated around that time [1], but there were still mentions of Travis here and there.
I'm mostly guessing at the env var steps, so that's where I'd like a review / confirmation!
N/A
> Remove Travis from docs

- CHANGELOG.md
- app/models/transaction.rb
- app/services/create_transaction.rb
- app/services/import_transactions.rb
- db/data/20210215165822_set_default_attributes_on_transaction.rb
- db/data_schema.rb
- spec/models/transaction_spec.rb
- spec/services/create_transaction_spec.rb
- spec/services/import_transactions_spec.rb
- Transaction description is populated from the financial quarter and year and from the activity's title
- The default type for a transaction is Disbursement, set during creation and import
- The providing organisation for a transaction is set from the activity
> (1496) Set default values for various Transaction attributes

- CHANGELOG.md
- app/controllers/staff/organisations_controller.rb
- app/views/staff/organisations/_grouped_programmes.html.haml
- app/views/staff/organisations/show.html.haml
- config/locales/models/activity.en.yml
- package-lock.json
- spec/features/staff/users_can_view_an_organisation_spec.rb
Allow users to see a list of programmes an organisation is extending from the organisation's show page (which is also the first page delivery partners will see when signing into RODA).
The next step will allow users to create a child activity from this page.
> (1458) Show programmes grouped by fund on organisation show page

- CHANGELOG.md
- app/views/layouts/application.html.haml
- app/views/pages/terms_of_service.html.haml
- config/locales/views/footer.en.yml
- config/locales/views/terms_of_service.en.yml
- spec/controllers/pages_controller_spec.rb
- spec/features/user_can_view_static_pages_spec.rb
Trello: https://trello.com/c/2DjzIjVC
We are now publishing the Terms of the Service on RODA. The link will live in the footer, along with the Privacy policy, Cookie statement, Accessibility statement, and Support section. The information was approved by our service designer in collaboration with the client. I have just amended some links to RODA production that were broken since we are now hosted on a service.gov.uk domain.
I added this page to the specs that cover the static pages to make sure it also gets tested.
> (1444) Publish Terms of Service

- app/models/transaction.rb
- db/migrate/20210216113434_add_financial_quarter_to_transactions.rb
- db/migrate/20210216140931_set_financial_quarter_on_transactions.rb
- db/schema.rb
This PR is the initial work that adds `transactions.financial_{quarter,year}` to the schema, and begins populating them for existing and newly created records. Once this is deployed, we should migrate the UI to set these fields directly, rather than the date.
I have one question related to this so far, which is how the quarter is inferred. There are two possible sources for this inference: the transaction's date, and the transaction's report's financial quarter. Some background information I found out while reviewing our existing data:
- In production, there are currently 3,116 transactions and all have a date set.
- Some transactions do not belong to a report, since they belong to level A/B activities. 2,989 transactions _do_ belong to a report.
- Most transactions belong to "historic" …
> (1501) Store financial quarter and year on transaction

- .github/workflows/deploy.yml
- CHANGELOG.md
- app/views/layouts/application.html.haml
- app/views/shared/_no_index.html.haml
- doc/manage-environment-variables.md
- spec/views/layouts/application_spec.rb
- terraform/app.tf
- terraform/variables.tf
This adds a new environment variable to the application: `ROBOT_NOINDEX`. If it is set to true, the application renders two `meta` tags in the header, which tell search engines to not crawl the site.
> (1490) No search engine indexing on environments other than production

- app/models/activity.rb
- db/migrate/20210219121229_remove_ingested_from_activity.rb
- db/schema.rb
- spec/models/activity_spec.rb
Some history:
The `ingested` flag was part of the old ingesting of historic activity
data from published activities. This was our first attempt to ingest
historic data and it was difficult for many reasons.
At the time we were also developing the application and that included
adding fields that were entirely new i.e. the fileds would not be in the
ingested data set.
This meant an `ingested` activity would be missing the new fields but
still needed to be considered valid in certain contexts.
You can see how the ingested flag was used to force certain validation
rules.
Why are we removing the field?
We no longer need the ingested flag as as new delivery partners are on
boarded to the service ALL of their historic is prepared by BEIS and
imported into the application replacing everything …
> (1466) Remove ingested from activities

- CHANGELOG.md
- app/controllers/auth0_controller.rb
- app/controllers/concerns/secured.rb
- spec/features/staff/users_can_sign_in_spec.rb
If a user accesses a URL (e.g. from a deep link), but is not signed in, this sets a session variable of the page they visited, and then redirects to that page after they sign in (if the variable is available).
> Redirect to previously visited URL if unauthorised

- spec/features/staff/users_can_upload_activities_spec.rb
This test was sometimes failing because the order of the new activities was not guaranteed.
> Fix flickering test

- .github/workflows/deploy.yml
- CHANGELOG.md
- config/environments/production.rb
- config/routes.rb
- spec/requests/domain_redirect_spec.rb
- terraform/app.tf
- terraform/variables.tf
This redirects the old domains (https://beis-roda-[staging|prod].london.cloudapps.digital/) to the new domains. Currently, trying to access the site via the old domains results in an error. This adds the old domains to the list of allowed domains, and then redirects them to the canonincal domain. The env vars are ready to go and set in Github, so no extra work is required to deploy this
> (1509) Redirect old domain to new one

- terraform/worker.tf
This had me scratching my head for a while, but I discovered that the worker container (which I didn't think we were using!) is used to send emails via Notify, and still has the old domain set, so any emails sent will have the old domain in URLs.
> (1512) Set correct domain in the worker container

- app/services/remove_beis_reports.rb
- spec/services/remove_beis_reports_spec.rb
There are two reports in production that belong to BEIS:
> Report.joins(:organisation).where(organisations: { service_owner: true }).count
=> 2
We'd like to remove them, because BEIS themselves do not submit data to
the report assurance process. But first we need to consider any records
that are linked to them and decide how to handle these. Most types of
record linked to transactions have no instances related to these
reports:
> Budget.joins(report: [:organisation]).where(organisations: { service_owner: true }).count
=> 0
> Comment.joins(report: [:organisation]).where(organisations: { service_owner: true }).count
=> 0
> PlannedDisbursement.joins(report: [:organisation]).where(organisations: { service_owner: true }).count
=> 0
However there are some transactions linked to the reports …
> (1336) Remove reports that belong to BEIS

- config/application.rb
This causes problems when the application boots, because the code in our generators is modularised in a way that isn't compatible with how Zeitwerk auto loads code. We can make it work with Zeitwerk, but given we don't _need_ this code to be autoloaded in production, it seems like a waste of time. It also means the generated name of the generator is `generators:data_migration:data_migration`, which seems a bit of a mouthful, and there doesn't seem to be an easy way to override that.
All the classes we have in `lib/` are already required where they need to be required now, so we don't need to autoload them.
> Don't eager load files in `lib`

- app/controllers/staff/transaction_uploads_controller.rb
- app/models/report.rb
- spec/controllers/staff/transactions_uploads_controller_spec.rb
- spec/models/report_spec.rb
This is a two-step process, the first commit removes any activities that aren't reportable (i.e. not current) from the `reportable_activites` scope. The second commit uses the `hierarchically_grouped_projects` method we already use on the report variance page to organise the activities hierarchically. We hope this will make is easier for delivery partners to find the relevant activity, particularly when there are a lot of activities to parse in a big CSV.
> (1515) Make the transaction upload CSV show activities hierarchically

- db/data/20210303102617_remove_royal_accademy_of_engineering_and_british_accademy_legacy_data.rb
__** Requires data migration to be run manually once deployed **__
This data migration will remove all data for known  Delivery Partner
organisations.
The goal of this work is to remove all the data we have imported via the
legacy IATI data for:
- Royal Academy of Engineering
- British Academy
We are doing this because BEIS would like to change the RODA identifier
for all the activities which work 'top down' i.e. any changes to the ID
at the top level need to propagate down so effectively we would need to
change all the IDs. We decided that as the data is to be replaced
entirely (see below) the simplest approach is to remove the data in its
entirety.
It is safe to carry out this action as neither organisation has used RODA
to report as yet and the new data migration process will
replace …
> (1420) Data migration to remove all legacy data

- CHANGELOG.md
Missed replacing `unreleased` with the correct release number.
> Fix changelog link for release 37

- db/seeds/organisations.rb
- db/seeds/organisations.yml
When setting up the repo for the first time I received an error as part
of the database seeding process.
```
NoMethodError: undefined method `organisation' for nil:NilClass
```
This is was caused by the organisation records not being created due to
being considered invalid, meaning that no users were created.
There was a new validation added in a95d2f92c2c62721c4a80318ceed0c22da139426
to the Organisation model that checks for the validity of the
`beis_organisation_reference`, this field wasn't part of our sample
data for our seeds.
I've added the `short_name` property to the sample data YAML file and
populated it using the corresponding values from the
`vendor/data/beis_organisation_references.csv` file.
I've also added a bang to the the organisation update action so that
if something …
> Fix organisation seeds

- CHANGELOG.md
- app/services/activities/import_from_csv.rb
- app/validators/channel_of_delivery_code_validator.rb
- spec/services/activities/import_from_csv_spec.rb
- Allow importing into existing activities without repeating the Channel of delivery code in the uploaded spreadsheet
> (1557) Allow blank Channel of delivery code when importing

- .gitignore
This adds all filename patterns from dxw's Rails template [1] that are
designed to prevent data files that might contain sensitive information
from being committed.
I have removed any existing patterns from .gitignore that duplicate the
entries in this list.
[1]: https://github.com/dxw/rails-template
> (1588) Ignore sensitive files

- CHANGELOG.md
- app/views/staff/activities/historic.html.haml
- app/views/staff/shared/activities/_current.html.haml
- app/views/staff/shared/programmes/_table.html.haml
- app/views/staff/shared/projects/_table.html.haml
- app/views/staff/shared/reports/_table_budgets.html.haml
- app/views/staff/shared/reports/_table_variance.html.haml
- app/views/staff/shared/third_party_projects/_table.html.haml
- config/locales/models/fund.en.yml
- config/locales/models/programme.en.yml
- config/locales/models/project.en.yml
- config/locales/models/third_party_project.en.yml
- spec/features/staff/users_can_filter_activities_spec.rb
- spec/features/staff/users_can_view_activities_spec.rb
- spec/features/staff/users_can_view_an_activity_spec.rb
- spec/features/staff/users_can_view_reports_spec.rb
There are a few places left in the application where we display the
Delivery Partner Identifier in a column labelled "RODA Identifier" or
just "Identifier". This is probably left over from when we first
introduced RODA Identifiers, and it creates confusion as activities are
shown with different IDs across pages.
This changes most of the places in the app where we show a single ID for
an activity, to display the RODA Identifier. We still display Delivery
Partner Identifiers in places where they're explicitly called out as
such, like the activity details page and XML export.
> Display RODA Identifiers consistently everywhere

- bin/db-restore
- doc/database-backup-and-restore.md
This adds a script that:
- dumps the data from a live database (either staging, prod,  or pentest) to a known location (in `/tmp`) WITHOUT the `users` table
- drops the existing development database
- loads the data into the dev databse
- removes any extraneous Postgres extensions (added by GOV.UK PaaS),
- makes sure the migrations are updated
- seeds the local users
There is also a trap function that runs no matter what happens, to clean up our backup file. I've also updated the documentation, so users know to just run this script.
> Write a script to automate the database restore process

- CHANGELOG.md
- app/controllers/staff/budgets_controller.rb
- app/models/budget.rb
- app/presenters/budget_presenter.rb
- app/services/create_budget.rb
- app/views/staff/budgets/_form.html.haml
- app/views/staff/shared/budgets/_table.html.haml
- app/views/staff/shared/reports/_table_budgets.html.haml
- config/locales/models/budget.en.yml
- spec/features/staff/users_can_create_a_budget_spec.rb
- spec/features/staff/users_can_edit_a_budget_spec.rb
- spec/features/staff/users_can_view_budgets_on_an_activity_page_spec.rb
- spec/models/budget_spec.rb
- spec/policies/budget_policy_spec.rb
- spec/services/create_budget_spec.rb
This is the next step in changing budget to allow support for additional funding arrangements.
We do not need to collect the IATI budget type and budget status as we will be able to infer them; for the time being they are set to original and commited respectively.
We also know the funding_type based on the parent activity, for now we select the correct response by default and validate that the user does not try and provide an incorrect response. 
The resaon to keep the element in the form is that we will very soon add further funding types (transferred, external, etc) so it feels like a waste to remove something we will end up putting back in.
- [ x] Is a changelog entry required? An entry should always be made in `CHANGELOG.md`, unless this PR is a small tweak which has no impact outside …
> (1463) Simplify the way we collect and show budgets

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/controllers/staff/reports_controller.rb
- app/helpers/codelist_helper.rb
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/services/activities/import_from_csv.rb
- app/services/activity/updater.rb
- app/services/export_activity_to_csv.rb
- app/views/staff/activity_forms/gcrf_strategic_area.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- config/locales/models/activity.en.yml
- db/migrate/20210319154548_add_strategic_area_to_activities.rb
- db/schema.rb
- spec/controllers/staff/activity_forms_controller_spec.rb
- spec/factories/activity.rb
- spec/features/staff/beis_users_can_create_a_programme_level_activity_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/features/staff/users_can_upload_activities_spec.rb
- spec/models/activity_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/services/activities/import_from_csv_spec.rb
- spec/support/form_helpers.rb
- vendor/data/codelists/BEIS/gcrf_strategic_area.yml
> Users need to be able to report which strategic area their GCRF funding applies to. This has previously been captured by the UID but is unlikely to be the case in the future. This is important for Fund Managers and BEIS finance team.
- Users can now report the strategic area under which the GCRF allocation was made
- They can choose a maximum of two areas
- The strategic area is included in the CSV report
- The activity CSV import will ingest the strategic area
- Only show the strategic area question for programme level activities
- For project and third-party level activities use the strategic area from the programme level activity
> (1576) Users can report the strategic area under which the GCRF allocation was made

- CHANGELOG.md
This line was accidentally included in the previous release as part of a
rebase. The feature is currently unreleased.
https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/1011/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR556
> Fix unreleased section in changelog

- spec/services/activities/import_from_csv_spec.rb
The initial intent of [the card](https://trello.com/c/4gl4n8Ef/1569-roda-team-can-import-activities-at-level-b) was to change the Rake importer so we could import Level B (Programme) activities via the command line. It turns out that recent changes we've made to the importer make this very easy to do, so this PR is simply adding some extra tests to make sure what we're testing for better reflects reality.
Another issue that this has raised is that, at the moment, delivery partners can, in theory, create level B activities, which we don't really want to do. This issue is logged in [another card](https://trello.com/c/W7orkOeN/1566-activity-import-respects-the-policies)
> (1569) RODA team can import activities at Level B

- CHANGELOG.md
- app/models/transaction.rb
- app/presenters/transaction_presenter.rb
- app/services/import_transactions.rb
- app/validators/transaction_organisation_validator.rb
- app/views/staff/shared/xml/_transaction.xml.haml
- config/locales/models/transaction.en.yml
- spec/factories/transaction.rb
- spec/features/staff/users_can_create_a_transaction_spec.rb
- spec/features/staff/users_can_upload_transactions_spec.rb
- spec/features/staff/users_can_view_an_activity_as_xml_spec.rb
- spec/models/transaction_spec.rb
- spec/presenters/transaction_presenter_spec.rb
- spec/services/import_transactions_spec.rb
- spec/support/form_helpers.rb
This updates the transaction validations to make the Organisation optional. However, if one of the Organisation fields are present, then at least the Name and Type should be present. I've also updated the form to make it clearer that Organisation is now optional. The XML should now not include receiving organisation data, and the receiving organisation shows as `N/A` if an organisation is not provided too.
> (1578) Receiving organisation is optional for transactions

- db/migrate/20210324161847_remove_legacy_iati_xml_from_activity.rb
- db/schema.rb
This column was added in 71ba7adcf04cc700fba6014e6fbbe0652838dad3 in order to preserve the IATI data used to generate ingested activities.
This historical data hasn’t been needed since, and is adding visual noise when inspecting activities via a console.
We think it’s safe to drop this column. We will check with the responsible person from BEIS before doing so in production.
> (1603) Remove `legacy_iati_xml` column

- .dockerignore
- bin/db-restore
The command wasn't working correctly because it was attempting to seed the `users` table that didn't exist as it was explicitly excluded from the database dump.
Changing `--exclude-table` to `--exclude-table-data` means that the schema for the users table is dumped, but its contents isn't.
I've also excluded the internal `ar_internal_metadata` and`spatial_ref_sys` tables from the backup as well.
Finally calling `rails db:environment:set` let's Rails know we're running a development environment (despite the copy of the database looking like a production one).
NB: I'm entirely sure why this is needed when we're excluding `ar_internal_metadata` from the dump, but I got warnings without it.
Using `pgsql -f dump.sql` instead of `pgsql ... < dump.sql` seemed to resolve a lot of the random …
> (1608) "bin/db-restore" script fixes

- CHANGELOG.md
- app/services/import_planned_disbursements.rb
- app/services/planned_disbursement_history.rb
- script/import_forecasts.rb
- spec/services/import_planned_disbursements_spec.rb
- spec/services/planned_disbursement_history_spec.rb
This revives a script we used in the previous quarter to back-fill some forecast data into the previous quarter's approved report, before opening the next reporting round.
Since this was first introduced and then removed, the forecast import service has been exposed to end users and so has gained some authorization logic and other checks that meant this functionality had to be reworked beyond just reverting the commits that removed it. Details in the commit messages.
> (1581) Backfill forecasts data into historic reports for new partners

- db/migrate/20210326054912_remove_null_from_activity_level.rb
Remove any activities with a `NULL` value in the `levels` column of the `activities` table, to allow the migration to complete successfully.
This caused the deployment to staging to fail.
> Fix broken migration

- CHANGELOG.md
- app/controllers/staff/planned_disbursement_uploads_controller.rb
- app/services/import_planned_disbursements.rb
- spec/features/staff/users_can_upload_planned_disbursements_spec.rb
- spec/services/import_planned_disbursements_spec.rb
This adds column headings for the next 20 financial quarters to the forecast CSV template. The cell values are left blank rather than being filled with zeros, so that only cells the user actually fills in are treated as new data. A fuller explanation for this is in the commit messages.
> (1601) Add financial quarter headings to forecast upload template

- CHANGELOG.md
- app/services/activities/import_from_csv.rb
- spec/services/activities/import_from_csv_spec.rb
When we're updating an activity, we don't always want to have to set every single variable. As it stands, when we update a record, there are some variables we're expected to set every single time (e.g. sector code).
This updates the Converter to behave differently when updating to when creating a new activity. If we're updating, we grab the row, and only run the converter on fields that are expressly filled out. We also don't do any of the inferrence when updating, as this can overwrite data that is already set on the Activity.
This also has the side effect of any policy marker fields not being set to `not_assessed` by default. This is fine for now, and we're going to write a seperate card to write a migration that sets all Activity policy marker fields to default to `not_assessed` at the …
> (1567) Activity importer can update an activity without requiring the sector code.

- spec/features/staff/users_can_upload_planned_disbursements_spec.rb
The setup for the test in question generates a CSV containing two result rows. The order of these was consistently reversed on two developers' machines (including mine), whereas it was fine for another two.
Rather than spend to long puzzling over this strange issue, I've updated the test to check that the expected hash is *included* in `rows` rather than expecting it to be the first result.
We suspect something to do with Postgres versions (the two it was affecting are running older versions), but can't be certain.
> Fix puzzling test result ordering bug

- CHANGELOG.md
- app/services/activities/import_from_csv.rb
- spec/services/activities/import_from_csv_spec.rb
In certain circumstances, when trying to update an activity, we hit an error in the ImplemeningOrganisationBuilder, where the builder tried to add an error to the Errors array, but because there were no implementing organisations available, we got an `undefined method `errors' for nil:NilClass` error.
This reworks how the `ImplemeningOrganisationBuilder` works to memoize the organisation that gets built, rather than fetching the organisation's last implementing organisation, which may or may not be the correct one, or even exist at all.
I've also updated the updater, so it only attempts to build an implementing organisation if the relevant fields are present, in a similar way to how the creator works.
> (1609) Refactor handling of implementing organisations

- CHANGELOG.md
- app/assets/stylesheets/partials/_definition_list.scss
- app/controllers/staff/activity_financials_controller.rb
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/views/staff/activity_financials/show.html.haml
- spec/features/staff/users_can_view_an_activity_spec.rb
- spec/models/activity_spec.rb
- spec/presenters/activity_presenter_spec.rb
- Add total spend and total budget to the activity financials page
> (1602) Add total spend and total budget to the activity financials page

- CHANGELOG.md
- app/helpers/application_helper.rb
- app/views/pages/accessibility_statement.html.haml
- app/views/staff/activity_forms/_wrapper.html.haml
- app/views/staff/activity_forms/sector_category.html.haml
- app/views/staff/organisations/_form.html.haml
- config/locales/models/activity.en.yml
- config/locales/models/organisation.en.yml
- spec/helpers/application_helper_spec.rb
- Data dictionary link opens in a new window/tab by default
- Existing links that open in new windows now use the same helper instead of being manually coded
> (1620) Data dictionary link opens in a new tab

- spec/features/staff/users_can_upload_planned_disbursements_spec.rb
PR #1032 corrected for the fact that this test assumes the acitivty rows
in the CSV template come out in a defined order, which is not true. What
this test should actually be doing is checking that every activity in
the CSV has a row full of empty cells for the forecast columns.
> Correct test for empty forecast cells in CSV template

- CHANGELOG.md
- app/helpers/codelist_helper.rb
- app/presenters/activity_presenter.rb
- app/views/staff/activity_forms/channel_of_delivery_code.html.haml
- spec/helpers/codelist_helper_spec.rb
- spec/support/form_helpers.rb
This changes the channel of delivery code options to radio buttons, rather than a select, as recent usability testing that radio buttons are easier to use to report with. I've also changed the labels to be consistent with how we display them in the details tab.
> Change channel of delivery code to radio buttons

- CHANGELOG.md
- app/models/activity.rb
- config/locales/models/activity.en.yml
- spec/features/staff/users_can_add_benefitting_countries_spec.rb
This is required in order to import data for new partners, whose
activities may exceed the limit currently in place.
> (1642) Remove the limit on the number of intended beneficiaries

- spec/features/staff/beis_users_can_create_a_transfer_spec.rb
- spec/support/form_helpers.rb
Now we've moved into a new financial year, the tests for the transfers were breaking, as the financial years and quarters were hardcoded to the previous financial year. To fix this, I've set the parameters to always default to the current financial year and quarter.
> Fix brittle transfer tests

- CHANGELOG.md
- app/policies/activity_policy.rb
- spec/policies/activity_policy_spec.rb
Currently the only way to determine whether an activity can be created at a particular level is to check using `ActivityPolicy.create?`. This doesn't really work when you're trying to run this check against an activity that doesn't yet exist. This means we're forced to call the `create?` check without passing in a given activity, which means we're unable to check for an editable report, for example.
Instead of doing this, we introduce a new method `ActivityPolicy.create_child?`. Asking the parent activity whether a child can be created under it means we have enough information to give an accurate response.
> (1639) Introduce "create_child?" method to ActivityPolicy

- app/services/import_converter.rb
- script/convert_import.rb
- spec/services/import_converter_spec.rb
To perform the initial import of new delivery partners' records into
RODA, we need to take the spreadsheets they've provided and convert them
into the schema supported by the transaction and forecast importers.
To run the script:
$ ruby script/convert_import.rb \
--level C \
--input path/to/input_file.csv \
--output path/to/output
This reads the data from `path/to/input_file.csv` and writes two new
files: `path/to/output_transactions.csv` and
`path/to/output_forecasts.csv`, which will be compatible with our
existing importers. It does not write anything to the database or
interact with the application in any other way, it purely converts one
CSV file into two others.
The `--level` option must be either `C` or `D` to indicate the level of
the activities being imported.
The main job of this …
> Add script for converting import data files

- app/services/import_converter.rb
Ruby's CSV parse emits `nil` rather than an empty string for empty
cells, so we need to skip such values when extracting transactions and
forecasts from import data sets.
> Handle nil values in ImportConverter

- CHANGELOG.md
- app/controllers/staff/activity_uploads_controller.rb
- app/views/staff/activity_uploads/_upload_form.html.haml
- app/views/staff/activity_uploads/new.html.haml
- app/views/staff/activity_uploads/update.html.haml
- config/locales/models/activity.en.yml
- The activity upload UI looks similar to the actuals and forecasts upload UI
*Upload page*
*Post-upload page*
*Upload page*
*Post-upload page*
> (1652) Activity uploads interface

- app/presenters/activity_presenter.rb
- db/migrate/20210406094816_change_gcrf_strategic_area_arrays_to_integers.rb
- db/schema.rb
- spec/features/staff/beis_users_can_create_a_programme_level_activity_spec.rb
- spec/services/activities/import_from_csv_spec.rb
This was  also causing issues where the `gcrf_strategic_area_options` were returning the code as an integer, but the codes were stored as a string. I looked into tweaking how the options were presented, or even changing the underlying YAML to made the codes into strings, but I finished up taking the approach that we should trust the codelist and if the codes are integers, so the data should be stored as an integer too.
> (1649) Change GCRF stategic area checkboxes to integers

- app/services/import_converter.rb
- script/convert_import.rb
Our script for extracting transactions and forecasts from import data
files was failing to recognise the first heading in CSV files because of
the presence of a byte order mark. We remove this before parsing.
We also make the converter throw an error if the ID columns it requires
are not present; `values_at` returns nil instead of throwing on
unrecognised keys.
> Remove byte order mark from the start of import files

- CHANGELOG.md
- app/controllers/staff/organisations_controller.rb
- app/views/staff/organisations/_grouped_programmes.html.haml
- app/views/staff/shared/activities/_projects.html.haml
- spec/features/staff/users_can_create_a_project_level_activity_spec.rb
- spec/features/staff/users_can_create_a_third_party_project_level_activity_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/features/staff/users_can_view_an_organisation_spec.rb
This is already controlled by the ActivityPolicy, which means that a delivery partner can't create or edit an activity when there is no editable report. This PR just hides the "Add Child" buttons based on the policy - currently clicking on "Add child" will result in a "Not Authorised" error.
I've also added a test to make sure a delivery partner can't see "Add" or "Edit" links on any part of an Activity's details when there is no editable report. This is already the case, but gives us more confidence and documents the expected behaviour.
> (1648) Users cannot create or edit activites whilst there is no active report

- app/services/import_converter.rb
- spec/services/import_converter_spec.rb
We have noticed that some identifier fragments in import data sets
include leading or trailing space in their identifier fields, and these
spaces should not persist when we join the fragments together. This
change strips the space off the values when building the compound ID.
> Remove spaces from identifier fragments in ImportConverter

- db/data/20210412134546_fix_extending_organisation_inconsistencies.rb
- spec/data/20210412134546_fix_extending_organisation_inconsistencies_spec.rb
- spec/models/activity_spec.rb
This data migration ensures that existing activities have `organisation` and `extending_organisation` set consistently. This mirrors the values that `ActivityDefaults` assigns for new activities depending on their level:
- Fund: organisation / extending_organisation are always both BEIS
- Programme: organisation is BEIS and extending_organisation is set to a delivery partner
- Project: organisation / extending_organisation are the same DP
- Third-party Project: organisation / extending_organisation are the same DP
In the past `extending_organisation_id` has been an optional field, so we copy this value from `organisation_id` for projects and third-party projects.
I output a warning for any programmes whose `extending_organisation` is incorrectly set to BEIS, as these will need to be …
> (1645) Make organisation and extending_organisation consistent

- CHANGELOG.md
- app/models/planned_disbursement.rb
- spec/features/staff/users_can_upload_planned_disbursements_spec.rb
- spec/services/export_activity_to_csv_spec.rb
- spec/services/planned_disbursement_history_spec.rb
Under the assurance process, over any given quarter, the forecast for an
activity should match its actual net spending. Since transactions can
have negative values (representing refunds), it follows that forecasts
should be allowed to be negative, to record a prediction that an
activity's net spending will be negative in some future quarter.
> (1665) Allow forecasts to be negative

- doc/importing-new-delivery-partner-data.md
When we on-board new delivery partners we need to bring in all their
existing activities and financial data at the time they are on-boarded.
This is a one time only operation run by developers with data supplied
by BEIS.
We want to document the process in the code as the most useful place to
do so and expect it to be removed once the service completes on-boarding
all delivery partners in Q1 2021-2022.
> (Chore) Document the process for importing new data

- app/policies/activity_policy.rb
- app/views/staff/organisations/show.html.haml
- app/views/staff/shared/activities/_projects.html.haml
- app/views/staff/shared/activities/_third_party_projects.html.haml
- config/locales/models/organisation.en.yml
- spec/features/staff/users_can_create_a_project_level_activity_spec.rb
- spec/features/staff/users_can_create_a_third_party_project_level_activity_spec.rb
- spec/features/staff/users_can_view_fund_level_activities_spec.rb
- spec/features/staff/users_can_view_project_level_activities_spec.rb
- spec/features/staff/users_can_view_third_party_project_level_activities_spec.rb
Update Organisation#show and the third-party projects shared partial to use the `ActivityPolicy#create_child?` check.
NB: There are still a few places where we're using the old level-specific `create?` checks, but it proved pretty difficult to remove without breaking many tests, so let's leave it for now.
> (1644) Use ActivityPolicy#create_child? for more "create activity" buttons

- CHANGELOG.md
- doc/patterns.md
Create a guide to the various view helpers that developers have available to them. Starting with:
- `a11y_action_link`
- `link_to_new_tab`
I did wonder about implementing a proper pattern library, especially as we have a number of shared partials that might be useful to document, but this like a good start.
---
> (1641) Start documenting view helpers

- CHANGELOG.md
- app/presenters/activity_presenter.rb
- config/locales/codelists/2_03/iati.en.yml
- spec/presenters/activity_presenter_spec.rb
This adds a shared example that covers all presenter fields that have a translation. It runs through all the codes in a given codelist and checks that the output does not match the `/translation missing/` regex. I did consider raising an error, but I was concerned that might cause issues with legacy data. This at least makes sure any data that we add with the codelists we have now (and any codelists that change going forward) are covered by the translations.
> Make sure activity fields have all translations

- CHANGELOG.md
- app/controllers/staff/reports_controller.rb
- app/controllers/staff/spending_breakdowns_controller.rb
- app/services/activity_spending_breakdown.rb
- app/views/staff/reports/_download.haml
- config/locales/models/report.en.yml
- config/routes.rb
- spec/features/staff/users_can_view_reports_spec.rb
- spec/services/activity_spending_breakdown_spec.rb
This introduces a new report export CSV with a spending breakdown showing spending, refunds, and net values as distinct amounts for recent quarters. Specifically for each activity in the report, it includes:
- RODA, BEIS and DP identifiers
- title and description
- programme status and ODA eligibility
- for the most recent 7 quarters, the total spend, total refund and net
- for 13 quarters before those, the total net spend
- for 5 quarters after the report date, the forecast spend
The final commit is a refactoring of some code I encountered that I thought I would need to complete this feature. It ended up not being relevant but I thought I'd include it here in case people want it included. I'm happy to remove it if not.
> (1664) Export spending and refund data

- .pryrc
- Dockerfile
- doc/console-access.md
- doc/importing-new-delivery-partner-data.md
- Added `/usr/local/bin` to the `PATH`
- Automatically change into the `/app` directory on login
This means you can run `bin/rails c` rather than `cd /app; /usr/local/bin/ruby bin/rails c` 🎉 
- When running locally, prepend the Rails console prompt with `Rails.env`
- Make it super obvious you're connected to a production environment _(including warning banner when starting a non-sandboxed console in prod)_
- Show that you're running in `--sandbox` mode or not
Local development:
Staging (in sandbox mode):
Production:
> Remote shell improvements

- CHANGELOG.md
- app/models/activity.rb
- app/models/budget.rb
- app/presenters/activity_presenter.rb
- app/views/staff/activity_financials/show.html.haml
- spec/factories/budget.rb
- spec/features/staff/users_can_view_an_activity_spec.rb
- spec/models/activity_spec.rb
- spec/models/budget_spec.rb
- spec/presenters/activity_presenter_spec.rb
This tweaks the budget total calculation to only include transferred and direct budget, as well as showing to total forecast to date, as shown below:
> (1678) Improvements to totals

- CHANGELOG.md
- app/views/layouts/application.html.haml
- config/locales/views/footer.en.yml
- spec/features/user_can_view_static_pages_spec.rb
- Link to the Service performance Zendesk article in the footer
I have chosen to link to the generic article that will collect all service performance reports for each quarter, rather than to the specific link for the current quarter.
My thinking was that we don’t want to have to update the link during every quarter, but anyone disagrees this can be discussed.
> Link to the Service performance article in footer

- .github/workflows/rebase.yml
This tweaks the auto rebase action to automatically run the rebase action when a PR is set to automatically merge. This means that when a dev has approved a PR that is not up to date with the develop branch and set it to auto merge, this action will automatically bring it up to date (if possible), and it will then merge itself. As with the `/rebase` command, it adds a message to the PR if an automatic rebase is not possible.
We also check if the `AUTO_REBASE_PERSONAL_ACCESS_TOKEN` secret has been added, and add a message to the PR if it hasn't been added. I've added this secret coming from the dxw Rails user (who now has access to the project), so we can keep track with people rolling off the project for whatever reason. I'll delete the old, legacy `GH_ACCESS_TOKEN` secret (which is under …
> (1697) Automatically rebase when PR is set to auto merge

- CHANGELOG.md
- app/controllers/staff/searches_controller.rb
- app/presenters/activity_csv_presenter.rb
- app/services/activities/import_from_csv.rb
- app/services/activity_search.rb
- app/services/activity_spending_breakdown.rb
- app/services/export_activity_to_csv.rb
- app/views/staff/organisations/show.html.haml
- app/views/staff/searches/_form.html.haml
- app/views/staff/searches/show.html.haml
- config/locales/views/activity_search.en.yml
- config/routes.rb
- db/migrate/20210416123920_rename_beis_id_to_beis_identifier.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/features/staff/beis_users_can_invite_new_users_spec.rb
- spec/features/staff/users_can_search_for_activities_spec.rb
- spec/presenters/activity_csv_presenter_spec.rb
- spec/services/activities/import_from_csv_spec.rb
- spec/services/activity_search_spec.rb
- spec/services/activity_spending_breakdown_spec.rb
- spec/services/export_activity_to_csv_spec.rb
This adds a search function to the site, capable of searching for activities on the following fields:
- RODA identifier (both the complete ID and the activity-specific fragment)
- BEIS identifier
- Delivery partner identifier
- Previous identifier
- Title
All the identifier fields are case-insensitive complete matches -- you cannot search for a substring of an activity's ID. The title is also case-insensitive but supports partial matches, so you can find an activity without remember its complete title.
We could extend this partial matching to IDs, and perform word splitting on the query, and so on, but I'd rather put this in front of users and test it before adding such complexity.
This shows the search box on the home page:
Results for searching for an activity's RODA ID fragment: …
> (1674) Activity search

- bin/db-restore
There has recently been a row introduced into the database, which had a `%` literal in the title, which has caused issues with the database restore. To get around this, and give us a more reliable restore process, I've set the format to be a `.tar` file, which can be restored via `pg_restore`, rather than a plain text SQL dump.
> Use `pg_restore` to restore the dump

- bin/db-restore
To prevent a GPaaS user who has access to multiple tenants from restoring the database for the wrong project, pass the `-o` switch to `cf login`.
Additionally, I've added a check which calls `cf target`. If the user is already logged in and has access to the BEIS tenant (i.e. they recently accessed the console in production), they won't be asked to reauthenticate.
> Database restore script passes organisation flag

- CHANGELOG.md
- vendor/data/codelists/BEIS/gcrf_strategic_area.yml
This adds a new `Agile response in emergencies` option to the GCRF Strategic Area options
> Add new category to GCRF strategic area options

- CHANGELOG.md
- app/controllers/staff/reports_controller.rb
- app/presenters/activity_csv_presenter.rb
- app/services/export_activity_to_csv.rb
- spec/presenters/activity_csv_presenter_spec.rb
Users want to see the implementing organisations in the report csv. As
there can be multiple implementing organisations for a given activity we
need a separator when outputting into a single csv cell. As with the
rest of the application we use a pipe "|" symbol to achieve this.
As a general pattern we use a presenter to change the way data is
presented in certain contexts, here the csv presenter does the job.
> (1694) Feature include implementing organisation in the csv export

- CHANGELOG.md
- app/presenters/activity_presenter.rb
- app/services/activity_spending_breakdown.rb
- app/services/export_activity_to_csv.rb
- spec/features/staff/users_can_view_reports_spec.rb
Historical “ingested” reports don’t have any financial year and quarter.
Many of the features built around a report rely on the report having a financial quarter and year, and break if the report doesn’t.
In order to allow the historical reports to be accessed and downloaded, we need to add a lot of guards against the lack of financial year and quarter.
(Any reports being created now enforce the presence of a FY/FQ by assigning default values at creation, and the fields are readonly at database level.)
> Allow reports without financial year to be accessed

- CHANGELOG.md
- app/controllers/staff/organisations_controller.rb
- app/models/activity.rb
- app/models/financial_quarter.rb
- app/services/find_programme_activities.rb
- app/services/find_project_activities.rb
- app/services/find_third_party_project_activities.rb
- app/views/staff/organisations/show.xml.haml
- app/views/staff/shared/xml/_transaction.xml.haml
- config/environments/test.rb
- spec/features/staff/users_can_view_an_organisation_as_xml_spec.rb
- spec/models/activity_spec.rb
- spec/services/find_programme_activities_spec.rb
- spec/services/find_project_activities_spec.rb
- spec/services/find_third_party_project_activities_spec.rb
When reporting programme level activities to IATI we want to include transactions belonging to all child activities as well. We don't want an entry for each transaction rather we want to group them by financial quarter.
> (1677) Sum programme and child activity transactions by financial quarter in IATI XML

- CHANGELOG.md
- app/views/staff/shared/xml/_activity.xml.haml
- config/locales/views/iati_xml.en.yml
- spec/support/shared_examples/behaves_like_valid_activity_xml.rb
- Add BEIS contact info to the IATI XML
> (1682) Add BEIS contact info to the IATI XML

- CHANGELOG.md
- app/controllers/staff/planned_disbursements_controller.rb
- app/services/planned_disbursement_history.rb
- spec/features/staff/users_can_delete_a_planned_disbursement_spec.rb
- spec/services/planned_disbursement_history_spec.rb
- spec/services/planned_disbursement_overview_spec.rb
Deleting a forecast is equivalent to setting the latest revision to 0.
Rather than plainly deleting all revisions, different things need to happen depending on whether the forecast is pinned to a report, like in the case of level C and D activities, or not pinned, like in the case of levels A and B.
The forecast history already takes care of all these cases when setting a value to 0, whether through the interface or via bulk upload.
Deletion is a nicer way for users to express the intent to remove that forecast, while the history mechanism remains invisible from the outside.
Co-authored-by: jcoglan <james.coglan@dxw.com>
> Deleting a forecast is non-destructive

- CHANGELOG.md
- app/views/report_mailer/_submitted_service_owner.text.erb
- Fix a typo in the email notification sent to BEIS when a DP submits a report
> Fix typo in email notification
