- CHANGELOG.md
- app/services/activities/import_from_csv.rb
- spec/services/activities/import_from_csv_spec.rb
By default `sdgs_apply` is `false`.
Set it to `true` if at least one Sustainable Development Goal is populated during import.
NB: We don’t have a way to remove attributes during import, which is why we can’t currently detect if the goals are entirely removed in order to set it to `false`.
The goals themselves were set, but not correctly reflected in the interface. The interface said "Not applicable".
The goals are set and they are reflected in the interface.
> Infer the value of `sdgs_apply` when importing

- CHANGELOG.md
- app/controllers/staff/reports_controller.rb
- app/services/export_activity_to_csv.rb
- spec/services/export_activity_to_csv_spec.rb
Although of little value to delivery partners, having these columns in the report CSV file allows BEIS users to sort and filter the "all reports" CSV file by Delivery partner and/or fund name.
> (1712) Include organisation short name and fund name in report CSV files

- CHANGELOG.md
- app/mailers/report_mailer.rb
- app/models/user.rb
- app/services/report/send_state_change_emails.rb
- spec/mailers/report_mailer_spec.rb
- spec/services/report/send_state_change_emails_spec.rb
- spec/support/custom_email_matchers.rb
- Prevent report mailer from sending emails to inactive users
> (1738) Only send report-related emails to active users

- CHANGELOG.md
- db/data/20210514141445_change_gcrf_strategic_area_code_2_to_3.rb
- spec/presenters/activity_presenter_spec.rb
- vendor/data/codelists/BEIS/gcrf_strategic_area.yml
`Academies Collective Fund` and `Resilient Futures` should have been one single strategic area, so we're merging them into one, with code `3`. I've also added a data migration to change any activities with code `2` to a code `3`
> (1748) Merge two GCRF strategic areas

- CHANGELOG.md
- app/views/staff/organisations/_table.html.haml
- config/locales/models/organisation.en.yml
- spec/features/staff/beis_users_can_view_organisations_spec.rb
- Show organisation short name on organisations index page
> (1711) Show short name on organisations page

- .github/workflows/trigger_rebase.yml
As well as triggering a rebase by setting a PR to automerge or commenting `/rebase`, this PR adds the functionality to check over all PRs that are set to automerge and rebase them once a PR has been merged to `develop` or `master`. This is particularly helpful when we have a big backlog of PRs (i.e. from Dependabot), so we don't have to constantly manually rebase every time a new PR is merged.
> Trigger a rebase on all auto merge PRs on every merge to Develop

- CHANGELOG.md
- app/models/activity.rb
- spec/models/activity_spec.rb
Our first interation of totaling budgets was slightly wrong.
The total budget for a given activity is the sum of the budget entities at the current level only (not the sum of child entities like other finance data).
> (1799) Total budget should only be from specfic activity

- CHANGELOG.md
- Replace the broken sector code hint link with an easier to maintain BEIS Zendesk link
- Include 'source fund' and 'delivery partner short name' in CSV export
- Prevent report mailer from sending emails to inactive users
- Merge Academies Collective Fund and Resilient Futures GCRF strategic areas into one
- Show organisation short name on organisations index page
> 🚀 Release 50 🚀

- CHANGELOG.md
- app/controllers/staff/activity_financials_controller.rb
- app/controllers/staff/transfers_controller.rb
- app/models/report.rb
- app/models/transfer.rb
- app/policies/activity_policy.rb
- app/policies/transfer_policy.rb
- app/views/staff/activity_financials/show.html.haml
- db/migrate/20210518171318_add_report_association_to_transfers.rb
- db/schema.rb
- spec/controllers/staff/transfers_controller_spec.rb
- spec/features/staff/users_can_create_a_transfer_spec.rb
- spec/features/staff/users_can_edit_a_transfer_spec.rb
- spec/policies/activity_policy_spec.rb
- spec/policies/transfer_policy_spec.rb
- Allow DP users to create transfers from project and 3rd party project activities, and associate them with the current report
- Allow BEIS users to create transfers from fund and programme activities only
> (1805) Transfers must be associated to the report

- CHANGELOG.md
- Dockerfile
- app/controllers/public/base_controller.rb
- script/docker-push
- spec/requests/health_check_spec.rb
This sets the current Git sha and the time the image was built as env vars in our Docker file, which we then expose via the healthcheck endpoint, which will be useful for checking deploy throughput, as well as letting us know exactly what version of the code is deployed.
> Add some useful stats to our healthcheck endpoint

- CHANGELOG.md
- app/controllers/staff/activity_uploads_controller.rb
- app/controllers/staff/planned_disbursement_uploads_controller.rb
- app/controllers/staff/transaction_uploads_controller.rb
- app/policies/report_policy.rb
- app/views/staff/activity_uploads/new.html.haml
- app/views/staff/planned_disbursement_uploads/new.html.haml
- app/views/staff/reports/_actions.html.haml
- app/views/staff/reports/budgets.html.haml
- app/views/staff/reports/variance.html.haml
- app/views/staff/transaction_uploads/new.html.haml
- config/locales/models/report.en.yml
- spec/controllers/staff/activity_uploads_controller_spec.rb
- spec/controllers/staff/planned_disbursement_uploads_controller_spec.rb
- spec/controllers/staff/transaction_uploads_controller_spec.rb
- spec/models/report_spec.rb
- spec/policies/report_policy_spec.rb
The various upload controllers have been  relying on `ReportPolicy.show?` to determine whether to allow the user to upload, which caused:
- BEIS users were able to upload into any report at any time(!)
- Delivery partners could upload  as long as the current report belonged to them and wasn't inactive
This change introduces `ReportPolicy.upload?` which does the following:
- BEIS users can *never* upload
- Delivery partners can upload where the selected report is editable (i.e. has a state of 'active' or 'awaiting_changes')
> (1753) Hide upload buttons where appropriate

- CHANGELOG.md
- app/controllers/staff/organisations_controller.rb
- app/models/activity.rb
- app/models/financial_quarter.rb
- app/models/financial_year.rb
- app/presenters/planned_disbursement_aggregate.rb
- app/views/staff/organisations/show.xml.haml
- doc/xml-validation.md
- spec/features/staff/users_can_view_an_organisation_as_xml_spec.rb
- spec/models/financial_quarter_spec.rb
- spec/models/financial_year_spec.rb
- Sum programme and child activity forecasts by financial quarter in IATI XML
> (1681) Rolled up forecasts must be calculated in IATI XML

- CHANGELOG.md
- app/controllers/staff/users_controller.rb
- app/helpers/form_helper.rb
- app/models/user.rb
- app/policies/application_policy.rb
- app/policies/organisation_policy.rb
- app/policies/project_policy.rb
- app/policies/third_party_project_policy.rb
- app/views/staff/shared/users/_table.html.haml
- app/views/staff/users/_form.html.haml
- app/views/staff/users/show.html.haml
- config/locales/models/user.en.yml
- db/migrate/20210520134602_remove_role_from_users.rb
- db/schema.rb
- db/seeds/development_users.rb
- db/seeds/pentest_users.rb
- db/seeds/staging_users.rb
- spec/factories/user.rb
- spec/features/staff/beis_users_can_edit_a_user_spec.rb
- spec/models/user_spec.rb
- Remove roles from users. All users were 'administrators', with their access determined by the organisation they belong to
- Update `delivery_partner?` to use the organisation role instead of assuming "NOT a service owner" means the same thing
> (1824) Address some policy inconsistencies

- CHANGELOG.md
- app/helpers/application_helper.rb
- app/views/layouts/application.html.haml
- Extend the `link_to_new_tab` pattern to allow specifying the CSS class, while using the default `govuk-link` to keep existing usages as they are.
> (1713) Open footer external links in new tabs

- CHANGELOG.md
- config/locales/codelists/2_03/iati.en.yml
- spec/features/staff/users_can_add_benefitting_countries_spec.rb
- spec/features/staff/users_can_choose_recipient_country_spec.rb
- vendor/data/codelists/IATI/2_03/activity/recipient_country.yml
The recipient country codelist is lifted from IATI codelists, and is the source for the select boxes used on the activity form to select the recipient countries.
However, in this case, we don’t want to create a BEIS-specific codelist file, and accept that if we ever replace this file with a new codelist release from IATI, we might have to do the change again.
The IATI locale file was compiled by us based on official IATI codelists, and is used to display country names in both recipient country and intended beneficiaries sections on the activity details page.
> Use consistent naming for China

- CHANGELOG.md
- app/controllers/staff/users_controller.rb
This is to help BEIS users locate users more quickly in a long list. The
list is still sorted primarily by organisation, but within that users
are sorted by their full name.
> Sort users alphabetically on the `Users` screen

- app/views/staff/searches/_form.html.haml
When usig the search in Firefox (v89) as the text field is not set to `autocomplete=off` the browser show historic
suggestions. these suggestion take a second to appear and  by that point the user is click the search button directly under the autocomplete list thereby selecting a possibly incorrect serach value and submitting the form.
This sets `autocomplete` to `off`, so the browser does not show the historic suggestions.
> (1772) Set autocomplete to `off` for activity search

- CHANGELOG.md
- app/views/staff/shared/activities/_activity.html.haml
- spec/features/staff/users_can_edit_an_activity_spec.rb
- Only show Channel of delivery code for projects and third-party projects
> (1792) Do not show channel of delivery code on level B activities

- CHANGELOG.md
- app/mailers/report_mailer.rb
- app/services/report/send_state_change_emails.rb
- app/views/report_mailer/_approved_delivery_partner.text.erb
- app/views/report_mailer/_approved_service_owner.text.erb
- app/views/report_mailer/approved.text.erb
- config/locales/models/report.en.yml
- spec/features/staff/users_can_approve_a_report_spec.rb
- spec/mailers/report_mailer_spec.rb
- spec/services/report/send_state_change_emails_spec.rb
- Send approved report email notifications to BEIS users
> (1818) BEIS users receive report approved notification

- CHANGELOG.md
- app/models/organisation.rb
- app/views/staff/organisations/_form.html.haml
- app/views/staff/organisations/_table.html.haml
- config/locales/models/organisation.en.yml
- config/routes.rb
- spec/factories/organisation.rb
- spec/features/staff/beis_users_can_create_an_organisation_spec.rb
- spec/features/staff/beis_users_can_view_organisations_spec.rb
- spec/features/staff/users_can_edit_an_organisation_spec.rb
- spec/models/organisation_spec.rb
- Allow organisations of type "External Income Provider" to be created
> (1845) External Income Providers can be created

- CHANGELOG.md
- app/models/report.rb
- app/views/staff/reports/_summary.html.haml
- app/views/staff/reports/budgets.html.haml
- app/views/staff/reports/variance.html.haml
- config/locales/models/report.en.yml
- spec/features/staff/beis_users_can_edit_a_report_spec.rb
- spec/features/staff/users_can_activate_reports_spec.rb
- spec/features/staff/users_can_view_reports_spec.rb
- spec/models/report_spec.rb
- spec/views/staff/shared/message_spec.rb
Previously, we used the report description to derive the title shown on a single report view.
So far we have only ever seen a single report per quarter and the description is designed to be used when more than one report occurs in the same quarter.
The descriptions of the reports we have seen have generally been `[financial quarter] [fund] report` which made the title repetative and unclear.
The report description was also required which meant a user had to fill it in before being able to activate a report. This PR introduces two changes to ease this:
- the single report page now creates the title from two known values so it can be rendered without the user providing a descripiton formalising the report page title to `[financial quarter] [fund name] report` and showing the description in …
> (1840) Improvements to single report view

- CHANGELOG.md
- app/controllers/concerns/stream_csv_download.rb
- app/controllers/staff/exports/organisations_controller.rb
- app/controllers/staff/exports_controller.rb
- app/policies/export_policy.rb
- app/services/quarterly_transaction_export.rb
- app/views/shared/_navigation.html.haml
- app/views/staff/exports/index.html.haml
- app/views/staff/exports/organisations/show.html.haml
- config/locales/views/exports.en.yml
- config/routes.rb
- script/test
- spec/features/staff/beis_users_can_download_exports_spec.rb
- spec/policies/export_policy_spec.rb
- spec/services/quarterly_transaction_export_spec.rb
This adds the ability for BEIS users to download all the transactions for each delivery partner as a CSV file that lists all the partner's activities with their total spending by quarter.
The main points of note here are that we probably want to iterate the design here -- do we want this split up by delivery partner, or should we have one big download? Do we need it more granular and split up by fund, etc.
The permissions here are very coarse, I've just limited this to only BEIS users. I'd expect this to change as iterating the design would probably mean changing the routes/resources/controllers we have here so I didn't want to get too into modelling permissions over those until we've a better idea of what we really want.
All these changes are only visible to BEIS users. A new item is …
> CSV export of all actual spend

- CHANGELOG.md
- app/helpers/application_helper.rb
- app/views/pages/accessibility_statement.html.haml
- app/views/pages/terms_of_service.html.haml
- app/views/report_mailer/_footer.text.erb
- app/views/shared/_help_and_support.html.haml
This replaces all the mentions of the old support email (RODAsupport@odamanagement.org) with the new one (support@beisodahelp.zendesk.com), and adds a helper the generate a link to the support email.
> (1848) Change the email address given in email notifications

- spec/services/quarterly_transaction_export_spec.rb
This test always fails for me, but it doesn't appear to fail on CI or
on other people's machines. It could be because I'm running a newer
version of Postgres (13.2) -- in any case, we don't specify the return
order for the transaction data, so we can use `match_array` instead.
> Fix transaction export spec array assertion

- CHANGELOG.md
- app/controllers/staff/activity_other_funding_controller.rb
- app/controllers/staff/external_incomes_controller.rb
- app/helpers/form_helper.rb
- app/models/activity.rb
- app/models/external_income.rb
- app/models/organisation.rb
- app/policies/external_income_policy.rb
- app/presenters/external_income_presenter.rb
- app/views/staff/activity_other_funding/show.html.haml
- app/views/staff/external_incomes/_form.html.haml
- app/views/staff/external_incomes/edit.html.haml
- app/views/staff/external_incomes/new.html.haml
- app/views/staff/matched_efforts/edit.html.haml
- app/views/staff/shared/external_income/_table.html.haml
- config/locales/models/external_income.en.yml
- config/locales/models/matched_effort.en.yml
- config/routes.rb
- db/migrate/20210527130555_add_external_income.rb
- db/schema.rb
- spec/factories/external_income.rb
- spec/features/staff/users_can_create_an_external_income_spec.rb
- spec/features/staff/users_can_edit_an_external_income_spec.rb
- spec/features/staff/users_can_view_an_activitys_funding_spec.rb
- spec/models/activity_spec.rb
- spec/models/organisation_spec.rb
- spec/policies/external_income_policy_spec.rb
- spec/presenters/external_income_presenter_spec.rb
- spec/support/form_helpers.rb
- Allow users to add, edit and delete external income on activities
> (1774) Allow users to add, edit and delete external income on activities

- CHANGELOG.md
- app/models/activity.rb
- app/models/report.rb
- spec/controllers/staff/transaction_uploads_controller_spec.rb
- spec/models/activity_spec.rb
- spec/models/report_spec.rb
This updates the Report `reportable_activities` method to only return Activities that have an ODA Status of "eligible" and are do not have a programme status of "completed", "stopped", "cancelled" or "paused". I've done a bit of refactoring on the way too, and added some extra tests.
> (1812) Only show activities with relevant statuses in the actuals upload template

- CHANGELOG.md
- app/controllers/staff/reports_controller.rb
- spec/features/staff/users_can_view_reports_spec.rb
- Approved reports are displayed in historical order
> (1816) Approved reports are displayed in historical order

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/helpers/codelist_helper.rb
- app/models/codelist.rb
- app/models/fund.rb
- app/services/activities/import_from_csv.rb
- app/views/staff/activity_forms/fstc_applies.html.haml
- config/locales/models/activity.en.yml
- db/data/20210527151650_update_fstc_applies_based_on_aid_type.rb
- spec/features/staff/beis_users_can_create_a_programme_level_activity_spec.rb
- spec/features/staff/users_can_create_a_project_level_activity_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/helpers/codelist_helper_spec.rb
- spec/models/codelist_spec.rb
- spec/support/form_helpers.rb
- vendor/data/codelists/BEIS/aid_type.yml
This updates the logic in the `fstc_applies` question step to set it automatically in most cases based on the the Aid Type. Before we were only setting the value of `fstc_applies` in one particular case, now we can set it in virtually all cases, except in a couple where we need to ask.
We do this by creating a new BEIS Aid Type codelist which has a `ftsc_applies` value in the YAML that tells us whether to set it to true or false. If the value is not true or false, we ask.
There is also a data migration that we'll need to run that will set historical activities to the value we expect. BEIS are aware and will tell DPs this is happening. We'll also need to tell BEIS when this is done.
> (1767) Verify and improve fstc_applies question logic and experience

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/services/activities/import_from_csv.rb
- app/views/staff/shared/activities/_activity.html.haml
- config/locales/models/activity.en.yml
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/features/staff/users_can_upload_activities_spec.rb
- Users can no longer update the delivery partner identifier
> (1837) Users can no longer update the delivery partner identifier

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/helpers/codelist_helper.rb
- app/services/activity/updater.rb
- app/views/staff/shared/activities/_activity.html.haml
- spec/factories/activity.rb
- spec/features/staff/users_can_create_a_project_level_activity_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/features/staff/users_can_manage_collaboration_type_for_activities_spec.rb
- spec/helpers/codelist_helper_spec.rb
- spec/support/form_helpers.rb
- vendor/data/codelists/BEIS/aid_type.yml
- vendor/data/codelists/BEIS/collaboration_type.yml
If `aid_type` is set to `B02` or `B03` then we infer the value of `collaboration_type` and do not let the user change it.
I based this on an earlier pattern that @CristinaRO implemented for inferring the FSTC value, but this has recently been refactored in `CodelistHelper`. I have got this working on top of those recent changes but wonder if I should also refactor what I've done here to match the new pattern done by @pezholio.
> (1790) Collaboration type logic

- CHANGELOG.md
- app/controllers/staff/activity_uploads_controller.rb
- app/views/staff/activity_uploads/_success_table.html.haml
- app/views/staff/activity_uploads/update.html.haml
- spec/features/staff/users_can_upload_activities_spec.rb
Show the user a table view of the freshly uploaded activities, split by created and updated.
> (1871) Show the user the uploaded activities

- .dockerignore
- bin/db-restore
- doc/database-backup-and-restore.md
- script/db-restore
- script/prepare_for_import.rb
As part of the import process for newly onboarded DPs, we need to test the data in development. 
As part of this process, to make sure our local  environment mirrors that of  the production environment, we need to take  a cut of the production data  and import it to our local environment. 
As well as this, we need to make sure  that we have a user for the DP we are  testing with, as well as an active  report. As we have to do this a number of  times for each DP, this needs to be done a lot, so I've added a script that  allows us to automate this, to make the testing process less painful.
> (1889) Create a script to prepare the dev environment for a data import

- CHANGELOG.md
- app/controllers/staff/incoming_transfers_controller.rb
- app/controllers/staff/outgoing_transfers_controller.rb
- app/views/staff/incoming_transfers/confirm.html.haml
- app/views/staff/outgoing_transfers/confirm.html.haml
- app/views/staff/shared/transfers/_form.html.haml
- app/views/staff/shared/transfers/_index.html.haml
- config/locales/models/incoming_transfer.en.yml
- config/locales/models/outgoing_transfer.en.yml
- db/migrate/20210614155407_add_beis_identifier_to_transfers.rb
- db/schema.rb
- spec/features/staff/users_can_create_an_incoming_transfer_spec.rb
- spec/support/form_helpers.rb
- spec/support/shared_examples/creating_a_transfer.rb
- Incoming and outgoing transfers can store the historic BEIS identifier (tracker row ID)
> (1835) Transfers store historic BEIS identifier

- CHANGELOG.md
- app/helpers/form_helper.rb
- app/views/staff/shared/activities/_filter.html.haml
- spec/features/staff/users_can_view_activities_spec.rb
- spec/helpers/form_helper_spec.rb
As only Delivery Partners have activities assoiciated with them, we don't want to see any non-Delivery Partners to be able to be selected when filtering Activites by organisation.
> (1895) Hide non-DP orgs on the Activities dropdown

- CHANGELOG.md
- app/helpers/form_helper.rb
- app/models/organisation.rb
- app/views/staff/shared/activities/_filter.html.haml
- spec/features/staff/users_can_filter_activities_spec.rb
- spec/helpers/form_helper_spec.rb
- spec/models/organisation_spec.rb
- Fix: include BEIS in the organisation filter on the activities page
> (1907) BEIS should be in the activities organisation filter

- CHANGELOG.md
- db/data/20210624142643_change_gcrf_strategic_area_to_alphanumeric.rb
- db/migrate/20210624123510_change_gcrf_strategic_area_to_string.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/models/activity_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/services/activities/import_from_csv_spec.rb
- vendor/data/codelists/BEIS/gcrf_strategic_area.yml
This changes the GCRF Strategic Area codes from numeric to Alphanumeric, so we can use them when we start to automate the RODA identifiers. I've also added a data migration that will need running to change the existing codes that we do have.
> (1808) Change GCRF Strategic Area codes to Alphanumeric

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/models/activity.rb
- app/models/historical_event.rb
- app/models/user.rb
- app/services/history_recorder.rb
- db/migrate/20210624093716_create_historical_events.rb
- db/schema.rb
- spec/controllers/staff/activity_forms_controller_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/models/activity_spec.rb
- spec/models/historical_event_spec.rb
- spec/models/user_spec.rb
- spec/services/history_recorder_spec.rb
- spec/spec_helper.rb
https://trello.com/c/tt3mt1wQ/1927-record-activity-changes-made-via-wizard
`Staff::ActivityFormsController` uses new `HistoryRecorder` service to record changes made via wizard:
e.g.
```ruby
HistoryRecorder
.new(user: current_user)
.call(
changes: @activity.changes,
reference: "Update to Activity purpose",
activity: @activity
)
```
For each change in the list of `changes` given to `HistoryRecorder`, the recorder creates a `HistoricalEvent` record.
**HistoricalEvent**:
- `activity_id`: uuid
- `value_changed`: the attribute, e.g. "title",
- `new_value`: stored as YAML to handle various data types 
- `previous_value`: stored as YAML to handle various data types 
- `user_id`: UUID (but maybe should be email address or name?),
- `reference`: e.g 'Update to Activity purpose' or 'Upload of …
> Feature (1927) Record changes made to Activities via Wizard

- CHANGELOG.md
- app/controllers/staff/report_transactions_controller.rb
- app/controllers/staff/transaction_uploads_controller.rb
- app/services/import_transactions.rb
- app/views/shared/transactions/_transactions_by_activity.html.haml
- app/views/staff/reports/_actions.html.haml
- app/views/staff/reports/_tab.html.haml
- app/views/staff/reports/_tab_list.html.haml
- app/views/staff/reports/forecasts.html.haml
- app/views/staff/reports/transactions.html.haml
- app/views/staff/transaction_uploads/update.html.haml
- config/locales/models/report.en.yml
- config/locales/models/transaction.en.yml
- config/routes.rb
- spec/features/staff/users_can_upload_transactions_spec.rb
- spec/features/staff/users_can_view_actuals_within_report_spec.rb
- spec/services/import_transactions_spec.rb
This builds on some of the work in #1189 to:
* Add a new "Actuals" tab to the reports section to show transactions that have been reported during a reporting cycle, together with totals
* Move the "Upload Actuals" button to the "Actuals" page
* Present uploaded transactions back to the user when they have been successfully uploaded, together with a button to navigate back to the Report
> (1530) Improvements to the reporting actual spend journey

- Gemfile
- Gemfile.lock
This provides handy debugging behaviour on top of pry, e.g.
taken from https://github.com/deivid-rodriguez/pry-byebug
*break*: Manage breakpoints.
*step*: Step execution into the next line or method.
Takes an optional numeric argument to step
multiple times.
*next*: Step over to the next line within the same frame.
Also takes an optional numeric argument to step
multiple lines.
*finish*: Execute until current stack frame returns.
*continue*: Continue program execution and end the Pry session.
> Add pry-byebug gem for more powerful debugging

- CHANGELOG.md
- app/services/activities/import_from_csv.rb
- spec/features/staff/users_can_upload_activities_spec.rb
- spec/services/activities/import_from_csv_spec.rb
https://trello.com/c/BDdnYxcb/1928-record-activity-changes-made-in-bulk
When processing bulk imports of activities in CSV form we now record any updates to existing activities using the new `HistoryRecorder` service, which creates a `HistoricalEntry` record for each attribute being updated. 
Those updated attributes are obtained using `Activity#changes` before the activity in question is saved.
> Feature (1928) Record activity changes made in bulk via CSV upload

- doc/forecasts-and-versioning.md
When an activity has been added which is not required, usually through
error, we need to delete it and all its associated entities.
This is the ONE time it is safe to delete `Forecast` rows in the database.
> Document deleting the entire forecast history

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/models/historical_event.rb
- app/models/report.rb
- app/services/history_recorder.rb
- db/migrate/20210630094140_add_report_id_to_historical_event.rb
- db/schema.rb
- spec/controllers/staff/activity_forms_controller_spec.rb
- spec/features/staff/users_can_edit_an_activity_spec.rb
- spec/models/historical_event_spec.rb
- spec/models/report_spec.rb
- spec/services/history_recorder_spec.rb
When editing an `Activity` via the `ActivityFormController` we now:
- look up the appropriate `Report` 
- pass that report to the `HistoryRecorder`
- see the `HistoryRecorder` associate the given `Report` with each `HistoricalEvent` created
> (1930) Feature: associate Report with Wizard-orchestrated change to activity

- CHANGELOG.md
- app/controllers/auth0_controller.rb
- app/controllers/staff/dashboards_controller.rb
- app/controllers/staff/home_controller.rb
- app/policies/dashboard_policy.rb
- app/policies/home_policy.rb
- app/views/layouts/application.html.haml
- app/views/shared/_navigation.html.haml
- app/views/staff/home/_delivery_partner_organisations_table.html.haml
- app/views/staff/home/show.html.haml
- config/locales/default.en.yml
- config/routes.rb
- spec/features/staff/users_can_sign_in_spec.rb
- spec/features/staff/users_can_view_a_home_page_spec.rb
- spec/features/staff/users_can_view_the_site_navigation_spec.rb
We have been using the organisation show page as the user 'home' page for some time, which never felt right.
This work introduces a distinct home page for BEIS users that lets them focus on common tasks and as a 'launching off point' for the applicaiton, this is the design in our last round of user testing.
Future work will do something similar for delivery partner users, but for now we redirect and keep the experience the same fo them.
> (1894) Feature: new BEIS user home page

- doc/architecture/decisions/0031-replace-publicactivity-with-our-own-hand-rolled-way-of-recording-changes.md
This adds an ADR for our decision to roll our own approach to logging history via the `HistoricalActivity` model and associated services.
> ADR: Replace PublicActivity with HistoricalActivity

- CHANGELOG.md
- app/controllers/staff/budgets_controller.rb
- app/models/budget.rb
- app/presenters/budget_presenter.rb
- spec/features/staff/users_can_create_a_budget_spec.rb
- spec/models/budget_spec.rb
- spec/presenters/budget_presenter_spec.rb
When tweaking the allowed budget types, we stopped defaulting to a particular type, and this highlighted the fact that we didn't actually validate the `budget_type` was present. This PR adds a validation to make sure a Budget Type is selected, as well as setting the default `budget_type` to `direct`.
> (1937) Budget type should be required and default to the direct type of the current activity fund

- CHANGELOG.md
- app/controllers/public/visitors_controller.rb
- app/controllers/staff/home_controller.rb
- app/javascript/packs/application.js
- app/views/staff/home/delivery_partner.html.haml
- app/views/staff/home/service_owner.html.haml
- app/views/staff/shared/activities/tree_view/_row.html.haml
- app/views/staff/shared/activities/tree_view/_table.html.haml
- app/views/staff/shared/activities/tree_view/_table_tabbed.html.haml
- config/locales/models/activity.en.yml
- spec/features/public/visitors/home_page_spec.rb
- spec/features/staff/users_can_sign_in_spec.rb
- spec/features/staff/users_can_view_a_home_page_spec.rb
Following #1210 this work intoduces the delivery partner home page.
Delivery partners see the search widget and the hierarchical activity view on their home page, allowing them to locate their most common activities right from the home page.
The activity views are split by fund and progressively enchanced into tabs, this allows the users to view both funds activities without using a great deal of vertical space, for users with large numbers of activities this stops them potentially having to scroll a long way to locate activities.
The last commit 346384d contains a change to the JS pack as it seems the GOVUK JS was never being initialised correctly that makes the GOVUK JS tabs work.
> (1934) Feature: create new delivery partner home page

- CHANGELOG.md
- app/controllers/staff/activity_uploads_controller.rb
- app/services/activities/import_from_csv.rb
- spec/controllers/staff/activity_uploads_controller_spec.rb
- spec/features/staff/users_can_upload_activities_spec.rb
- spec/services/activities/import_from_csv_spec.rb
This PR adds an optional `report` parameter to `Activities::ImportFromCsv` (and its internal `ActivityUpdater` class) so that when a CSV containing changes to existing activities is uploaded via the `Staff::ActivityUploadsController`, the appropriate report can be passed through to the `HistoryRecorder`.
> (1929) Feature: associate report with HistoricalEvents arising from bulk changes to activities

- CHANGELOG.md
- app/controllers/staff/report_activities_controller.rb
- app/controllers/staff/report_variance_controller.rb
- app/controllers/staff/reports_controller.rb
- app/controllers/staff/spending_breakdowns_controller.rb
- app/models/activity.rb
- app/models/report.rb
- app/services/activity/projects_for_report_finder.rb
- spec/factories/activity.rb
- spec/features/staff/users_can_upload_forecasts_spec.rb
- spec/features/staff/users_can_upload_transactions_spec.rb
- spec/models/activity_spec.rb
- spec/models/report_spec.rb
- spec/services/activity/projects_for_report_finder_spec.rb
The `projects_and_third_party_projects_for_report` scope is currently quite slow because we walk the entire tree to
get the activities. Now we have the `source_fund_code` attribute, we can get all these in one query.
I also had to make some tweaks to the Activity factory to get the parent fund by fetching or creating a parent fund.
> Optimise projects_and_third_party_projects_for_report scope

- CHANGELOG.md
- app/assets/stylesheets/partials/_historical_events.css.scss
- app/controllers/staff/activity_historical_events_controller.rb
- app/services/activity/historical_events_grouper.rb
- app/views/staff/activity_historical_events/show.html.haml
- config/environments/test.rb
- spec/controllers/staff/activity_historical_events_controller_spec.rb
- spec/features/staff/users_can_view_an_activitys_change_history_spec.rb
- spec/services/activity/historical_events_grouper_spec.rb
- Group historical events by reference (and timestamp)
- Order, newest first
Ordered by creation time, ungrouped:
Ordered (newest first), and grouped by reference:
> Group historical events according to reference. And order, newest first

- app/models/fund.rb
- spec/controllers/staff/activity_forms_controller_spec.rb
- spec/factories/activity.rb
- spec/models/activity_spec.rb
- spec/models/fund_spec.rb
- spec/services/export_activity_to_csv_spec.rb
- vendor/data/codelists/BEIS/fund_types.yml
This allows the `Fund` model to return the short name of a given Fund - taken from the Yaml code file. I've also made a couple of quality of life improvments and also made sure all our knowedge about a fund's codes is taken from the Yaml file, rather than spread across the codebase.
> (1993) Fund model stores the shortname

- app/controllers/staff/activities_controller.rb
- app/controllers/staff/home_controller.rb
- app/services/activity/grouped_activities_fetcher.rb
- app/views/staff/activities/historic.html.haml
- app/views/staff/activities/index.html.haml
- app/views/staff/home/delivery_partner.html.haml
- app/views/staff/shared/activities/_table.html.haml
- app/views/staff/shared/activities/tree_view/_table.html.haml
- app/views/staff/shared/activities/tree_view/_table_tabbed.html.haml
- spec/controllers/staff/activities_controller_spec.rb
- spec/controllers/staff/home_controller_spec.rb
- spec/features/staff/users_can_view_activities_spec.rb
- spec/services/activity/grouped_actitvities_fetcher_spec.rb
This PR changes the way we fetch grouped activities by adding a new `Activity::GroupedActivitiesFetcher`, which we can
use in the homepage and activities page. It also improves on what we have by doing all the fetching of child activities in the class itself, rather than while rendering the page. It also fixes a bug where child activities didn't have the same scope as the programmes, so historic projects were showing up under currently running programmes.
I've also taken the opportunity to tweak some of the feature tests to use stubs and mocks, so we're not having to create so many objects in the database, hopefully speeding up the tests a little bit.
> (1956) Improve the query that populates the activity tree view

- CHANGELOG.md
- app/models/activity.rb
- app/models/report.rb
- db/data/20210712154115_remove_orphaned_historical_events.rb
- spec/models/report_spec.rb
We heard from a BEIS user that they could not view a report. The issue was that we had deleted an `Activity` from the report that had already created some `HistroricalEvents`. This meant the event stored the ID of an activity that no longer exists.
The `Report` method `activities_updated` uses the Activity IDs in the HistoricalEvents to get a list of 'activities which have been modified in this report`. Under the hood, this method called `find` passing in an array of activity IDs from the historical events.
In cases where the activity has been deleted, this causes `find` to raise an error.
To fix this we swap to a `where` as this will always return a enumerable, even if it is empty and so the view can be rendered in an empty state.
This work also adds `dependent: destroy` on `Activity` so …
> (2004) fix: orphanned historicevents cause activitiesupdated to fail

- CHANGELOG.md
- app/services/history_recorder.rb
- db/data/20210712154227_remove_historical_events_for_wizard_form_state_changes.rb
- spec/services/history_recorder_spec.rb
https://trello.com/c/Yr4Kxj3X/1995-change-history-includes-the-formstate-changes
We no longer record HistoricalEvents for changes which are to `Activity#form_state`. This is an internal property of the Wizard system we are using for multi-step forms.
We also include a simple data migration to remove existing events of this type. It should be run after deployment with:
```
rails runner db/data/20210712154227_remove_historical_events_for_wizard_form_state_changes.rb
```
- [ x] Run 'data migration' after deployment
> Fix (1995) Don't record changes in the Wizard's "Form state"

- CHANGELOG.md
- app/controllers/staff/report_activities_controller.rb
- app/views/staff/activity_uploads/_activities_table.html.haml
- app/views/staff/activity_uploads/update.html.haml
- app/views/staff/reports/activities.html.haml
- config/locales/models/activity.en.yml
- spec/features/staff/users_can_upload_activities_spec.rb
- spec/features/staff/users_can_view_reports_spec.rb
The goal of the report > activities tab is to show all users a clear list of the activites which have either been:
- newly added to the report
- had the activity attributes changed in the report
Now we have the `new_activties` association and the `activites_updated` method on Report, this is straight forward to achieve.
> (1948) Feature: split activity report by new and updated activities

- .github/workflows/deploy.yml
- script/deploy-notification
This adds a new job in the deploy Github Action to poll the Health Check URL and check the SHA returned matches the current SHA of the code we’ve deployed.
Once it does it sends a message to our Slack channel to inform the team that the code has been deployed.
This only runs on production deploys and times out after 30 minutes (in case something has gone wrong and we end up waiting forever for something that is never going to happen)
Here's a sample of how the Slack message will look
> Send a notification on successful deploy

- CHANGELOG.md
- app/views/staff/exports/index.html.haml
- Exports page uses the two columns pattern, and has accessibility links to each delivery partner’s exports page.
> (1961) Exports page has accessibility links

- CHANGELOG.md
- app/controllers/staff/activity_forms_controller.rb
- app/controllers/staff/transactions_controller.rb
- app/models/historical_event.rb
- app/models/transaction.rb
- app/services/activities/import_from_csv.rb
- app/services/history_recorder.rb
- app/services/update_transaction.rb
- app/views/staff/activity_historical_events/show.html.haml
- db/migrate/20210719082105_make_historical_event_polymorphic.rb
- db/schema.rb
- spec/controllers/staff/activity_forms_controller_spec.rb
- spec/controllers/staff/transactions_controller_spec.rb
- spec/factories/historical_event.rb
- spec/features/staff/users_can_edit_a_transaction_spec.rb
- spec/features/staff/users_can_view_an_activitys_change_history_spec.rb
- spec/models/historical_event_spec.rb
- spec/models/transaction_spec.rb
- spec/services/activities/import_from_csv_spec.rb
- spec/services/activity/historical_events_grouper_spec.rb
- spec/services/history_recorder_spec.rb
- spec/services/update_transaction_spec.rb
Every historical event is associated with an activity. It is through the lens of an activity (the 'Activity page') that we wish to study changes.
Some historical events concern the associated activity directly, but others concern a related item, such as a Transaction, Budget or Forecast. 
In this PR we
- require users of `HistoryRecorder` to supply a "trackable" entity in addition to an associated Activity
- adapt the `UpdateTransaction` service to record changes using the `HistoryRecorder`
- add a 'polymorphic' `trackable` association on `HistoricalEvent` to identify the entity (Transaction or Activity and soon Budget and Forecast) which has changed
Details of changes to transactions (aka "actuals") now shown in an Activity's "Change history"
tab: …
> (1949) Feature: track changes to financial info (Transactions aka Actuals initially)

- app/views/staff/exports/index.html.haml
- app/views/staff/home/_delivery_partner_organisations_table.html.haml
- config/locales/default.en.yml
- Don't show visited state for exports links
- Add exports link to the organisations table
> (1961) Tweak table links

- CHANGELOG.md
- app/views/shared/transactions/_transactions_by_activity.html.haml
- app/views/staff/reports/transactions.html.haml
- app/views/staff/transaction_uploads/new.html.haml
- config/locales/models/report.en.yml
- config/locales/models/transaction.en.yml
- spec/features/staff/users_can_upload_transactions_spec.rb
- spec/features/staff/users_can_view_actuals_within_report_spec.rb
- spec/features/staff/users_can_view_reports_spec.rb
The main motivation here was:
- the old content was using the wrong lanuage and linking to the wrong guidance
- it was clear in Q1 that showing the financial quarter for each actual spend entry would help users in the short term.
As we don't have a content designer, I had a go at improving things on the tab and relating upload page.
Actuals tab with no active report:
Actuals tabs with active report, shows new content and layout:
Actual spend upload, shows new content:
> (2011) Report actuals tab improvements

- CHANGELOG.md
- app/controllers/staff/spending_breakdowns_controller.rb
- spec/features/staff/users_can_view_reports_spec.rb
Spending reports were throwing a:
NoMethodError (undefined method `each' for #<Activity::ProjectsForReportFinder>):
/app/controllers/staff/spending_breakdowns_controller.rb:24
error which was causing an empty CSV file to be downloaded.
We now include an Actual "transaction" in our feature test
and verify that the downloaded file is not empty.
Trello: https://trello.com/c/ceicvcWC/2010
> Fix: Load report activities correctly for spending report

- .github/workflows/deploy.yml
- README.md
- script/deploy-terraform
This updates the deploy script to deploy to the pentest (training) environment at the same time as we deploy to production to ensure parity of feature set across the two environments.
~I haven't yet added the environment variables to Github, so this needs to be done first. Will update the PR when I'm done.~
I've tweaked the steps to run as seperate jobs for a couple of reasons:
- I (think?) it's more readable
- It allows us to run the prod and training deploys in parallel, so the deploy shouldn't be much slower than what we have already.
Totally happy to have a chat about how this all fits together - I am aware that I am the Github Actions "expert" here, so keen to pass on more knowlege if I can!
> (2009) Auto deploy to pentest environment

- CHANGELOG.md
- app/controllers/staff/budgets_controller.rb
- app/policies/budget_policy.rb
- app/views/staff/budgets/_form.html.haml
- config/locales/models/budget.en.yml
- config/routes.rb
- spec/features/staff/users_can_edit_a_budget_spec.rb
- spec/policies/budget_policy_spec.rb
We want to make sure if there is an editable report, then budgets created erroneously can be deleted.
> (1997) Allow budgets to be destroyed

- app/views/staff/reports/budgets.html.haml
- app/views/staff/shared/reports/_table_budgets.html.haml
- config/locales/models/budget.en.yml
This is just some small text tweaks to the budget tab within reports
> (1964) improve the budget report tab

- CHANGELOG.md
- app/assets/stylesheets/partials/_forms.css.scss
- app/helpers/codelist_helper.rb
- app/javascript/packs/application.js
- app/javascript/src/region-countries-checkbox.js
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/services/activity/updater.rb
- app/views/staff/activity_forms/benefitting_countries.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- config/locales/models/activity.en.yml
- db/migrate/20210727163803_add_benefitting_countries_to_activities.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/features/staff/beis_users_can_create_a_programme_level_activity_spec.rb
- spec/features/staff/users_can_add_benefitting_countries_in_one_step_spec.rb
- spec/features/staff/users_can_add_benefitting_countries_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/support/form_helpers.rb
- Collect all `benefitting_countries` in one step
> (1979) Collect benefitting countries

- app/views/staff/organisations/_table.html.haml
- app/views/staff/shared/activities/tree_view/_table.html.haml
- app/views/staff/shared/reports/_table_header.html.haml
- app/views/staff/shared/reports/_table_variance.html.haml
- app/views/staff/shared/users/_table.html.haml
This came up in a recent accessibility review. I've wrapped the text in a `govuk-visually-hidden` span, because adding "Actions" everywhere adds a bit too much visual noise.
> (2027) Ensure table headers have discernible text

- app/views/staff/reports/_tab_list.html.haml
This has the effect of invalidating the HTML code. Screen readers notify users when they come to a list, and tell them how many items are in a list. If you don't mark up a list using proper semantic markup in a hierarchy, list items cannot inform the listener that they are listening to a list when no parent is indicating the presence of a list and the type of list.
> (2033) Remove role=navigation from reports tabs

- CHANGELOG.md
- app/controllers/staff/report_variance_controller.rb
- app/services/activity/variance_fetcher.rb
- app/views/staff/reports/variance.html.haml
- app/views/staff/shared/reports/_table_variance.html.haml
- config/locales/default.en.yml
- config/locales/models/activity.en.yml
- spec/features/staff/users_can_create_a_comment_spec.rb
- spec/features/staff/users_can_edit_a_comment_spec.rb
- spec/features/staff/users_can_view_reports_spec.rb
- spec/services/activity/variance_fetcher_spec.rb
This improves the report variance tab to only show activities that actually have variance, as well as showing the total. I've also made a bunch of changes to the view to (hopefully) make the tab a bit more approachable.
> (1977) Improve the report variance tab

- CHANGELOG.md
- Move IATI XML exports to the exports section
- Collect all benefitting countries in one step
- Benefitting countries can be imported via CSV upload
- Tidy up Report Variance tab to only show activities that have a varaince
> Release 65

- app/services/activity_search.rb
- spec/services/activity_search_spec.rb
Before, the ActivitySearch only searched for activities where the organisation matched the organisation of
the DP. However, this doesn't quite chime with the experience of how DPs view Activities. When they log in they see Programmes, Projects and Third-Party Projects.
Programmes ALWAYS have the `organisation` set to the Service Owner organisation, while the `extending_organisation` is that of the Delivery Partner. Projects and Third-Party Projects have both `organisation` and `extending_organisation` set to that of the Delivery Partner.
With this in mind, to get Programmes to show up in the search, we need to search by `extending_orgaisation`, not `organisation`. I've updated the tests to reflect this too.
> Allow DPs to search for their own programmes

- CHANGELOG.md
- app/controllers/concerns/auth.rb
- spec/features/staff/users_can_sign_in_spec.rb
Currently, users that are made inactive, but still logged in can access parts of the site while their session remains valid (i.e. they don't logout, or their session doesn't time out). To get around this edge case, when fetching the `current_user`, we limit our query to only current users. If an active user is not found, we invalidate the session and return an error message
> Make sure users are active even after login

- CHANGELOG.md
- app/helpers/activity_helper.rb
- app/views/staff/shared/xml/_activity.xml.haml
- spec/features/staff/users_can_view_an_activity_as_xml_spec.rb
- spec/helpers/activity_helper_spec.rb
This adjusts the XML exports to use the new `benefitting_countries` field, rather than the old, legacy `recipient_country` / `recipient_region` fields
> (1982) Adjust XML exports to use new benefitting countries field

- app/views/staff/shared/activities/_activity.html.haml
Add and Edit links must have an accessible name
- Add helper which generates accessible links for "Add", "Edit".
- "Govuk-visually-hidden" accessible name
> 2034 serious links must have an accessible name

- db/data/20210804154421_backfill_benefitting_countries.rb
- spec/features/staff/users_can_add_benefitting_countries_in_one_step_spec.rb
- vendor/data/codelists/BEIS/region_to_subregion_mapping.yml
- vendor/data/codelists/IATI/2_03/activity/intended_beneficiaries.yml
**ETA**: There are activities which have `geography=recipient_region` but also have `recipient_country` and/or `intended_beneficiaries`.
There are activities which have `geography=recipient_country` but also have `recipient_region`.
While the two geography options should have been mutually exclusive, the reality is that users have managed to fill in more data than that, and we don’t want to risk losing it.
Our choices were to only use the data corresponding to the geography - and risk discarding some data; use any and all data we can find in the records - and risk having the wrong data; run a report for any ambiguous cases - and risk delaying the process indefinitely.
Following a discussion with Meyric, we have chosen the second option.
The legacy fields will not be removed until BEIS are …
> (1985) Backfill benefitting_countries where possible

- app/assets/stylesheets/partials/_table.scss
Table overflows the normal device veiwport, causing the browser to add a horizontal scroll on the website, this is an accessibility issue. I have styled the data tables so that it doesn't break from its container and scrolls within its wrapper div
trello card: https://trello.com/c/fh8On5Hg/2032-moderate-page-reflow-issues-horizontal-scroll
> Add horizontal scroll inside wrapper

- CHANGELOG.md
- app/controllers/staff/activity_financials_controller.rb
- app/controllers/staff/refunds_controller.rb
- app/models/refund.rb
- app/policies/activity_policy.rb
- app/policies/refund_policy.rb
- app/presenters/refund_presenter.rb
- app/services/create_refund.rb
- app/services/update_refund.rb
- app/views/staff/activity_financials/show.html.haml
- app/views/staff/refunds/_form.html.haml
- app/views/staff/refunds/edit.html.haml
- app/views/staff/refunds/new.html.haml
- app/views/staff/shared/activities/_refunds.html.haml
- app/views/staff/shared/refunds/_table.html.haml
- config/locales/models/activity.en.yml
- config/locales/models/refund.en.yml
- config/routes.rb
- db/migrate/20210811093658_create_refunds.rb
- db/schema.rb
- spec/factories/refunds.rb
- spec/features/staff/users_can_create_a_refund_spec.rb
- spec/features/staff/users_can_edit_a_refund_spec.rb
- spec/models/refund_spec.rb
- spec/policies/activity_policy_spec.rb
- spec/policies/refund_policy_spec.rb
- spec/services/create_refund_spec.rb
- spec/services/update_refund_spec.rb
This allows users to post and edit a refund against an active report from the activities page. All added refunds are then listed on the Activity's financials page.
> (2066) Post refund against active report

- CHANGELOG.md
- app/controllers/concerns/breadcrumbed.rb
- app/controllers/staff/activities_controller.rb
- config/locales/models/activity.en.yml
- spec/controllers/concerns/breadcrumbed_spec.rb
- spec/features/staff/users_can_view_fund_level_activities_spec.rb
- The default breadcrumb trail for BEIS users includes the DP organisation to whom the activity belongs
> (2062) Breadcrumb trail for BEIS users includes the delivery partner organisation activities index

- app/controllers/concerns/breadcrumbed.rb
- spec/controllers/concerns/breadcrumbed_spec.rb
- Fix programme breadcrumb for DP users
Looking at a fund:
Looking at a programme:
Looking at a third-party project:
Looking at a programme:
Looking at a third-party project:
> (2061) Fix programme breadcrumb for DP users

- CHANGELOG.md
- app/assets/stylesheets/partials/_breadcrumbs.css.scss
- app/controllers/application_controller.rb
This truncates breadcrumbs with an elipsis (`...`) if they are over a certain width, and adds a title to all the links, so hovering over a link shows the full name of the item.
> (2089) Breadcrumbs should be truncated if over a certain length number of items

- app/views/staff/reports/_tab.html.haml
- app/views/staff/reports/_tab_list.html.haml
- app/views/staff/shared/activities/_tab_nav.html.haml
- app/views/staff/shared/activities/_tab_nav_item.html.haml
- app/views/staff/shared/activities/_table.html.haml
- app/views/staff/shared/reports/_tabs.html.haml
For Activities and Reports pages ensure the structural syntax of the tablist matches the example set out in the GOV.UK Design System, when applied to a list.
- The list should include role="tablist", 
- The list item should include role="presentation" 
- The anchor link role="tab".
https://trello.com/c/h4CVmQNA/2037-critical-certain-aria-roles-must-be-contained-by-particular-parents
> 2037-critical-certain-aria-roles-must-be-contained-by-particular-parents

- CHANGELOG.md
- app/javascript/src/table-tree-view.js
Previously, the `aria-controls` attribute of the button was set to a value that didn't exist on the page. The purpose of `aria-controls` is to show assistive technology what element(s) are controlled by a given element (https://www.w3.org/TR/wai-aria-1.1/#aria-controls).
In our case, this is the child activities that are shown when clicking on the "expand" button. With this in mind, I'm grabbing all the child activity elements, and adding a space seperated list of the child IDs (`aria-controls` accepts a list of IDs, as well as a single ID). This tells assistive technology that clicking this button will show/hide those elements.
> (2038) *Critical* ARIA attributes must conform to valid values

- app/controllers/concerns/activities/breadcrumbed.rb
- app/controllers/concerns/searches/breadcrumbed.rb
- app/controllers/staff/searches_controller.rb
- spec/features/staff/users_can_search_for_activities_spec.rb
This builds on #1293 to add a search results breadcrumb and use the existing work we have done with the breadcrumb context to have a new context that shows a link back to the search results in breadcrumbs.
> (2063) Show search breadcrumb scheme when appropriate

- CHANGELOG.md
- app/views/staff/searches/show.html.haml
- config/locales/views/activity_search.en.yml
- spec/features/staff/users_can_search_for_activities_spec.rb
- Show an error message if the search query is empty
> (2088) Show error message if search query is empty

- config/environments/test.rb
`add_whitelist` has been replaced with `add_safelist`, so this removes the deprecation warning when running the tests.
> Remove Bullet deprecation warning

- spec/features/staff/users_can_create_a_refund_spec.rb
- spec/features/staff/users_can_edit_a_refund_spec.rb
After adding refunds, we got the error:
```
Shared example group 'refunds' has been previously defined at:
/Users/stuartharrison/Documents/beis-report-official-development-assistance/spec/features/staff/users_can_create_a_refund_spec.rb:4
...and you are now defining it at:
/Users/stuartharrison/Documents/beis-report-official-development-assistance/spec/features/staff/users_can_edit_a_refund_spec.rb:4
The new definition will overwrite the original one.
```
To get round this, I've given the two shared examples different (and more descriptive) names
> Fix duplicate shared example warning

- CHANGELOG.md
- app/policies/report_policy.rb
- app/presenters/report_presenter.rb
- app/services/report/organisation_reports_fetcher.rb
- app/views/staff/shared/reports/_table_header.html.haml
- app/views/staff/shared/reports/_table_row.html.haml
- app/views/staff/shared/reports/_tabs.html.haml
- config/locales/models/report.en.yml
- spec/features/staff/users_can_approve_a_report_spec.rb
- spec/presenters/report_presenter_spec.rb
- spec/services/report/organisation_reports_fetcher_spec.rb
- Reordered the columns as indicated in the mockup
- Added a "Can edit?" column to make it clearer to the DP why they can or cannot modify the data in the report
> (2101) Delivery partner users see status module on reports current tab

- .github/workflows/trigger_rebase.yml
We have an action that _should_ automatically rebase any PRs that are set to automerge against the develop branch. However, this has not been working, because of a [bug in the rebase action](https://github.com/cirrus-actions/rebase/issues/58) we use (example run here https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/runs/3398039357?check_suite_focus=true)
I've also tweaked the action to only trigger against the oldest PR set to automerge rather than needlessly rebasing all the PRs set to automerge (which will then go out of date). Once that one is merged, it will trigger a rebase on the second oldest one and cascade down, saving us time and resources.
> Fix automatic rebase

- spec/presenters/activity_presenter_spec.rb
Rather than building one activity for every code in the code list, we build one activity and update it for each item in the code list. This speeds up these tests considerably, going from ~12 seconds to ~0.5 seconds
> Speed up activity presenter spec

- db/data/20210823135218_set_nil_policy_markers_to_default.rb
This adds a data migration that sets any policy markers set to `nil` to the default state, which should be `not_assessed`. This will fix the issue where we see blank policy markers in the XML.
> Data migration sets nil policy markers to default

- CHANGELOG.md
- app/controllers/concerns/reports/breadcrumbed.rb
- app/services/report/grouped_reports_fetcher.rb
- app/services/report/organisation_reports_fetcher.rb
- app/views/staff/organisations/reports/index.html.haml
- app/views/staff/reports/index.html.haml
- app/views/staff/shared/reports/_tabs.html.haml
- config/locales/models/report.en.yml
- spec/controllers/concerns/reports/breadcrumbed_spec.rb
- spec/features/staff/users_can_approve_a_report_spec.rb
- spec/features/staff/users_can_view_reports_spec.rb
- spec/services/report/grouped_reports_fetcher_spec.rb
- spec/services/report/organisation_reports_fetcher_spec.rb
- Replace the use of "historic" with "approved" in the context of reports
> (2100) Rename "historic" to "approved" in the context of reports

- CHANGELOG.md
- app/controllers/staff/home_controller.rb
- app/views/staff/home/delivery_partner.html.haml
- config/locales/models/report.en.yml
- spec/features/staff/users_can_view_a_home_page_spec.rb
- List the current reports on the delivery partners’ homepage, to give them immediate access to one of the most important elements of RODA.
> (2102) Current reports are listed on DP homepage

- CHANGELOG.md
- app/controllers/staff/exports/organisations_controller.rb
- app/services/quarterly_external_income_export.rb
- app/views/staff/exports/organisations/show.html.haml
- config/locales/models/activity.en.yml
- config/locales/models/external_income.en.yml
- config/routes.rb
- spec/features/staff/beis_users_can_download_exports_spec.rb
- spec/services/quarterly_external_income_export_spec.rb
- BEIS users can export external income per organisation and fund
> (2117) BEIS users can export external income

- app/controllers/concerns/auth.rb
- app/controllers/staff/exports/organisations_controller.rb
- app/controllers/staff/exports_controller.rb
- app/policies/export/organisation_policy.rb
- app/policies/export_policy.rb
- app/views/shared/_navigation.html.haml
- app/views/staff/exports/organisations/show.html.haml
- spec/controllers/staff/exports/organisations_controller_spec.rb
- spec/policies/export/organisation_policy_spec.rb
- spec/views/staff/exports/organisations/show_spec.rb
- spec/views/staff/shared/navigation_spec.rb
This builds on the existing work to allow DP users to see the export page, as well as download their own external income data. I had to make a teeny tweak to the policy we use for exports, but hopefully this is more logical now. There's also a bunch of view specs added to test the template logic.
> (2118) A delivery partner user can export their own external income data

- app/models/activity.rb
- app/models/benefitting_country.rb
- app/presenters/activity_presenter.rb
- app/services/export_activity_to_csv.rb
- app/views/staff/shared/activities/_activity.html.haml
- config/locales/models/activity.en.yml
- spec/models/activity_spec.rb
- spec/models/benefitting_country_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/views/staff/shared/activities/activity_spec.rb
- vendor/data/codelists/BEIS/benefitting_countries.yml
- vendor/data/codelists/BEIS/benefitting_region_levels.yml
- vendor/data/codelists/BEIS/benefitting_regions.yml
This adds a new BEIS codelist that contains everything we know about benefitting countries, and uses this to infer a region when given an activity's benefitting countries. This is then presented to the user in the activity details page, as well as the report download and XML view.
> (1862) Infer region from new beneficiary countries information

- db/data/20210913122102_respect_legacy_recipient_region.rb
- Undo benefitting countries data migration for specific situations
> (2151) Undo benefitting countries data migration for specific situations

- spec/views/staff/shared/activities/activity_spec.rb
- Add a spec to describe the intended behaviour of the legacy field `recipient_region`
The intended behaviour is already in place, but it needs to be explicitly described to prevent regressions.
The `recipient_region` field acts as a legacy field, in that it is not editable anymore, but it has to be shown unless the user specifically chooses to provide benefitting_countries.
This feature will become more visible once we run the data migration that undoes the previous data migration, which had populated the inferred countries from the given region.
> (2150) Describe the intended behaviour for recipient_region

- terraform/app.tf
- terraform/worker.tf
We've been having some issues deploying, with the odd timeout causing our deploys to fail. After speaking to the GOV.UK PasS team, they've advised us that they've increased the maximum deploy timeout at their end, so have advised us to try increasing our maximum timeout to see if that helps.
> Increase deploy timeout

- CHANGELOG.md
- app/controllers/staff/exports/organisations_controller.rb
- app/controllers/staff/exports_controller.rb
- app/policies/export_policy.rb
- app/services/quarterly_external_income_export.rb
- app/views/staff/exports/index.html.haml
- config/locales/views/exports.en.yml
- config/routes.rb
- spec/controllers/staff/exports_controller_spec.rb
- spec/features/staff/beis_users_can_download_exports_spec.rb
- spec/policies/export_policy_spec.rb
- spec/services/quarterly_external_income_export_spec.rb
This builds on the external income export work to allow BEIS users to export data about External Income for all delivery partners. This is now listed on the BEIS users' export page like so:
> (2119) A BEIS user can export external income for all delivery partner organisations in a single file

- app/helpers/form_helper.rb
- app/models/benefitting_country.rb
- app/models/benefitting_region.rb
- spec/features/staff/users_can_add_benefitting_countries_in_one_step_spec.rb
- spec/models/activity_spec.rb
- spec/models/benefitting_country_spec.rb
- spec/models/benefitting_region_spec.rb
- spec/presenters/activity_presenter_spec.rb
In #1344 It was noted in a review that BenefittingCountry::Region was becoming a
first class citizen and we felt it should be split out in to its own
file.
We took the opportunity to rename it BenefittingRegion to keep the link
with the concept it is modelling as clear as we can.
> (2188) Chore: Split Region from BenefittingCountry

- CHANGELOG.md
- app/views/staff/home/_delivery_partner_organisations_table.html.haml
- spec/views/home/serice_owner_spec.rb
As with a delivery partners organisation details, activities and
exports, a BEIS user (the service owners) may want to view the reports
for a specific delivery partners.
Facilitating them to do so right from the home page we add a link.
> (2044) Feature: Add links to reports on BEIS homepage

- CHANGELOG.md
- app/views/staff/activities/children.html.haml
- app/views/staff/activities/comments.html.haml
- app/views/staff/activities/details.html.haml
- app/views/staff/activities/financials.html.haml
- app/views/staff/activities/historical_events.html.haml
- app/views/staff/activities/other_funding.html.haml
- app/views/staff/activities/transfers.html.haml
- app/views/staff/shared/activities/_activity_summary.html.haml
- config/locales/models/activity.en.yml
- spec/features/staff/users_can_edit_an_activity_spec.rb
- Show the activity summary for all activities except funds. (Most of the fields don’t make sense for fund-level activities.)
> (2085) Show activity summary on all activity tabs

- app/services/spending_breakdown/export.rb
- spec/factories/adjustments.rb
- spec/services/spending_breakdown/export_spec.rb
In the spirit of keeping PRs small, here is the first version of the new spending 
breakdown report. I'll be working and opening PRs to keep things managable 
and as concise as possible!
The intention is for this to replace the existing
ActivitySpendingBreakdown class.
The previous class is based on the principle that the spending breakdown
is related to a report, BEIS finance users are not concerned with the
report time period, they are more interested in all the data the application
contains to date. 
Here we introduce a class that takes a fund and optional organisation
and returns all the actual spend and refund values.
Now that we have the new Adjustment model, we also want to include the
correct type of adjustments in the calculations:
Actual spend total = Total actuals for an …
> (2158) Introduce SpendingBreakdown::Export

- app/models/activity.rb
- app/models/transaction.rb
- app/services/actual_overview.rb
- app/services/report/export.rb
- spec/models/transaction_spec.rb
- spec/services/actual_overview_spec.rb
- spec/services/report/export_spec.rb
This adds an argument to the `ActualOverview` class to include any adjustments, which is then used in the `Report::Export` class to make sure the calculations of Actuals are returned with the adjustments (either negative or positive) included. There was a bit of added complexity when I realised Adjustments could apply to Refunds as well as Actuals - detail is in the commit message.
> (2051) Include Adjustments in CSV exports

- app/models/activity.rb
- app/services/actual_overview.rb
- app/services/report/export.rb
- spec/services/actual_overview_spec.rb
- spec/services/report/export_spec.rb
This updates the ActualOverview to removet he activity from the initializer. When returning `all_quarters`, this now groups each transaction by financial year, financial quarter AND activity ID. This means that rather than querying transactions on an activity by activity basis for the export, we can load all of a report's transactions into memory when we start building the report, and pluck them from the `AllQuarters` instance based on the financial period and the activity.
I've also had to update the `value_for_report_quarter` method to accept an activity as an argument, so we can reuse the relation in the class, but append the query to search for a specific activity.
> (2051) Cache all transactions in an ActualOverview

- app/services/spending_breakdown/export.rb
- spec/services/spending_breakdown/export_spec.rb
Following on from #1361 this work introduces Forecasts to the Spending breakdown export.
As before this in not yet exposed to users, but you can interact with the class on the Rails console.
We want to display all Forecasts for the financial quarters not already covered by Actual spend and Refunds. We do this by taking the end of the range for Actual spend and Refunds and applying that as the start of the range of Forecasts.
Forecasts are already stored as a single total per financial quarter and activity so there is no need to sum them. We do have to utilise the `ForecastOverview` class which means we lose some control of the queries. Fortunately the `ForecastOverview` can be use with multiple activity ids allowing us to load all required latest values from the relevant forecasts - which …
> (2158) Feature: spending breakdown includes forecasts

- CHANGELOG.md
- app/models/activity.rb
- app/services/actual/overview.rb
- app/services/refund/overview.rb
- app/services/report/export.rb
- app/services/transaction_overview.rb
- spec/rails_helper.rb
- spec/services/actual/overview_spec.rb
- spec/services/refund/overview_spec.rb
- spec/services/report/export_spec.rb
- spec/support/shared_examples/transaction_report_history.rb
- spec/support/transaction_helpers.rb
This creates a Refund Overview class, which shares functionality with the Actual Overview to return the value of all of the refunds for an activity within the previous twelve quarters.
> (2051) Include refunds in the report exports

- CHANGELOG.md
- db/data/20210929_clear_additional_benefitting_countries_where_backfilling_not_appropriate.rb
It seems we were over-eager in backfilling the new `Activity#benefitting_countries`
field, in that we added all of the countries in the legacy `recipient_region` even
when the legacy `recipient_country` field was present.
Example: Activity with RODA id `'GCRF-EP_C_MS-4_2018EP/T00343X/1'`:
```
=> {"recipient_region"=>"1027",
"recipient_country"=>"UG",
"intended_beneficiaries"=>nil,
"requires_additional_benefitting_countries"=>false,
"country_delivery_partners"=>[],
"benefitting_countries"=>["UG", "BI", "KM", "DJ", "ER", "ET",
"KE", "MG", "MW", "MU", "MZ", "RW",
"SO", "SS", "SD", "TZ", "ZM", "ZW"]}
```
In this script, we find the approx 4,000 activities which are affected:
- legacy `recipient_region` is present, and
- legacy `recipient_country` is present, and
- there are no …
> Add data migration to fix up over-eager backfilling of benefitting_countries

- README.md
- doc/0_index_of_contents.md
- Adds a new "index of contents" to the `doc/` directory, with links to each documentation page.
- Add a link to this index of documentation to the README at the root
Next we can add some "stubs" to highlight missing docs which intend to add over the next few weeks.
> Doc: index of contents

- CHANGELOG.md
- app/presenters/activity_presenter.rb
- app/services/activities/import_from_csv.rb
- app/views/staff/activity_forms/requires_additional_benefitting_countries.html.haml
- app/views/staff/shared/activities/_activity.html.haml
- config/locales/codelists/2_03/iati.en.yml
- config/locales/models/activity.en.yml
- db/migrate/20210929155655_remove_additionl_benefitting_countries_required.rb
- db/schema.rb
- spec/factories/activity.rb
- spec/presenters/activity_presenter_spec.rb
- spec/support/activity_helpers.rb
- spec/views/staff/shared/activities/activity_spec.rb
The `requires_additional_benefitting_countries` is no longer valuable since we replaced `recipient_region`, `recipient_country` and `intended_beneficiaries` with `benefitting_countries` and `benefitting_region`.
Here we remove the column and any associated items.
We also decided to always show ALL the related geography attributes regardless of their state to help users:
- understand what data an activity does or does not have, rather than hiding that
- understand how they could migrate the data to the new values
We also added a 'read only` flag to the label to help users understand why the values in the old fields can longer been changed.
> (2216) Chore: remove geography fields no longer required  from interface

- db/data/20210930151236_intended_benefeciaries_to_benefitting_countries.rb
It seems we were over-eager in backfilling the new
`Activity#benefitting_countries` field, in that we added all of the
countries in the legacy `recipient_region` even when the legacy
`intended_beneficiaries` field was present and populated with a more
granular set of country data
Example: Activity with RODA id 'GCRF-UKR_ARE_C19-Ag2020EP/V044613/1':
=> {"recipient_region"=>"289",
"recipient_country"=>"nil",
"intended_beneficiaries"=>["NG", "ZA"],
"requires_additional_benefitting_countries"=>false,
"benefitting_countries"=>["PH", "IN", "KH", "CN", "KP", "ID",
"LA", "MY", "MN", "TH", "TL", "VN", "IR", "IQ", "JO", "LB", "SY",
"PS", "YE", "AF", "BD", "BT", "MV", "MM", "NP", "PK", "LK"]
In this script, we find the approx 400 activities which are affected:
- legacy `recipient_region` is present, …
> (2221) Re-populate benefitting countries

- CHANGELOG.md
2021-10-01
- Fix up activities (with legacy intended beneficiaries) where backfilling was
too enthusiastic
Be need to run the data migration after deploy:
```
rails runner db/data/20210930151236_intended_benefeciaries_to_benefitting_countries.rb
```
> Release 77

- app/controllers/staff/report_comments_controller.rb
- app/models/report.rb
- app/services/report/grouped_comments_fetcher.rb
- app/views/staff/reports/_tab_list.html.haml
- app/views/staff/reports/comments.html.haml
- config/locales/models/comment.en.yml
- config/locales/models/report.en.yml
- config/routes.rb
- spec/controllers/staff/report_comments_controller_spec.rb
- spec/features/staff/users_can_view_reports_spec.rb
- spec/services/report/grouped_comments_fetcher_spec.rb
- spec/support/report_page.rb
This adds a comments tab to the Report page, showing a list of all comments made in a reporting period, grouped by their activity
> (2203) Add comments tab to report

- doc/0_index_of_contents.md
- doc/support_tasks/reset_mfa.md
In the scenario where a user can't complete MFA because their phone number has
changed, support will need to manually reset the user's MFA settings via the
Auth0 control panel.
> Add a support doc for resetting a user's MFA setting

- app/models/adjustment.rb
- app/models/refund.rb
- db/data/20211004_backfill_missing_attrs_on_refunds_and_adjustments.rb
- spec/models/adjustment_spec.rb
- spec/models/refund_spec.rb
Refunds and Adjustments were being created with blank attributes:
- `currency` should be "GBP"
- `transaction_type` should be "3" for "Disbursement"
This isn't causing an immediate problem, but both refunds and adjustments are "transactions" and so
ought to conform to the normal transaction behaviour.
In this PR we:
- add attribute initialisers to `Refund` and `Adjustment`
- add a data migration to fix up existing records 
(to be run with `rails runner db/data/20211004_backfill_missing_attrs_on_refunds_and_adjustments.rb`)
> Fix (2222) Populate currency and transaction_type properties for Refund and Adjustment records

- CHANGELOG.md
- app/models/activity.rb
- app/views/staff/activities/comments.html.haml
- app/views/staff/shared/reports/_table_variance.html.haml
- config/locales/models/report.en.yml
- spec/features/staff/users_can_create_a_comment_spec.rb
- spec/features/staff/users_can_view_reports_spec.rb
- spec/models/activity_spec.rb
- spec/services/report/export_spec.rb
- spec/support/comment_form.rb
- spec/views/staff/shared/reports/_table_variance_spec.rb
This is a fix to a bug we have in the new comment work that we found whilst working on the report csv.
The `comments_for_report` method on actvity still assumes that there is only ever one comment per activity, per report and so uses `find_by` returning the first found comment or nil.
In the report csv we attempt to map over the result of this method and if there are no comments, blow up sliently and produce an empty csv file.
As we now allow multiple comments per report, per activity, we have also updated the links against variance in a report as we want to direct uses to the activity comments rather than a specific comment, where they can then add or view the comments.
We have also styled the add comment link as a button as it is the primary action in the scope of the comment tab.
> Fix: Comments for report

- db/data/20211027111140_copy_extending_organisation_to_implementing_organisation_at_level_b.rb
This is a short term fix for implementing organisation on all level B
activities that have an extending organisation (all of them).
We take the extending organisation and use it to create a new
implementing organisation on activities that do not have any.
This will mean IATI data at level B will include an implementing
organisation which is not currently the case.
There is a longer term issue to fix: When creating new level B
activities the implementing organisation should be set to the delivery
partner, but that work will take longer and so we are correcting the
data here to enable IATI publishing to happen in the short term.
https://trello.com/c/lirfmCWM
> (2271) Data migration: fix implementing org on level B activities

- vendor/data/codelists/BEIS/benefitting_countries.yml
This benefitting country 'States Ex-Yugoslavia unspecified' is not valid
if published to IATI, which implies it is not valid elsewhere.
These benefitting countries were supplied by BEIS and there is probably
some logic to this one that we do not know about, but we cannot support
a benefitting country code of 'A region on IATI code 88' and nor can
IATI.
By removing this we stand more chance of surfacing any business logic
here and in the meantime:
- no new activities can be created that benefit this invalid
county/region
- existing activities can be published to IATI that include all
benefitting countries, which means 'developing countries, unspecified'
and is real need
I've checked in production and we have no activities with this
benefitting country set with:
`Activity.where("'A region …
> (2273) fix: Remove Benefitting country code

- app/helpers/activity_helper.rb
- spec/helpers/activity_helper_spec.rb
The old calculation using `divmod` fails for numbers > 100.
As we have ~180 countries and selecting all of them is something that
happens we need the percentage calculation to work.
What matters to us right now is that the IATI XML is valid and NOT that
the percentage is accurate (it is not and for BEIS is may be impossible
to make it accurate).
I tested what percentages can be valid in the IATI XML for both 3
countries and 180 and this simpler calculation satisfies the validator.
> (2272) Fix: benefitting country percentage split calculation

- app/models/export/activity_actuals_columns.rb
- app/services/export/spending_breakdown.rb
- spec/models/export/activity_actuals_columns_spec.rb
- spec/services/export/spending_breakdown_spec.rb
Here we are at step 6️⃣ ! Now we have the `ActivityActualsColumns` class, we can use it, here in the spending breakdown report.
To complete the expected behaviour, we need to know the last finacial quarter we have actual data for and then use that to start showing forecast data. Here I extend 'ActivityActualsColumns` to return this.
In the last commit I take some steps to clean up the `spending_breakdown_spec` although the fixtures for forecasts are still a bit rough, they will be removed in coming work to split out a forecast columns class.
> (2246) Refactor: spending breakdown uses activity actuals columns

- app/models/export/activity_forecast_columns.rb
- spec/models/export/activity_forecast_columns_spec.rb
Number 7️⃣ in the series!
We extract the forecast columns out of the spending breakdown class. 
We then extend it to allow it to produce a 'snapshot' of forecasts which shows the forecasts values as they were when reported.
We also allow it to take a 'starting financial quarter', this sets the first financial quarter in the series and can be used in exports that require the latest forecasted values but only for a specific set of financal quarters, for example in the spending breakdown export.
> (2246) Feature new forecast columns export

- doc/deleting-things-from-production.md
- lib/tasks/delete_activity.rake
- spec/lib/tasks/delete_activity_spec.rb
Every report results in a bunch of activities that a developer has to
delete as the application cannot do this yet.
This rake task attempts to aid developers in performing this support
task by running the steps for a given activity database ID.
Some associations are destroyed along with the `Activity` object, others
would be orphaned. I wanted to update the documentation we have on this
and through the process of finding out, I figured we may as well wrap
the knowledge in a rake task.
Developers are encouraged to `think` about what they are doing here as
ultimately this is destructive, but they save a great deal of work on
the console by running the task and interpreting the result before performing 
the destruvtive action.
> (2276) Chore: delete activity rake task

- app/models/export/activity_actuals_columns.rb
- app/models/export/activity_forecast_columns.rb
- app/models/export/activity_variance_column.rb
- spec/models/export/activity_actuals_columns_spec.rb
- spec/models/export/activity_forecast_columns_spec.rb
- spec/models/export/activity_variance_column_spec.rb
Welcome to 9️⃣ !
This is the variance column. At this point I kept this one simple with some baked in assumptions. The main one being that this is only ever used to export a report and so has a  fixed financial quarter and so the variance will be the last financial quarter from the actuals and the first financial quarter from the forecasts.
I can see nice ways to improve this later with further refactoring on the underlying data structure, but I would like to complete this Export epic work so we can deliver on the user need and come back if there is the opportunity (and yes I know that is a classic thing to say! 😄 )
> (2246) feature: Variance column

- app/models/export/activity_implementing_organisation_column.rb
- spec/models/export/activity_implementing_organisation_column_spec.rb
Allows Implementing organisations to be exported.
Returns the name only as the only use case we have for this
right now is the report csv which only requires the name.
Multiple implementing organisations are delimited with a pipe (|).
When the activity is at Level B (a programme) there is no guarantee
there will be any implementing organisations, but the
extending organisation will have the correct organisation details, so we
use that.
We pass in an ActiveRecord::Relation of activities so we can leverage
Rails lazy loading of the organisations, failing to pass in the correct
type would cause an error, failing to pass in the correct type would
cause an error, so we check this.
> (2246) feature: Introduce Activity Implementing Organisation Column

- app/models/export/activity_change_state_column.rb
- spec/models/export/activity_change_state_column_spec.rb
This requires a `Report` in order to work out if change has occurred, the
report gives the context in order to do so.
I am sticking with passing in the activities even though we could use
`all_report_activities`, if the activity is not in the report we return
nil - I think this is preferable over throwing an error that may not be
immediately clear.
> (2246) feature: Introduce ActivityChangeStateColumn

- app/models/export/activity_comments_column.rb
- spec/models/export/activity_comments_column_spec.rb
This class is concerned with exporting a column of activity comments.
You can pass in a `Report` and only the comments added in that report
will be returned or you can not, in which case you will get all comments
for each activity.
In either case there are an unknown number of comments that must be added
into a single table cell, so we output the comments separated with the
following:
`----`
which is surrounded by new lines.
We would usually delimit with a pipe but that did not feel like enough
(currently comments are separated by a new line).
> (2246) feature: Introduce ActivityCommentsColumn

- app/services/export/spending_breakdown.rb
- spec/services/export/spending_breakdown_spec.rb
When we moved the spending breakdown report to the new `Export` classes
we missed that we only need to load the `row` data once and then loop
over the rows to collate the data together, instead we loaded the entire
data set for each wow which  makes the export take far too long as all
the expensive calls are happening for each row instead of once for all
rows!
> Fix: Spending breakdown export not cached

- CHANGELOG.md
- app/controllers/staff/reports_controller.rb
- app/views/staff/reports/_download.haml
- spec/controllers/staff/reports_controller_spec.rb
- spec/features/staff/users_can_view_reports_spec.rb
Whilst we are introducing the new report csv we want to offer the old
one to reassure users that any workflows will not be broken. Once they
have confidence in the new export, this work can be rollback.
> (2246) Allow users to download legacy report csv

- doc/0_index_of_contents.md
- doc/support_tasks/add_accepted_channel_of_delivery_code.md
We currently have the need to do this (see https://trello.com/c/3DPKYfLg/2321-channel-delivery-code).
As we are also currently working on both BEIS' "Operating manual" and the "Developer docs" stored here in `doc/`, we'll take the opportunity to follow the support process:
- BEIS raise a support ticket on Zendesk
- dxw follow the support runbook entry
> Doc: Add support runbook for adding a channel of delivery code to accepted list

- lib/tasks/delete_activity.rake
- spec/lib/tasks/delete_activity_spec.rb
The rake tasks output lots of useful info to stdout via the
`puts` method.
But the info is not so useful to see in the middle of the
RSpec output.
So we now stub the calls to `Kernel.puts`.
> Stub out logging to stdout (via 'puts') in specs

- app/models/activity.rb
- spec/features/staff/beis_users_can_create_a_programme_level_activity_spec.rb
- spec/features/staff/users_can_create_a_project_level_activity_spec.rb
Trello https://trello.com/c/5jyIqHIi/2281
During the recent submission of data to IATI we recognised the need to supply "implement organisation" data for Level B activities (Programmes).
i.e. the XML submitted should include a `<participating-org>` element with a `role` attribute of `4` to signify "implementing organisation", e.g.:
```
<participating-org ref="GB-CHC-293074" role="4" type="80">
<narrative>Royal Academy of Engineering</narrative>
</participating-org>
```
See https://iatistandard.org/en/iati-standard/203/codelists/organisationrole/
We recently ran a data migration to backfill these implementing organisations for pre-existing programmes. See:
`20211027111140_copy_extending_organisation_to_implementing_organisation_at_level_b.rb`
This commit changes the `Activity::new_child` …
> Feature (2281) Set implementing organisation for new programmes (level b)

- app/presenters/activity_presenter.rb
- config/locales/models/activity.en.yml
- db/data/20211118113311_remove_incompatible_country_codes.rb
- spec/presenters/activity_presenter_spec.rb
We discovered we has some 'unknown country codes' - interestingly this is exactly why we put 'unknown country codes' in. to discover any in the data set!
I've done two things:
1. We now show the unknown code along with the text, this will help users (and us) 'debug' the data
2. A data migration to remove the codes from the activities that have them now.
###Data migrattion to run in this PR
`rails runner db/data/20211118113311_remove_incompatible_country_codes.r`
https://trello.com/c/tHbVco0U
> (2324) Fix: show unknown country codes and data migration to remove those in production 

- spec/lib/tasks/delete_activity_spec.rb
When I wrote the delete activity task, I thought afterwards that it
would not delete descendent activities. Looking at it here though, it is
recursive and deletes right down the hierarchy.
Here is a spec to confirm that behaviour.
https://trello.com/c/WJwzZHXX
> (2286) Check delete activity rake task is recursive

- CHANGELOG.md
- app/models/actual.rb
- app/models/import/actual_history.rb
- config/locales/models/actual.en.yml
- spec/features/staff/users_can_create_an_actual_spec.rb
- spec/models/actual_spec.rb
- spec/models/import/actual_history_spec.rb
- spec/models/transaction_spec.rb
This is the new importer for historic actual spend that ony BEIS users can use, it is not currently available that will follow.
Historic actual spend is treated differently to regular actual spend in that we expect negative values and we expect financial quarters in the past, as already mentioned, we only expect BEIS users to perform this upload and we don't expect it to be something long term, it is only fir use during migration to the service.
The import follows the `Import::Commitments` in that it returns `true` or `false` and builds arrays of `errors` and `imported` actuals - I like this interface.
Here I start out by preventing negative values in 'regular' actuals and allowing them when the validation context is `:history`. The importer then creates it's actuals in this context and …
> (2252) Feature: new actual history importer

- app/models/export/activity_forecast_columns.rb
- spec/models/export/activity_forecast_columns_spec.rb
Whilst the last column of actuals will always have values, there is a
high chance that the first column of forecasts will have none, when this
happens the value pulled out when rendering data will be `nil` and when
the variance column tries to calculate, the nil causes an error.
As a general rule, where we have no data we have to assume zero, so here
we replace nil with zero if there is no value.
> Fix rows_for_first_financial_quarter

- CHANGELOG.md
- app/controllers/staff/uploads/actual_histories_controller.rb
- app/models/csv_file_upload.rb
- app/models/import/actual_history.rb
- app/models/import/row_error.rb
- app/policies/report_policy.rb
- app/views/staff/reports/_actuals_upload.html.haml
- app/views/staff/reports/_actuals_upload_history.html.haml
- app/views/staff/reports/actuals.html.haml
- app/views/staff/uploads/actual_histories/_errors_table.html.haml
- app/views/staff/uploads/actual_histories/new.html.haml
- app/views/staff/uploads/actual_histories/update.html.haml
- config/locales/default.en.yml
- config/locales/views/uploads/actual_histories.en.yml
- config/routes.rb
- spec/controllers/staff/uploads/actual_histories_controller_spec.rb
- spec/features/staff/beis_users_can_upload_actuals_history_spec.rb
- spec/models/import/actual_history_spec.rb
- spec/policies/report_policy_spec.rb
This is the BEIS users actual spend history upload. I decided to utiltise the exisiting report UI to house this, as we decided that these backfilling imports would still use a Report to encapsulate them it make sense to use the existing paths to a single report to guide users.
The importer itself was added in #1472 
https://trello.com/c/IKyiv8kX
> (2252) Feature: BEIS users can upload actuals

- CHANGELOG.md
- app/models/import/actual_history.rb
- app/views/staff/reports/_actuals_upload_history.html.haml
- config/locales/views/uploads/actual_histories.en.yml
- spec/models/import/actual_history_spec.rb
In #1478 we decided the actual history importer should onlt allow values from past financial quarters. Here we change the `Import::ActualHistory` to enforce this. See the commit message for details on what 'the past' means in this context.
I've had a go at making the help on the initial upload content a little clearer? 🧑‍⚖️
> (2252) Feature: actual history must be in the past

- CHANGELOG.md
- app/views/staff/shared/activities/_activity.html.haml
- app/views/staff/shared/activities/_activity_summary.html.haml
- config/locales/models/activity.en.yml
- spec/support/activity_helpers.rb
- spec/views/staff/shared/activities/activity_spec.rb
We are slowing refactor where and what we use to describe the various
attributes in use throughout the service.
With this change the Activity summary view and report csv file share the
same locales.
Here the Activity summary view is updated to use the
`activerecord.attributes.activity` namespace whenever possible. Not
everything is an activerecord attributes so I have had to use my best
judgement when to include a key and when to not.
> Activity summary view uses BEIS locale strings

- CHANGELOG.md
- script/deploy-notification
* When using the Slack API, `<!here>` is used in place of `@here`, otherwise the message just shows '@here' in plain text rather than notifying user.
> Fix deploy notification

- CHANGELOG.md
- app/controllers/public/base_controller.rb
- spec/requests/health_check_spec.rb
We want to know if the Sidekiq worker has failed for any reason and raise
an alert.
We decided it was acceptable to add some very basic stats to the public
`health_check` endpoint for this purpose.
We leverage the Sidekiq API to return the two statistics we want:
- the size of `enqueued`
- the `retry_size`
See:
https://github.com/mperham/sidekiq/wiki/API
and
https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/blob/develop/doc/background-jobs.md
> (2282) Feature: Add basic Sidekiq stats to health check endpoint

- app/views/staff/uploads/actual_histories/update.html.haml
It raises a deprecation warning.
> Fix: Don't use file extensions in partial names

- CHANGELOG.md
- app/views/staff/actual_uploads/new.html.haml
- config/locales/models/actual.en.yml
- spec/features/staff/users_can_upload_actuals_spec.rb
Some users have duplicated their actual spend data during reporting due
to us not being clear that the upload appends to the data already in the
application as opposed to replacing it.
As a first step towards fixing this issue, we add a strong warning to
users that the upload will append data.
The Linked guidance should be updated along with this change.
> (2333) Feature: Add a warning to the actual upload page

- app/models/export/activity_actuals_columns.rb
- app/services/export/spending_breakdown.rb
- spec/models/export/activity_actuals_columns_spec.rb
- spec/services/export/spending_breakdown_spec.rb
I had noticed the "when there are no actual spend, refunds and
forecasts" failing in CI a couple of times.
I noted down the seeds and ran them locally and was unable to reproduce
the failing.
I think these changes better describe the behaviour which is when there
are activities to render in the spending breakdown and NONE of them have
any spend, refunds or adjustments we cannot handle that and the code
cannot run.
I think that the issue would only arise when there are un-cleared
fixtures in the database AND the activities fixtures happen to meet the
criteria that they appear in the spending breakdown - this is the only
way I can explain the random occurrences.
The chances of ALL activities for a DP having no spend is pretty small
and I think pragmatically could only happen under test, but …
> (2334) Fix: Spending breakdown handles no data in activities

- CHANGELOG.md
- app/models/organisation.rb
- app/models/report.rb
- spec/models/report_spec.rb
- Ensure new reports have a financial period no later than the period of their creation
-  Add has_many reports association to Organisation
- Ensure new report does not rewrite history. A new report will be invalid if there is a pre-existing report for a later period.
> Feature (2325) New reports have a valid financial period.

- CHANGELOG.md
- backing-services-docker-compose.yml
* The Postgres RDSs have been updated to version 13, so this should be
the same to ensure the local development environment is the same
> Use postgres 13 in backing-services-docker-compose.yml

- CHANGELOG.md
This was a `U+2013` "EN-Dash"
`String#codepoints => [8211]`
> Tweak: remove a non-standard dash from the Changelog

- db/data/20211207144100_delete_unwanted_budgets.rb
Filter unwanted budgets for deletion
Budget figures were entered (est. July/August 2020) for the first onboarded delivery partners UKSA, AMS and RS in order to meet IATI publishing requirements using RODA for the first time.
- Some of the activities have multiple budgets across years that are fixed on 2020-2021.
- When originally added to RODA you couldn't delete a budget once entered. Some data entry errors were made and these were edited to 0.01.
> Filter unwanted budgets for deletion

- CHANGELOG.md
- app/controllers/staff/implementing_organisations_controller.rb
- app/controllers/staff/organisations_controller.rb
- app/models/organisation.rb
- app/presenters/organisation_presenter.rb
- app/services/activities/import_from_csv.rb
- app/views/staff/organisations/_form.html.haml
- app/views/staff/organisations/_table.html.haml
- app/views/staff/organisations/show.html.haml
- config/locales/models/organisation.en.yml
- config/routes.rb
- spec/features/staff/beis_users_can_create_an_organisation_spec.rb
- spec/features/staff/beis_users_can_view_organisations_spec.rb
- spec/features/staff/users_can_manage_implementing_organisations_spec.rb
- spec/models/organisation_spec.rb
- spec/presenters/organisation_presenter_spec.rb
BEIS users can now and edit implementing organisations. Often this
will be in response to the needs of delivery partners.
All organisations which can be considered "implementing":
i) legacy organisations such as BEIS which have a role
other than `implementing_organisation` but have an
OrgParticipation of the role `implementing`
ii) organisations which were migrated over from
`implementing_organisations`. They don't have any
`Organisation#role` as this is a deprecated concept. They do
have an OrgParticipation of the role `implementing`
iii) an Organisation newly created by BEIS which has the
role `implementing_organisation` and as yet has no
OrgParticipation. This is because it has not yet been
associated with an activity by a delivery partner --
presumably this will shortly be done, as we …
> Feature (2098 pt3) BEIS manage Implementing organisations

- lib/tasks/delete_activity.rake
https://trello.com/c/ElWiw4K1/26-beis-roda-delete-activity-rake-task-is-broken
ImplementingOrganisation has been replaced with the OrgParticipation model. This
was updated everywhere except for the delete activity task, and as a result
the task was not functioning correctly.
> Replace ImplementingOrganisation with OrgParticipation in delete activity task

- spec/features/staff/users_can_view_an_activity_spec.rb
- spec/models/financial_year_spec.rb
These specs failed once the year changed from 2021 to 2022.
We now use the Rails time-travelling test helper
(`ActiveSupport::Testing::TimeHelpers#travel_to`) to lock
our examples to mid-Dec 2021.
> Fix 3 spec failures due to change in year

- db/data/20220106163037_remove_actuals_from_given_activities.rb
Script for deleting (only pre-2022) historic actuals associated with a list of activities. See https://dxw.zendesk.com/agent/tickets/15615 for details.
The process: 
1. Upload the CSV provided by BEIS listing the target activities to GPaaS and locate it as `tmp/activities_whose_actuals_are_to_be_deleted.csv`
2. Run this script with the command `bin/rails runner db/data/20220106163037_remove_actuals_from_given_activities.rb`
3.  Download the output files `tmp/activities_and_their_actuals.csv` and `tmp/actuals_for_deletion.csv` for a record of what was deleted.
> Support: Delete all "actuals" associated with a given list of activities

- script/db-restore
If a database or extension does not exist, attempting to DROP it
fails and halts the restore process. Specifically, `postgis` did
not exist as an extension when installing a local development
environment for me.
```
==> Removing extraneous Postgres extensions...
NOTICE:  extension "postgis" does not exist, skipping
DROP EXTENSION
```
None.
> Add IF EXISTS to DROP commands for databases/extensions

- README.md
We noticed `.env.development.local` is referenced inside one of the scripts, so we shouldn't discourage its use.
We also tidy up what should have been a hyperlink which got missed.
> Go back to .env.development.local and add hyperlink

- config/locales/models/activity.en.yml
- config/locales/models/report.en.yml
A number of duplicated keys in YAML files were discovered from running the `check-yaml` pre-commit hook (see pre-commit.com)
(further information: https://yaml.readthedocs.io/en/latest/api.html#duplicate-keys )
The following decisions were made whilst correcting them:
* Almost all duplicated keys with string values were identical duplicates; one was removed.
* The only exception is `State`/`Status` for the `state` key; State (the first key) was removed as there's evidence of an attempt to change from State to Status.
* All duplicated keys with hash values had no overlap in the keys of the hashes; the 'failure' subkeys were merged with the other subkeys from the duplicated keys. This *does* change the interpretation of the YAML file (the second, more substantial key with non-`failure` …
> Lint YAML files

- CHANGELOG.md
- app/controllers/staff/users_controller.rb
`includes` doesn't like it if you try to sort on the users table first, so we `joins` as well.
`joins` on its own raises an error saying to add includes:
```
Bullet::Notification::UnoptimizedQueryError:
user: dragon
GET /users
USE eager loading detected
User => [:organisation]
Add to your query: .includes([:organisation])
```
Mikey Middleton would appear in the middle.
- ❌ Is an ADR required? An ADR should be added if this PR introduces a change to the architecture.
- ❌ Do any environment variables need amending or adding?
- ❌ Have any changes to the XML been checked with the IATI validator? See [XML Validation](https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/blob/develop/doc/xml-validation.md)
> Move deactivated users to the bottom of the list of users

- spec/policies/activity_policy_spec.rb
- spec/policies/actual_policy_spec.rb
- spec/policies/budget_policy_spec.rb
- spec/policies/external_income_policy_spec.rb
- spec/policies/fund_policy_spec.rb
- spec/policies/matched_effort_policy_spec.rb
- spec/policies/organisation_policy_spec.rb
- spec/policies/programme_policy_spec.rb
- spec/policies/project_policy_spec.rb
- spec/policies/third_party_project_policy_spec.rb
- spec/policies/user_policy_spec.rb
- Refactor policy specs to decrease the setup costs of individual examples
On my machine, the comparative gains when running all policy specs are as such:
Initial:
```
Finished in 1 minute 48.85 seconds (files took 10.44 seconds to load)
446 examples, 0 failures
```
After refactoring:
```
Finished in 1 minute 6.61 seconds (files took 4.49 seconds to load)
263 examples, 0 failures
```
> (2348) Refactor policy specs to minimise setup costs

- Gemfile.lock
Since [upgrading Bundler to 2.3.5 and Rubygems to 3.3.5](https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/1542), `bundle install`
will now compile gems with native components rather than auto-selecting
a precompiled version. In some cases those compilations take so long to
be indistinguishable from a hang.
When we add MacOS variants with
```
bundle lock --add-platform x86_64-darwin
```
then precompiled versions are selected and used in dev, preventing hangs
on `bundle install` when compiling nokogiri, sassc et al
Note that I've not been able to find the behaviour change that causes
this; the bundler gem release notes stop at 2.1.4, after which bundler
started shipping with ruby. We were on 2.1.4 before we leapt to 2.3.5
apropos of the mini_racer issues …
> Add recent MacOS platforms to Gemfile.lock

- CHANGELOG.md
- Gemfile.lock
- app/models/activity.rb
- db/data/20220127155800_invalid_activities_viewer.rb
- db/data/20220127173100_correct_control_code_activity.rb
- spec/models/activity_spec.rb
For fields which are of type 'string' or 'text' (and not an array
of those), before we validate we delete almost all control characters to
avoid XML documents we generate being malformed due to containing
unescaped control characters.
(We don't remove tab, carriage return or line-feed as they're
commonly found within normal text, and are permitted as-is within XML
documents. https://www.w3.org/International/questions/qa-controls#support )
- ❌ Is an ADR required? An ADR should be added if this PR introduces a change to the architecture.
- ❌  Do any environment variables need amending or adding?
(The XML doesn't pass, due to a schema validation error, which we'll look into next)
❯ bundle exec rails runner db/data/20220127173100_correct_control_code_activity.rb`
> Remove control characters from Activities

- CHANGELOG.md
- app/models/activity.rb
- app/views/staff/shared/xml/_activity.xml.haml
- spec/services/activities/import_from_csv_spec.rb
- Ensure that activities validate the presence of `planned_start_date` (or `actual_start_date`) and `planned_end_date` (or `actual_end_date`)
Previously, imported activities were validated in a context that was missing the `:dates_step` validation step.
This has allowed a few activities to be imported without any of `planned_start_date`, `actual_start_date`, `planned_end_date`, `actual_end_date`. These activities go on to generate an invalid IATI XML, which is missing the `iso-date` attribute from the `activity-date` field.
This fix ensures that both imported activities and activities created via the UI form will be validated against the `:dates_step`.
> (2360) Include date validation step when importing

- db/data/20220202135400-all-caps-orgs.rb
Needed for data quality and sorting on drop-down for choosing
an Implementing Organisation.
> Standardise Org names -- all caps, no surplus spaces

- doc/utilities.md
- lib/tasks/invalid_activities.rake
- spec/lib/tasks/invalid_activities_spec.rb
This adds a 'data_holes' rake task for generating CSV reports to hi. We play about with the errors a bit to get them all their own columns to ensure the data is sortable.
> Create CSV report of missing data in activities via validation errors

- app/controllers/errors_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/staff/base_controller.rb
- app/services/activity/tab.rb
- app/services/find_programme_activities.rb
- app/services/find_project_activities.rb
- app/services/find_third_party_project_activities.rb
`include Pundit` -> `include Pundit::Authorization` following dependabot
upgrade to 2.2.0
See
https://github.com/varvet/pundit/blob/main/CHANGELOG.md#220-2022-02-11
Deprecation warnings go away
> Fix Pundit deprecation warnings

- config/initializers/devise.rb
- spec/features/staff/users_can_sign_in_spec.rb
Devise is configured to remember logins for 30 days.
As an aside, note that we haven't been updating the CHANGELOG.md for `devise-authentication`. Add a card to remember to do this before merging to `develop`.
> 2387 remember my login for 30 days

- app/models/user.rb
- config/locales/devise.en.yml
- spec/features/public/visitors/home_page_spec.rb
- spec/features/staff/beis_users_can_edit_a_user_spec.rb
- spec/features/staff/users_can_sign_in_spec.rb
A deactivated user does not get signed in, so we have removed the old
text and only slightly modified the default devise message.
We are not deleting unused translations at this stage. That has been
planned as a larger “mop-up” operation for later.
We also handle the user editing specs, because this seemed like the best
place to reinstate them.
Co-authored-by: rgarner <rgarner@zephyros-systems.co.uk>
> Admin can deactivate a user

- CHANGELOG.md
- app/views/staff/actual_uploads/update.html.haml
- app/views/staff/forecast_uploads/update.html.haml
- app/views/staff/reports/_activities_upload.html.haml
- app/views/staff/reports/_actuals_upload.html.haml
- app/views/staff/reports/_actuals_upload_history.html.haml
- app/views/staff/reports/_forecasts_upload.html.haml
- app/views/staff/reports/activities.html.haml
- app/views/staff/reports/forecasts.html.haml
- config/locales/models/activity.en.yml
- config/locales/models/actual.en.yml
- config/locales/models/forecast.en.yml
- spec/features/staff/users_can_upload_activities_spec.rb
- spec/features/staff/users_can_upload_actuals_spec.rb
- spec/features/staff/users_can_upload_forecasts_spec.rb
- spec/features/staff/users_can_view_forecasts_within_report_spec.rb
Forecasts: Before
Forecasts: After
-----
Activities: Before
Activities: After
> 2410: Make forecast and activity CSV upload look like actuals

- Gemfile
- Gemfile.lock
Adds a REPL to Rails in local development in the context of the exception
> Add binding_of_caller to allow REPL in local dev

- app/controllers/users/sessions_controller.rb
- app/views/devise/sessions/mobile_number.html.haml
- app/views/devise/sessions/otp_attempt.html.haml
- app/views/devise/sessions/two_factor.html.haml
- config/routes.rb
- db/migrate/20220224151206_add_mobile_number_confirmed_at.rb
- db/migrate/20220301145502_default_user_otp_required_for_login_to_true.rb
- db/schema.rb
- spec/factories/user.rb
- spec/features/staff/users_can_sign_in_spec.rb
Collect mobile numbers for accounts that require OTP for login. Note that we aren't mandating that yet and it's `users.otp_required_for_login`.
The link to check shows only until the mobile number is confirmed for the first time:
> 2388 registering mfa number for the first time

- app/controllers/staff/users_controller.rb
- app/models/user.rb
- app/services/update_user.rb
- app/views/staff/users/_form.html.haml
- app/views/staff/users/show.html.haml
- config/locales/models/user.en.yml
- spec/features/staff/beis_users_can_edit_a_user_spec.rb
- spec/features/staff/beis_users_can_view_other_users_spec.rb
- spec/services/update_user_spec.rb
- Allow BEIS users to reset any user's mobile number used for MFA, by using the edit user flow
> (2391) Resetting a user's mobile number for MFA

- Gemfile
- Gemfile.lock
- app/models/user.rb
- app/services/create_user.rb
- app/validators/email_validator.rb
- app/views/devise/passwords/edit.html.haml
- app/views/devise/passwords/new.html.haml
- config/initializers/devise.rb
- config/initializers/devise_security.rb
- config/locales/default.en.yml
- config/locales/devise.security_extension.en.yml
- config/locales/models/user.en.yml
- db/seeds/development_users.rb
- spec/factories/user.rb
- spec/features/staff/users_can_reset_password_spec.rb
- spec/models/user_spec.rb
- Enforce password requirements as close to BEIS requirements and GOV.UK guidelines as possible
- Turn devise's `paranoid` mode on, to avoid email enumeration attacks
> (2386) Update password policy to align with BEIS policy

- config/initializers/devise.rb
- config/locales/devise.en.yml
- spec/features/staff/users_can_reset_password_spec.rb
- Set `Devise.sign_in_after_reset_password = false` in order to ensure users go through the full MFA authentication flow after resetting their password
It's a more Devise-y way of fixing the bug that we previously fixed by hooking into Devise internals.
> (2447) On password reset, redirect to login

- config/initializers/devise.rb
Extend the password expiry link to 2 weeks. After the 2 weeks is up, we'll bring it back down to a more sensible period.
> Temporarily extend password reset expiry

- app/mailers/user_mailer.rb
- app/views/user_mailer/first_time_devise_reset_password_instructions.text.erb
- config/locales/devise.en.yml
- lib/tasks/users.rake
A one-time mass email to send password reset links to every RODA user on
migration from Auth0 to Devise.
Run this after deployment of a merged Devise authentication solution.
Co-authored-by: Dragon <david.mckee@dxw.com>
> rake users:active:send_password_resets

- CHANGELOG.md
- app/controllers/users/sessions_controller.rb
- app/models/user.rb
- spec/features/staff/beis_users_can_edit_a_user_spec.rb
- spec/features/staff/users_can_sign_in_spec.rb
- spec/models/user_spec.rb
- Relax user model validation to permit capitalisation changes and whitespace removal from email addresses
- Use Devise case-insensitive method when retrieving users for authentication
> (2454) Better handling of non-lowercase email addresses

- CHANGELOG.md
- app/services/activity_search.rb
- config/locales/views/activity_search.en.yml
- spec/features/staff/users_can_sign_in_spec.rb
- spec/services/activity_search_spec.rb
- Add functionality to search for activities by IATI identifier
> (2425) Activities can be searched by IATI identifier

- CHANGELOG.md
- app/models/activity.rb
- db/data/20220308163700_add_ooda_fund_activity.rb
- db/seeds/activity.rb
- spec/factories/activity.rb
- spec/features/staff/beis_users_can_create_a_programme_level_activity_spec.rb
- spec/models/iati/xml_download_spec.rb
- spec/support/activity_form.rb
- vendor/data/codelists/BEIS/fund_types.yml
We add the Other ODA (OODA) fund, both as a Fund in the codelist and as an Activity with level: 'fund'
For the Activity, we generated the values in the data migration by: 
Sector and Sector Category are identical to GCRF (after discussion from BEIS)
Description and start date are directly from BEIS
Other values generally there to pass validation 
We removed GDI validation from Activities at Fund Level since it's nil for both GCRF/NF
We've done some testing that if we swap the :newton_funded traits in the activities factories to reference OODA activities, any failing tests are understood not to be due to OODA.
> 2431: Add Other ODA fund into RODA

- CHANGELOG.md
- app/controllers/users/sessions_controller.rb
- app/views/devise/sessions/mobile_number.html.haml
- lib/notify/otp_message.rb
- spec/features/staff/users_can_sign_in_spec.rb
- spec/lib/notify/otp_message_spec.rb
- Prevent server errors when a mobile number is invalid
> (2460) Catch GOV.UK mobile phone validation errors

- CHANGELOG.md
- app/services/create_actual.rb
- app/services/create_refund.rb
- app/services/import_actuals.rb
- app/services/refund/grouped_refund_fetcher.rb
- app/views/shared/refunds/_refunds_by_activity.html.haml
- app/views/staff/reports/_actuals_upload.html.haml
- config/locales/models/actual.en.yml
- config/locales/models/report.en.yml
- spec/controllers/staff/actual_uploads_controller_spec.rb
- spec/features/staff/users_can_upload_actuals_spec.rb
- spec/features/staff/users_can_upload_refunds_spec.rb
- spec/services/create_actual_spec.rb
- spec/services/create_refund_spec.rb
- spec/services/import_actuals_spec.rb
- spec/services/refund/grouped_refund_fetcher_spec.rb
The chosen method is to bolt this functionality onto the existing Actuals
upload, renaming the Value column to Actual Value and adding a new Refund Value
column.
Exactly one of these values must be filled in for an upload to occur.
Create Actual now takes an optional parameter which allows it to generate a
Refund instead, but is otherwise unchanged.
Import Actual contains logic for determining whether a row is a Refund or
Actual, based on the presence of the two types of value.
We also make comments visible on 'refunds by activity'
CSV upload has Actual Value and Refund Value
Refunds have comments (still messy)
> 2412: Bulk upload Refunds

- CHANGELOG.md
- app/views/staff/users/show.html.haml
- config/locales/models/user.en.yml
- db/migrate/20220328164915_remove_users_identifier.rb
- db/schema.rb
- spec/factories/user.rb
- spec/features/staff/users_can_sign_in_spec.rb
- spec/support/authentication_helpers.rb
The last legacy of Auth0. Also remove:
- a mock still allowing it
- factory still setting it
- user view still displaying it
- a translation serving the view
- a spec still using one
\* Thanks @CristinaRO 
Imagine the identifier field, on the users show page
Now imagine it gone
> Remove users.identifier / mashed potato from our hair*

- CHANGELOG.md
- app/helpers/codelist_helper.rb
- app/models/codelist.rb
- app/models/export/activity_attributes_columns.rb
- app/presenters/activity_csv_presenter.rb
- app/presenters/activity_presenter.rb
- spec/helpers/codelist_helper_spec.rb
- spec/presenters/activity_csv_presenter_spec.rb
- spec/presenters/activity_presenter_spec.rb
When viewing the CSV export of a Report or creating a new activity, the Sector, Sector Category, Aid Type, Flow, Finance Type, and Tied Status codes are given in a similar format to the Channel of Delivery codes (e.g. `1234: Kittens and other felines`)
> 2423: Add numeric codes to fields in report export, add Activity

- CHANGELOG.md
- app/controllers/staff/refunds_controller.rb
- app/models/refund_form.rb
- spec/features/staff/users_can_create_a_refund_spec.rb
This validation wasn't being copied up from the object, and so `CreateRefund`
was silently failing. Copy the validation up to fix this error.
In addition, make sure further mismatches between RefundForm and
CreateRefund can't silently fail by checking the return value of
CreateRefund#call.
Co-authored-by: Cristina Rotaru <cristina@dxw.com>
> Make refund form validate numeric values

- app/controllers/concerns/hide_from_bullet.rb
- The gem `bullet` is only bundled for test and development environments,
so when skipping it we first need to make sure it’s defined.
> Fix attempt to use an unloaded gem

- Gemfile.lock
Update puma to address https://github.com/advisories/GHSA-h99w-9q5r-gjq9
While the vulnerability can only be exploited under specific conditions, I've opened this PR in case we think it's better safe than sorry, to be able to expedite releasing it.
> Hotfix puma

- CHANGELOG.md
- app/helpers/application_helper.rb
- app/views/layouts/application.html.haml
- app/views/staff/activities/historic.html.haml
- app/views/staff/organisations/_table.html.haml
- app/views/staff/shared/activities/_tab_nav_item.html.haml
- app/views/staff/shared/activities/_table.html.haml
- app/views/staff/shared/actuals/_table.html.haml
- app/views/staff/shared/adjustments/_table.html.haml
- app/views/staff/shared/external_income/_table.html.haml
- app/views/staff/shared/forecasts/_table.html.haml
- app/views/staff/shared/implementing_organisations/_table.html.haml
- app/views/staff/shared/matched_effort/_table.html.haml
- app/views/staff/shared/refunds/_table.html.haml
- app/views/staff/shared/reports/_table_budgets.html.haml
- app/views/staff/shared/transfers/_index.html.haml
- config/locales/default.en.yml
- Ensure table cells are not empty for screenreaders
- Remove invalid “aria-controls” attributes
- Add missing tablist role to tab lists
- Add landmarks to page contents that wasn't part of any landmarks
> (2475) Fix some accessibility issues with tables and tab lists

- CHANGELOG.md
- app/views/pages/cookie_statement.html.haml
- Declare `remember_user_token` on cookies statement
- Fix declared duration of default session from 24 hours to the actual value of 12 hours
> (2474) Declare rememberable user token on statement

- CHANGELOG.md
- app/models/organisation.rb
- app/views/staff/organisations/_table.html.haml
- config/locales/models/organisation.en.yml
- spec/features/staff/beis_users_can_view_organisations_spec.rb
- Organisations are sorted by active status on the organisations page (applies to all types of organisation: delivery partner, matched effort providers, external income providers, and implementing organisations)
> Sort organisations by active status first

- CHANGELOG.md
- config/initializers/devise.rb
We had extended the validity of "Reset password" links to two weeks to enable
users recieving the password reset link that we'd sent them sufficient time to
log in with the link provided.
The 31st of March is the fourteen-day anniversary of us making that change --
the reset links will become invalid soon, so now is a good time to change this
setting back to something more reasonable.
There was some discussion about the most appropriate amount of time: 24 hours
is an arbitarily-chosen compromise.
> "Reset password" links expire after 24 hours

- app/helpers/application_helper.rb
- spec/helpers/application_helper_spec.rb
On the implementing organisations index page, the View link has a visible space
which is part of the hyperlink (so it looks like View_). We move the space to
be a part of the visually hidden content instead.
> View link has trailing spaces

- db/data/20220405171000_delete_benefitting_countries.rb
Support ticket https://dxw.zendesk.com/agent/tickets/15636 brought it to our
attention that there are 33 countries which have not been eligible during the period
covered by RODA.
57 activities have included these countries in their list of #benefitting_countries.
This is due to the mechanism where when a grouping "region" is selected, all of the
constituent countries are added to the Activity#benefitting_countries list.
In the data migration we:
- print out information on:
- the 33 countries and affected activities
- the affected 57 activities
- remove the invalid countries from each of the affected 57 activities'
#benefitting_countries list
REMOVING THE 33 COUNTRIES THEMSELVES
This will be done in a separate PR/Release as we need the 33
entries in …
> Remove invalid countries from 57 activities' benefitting_countries

- vendor/data/codelists/BEIS/benefitting_countries.yml
**NB: Do not merge until https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/1668 has been deployed**
Support ticket https://dxw.zendesk.com/agent/tickets/15636 brought it to our
attention that there are 33 countries which have not been eligible during the period
covered by RODA.
57 activities have included these countries in their list of #benefitting_countries.
This is due to the mechanism where when a grouping "region" is selected, all of the
constituent countries are added to the Activity#benefitting_countries list.
**The previous PR https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/1668 removes the association of these 33 countries with 57 activities. Once that data migration has been deployed and run we are safe to …
> Remove 33 invalid countries from Benefitting Countries CodeList

- .env.example
- .env.test
- CHANGELOG.md
- Gemfile
- Gemfile.lock
- app/controllers/staff/exports_controller.rb
- app/jobs/spending_breakdown_job.rb
- app/mailers/download_link_mailer.rb
- app/services/export/s3_uploader.rb
- app/services/export/s3_uploader_config.rb
- app/views/download_link_mailer/send_failure_notification.text.erb
- app/views/download_link_mailer/send_link.text.erb
- app/views/staff/exports/export_in_progress.html.haml
- app/views/staff/exports/index.html.haml
- config/locales/views/exports.en.yml
- spec/controllers/staff/exports_controller_spec.rb
- spec/features/staff/users_can_export_spending_breakdown_spec.rb
- spec/jobs/spending_breakdown_job_spec.rb
- spec/mailers/download_link_mailer_spec.rb
- spec/mailers/previews/download_link_mailer_preview.rb
- spec/services/export/s3_uploader_config_spec.rb
- spec/services/export/s3_uploader_spec.rb
- terraform/s3-export-download-bucket.tf
- terraform/worker.tf
The "BEIS" (admin) version of the "spending breakdown" export is a comprehensive output of all spending for all time periods for all organisations -- for a given fund. In recent history this export was considered "broken" because it timed out due to the volume of queries. By contrast, the "Delivery partner" version of the export (which only outputs details for the delivery partner's organisation) has been functional.
From Oct to Nov 2021 we undertook a major refactoring of "exports" (See https://trello.com/c/hbeQLje4/2255-export-improvements). At the end of this process we noted that the spending breakdown export was approx 35% faster. 
However, when the BEIS assurers attempted to run the export in December they experienced 504 (timeout) errors on production. On my (admittedly puny) …
> Feature: move spending breakdown into async job

- .env.example
- .env.test
- app/services/export/s3_uploader_config.rb
- spec/services/export/s3_uploader_config_spec.rb
We originally planned to have the buckets named:
`s3-export-download-bucket-{environment}`
but the Terraform convention which we've followed (see
`terraform/s3-export-download-bucket.tf`) gives us:
`beis-roda-{environment}-s3-export-download-bucket`
In this commit we relax the "matcher" regex in the
`S3UploaderConfig` helper and update our sample env
dotfiles.
> Fix: tweak S3UploaderConfig to match Terraform naming

- app/views/staff/external_incomes/_form.html.haml
- spec/features/staff/users_can_create_an_external_income_spec.rb
- spec/support/form_helpers.rb
On April 1st 2022 (financial year 2022-2023) I may be
needing to post external income for the period Q4 2021-2022.
Previously we were offering only the ten years starting from
the "currrent" financial year, i.e. 2022-2023. We now
include the previous year also.
- [  ] Identify other places suffering from the same problem. Where the "previous" financial year also needs to be displayed!
> Fix: Include previous year in drop-down when posting external income

- CHANGELOG.md
- Fix spending breakdown report by running asynchronously and emailing a download link
to the requester.
- Fix missing Q4 21/22 option in external income by including "previous" year  as well as
the next ten.
NB: the async spending breakdown report can't currently be downloaded from the S3 buckets 
due to a permissions issue. We are about to raise a ticket with the GPaaS support team to look
into this.
> Release 108

- Dockerfile
- app/services/export/s3_uploader.rb
- spec/services/export/s3_uploader_spec.rb
It seems to be impossible to generate a pre-signed GET url
using the GPaaS S3 config, either on a bucket which is
created as "public" or "private".
I've identified two ways of generating a working download
link using Terraform / GPaaS:
This has the disadvantage that the links never expire.
However, I think it's adequate in terms of security as the
url is essentially unguessable e.g.
`https://paas-s3-broker-prod-lon-8cc9c2c5-43f7-44bf-a5c1-11c4256feba8.s3.eu-west-2.amazonaws.com/GCRF_spending_breakdown-20220411170906.csv`
By generating a separate set of AWS credentials which are
explicitly set to enable external access:
```
cf create-service-key \
beis-roda-staging-s3-export-download-bucket \
beis-roda-staging-s3-export-download-bucket \
-c '{"allow_external_access": true}'
```
and using …
> Generate public rather than pre-signed url for download link

- CHANGELOG.md
- app/services/activities/import_from_csv.rb
- spec/models/activity_spec.rb
https://dxw.zendesk.com/agent/tickets/16367 reports the following bug:
Issue: delivery partners are accidently changing ODA eligible activities to 'no longer eligible.
Expected behaviour: If a delivery partner doesn't use one of the three upload codes for ODA eligibility in activities bulk upload RODA won't accept the CSV and list the error in the 'List of errors in your updated CSV file'.
Defective behaviour: If a delivery partner uses 'text' rather than the designated bulk upload codes (i.e. 'eligible') the eligibility status changes in the activity (unknown to the user).
This is caused by "kitten".to_i returning 0, rather surprisingly. Integer("kitten") raises an error as expected.
## Next steps
It might be worth reviewing the use of `to_i` on user-generated input more generally.
> 16367 no validation for oda eligibility

- CHANGELOG.md
- app/services/activities/import_from_csv.rb
- spec/features/staff/users_can_upload_activities_spec.rb
- spec/services/activities/import_from_csv_spec.rb
- spec/services/export/report_spec.rb
This PR fixes two bugs in the handling of implementing organisations when updating activities using the bulk upload method:
1. the bulk upload CSV template for activities was missing a column for describing each activity's implementing organisations. This resulted in any pre-existing associations being removed when an activity was updated in this way. We now have a `Implementing organisation names` column which takes a pipe-delimited list of organisation names
2. the update code (in `Activity::ImportFromCsv`) did not handle an activity being associated with multiple implementing organisations. 
This work results from a [bug report 16160](https://dxw.zendesk.com/agent/tickets/16160) showing that whenever an
activity with a pre-existing implementing organisation
association is updated via …
> Fix: 16160 - Bulk update of activities including implementing organisations

- spec/features/staff/beis_users_can_upload_actuals_history_spec.rb
At some point in the last eighteen hours since 9f5299d336ad425184e1ba565534ea7f98f13e4d
passed CI I suspect a version of the testing software (Capybara?) has been silently
updated causing the tests to fail with:
Failure/Error: expect(page).to have_content("1")
expected to find text "1" in
Value 2 Ten thousand pounds Value must be a valid number [highly abbreviated]
(However, it was found 1 time including non-visible text.)
My suspicion is that the line number in the CSV always should have been 2, but 1 passed
because it was in some invisible text somewhere, until this update.
> Adjust rowcount for test which passed due to invisible text

- script/terraform_test
Passes `-backend=false` to `terraform_test`'s `terraform init` command, to ensure we don't try and configure a backend for it.
This is currently failing on CI due to it trying to configure S3. Passing this flag should allow Dependabot to be able to run CI without us needing to set its own secrets e.g. CF username and password
> Don't setup backend for `terraform_test` script

- lib/tasks/shellcheck.rake
I'm not quite sure what might have caused this to change, but running
`script/test` failed at the linting stage as it was trying to lint
`vendor/`, a directory of libraries we don't control.
> Exclude vendor from shellcheck

- .github/workflows/rebase.yml
- .github/workflows/trigger_rebase.yml
This is currently failing the "automatic rebase" step of the build with the following error:
```
fatal: detected dubious ownership in repository at '/github/workspace'
```
This is due to a change in the `actions/checkout` package, it has now been fixed in [version 1.6](https://github.com/cirrus-actions/rebase/releases/tag/1.6) but let's update to version 1.7 as it's the latest now.
> Update rebase action in workflows to 1.7

- doc/0_index_of_contents.md
- doc/support_tasks/training_db_sync.md
- script/training_db_sync.rb
This script is designed to update the 'training' environment
with a copy of the production data ('prod').
User credentials are scrubbed, requiring users to reset their
passwords after each 'sync'.
It can be run from a developer or ops person's laptop
provided the user has:
- a GPaaS (https://docs.cloud.service.gov.uk) account for BEIS RODA
- the Cloudfoundry tools installed
(https://docs.cloud.service.gov.uk/get_started.html#set-up-the-cloud-foundry-command-line)
- installed the Conduit plugin for Cloudfoundry/GPaaS
(https://docs.cloud.service.gov.uk/guidance.html#using-the-conduit-plugin)
Environment variables expected:
- `GPAAS_CF_USER`
- `GPAAS_CF_PASSWORD`
Set these in your `.env` file or export to your shell
manually.
Run the script using the `bin/rails runner` command so that
the …
> Replace DB in 'training' env with copy from 'prod'

- CHANGELOG.md
- app/assets/stylesheets/partials/_alerts.css.scss
- app/helpers/application_helper.rb
- app/views/layouts/application.html.haml
- spec/features/staff/users_can_view_environment_banner_spec.rb
- spec/helpers/application_helper_spec.rb
- Display a banner on non-production environments to make it clearer to users which site they're using
> (2509) Add banner to non production envs

- CHANGELOG.md
- app/helpers/application_helper.rb
- app/mailers/application_mailer.rb
- app/mailers/download_link_mailer.rb
- app/mailers/report_mailer.rb
- app/mailers/user_mailer.rb
- app/views/layouts/application.html.haml
- config/locales/devise.en.yml
- config/locales/models/report.en.yml
- config/locales/views/exports.en.yml
- spec/features/staff/beis_users_can_invite_new_users_spec.rb
- spec/features/staff/users_can_approve_a_report_spec.rb
- spec/features/staff/users_can_mark_a_report_as_awaiting_changes_spec.rb
- spec/features/staff/users_can_submit_a_report_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/mailers/download_link_mailer_spec.rb
- spec/mailers/report_mailer_spec.rb
- spec/mailers/user_mailer_spec.rb
- Show the environment name (e.g. "training") in the subject of emails sent by the application
NOTE: If approved in its present form, this change will require updating the GOV.UK Notify welcome email template to add `environment_mailer_prefix` as a personalisation.
> (2520) Show environment in email subjects

- db/data/20220715170000_use_graduated_country_as_benefitting_country.rb
Zendesk ticket: https://dxw.zendesk.com/agent/tickets/16109
Since:
https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/commit/fe68bc2463512c73b6f594b9bc1d19890dbb6b13
(Sept 2021), when adding or updating an activity via the bulk
upload mechanism, it's not been possible to associate a "graduated"
country with an activity as an entry in `benefitting_countries`. However,
there are some historic activities (they have `actual_end_dates`)
which are missing a benefitting country which was valid at
the time it was active.
For example, GCRF-AH_C_LGI-2016AH/P009158/1 was active between
01-Nov-2016 and 30-Jun-2017.
At that time Chile was a valid benefitting country. However, the
historic activity was added to RODA last year (15-Jun-2021)
and by that later date Chile was …
> Use graduated country as 'benefitting' in 4 historic cases

- CHANGELOG.md
- Display a banner on non-production environments to make it clearer to
users which site they're using
- Show the environment name (e.g. "training") in the subject of emails
sent by the application
> Release 113

- CHANGELOG.md
- app/validators/date_within_boundaries_validator.rb
- spec/features/staff/beis_users_can_edit_a_report_spec.rb
- spec/validators/date_within_boundaries_validator_spec.rb
As per: https://dxw.zendesk.com/agent/tickets/16783
Allow 2005 start date for historical activities
This is a temporary solution to allow migration of historical data in
the service, as BEIS are currently adding historical activities and this
feels like a safe sensible earliest date to allow.
We will undo this commit once the new activities have been added.
> Allow 2005 start date for historical activities

- CHANGELOG.md
- app/helpers/application_helper.rb
- spec/helpers/application_helper_spec.rb
- spec/mailers/user_mailer_spec.rb
Don't pass nil as environment mailer prefix
This threw an error on production, meaning new users wouldn't receive
the welcome email.
> Ensure welcome emails are sent from production

- app/helpers/application_helper.rb
- spec/features/staff/users_can_view_environment_banner_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/mailers/download_link_mailer_spec.rb
- spec/mailers/report_mailer_spec.rb
- spec/mailers/user_mailer_spec.rb
The env var `DOMAIN` is set on both app and worker instances, whereas
`CANONICAL_HOSTNAME` is only set on app instances.
In order to have environment name detection working for emails sent via
workers, we need to use the variable that is available to all of them.
> Use DOMAIN instead of CANONICAL_HOSTNAME

- CHANGELOG.md
- app/mailers/user_mailer.rb
- config/locales/devise.en.yml
- spec/features/staff/beis_users_can_invite_new_users_spec.rb
- spec/mailers/user_mailer_spec.rb
This PR needs testing on staging first, so do not mark as ready for review until after deploy to prod (to avoid holding up the deploy).
- Use locale string for welcome email subject
> Use locale string for welcome email subject

- CHANGELOG.md
Temporary allow activities to be added with the earliest actual start date of mid 2005 for historical data migration
- Fix issue where welcome emails wouldn't be sent on production
- Send welcome email subject from the application instead of trying to pesonalise the templated subject
> release 114

- CHANGELOG.md
- app/views/staff/reports/show.html.haml
- config/locales/models/report.en.yml
- spec/features/staff/users_can_view_reports_spec.rb
- Show total of refunds in report summary
> (2501) Show total of refunds in report summary

- CHANGELOG.md
- app/services/activity/inference.rb
- vendor/data/codelists/BEIS/aid_type.yml
- Fix the misspelling of "FSTC" in a codelist and in the service using the codelist
FSTC stands for “Free-standing Technical Cooperation”.[1]
The misspelling in the codelist is consistent with the code that checks
for that key, and the activity attribute is correctly spelled. However,
the misspelling is a source of confusion, so we want to fix it.
[1] If we were to use the official acronym, via OECD:
https://stats.oecd.org/glossary/detail.asp?ID=6022
we would be switching all of them to “FTC”. However, I feel that would
be more disruptive than helpful at this point.
> (2517) Fix misspelling of “FSTC” in codelist

- CHANGELOG.md
- app/models/export/activity_attributes_columns.rb
- app/models/export/activity_attributes_order.rb
- app/presenters/activity_csv_presenter.rb
- config/locales/models/activity.en.yml
- spec/models/export/activity_attributes_columns_spec.rb
- spec/models/export/activity_attributes_order_spec.rb
- spec/presenters/activity_csv_presenter_spec.rb
- Add parent programme ID and title, and parent project ID and title where applicable, to activity rows in report CSVs
> (2502) Include detail of activities within RODA hierarchy in CSVs

- spec/models/activity_spec.rb
The test was throwing a warning:
“Using the `raise_error` matcher without providing a specific error or
message risks false positives, since `raise_error` will match when Ruby
raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially
allowing the expectation to pass without even executing the method you
are intending to call.”
Fix by matching against a specific error message.
> Provide specific error message to spec

- CHANGELOG.md
- app/views/staff/shared/reports/_grouped_table.html.haml
- app/views/staff/shared/reports/_table.html.haml
- app/views/staff/shared/reports/_table_empty.html.haml
- config/locales/models/report.en.yml
- spec/features/staff/users_can_view_reports_spec.rb
- Make the message shown when there are no approved reports more accurate
> (2522) Inaccurate message on reports approved tab when no approved reports exist

- CHANGELOG.md
- app/services/export/report.rb
- spec/services/export/report_spec.rb
The previous implementation was calling `forecast_rows.any?` on some
forecast rows with the following structure:
```
{ 'activity-id'=>[100] }
```
This meant that we were calling `any?` on a hash value which was always
returning `true`, in contrast to the `headers` which would return an
empty array.
This led to the number of headers being out of sync with the number of
rows, causing columns to be out of sync from the `variance` row.
Now we check all the arrays in that hash are empty - if they are, we
don't render the variance row.
For the tests, We've added an entire new spec because the existing setup sets up a forecast, and
there's no easy way we could see to remove it or set it up at a later stage. It's intended
to otherwise be a complete copy of the setup for the with-forecast case. …
> Don't create rows with no export data

- CHANGELOG.md
- app/views/staff/home/_delivery_partner_organisations_table.html.haml
- config/locales/default.en.yml
- spec/views/home/service_owner_spec.rb
Replace "View details" link with link on Org name to free up some room in future for a link to "Upload activities".
I've also added a visually hidden span for screen readers here, although I wonder if the text could be a bit more obvious?
This PR also refactors text on links on this page to use translation files to be more consistent.
We'll be adding the "Upload data" link to this table in the next chunk of work.
> (2540) Replace Partner Org "view details" link with clickable Partner Org name link

- CHANGELOG.md
- app/controllers/staff/level_b_activity_uploads_controller.rb
- app/policies/organisation_policy.rb
- app/views/staff/home/_partner_organisations_table.html.haml
- app/views/staff/level_b_activity_uploads/new.html.haml
- config/locales/default.en.yml
- config/locales/models/activity.en.yml
- config/routes.rb
- spec/controllers/staff/level_b_activity_uploads_controller_spec.rb
- spec/features/staff/beis_users_can_upload_level_b_activities_spec.rb
- spec/policies/organisation_policy_spec.rb
- spec/views/home/service_owner_spec.rb
Add Level B activity bulk upload form view and a link to it from the [partner organisations table](http://localhost:3000/home). The view for the form includes a link to download the template CSV files, but it currently points nowhere
I'm not sure why the organisation names are title case on my end - the before screenshot is taken from #1753 (i.e. @Gweaton's setup), so it hopefully isn't a change I've introduced, just a local environment quirk (can look into this tomorrow)
---
> (2532) Add hub page for being able to download template upload CSV file

- app/controllers/staff/level_b_activity_uploads_controller.rb
- app/presenters/organisation_presenter.rb
- app/services/activities/import_from_csv.rb
- app/views/staff/level_b_activity_uploads/new.html.haml
- config/routes.rb
- spec/controllers/staff/level_b_activity_uploads_controller_spec.rb
- spec/features/staff/beis_users_can_upload_level_b_activities_spec.rb
This adds a controller action to enable users to download the template CSV for Level B activity data bulk uploads, linked from the view/form created in the previous commit. Currently it will respond with a template with the same headers as the standard activity upload
The changelog will be updated after 2533 (processing the upload)
> (2531) Add Level B template CSV download action

- db/data/20220920112227_rename_dp_to_po_in_form_state.rb
Adds a data migration for renaming an Activity's `form_state` value from `country_delivery_partners` to `country_partner_organisations`. Now that we've renamed `delivery_partners` to `partner_organisations` in the codebase, this data field is out of date. I believe there's only actually 1 Activity at this step, but we should always use a script to do this rather than the Rails console on production.
> (2571) Add data migration to migrate `country_delivery_partner` form state to `country_partner_organisation`

- CHANGELOG.md
- Replace "View details" link in the Partner Organisation table for BEIS users with a link on Organisation name instead
- Replace "Delivery partner" with "Partner organisation" and "DP" with "PO" in user-facing text, including CSV column headers
- Replace references to `delivery_partner` with `partner_organisation` (or `partner_organisation_user` depending on context) across the code, including a database migration to rename `delivery_partner_identifier` to `partner_organisation_identifier`
- Replace references to `country_delivery_partners` with `country_partner_organisations`, including database migration
- Replace code references to `uk_dp_named_contact` with `uk_po_named_contact`, including database migration
- Remove "PO Definition" from "Aims/Objectives" CSV headers
> Release 116

- app/services/activities/import_from_csv.rb
The policy marker convertor methods have their own error checking, so we don’t want the `Integer` conversion to raise an exception.
The commit dd28a23b20f05573f7eb4dfe6a841d945e15feb1 which made this change made it on the `master` branch somehow (investigation pending), despite the intention being to revert it, as the commit message of the commit
that made it into release-111 attests: dc61b9daf89b6bd68a407c62a52e9df154025d73.
> Fix error-raising code

- spec/lib/vcap_parser_spec.rb
The spec `it "loads redis URL to the ENV”` has side effects that can cause other specs to fail, depending on the order in which they are run.
`ClimateControl` can only reset `VCAP_SERVICES` for us, not the other env vars that are set during the spec running.
The default value of `VCAP_SERVICES` (set in .env.test) doesn’t have a value for `REDIS_URL`, so the value being set during this spec sticks, and overwrites the desired value of `REDIS_URL`, which is set in .env.test.
> Reset env var post-spec

- CHANGELOG.md
- Add ability for BEIS users to create and update Level B activities in bulk by uploading a CSV
- Make partner organisation identifier optional for Level B activities (both via the individual new activity form and bulk upload)
> Release 117

- package.json
- yarn.lock
- Upgrade `webpack-dev-server` in order to install a fixed version of `node-forge`.
N/A
> Bump webpack-dev-server to fix node-forge alert

- CHANGELOG.md
- app/controllers/staff/level_b/budgets/uploads_controller.rb
- app/controllers/staff/level_b_activity_uploads_controller.rb
- app/models/budget_upload.rb
- app/policies/level_b_policy.rb
- app/views/staff/level_b/budgets/uploads/new.html.haml
- config/locales/models/budget.en.yml
- config/routes.rb
- spec/controllers/staff/level_b/budgets/uploads_controller_spec.rb
- spec/features/staff/beis_users_can_upload_level_b_budgets_spec.rb
- spec/policies/level_b_policy_spec.rb
This adds a new view for bulk uploading Level B budget data via CSV. Currently the CSV template download and upload form are non-functional - these will be added in later commits
We added a new budget upload model and policy as this upload is not attached to a specific activity (or any entity) - budgets can be uploaded for multiple funds and organisations all in one CSV file
**Note:** linked in the parent Trello card is an design screenshot (`uploads_form.png`), which slightly differs in structure to the Level B activities upload form. We decided to keep it similar to the latter - we weren't sure how recent the design was - but we could change it to match the design more closely if preferred
> (2585) Add placeholder Level B budget upload page

- spec/controllers/staff/activities_controller_spec.rb
- spec/controllers/staff/organisations_controller_spec.rb
- spec/features/staff/beis_users_can_create_an_organisation_spec.rb
- spec/features/staff/beis_users_can_view_organisations_spec.rb
- spec/features/staff/beis_users_can_view_other_users_spec.rb
- spec/features/staff/users_can_edit_an_actual_spec.rb
- spec/features/staff/users_can_edit_an_organisation_spec.rb
- spec/features/staff/users_can_view_a_home_page_spec.rb
- spec/features/staff/users_can_view_the_site_navigation_spec.rb
- Ensure logged out specs start with clean state by logging out any potential users
N/A
> Ensure logged out specs start with clean state

- app/controllers/staff/level_b/budgets/uploads_controller.rb
- app/views/staff/level_b/budgets/uploads/new.html.haml
- config/routes.rb
- spec/controllers/staff/level_b/budgets/uploads_controller_spec.rb
- spec/features/staff/beis_users_can_upload_level_b_budgets_spec.rb
This adds a controller action to enable users to download the template CSV for Level B budget data bulk uploads, linked from the view/form created in the previous commit
The headers are as per the design collaboration with the client, but may still be subject to change. The naming of some columns differs slightly to that used in the activity templates
> (2588) Add Level B budget bulk upload template CSV download action

- CHANGELOG.md
- app/services/forecast_history.rb
- spec/services/forecast_history_spec.rb
- Ensure `Forecast.set_value` always returns a forecast or nil
> (2569) `Forecast.set_value` must return a forecast or nil

- app/controllers/staff/level_b/budgets/uploads_controller.rb
- app/services/budget/import.rb
- config/locales/models/budget.en.yml
- spec/services/budget/import_level_b_spec.rb
This adds a budget importer for processing bulk uploads in a similar way to the activities importer
> (2590) Add budget importer

- app/controllers/staff/level_b/budgets/uploads_controller.rb
- app/views/staff/level_b/activities/uploads/update.html.haml
- app/views/staff/level_b/budgets/uploads/create.html.haml
- app/views/staff/level_b/budgets/uploads/new.html.haml
- app/views/staff/shared/budgets/uploads/_budgets_table.html.haml
- app/views/staff/shared/budgets/uploads/_error_table.html.haml
- app/views/staff/shared/budgets/uploads/_upload_form.html.haml
- config/locales/models/budget.en.yml
- config/routes.rb
- spec/controllers/staff/level_b/budgets/uploads_controller_spec.rb
- spec/features/staff/beis_users_can_upload_level_b_budgets_spec.rb
- spec/fixtures/csv/invalid_level_b_budgets_upload.csv
- spec/fixtures/csv/valid_level_b_budgets_upload.csv
This adds the create action to the Level B budget uploads controller, handling the creation of budgets from the provided CSV
> (2594) Add budgets create action

- app/views/shared/_navigation.html.haml
- config/locales/models/budget.en.yml
- spec/features/staff/users_can_view_the_site_navigation_spec.rb
This adds a link to the Level B budgets bulk upload page to the top nav for BEIS users
> (2601) Add budgets link to top nav

- CHANGELOG.md
- app/controllers/staff/level_b/activities/uploads_controller.rb
- app/controllers/staff/level_b/budgets/uploads_controller.rb
- app/models/budget_upload.rb
- app/policies/level_b_policy.rb
- app/services/budget/import.rb
- app/views/shared/_navigation.html.haml
- app/views/staff/level_b/activities/uploads/update.html.haml
- app/views/staff/level_b/budgets/uploads/create.html.haml
- app/views/staff/level_b/budgets/uploads/new.html.haml
- app/views/staff/shared/budgets/uploads/_budgets_table.html.haml
- app/views/staff/shared/budgets/uploads/_error_table.html.haml
- app/views/staff/shared/budgets/uploads/_upload_form.html.haml
- config/locales/models/budget.en.yml
- config/routes.rb
- spec/controllers/staff/level_b/budgets/uploads_controller_spec.rb
- spec/features/staff/beis_users_can_upload_level_b_budgets_spec.rb
- spec/fixtures/csv/invalid_level_b_budgets_upload.csv
- spec/fixtures/csv/valid_level_b_budgets_upload.csv
- spec/policies/level_b_policy_spec.rb
- spec/services/budget/import_level_b_spec.rb
This adds the Level B budgets bulk upload functionality for BEIS users
(This will fail the first time because of using the 'invalid' CSV, then the second time because the 'valid' CSV has a parent activity that isn't in my local database)
https://user-images.githubusercontent.com/40244233/193571743-33533669-e42b-471e-b8f8-e52df62d659f.mov
> (2565) Build level b bulk budget upload functionality

- CHANGELOG.md
- app/views/staff/level_b/activities/uploads/new.html.haml
- app/views/staff/level_b/activities/uploads/update.html.haml
- Point the "Back to home" link on the Level B activities bulk upload to the home page instead of the organisations page
> (2587) Point “Back to home” link to homepage

- CHANGELOG.md
- app/models/export/activity_comments_column.rb
- app/services/report/export.rb
- spec/models/export/activity_comments_column_spec.rb
- spec/services/report/export_spec.rb
- Comments in reports CSV are delimited by a pipe, instead of a newline, to enable BEIS users' QA workflow
> (2555) Separate comments in reports CSV with a pipe

- app/controllers/staff/level_b/budgets/uploads_controller.rb
- app/services/budget/import.rb
- spec/features/staff/beis_users_can_upload_level_b_budgets_spec.rb
This removes the two unprocessed columns that were previously included in the CSV and rearranges the remaining columns per client input
> (2604, 2606) Update Level B budget upload CSV columns

- Gemfile
- Gemfile.lock
Reverts UKGovernmentBEIS/beis-report-official-development-assistance#1798
See https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/1798#issuecomment-1270725149 for details - this breaks test migrations and introduces a warning message when running tests. The comment notes what we can do to unbreak the migrations, but the warnings remain, and the tests (at least feature tests) run a little slower, so it's one to investigate later
> Revert "Bump spring-watcher-listen from 2.0.1 to 2.1.0"

- CHANGELOG.md
- script/training_db_sync.rb
After running the training db sync, which fetches the current users on production and writes them to the training environment database, we encountered the following error on logging in:
```
OpenSSL::Cipher::CipherError
```
This was a difficult one to debug, but after some digging, we discovered it was caused by users' passwords not being reset as expected in the `pw_reset_script` portion of the training db sync script.
This was a difficult one to debug, but we discovered that the `bin/rails` command wasn't being run (albeit silently, without any errors being surfaced to us running the command) due to the `ssh -c` command not placing the user in the `/app` directory where `bin/rails` is available.
Then, we discovered `ruby` wasn't available in the `PATH` as using double quotes around a …
> Fix training db sync script password reset command

- CHANGELOG.md
- app/controllers/staff/implementing_organisations_controller.rb
- app/models/org_participation.rb
- config/locales/models/org_participation.en.yml
- spec/controllers/staff/implementing_organisations_controller_spec.rb
- spec/factories/org_participation.rb
- spec/factories/organisation.rb
- spec/features/staff/users_can_manage_implementing_organisations_spec.rb
- spec/models/org_participation_spec.rb
This prevents users from adding inactive organisations as implementing organisations for activities
If the database is in sync with production, NERC CENTRE FOR ECOLOGY & HYRDOLOGY will appear before, but not after
> (2513) Make inactive organisations unusable

- CHANGELOG.md
- app/services/activity/import.rb
- app/services/budget/import.rb
- config/locales/models/activity.en.yml
- spec/services/activity/import_spec.rb
Makes incomplete parent activity error more explicit
Users have reported being unable to add Level C and D activities to some Level B activities, as they were met with the error message: "The parent activity is not valid". The error was caused by the Level B activity not being in the correct `form_state` (it must be `completed`).
This message didn't feel clear enough, as it didn't tell the user how to rectify the issue - stating that the parent is actually "incomplete".
Hopefully this should make it clearer to the user that they have to go in and finish creating the Level B activity.
This PR also includes a couple of smaller bits of renaming - while I'd like to refactor the importer class, this felt like a bigger job than was necessary for solving this issue.
> (2619) Improve error message when trying to create a Level C activity on an incomplete Level B activity

- spec/features/users_can_sign_in_spec.rb
- spec/requests/activity_forms_spec.rb
- spec/requests/organisations_spec.rb
As previously discovered[1], specs that log in a user have side effects on specs that rely on there being no logged in user for their initial state.
Fix a few more specs that didn’t log out after they were done.
[1] e31486980ac2a597534ee0e0c0abbfa0c84c350b
N/A
> Log out after specs that log in as a user

- CHANGELOG.md
- db/data/20221019111441_add_ispf_level_a_activity.rb
- db/seeds/activity.rb
- spec/models/iati/xml_download_spec.rb
- vendor/data/codelists/BEIS/fund_types.yml
This is the first step on the journey to add ISPF to the service, adding:
- The ISPF fund type to the fund type codelists
- A local ISPF level A activity
- A data migration to create the actual Level A activity (this will need to be run manually on the deployed environment once ready to go)
Because of how we're currently looping over all funds, locally we can already see links for adding new activities (see screenshot).
I've opened this PR against a longer-running feature branch rather than `develop` until we get feature flagging sorted to be able to hide this data on a deployed environment.
> [2625] Add bare bones ISPF to the service

- CHANGELOG.md
- app/controllers/reports_controller.rb
- app/models/activity.rb
- app/models/report.rb
- app/services/report/grouped_reports_fetcher.rb
- app/services/report/organisation_reports_fetcher.rb
- config/initializers/rollout.rb
- spec/factories/activity.rb
- spec/features/beis_users_can_create_a_report_spec.rb
- spec/rails_helper.rb
- spec/requests/rollout_spec.rb
- spec/rollout_spec.rb
- spec/services/report/grouped_reports_fetcher_spec.rb
- spec/services/report/organisation_reports_fetcher_spec.rb
- Hide ISPF reports when the ISPF feature flag is enabled
> (2662) Use feature flag to hide ISPF reports

- CHANGELOG.md
- app/controllers/activities_controller.rb
- app/services/report/organisation_reports_fetcher.rb
- spec/features/beis_users_can_create_a_programme_level_activity_spec.rb
**NB** This PR builds upon #1834 
- ISPF programmes cannot be created when the feature flag is enabled for BEIS users
> (2664) ISPF programmes cannot be created when the feature flag is enabled

- CHANGELOG.md
- app/services/activity/grouped_activities_fetcher.rb
- spec/factories/activity.rb
- spec/features/beis_users_can_create_a_programme_level_activity_spec.rb
- spec/features/users_can_view_activities_spec.rb
**NB** This PR builds upon #1835 
- ISPF activities are not shown to users when the feature flag is enabled
> (2665) Hide ISPF activities from home page and org page

- CHANGELOG.md
- app/controllers/activity_comments_controller.rb
- app/helpers/activity_helper.rb
- app/models/comment.rb
- app/policies/level_b_policy.rb
- app/views/activities/comments.html.haml
- app/views/activity_comments/edit.html.haml
- app/views/activity_comments/new.html.haml
- config/locales/models/comment.en.yml
- spec/controllers/activity_comments_controller_spec.rb
- spec/features/users_can_create_a_comment_spec.rb
- spec/features/users_can_edit_a_comment_spec.rb
- spec/features/users_can_view_comments_spec.rb
- spec/helpers/activity_helper_spec.rb
- spec/models/comment_spec.rb
- spec/policies/level_b_policy_spec.rb
This extends the activity comments functionality to allow BEIS users to add and edit comments at Level B
Partner organisations will be able to see comments on Level B activities, per client advice
> (2621) Allow comments on Level B activities

- CHANGELOG.md
- app/services/activity_search.rb
- spec/services/activity_search_spec.rb
- ISPF activities are not shown in search results when the feature flag is enabled
> (2666) Exclude ISPF activities from search results

- CHANGELOG.md
- app/helpers/comments_helper.rb
- app/models/export/activity_comments_column.rb
- app/services/budget/export.rb
- spec/features/beis_users_can_download_exports_spec.rb
- spec/helpers/comments_helper_spec.rb
- spec/services/budget/export_spec.rb
This adds Level B activity comments to the budget exports in a new column. There is no demand for comments for other levels in budget exports at present
I've extended one test to include a programme activity with two comments (since it already created a programme activity), but not the test above it (`downloading budgets for a partner organisation`) - is it worth doing this?
For the `export_spec`, I've updated the `#activity` tests. I notice that the private methods don't have tests - is this standard? I haven't added tests for `#activity_comments` for now
> (2677) Add Level B comments to budget exports

- CHANGELOG.md
- app/controllers/activity_forms_controller.rb
- app/helpers/codelist_helper.rb
- app/models/activity.rb
- app/models/codelist.rb
- app/models/partner_country.rb
- app/presenters/activity_presenter.rb
- app/services/activity/updater.rb
- app/views/activity_forms/ispf_partner_countries.html.haml
- app/views/shared/activities/_activity.html.haml
- config/locales/models/activity.en.yml
- db/migrate/20221031155150_add_ispf_partner_countries_to_activities.rb
- db/schema.rb
- spec/controllers/activity_forms_controller_spec.rb
- spec/factories/activity.rb
- spec/features/beis_users_can_create_a_programme_level_activity_spec.rb
- spec/helpers/codelist_helper_spec.rb
- spec/models/codelist_spec.rb
- spec/models/ispf_partner_country_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/support/activity_form.rb
- vendor/data/codelists/BEIS/ispf_partner_countries.yml
Adds ISPF partner countries to the activities table/model, a PartnerCountry (non-Active Record) model, a form step for adding this when creating an activity, and a line in the activity details page (including an edit link)
> (2670) Add ISPF partner countries

- CHANGELOG.md
- app/services/activity_defaults.rb
- spec/services/activity_defaults_spec.rb
Activities now inherit the `is_oda` attribute from their parent, so Level C/D activities will have the same `is_oda` value as was set on their parent Level B activity, and therefore be shown the correct ODA countries on the ISPF partner countries step
Other than skipping the ODA/non-ODA step, everything else is as per the Level B ISPF user journey
Re: feature tests: `spec/features/users_can_create_a_project_level_activity_spec.rb` isn't as comprehensive as `spec/features/beis_users_can_create_a_programme_level_activity_spec.rb` in testing different funds and the form steps, but perhaps we should expand it?
> (2642) Add new steps to the new activity form for Level C/D ODA ISPF activities

- CHANGELOG.md
- app/controllers/implementing_organisations_controller.rb
- app/views/activities/details.html.haml
- app/views/shared/activities/_implementing_organisations.html.haml
- app/views/shared/implementing_organisations/_table.html.haml
- spec/factories/activity.rb
- spec/features/users_can_manage_implementing_organisations_spec.rb
- spec/features/users_can_view_an_activitys_details_spec.rb
- Do not allow removing the implementing organisation from a level C or D ISPF activity if it is the only one
> (2694) Do not allow removing the last implementing org

- CHANGELOG.md
- app/controllers/activity_forms_controller.rb
- app/models/activity.rb
- spec/factories/activity.rb
- spec/features/users_can_create_a_project_level_activity_spec.rb
- spec/features/users_can_create_a_third_party_project_level_activity_spec.rb
- spec/models/activity_spec.rb
- spec/support/activity_form.rb
- Adds Level C/D non-ODA ISPF form journey
- Adds feature tests covering both ODA and non-ODA ISPF Level C/D UI user journeys
- Adds unit tests for the public methods added to `Activity` - coverage here is still not incomplete, though
> (2643) Add Level C/D non-ODA ISPF form journey

- CHANGELOG.md
- app/controllers/activity_forms_controller.rb
- app/models/activity.rb
- spec/features/beis_users_can_create_a_programme_level_activity_spec.rb
- spec/models/activity_spec.rb
- spec/support/activity_form.rb
This skips various form steps for Level B ISPF non-ODA activities
`is_non_oda_project?` is now only used in the `Activity` class, so it's shifted to a private method and its tests have been removed
> (2692) Update UI user journey for adding Level B ISPF non-ODA activity

- db/seeds/development_users.rb
- script/db-restore
- Fixes `db-restore` error and typo
- Integrates setting `otp_required_for_login` into local development user seeds, removing the need for devs to do this manually every time they sync with production data
> Fix db-restore and set OTP

- spec/features/beis_users_can_create_a_programme_level_activity_spec.rb
- spec/features/users_can_create_a_project_level_activity_spec.rb
- spec/features/users_can_create_a_third_party_project_level_activity_spec.rb
- spec/support/activity_form.rb
Previously `is_oda` was being passed into various methods in `ActivityForm`, however on initialisation we pass in the activity from which the `is_oda` value was always being taken. We can directly access this via the `@activity` instance method, so we don't need to pass in any of its attributes separately
> (2699) Remove superflous arguments in `ActivityForm`

- app/views/shared/activities/_activity.html.haml
- spec/views/shared/activities/activity_spec.rb
This uses all the new and existing `requires_X?` instance methods in the `Activity` class to determine whether to show fields in the activity details tab/page. One or two of these were already being used, while on some other fields the old logic of the `requires_X?` method was simply being replicated in the view - this brings the logic up to date and keeps the code DRY
It also updates the logic for displaying SDGs, however this does not use a `requires_X?` method. Since the validation of `sdg_1` is based on `sdgs_apply?` rather than a `requires_X?` method, the logic as to whether to skip this form step and show it in the view are kept separate/plain to avoid confusion about the difference between `sdgs_apply?` and `requires_sdgs?`
Example is non-ODA, which has the most changes …
> (2693) Hide fields from activity details based on `requires_X?` methods

- CHANGELOG.md
- app/policies/activity_policy.rb
- spec/policies/activity_policy_spec.rb
Previously redacting activities from IATI was only allowed to be done by BEIS users at Levels C/D. The client has indicated that it would also be useful to be able to do this at Level B, so this makes that possible
> (2706) Allow redacting programmes from IATI

- CHANGELOG.md
- app/models/adjustment.rb
- app/models/refund.rb
- app/models/transaction.rb
- db/data/20221108103513_backfill_missing_currencies_and_transaction_types.rb
- spec/models/actual_spec.rb
Sets default currency on all classes that inherit from `Transaction` (specifically to set this on `Actual`s).
Previously, this was only done for `Adjustment`s and `Refund`s, but `Actuals` are also a type of `Transaction` and are exported in IATI XML.
Because `Actual`s didn't have a default value for `currency`, this meant it was outputting XML tags with an empty string value e.g.
```
<transaction>
<transaction-type code="3"/>
<value currency="" value-date="2022-03-31">1000</value>
```
I'm not sure why the default value wasn't added for Actuals [here](https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/1383), it may have been an oversight, but as we export all `Transaction`-inheritors to the XML, I thought it would be safest to put the default values on the …
> [Support] Set default currency & transaction_type on Actuals

- CHANGELOG.md
- spec/helpers/codelist_helper_spec.rb
- vendor/data/codelists/BEIS/programme_status.yml
Change “Activities related to delivery of ODA activities only” to “Activities related to delivery costs” on the Activity Status form step, now that this could refer to ISPF non-ODA activities
> (2700) Remove reference to "ODA activities" in activity status descriptions

- spec/support/activity_form.rb
Removes unnecessary conditional in ActivityForm which was originally needed as we were passing in an argument to `send` to read from an `Activity`. It looks like we forgot to update this after removing that parameter from the method signature.
> Remove unnecessary conditional in ActivityForm

- CHANGELOG.md
- app/controllers/activity_forms_controller.rb
- app/models/activity.rb
- app/services/activity/updater.rb
- app/views/activity_forms/implementing_organisation.html.haml
- config/locales/models/activity.en.yml
- spec/controllers/activity_forms_controller_spec.rb
- spec/factories/activity.rb
- spec/features/users_can_create_a_project_level_activity_spec.rb
- spec/features/users_can_create_a_third_party_project_level_activity_spec.rb
- spec/models/activity_spec.rb
- spec/support/activity_form.rb
- Require ISPF third-party projects (level D) to have at least one implementing organisation set through the new activity journey
> (2456) Require implementing org for ISPF level D activities

- CHANGELOG.md
(Tidies up the changelog, as I felt it was a bit too granular.)
- Update seeds and create data migration for adding ISPF fund entity to the service
- Add ISPF Level B UI user journeys for adding activities
- Add ISPF Level C/D UI user journeys for adding activities
- Inherit `is_oda` from the parent activity - Level C/D ISPF activities will therefore be ODA or non-ODA based on the (grand)parent Level B activity
- Do not allow removing the implementing organisation from a level C or D ISPF activity if it is the only one
- Require ISPF third-party projects (level D) to have at least one implementing organisation set through the new activity journey
- Hide ISPF-facing functionality in the service and exports when the feature flag is enabled
- Allow programmes to be redacted from IATI
- Set …
> Update changelog for release 122

- app/models/activity.rb
- app/views/shared/activities/_activity.html.haml
- app/views/shared/activities/_activity_summary.html.haml
- config/locales/models/activity.en.yml
- db/migrate/20221114173210_add_linked_activity_to_activities.rb
- db/schema.rb
- spec/models/activity_spec.rb
- spec/views/shared/activities/activity_spec.rb
- Adds back-end activity linking
- Defines what programmes are linkable to a given programme (current definition: same level, same PO, opposite ODA type)
- Visualising of existing links
> (2686) Part 1: Link ODA and non-ODA ISPF programmes

- app/assets/stylesheets/partials/_autocomplete.scss
- app/controllers/activity_forms_controller.rb
- app/javascript/packs/application.js
- app/javascript/src/accessible-autocomplete.js
- app/models/activity.rb
- app/presenters/activity_presenter.rb
- app/services/activity/updater.rb
- app/views/activity_forms/linked_activity.html.haml
- app/views/shared/activities/_activity.html.haml
- app/views/shared/activities/_activity_summary.html.haml
- config/locales/models/activity.en.yml
- spec/controllers/activity_forms_controller_spec.rb
- spec/features/beis_users_can_create_a_programme_level_activity_spec.rb
- spec/models/activity_spec.rb
- spec/support/activity_form.rb
- Enable ISPF programme activities (level B) to be linked through the UI
- Only programmes that are not already linked are selectable for linking
> (2686) Part 2: Linking programmes through the UI

- CHANGELOG.md
- app/views/level_b/activities/uploads/new.html.haml
- spec/features/beis_users_can_upload_level_b_activities_spec.rb
- Hide the ISPF templates for level B bulk uploads when the ISPF feature flag is enabled.
I considered renaming the non-ISPF templates when the feature flag is hiding ISPF, but decided against it. It's not technically wrong, even if it might seem odd to name the template when there is no other template to distinguish it from.
> (2719) Hide ISPF level B templates with feature flag

- CHANGELOG.md
- app/presenters/report_presenter.rb
- app/views/activities/uploads/new.html.haml
- config/activity_csv_columns.yml
- spec/controllers/activities/uploads_controller_spec.rb
- spec/features/beis_users_can_upload_level_b_activities_spec.rb
- spec/features/users_can_upload_activities_spec.rb
- spec/fixtures/csv/valid_ispf_non_oda_activities_upload.csv
- spec/presenters/organisation_presenter_spec.rb
- spec/presenters/report_presenter_spec.rb
- spec/services/activity/import_spec.rb
This adds level C/D ISPF non-ODA bulk upload functionality
> (2646) Add ISPF non-ODA level C/D bulk upload

- app/controllers/activity_forms_controller.rb
- app/models/activity.rb
- app/policies/activity_policy.rb
- app/views/shared/activities/_activity.html.haml
- app/views/shared/activities/_activity_summary.html.haml
- config/locales/models/activity.en.yml
- spec/controllers/activity_forms_controller_spec.rb
- spec/features/users_can_create_a_project_level_activity_spec.rb
- spec/models/activity_spec.rb
- spec/policies/activity_policy_spec.rb
- spec/support/activity_form.rb
- spec/views/shared/activities/activity_spec.rb
- Projects that are children of linked programmes can be linked
- Programmes with linked children cannot have their linked activity edited
> (2686) Part 3: Enable linking projects (level C activities)

- app/controllers/activity_forms_controller.rb
- app/models/activity.rb
- app/policies/activity_policy.rb
- spec/controllers/activity_forms_controller_spec.rb
- spec/features/users_can_create_a_third_party_project_level_activity_spec.rb
- spec/models/activity_spec.rb
- spec/policies/activity_policy_spec.rb
- spec/support/activity_form.rb
- spec/views/shared/activities/activity_spec.rb
- Enable linking third-party projects (AKA level C activities)
> (2686) Part 4: enable level D activity linking

- app/views/shared/activities/_activity_summary.html.haml
Fixes activity summary table layout issue
> (2686) Part 4b: fix summary table

- CHANGELOG.md
- app/services/find_programme_activities.rb
- app/services/find_project_activities.rb
- app/services/find_third_party_project_activities.rb
- spec/services/find_programme_activities_spec.rb
- spec/services/find_project_activities_spec.rb
- spec/services/find_third_party_project_activities_spec.rb
This filters out non-ODA activities from IATI exports
> (2707) Exclude non ODA from IATI exports

- CHANGELOG.md
- app/assets/stylesheets/partials/_autocomplete.scss
- app/controllers/activity_forms_controller.rb
- app/javascript/packs/application.js
- app/javascript/src/accessible-autocomplete.js
- app/models/activity.rb
- app/policies/activity_policy.rb
- app/presenters/activity_presenter.rb
- app/services/activity/updater.rb
- app/views/activity_forms/linked_activity.html.haml
- app/views/shared/activities/_activity.html.haml
- app/views/shared/activities/_activity_summary.html.haml
- config/locales/models/activity.en.yml
- db/migrate/20221114173210_add_linked_activity_to_activities.rb
- db/schema.rb
- spec/controllers/activity_forms_controller_spec.rb
- spec/features/beis_users_can_create_a_programme_level_activity_spec.rb
- spec/features/users_can_create_a_project_level_activity_spec.rb
- spec/features/users_can_create_a_third_party_project_level_activity_spec.rb
- spec/models/activity_spec.rb
- spec/policies/activity_policy_spec.rb
- spec/support/activity_form.rb
- spec/views/shared/activities/activity_spec.rb
- Enable activity linking for ISPF activities - manually via the user interface
> (2686) Enable linking ISPF ODA with non-ODA activities via the UI

- CHANGELOG.md
- app/models/activity.rb
- config/locales/models/activity.en.yml
- spec/helpers/codelist_helper_spec.rb
- spec/models/activity_spec.rb
- spec/services/activity/import_level_b_spec.rb
- vendor/data/codelists/BEIS/ispf_partner_countries.yml
- Allow users to designate an ISPF activity as having no ISPF partner countries
> (2733) Add the "None" option to the ISPF partner countries selection

- CHANGELOG.md
- Filter non-ODA activities from IATI exports
- Enable activity linking for ISPF activities
- ISPF activities can have multiple ISPF themes
- ISPF activities can be tagged via the UI - tags can only be chosen from a BEIS-defined codelist
- Allow users to designate an ISPF activity as having no ISPF partner countries
> Release 124

- CHANGELOG.md
- app/views/shared/activities/_activity.html.haml
- spec/views/shared/activities/activity_spec.rb
- Show ODA / Non-ODA on level C and D activities' details pages
> (2738) Display ODA or Non-ODA for level C and D

- CHANGELOG.md
- app/views/shared/activities/_activity.html.haml
- Fix call to action link text for Benefitting countries to correctly change from Add to Edit when applicable
> (2741) Fix call to action text for Benefitting countries

- CHANGELOG.md
- Add report CSV download for ISPF activities
- Show ODA / Non-ODA on level C and D activities' details pages
- Fix call to action link text for Benefitting countries to correctly change from Add to Edit when applicable
- Reject ODA uploads via non-ODA form
- Tags for ISPF activities can be added via bulk uploads
- Add tags to spending breakdown and quarterly report CSV exports
> Release 125

- CHANGELOG.md
- app/models/activity.rb
- app/services/activity/import.rb
- config/locales/models/activity.en.yml
- spec/services/activity/import_spec.rb
- Show an error message if trying to upload a level D ISPF activity without an implementing organisation
Known limitations: this will not catch the attempt to *update* an existing activity and removing all the implementing organisations.
> (2745) Show an error if the implem orgs are missing when uploading a level D ISPF

- CHANGELOG.md
- app/controllers/exports/organisations_controller.rb
- app/models/activity.rb
- app/views/exports/organisations/show.xml.haml
- spec/controllers/exports/organisations_controller_spec.rb
- spec/models/activity_spec.rb
- 2747: fixes the transactions reported in level B IATI exports so that they reflect a quarterly sum of actuals minus adjustments and refunds (not just actuals)
- 2706: fixes redaction of programmes from IATI exports, adding a scope query that was missed from #1870
Debugged and checked using the example from the ticket: the activity with RODA ID `NF-BRNIF`. The figures are now in line with the report CSV, which is the same as the spending breakdown except for FQ3 2021-2022
> (2747) Fix level B IATI export figures and inclusion

- CHANGELOG.md
- Show an error message if trying to upload a level D ISPF activity without an implementing organisation
- Remove legacy report CSV generator
- Switch to using JSbundling and CSSbundling instead of now-deprecated Webpacker for our assets
- Fix exclusion from IATI of redacted programmes - an earlier change allowed programmes to be flagged for exclusion, but missed some code required for actually excluding them
- Update programme-level IATI exports to provide a quarterly summary of all transactions combined (actuals, adjustments and refunds), not just actuals
> Release 126

- app/presenters/report_presenter.rb
- spec/presenters/report_presenter_spec.rb
Removes unused report filename generation method.  
This was used for generating the filename for the legacy CSV, which was removed in #5bf495 (#1948)
I originally thought it would make sense to use the `ReportPresenter`'s method here, rather than the having the `Export:Report` class  have its own report generation method, but the other Export classes `Budget` and `ExternalIncome` have their own filename generation classes so it made sense to keep consistency across the three Export classes here.
> (2764) Remove unused report filename generation method

- CHANGELOG.md
- app/models/activity.rb
- app/views/exports/organisations/show.xml.haml
- spec/features/users_can_view_an_organisation_as_xml_spec.rb
- spec/models/activity_spec.rb
4f17df3 updated level B IATI exports to account for adjustments and refunds. This brings levels C and D in line. The only remaining difference between the level B and levels C and D is that at level B it included all descendents' transactions
> (2766) Reflect adjustments/refunds in level C/D IATI export

- app/views/reports_state/submit/confirm.html.haml
Adds `gtm-confirm-report-submission` ID to the PO's submit button for a report.
We'll pick this up in Google Tag Manager to allow us to capture metrics around how long it takes Partner Organisations to submit a report, to give us an understanding of any pain points we might be able to improve etc.
> Add ID for PO report submission

- app/views/shared/activities/tree_view/_table_tabbed.html.haml
- config/locales/models/activity.en.yml
- spec/features/users_can_view_activities_spec.rb
The paths `/organisations/:organisation_id/activities` and `/activities?organisation_id=:organisation_id` are both served by the `activities#index` controller action and pass in the same params. For Google Analytics, it's better for such shows to use the same path. This updates the single use of the latter path to the former
It also updates the small number of specs using its path helper, and moves the link's text into a translation
> (2779) Update links to organisation activities path

- CHANGELOG.md
- app/services/activity/updater.rb
- doc/activity-identifiers.md
- spec/controllers/activity_forms_controller_spec.rb
- Prefix the RODA identifiers of all non-ODA activities with "NODA-"
> (2736) Prefix all non-ODA identifiers with “NODA”

- db/migrate/20230125115632_remove_ispf_partner_countries_from_activities.rb
- db/schema.rb
This is superseded by `ispf_oda_partner_countries` and `ispf_non_oda_partner_countries`, to which all staging and training data have already been migrated
> (2784) Remove `ispf_partner_countries` column

- app/services/activity/import.rb
- config/locales/models/activity.en.yml
When there was an error with `implementing_org_participations` when importing activities, the column would be represented in snake case. This decorates the error so that it says "Implementing organisation names" instead
We may want to improve the error message at a later time - it currently says "Implementing org participations is invalid" (a default attribute error), which may be confusing to users
> (2743) Decorate activity importer implementing organisation error

- CHANGELOG.md
- app/controllers/reports_controller.rb
- app/controllers/reports_state_controller.rb
- app/helpers/report_helper.rb
- app/jobs/report_export_uploader_job.rb
- app/jobs/spending_breakdown_job.rb
- app/presenters/report_presenter.rb
- app/services/export/s3_downloader.rb
- app/services/export/s3_uploader.rb
- app/services/export/s3_uploader_config.rb
- app/views/reports/_download.haml
- app/views/reports/_summary.html.haml
- config/locales/default.en.yml
- config/locales/models/report.en.yml
- config/routes.rb
- db/migrate/20230116171600_add_export_filename_to_report.rb
- db/migrate/20230116173500_add_approved_at_to_reports.rb
- db/schema.rb
- spec/features/users_can_approve_a_report_spec.rb
- spec/features/users_can_view_reports_spec.rb
- spec/helpers/report_helper_spec.rb
- spec/jobs/report_export_uploader_job_spec.rb
- spec/jobs/spending_breakdown_job_spec.rb
- spec/presenters/report_presenter_spec.rb
- spec/services/export/s3_downloader_spec.rb
- spec/services/export/s3_uploader_config_spec.rb
- spec/services/export/s3_uploader_spec.rb
- terraform/app.tf
Uploads reports to a new private bucket on S3 when they're approved by the BEIS team, storing an `approved_at` datetime on the Report to display the date at which this happened to users.
We're doing this as reports have always been created with the most up-to-date data in the service at the point of clicking the "download" button. This meant the data for a report that was previously thought to approved (and closed for further editing) could be different if any future transactions were added that referred to that quarter, essentially changing historical data.
For any reports that haven't been approved yet, we pull them together with live data at the point of clicking the button, like we used to do.
> (2709) Upload reports to private S3 bucket on approval

- CHANGELOG.md
- app/controllers/activity_comments_controller.rb
- app/views/activity_comments/edit.html.haml
- app/views/activity_comments/new.html.haml
- config/locales/models/comment.en.yml
- spec/controllers/activity_comments_controller_spec.rb
- spec/features/users_can_create_a_comment_spec.rb
- spec/features/users_can_edit_a_comment_spec.rb
Previously:
- If when editing a comment, you submit the form with no body, an error would show up due to a missing instance variable
- Tests were missing for this in both the `update` and `create` controller actions (but the latter didn't cause an error)
- When an activity had no title, the heading when adding/editing comments was confusing: "Add a comment about"/"Edit comment about"
- Some comment tests were checking for the absence of the wrong translation
- If a create/update failed, the breadcrumbs would be lost when re-rendering the form
This fixes all of the above
> (2782) Fix invalid comment update and other edge cases

- CHANGELOG.md
- app/jobs/report_export_uploader_job.rb
- app/mailers/report_mailer.rb
- app/views/report_mailer/_approved_service_owner.text.erb
- app/views/report_mailer/upload_failed.text.erb
- config/locales/models/report.en.yml
- spec/jobs/report_export_uploader_job_spec.rb
- spec/mailers/report_mailer_spec.rb
- Report approved emails sent to BEIS users include a reminder that the report is going to be uploaded
- Send notification email to report approver if report upload fails
> (2773) Report uploading emails

- lib/tasks/reports.rake
This adds:
- A script for uploading a single report to S3 - useful if a single one fails to upload for some reason and can be added as a support ticket.
- A script to upload all approved but not yet uploaded reports to S3 for all organisations.
- Run this on staging and confirm it works as expected, then production!
> (2758) Add scripts for uploading approved reports to S3

- CHANGELOG.md
- app/controllers/exports_controller.rb
- app/jobs/spending_breakdown_job.rb
- app/mailers/download_link_mailer.rb
- app/models/activity.rb
- app/views/download_link_mailer/send_link.text.erb
- app/views/exports/index.html.haml
- config/routes.rb
- db/migrate/20230118131413_add_spending_breakdown_filename_to_activities.rb
- db/schema.rb
- spec/controllers/exports_controller_spec.rb
- spec/features/beis_users_can_download_exports_spec.rb
- spec/features/users_can_export_spending_breakdown_spec.rb
- spec/jobs/report_export_uploader_job_spec.rb
- spec/jobs/spending_breakdown_job_spec.rb
- spec/mailers/download_link_mailer_spec.rb
- spec/mailers/previews/download_link_mailer_preview.rb
- The latest generated spending breakdown CSVs can be downloaded from the Exports page
- Spending breakdown email notification has a link to the Exports page instead of a direct download link
- Spending breakdown exports use a private S3 bucket
> (2777) Spending breakdown download

- CHANGELOG.md
- app/models/export/activity_actuals_columns.rb
- spec/models/export/activity_actuals_columns_spec.rb
A while back, we added protection to `rows_for_first_financial_quarter` to prevent it trying to convert `nil` values to BigDecimals when there weren't any found.
Although [the PR](https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/1482) in which that was added suggests that there should always be a value for the last row of actuals, on Staging, at least, this doesn't appear to be the case.
Although the above may be due to slightly wonky, possibly invalid data on Staging, this error caused a report (with ID
b45c5b36-e502-4406-ac66-8a51321a177c) to fail being uploaded to S3 (particularly, when calling `Export::Report#rows`. We'd like to make sure this doesn't happen on Production.
> (2786) Fix `rows_for_last_financial_quarter`

- CHANGELOG.md
- app/controllers/reports_state_controller.rb
- app/mailers/report_mailer.rb
- app/models/report.rb
- app/policies/report_policy.rb
- app/services/report/send_state_change_emails.rb
- app/views/report_mailer/qa_completed.text.erb
- app/views/reports/_actions.html.haml
- app/views/reports_state/mark_qa_completed/complete.html.haml
- app/views/reports_state/mark_qa_completed/confirm.html.haml
- config/locales/models/report.en.yml
- spec/features/users_can_approve_a_report_spec.rb
- spec/features/users_can_mark_a_report_as_awaiting_changes_spec.rb
- spec/features/users_can_mark_a_report_as_qa_completed_spec.rb
- spec/features/users_can_mark_a_report_in_review_spec.rb
- spec/mailers/report_mailer_spec.rb
- spec/policies/report_policy_spec.rb
- spec/services/report/send_state_change_emails_spec.rb
Adds a QA completed step between in review and approved. When in review, users can now either request changes or mark the report as QA completed. When QA completed, they can request changes or approve the report
> (2550) Add QA completed report state

- db/data/20230203144832_add_chile_as_a_benefitting_country_to_old_activities.rb
We have received a support query regarding two old activities that should have Chile as a benefitting country, but don't.
Chile is no longer available in the UI as it is no longer an eligible benefitting country, however, it was at the time the activities were active.
- Add migration to add Chile as a benefitting country to old activities
We will need to run `rails runner db/data/20230203144832_add_chile_as_a_benefitting_country_to_old_activities.rb` after deployment.
> Add migration to add Chile as a benefitting country to old activities

- script/training_db_sync.rb
When running the training database sync script, the password reset method was failing silently in the `force_password_reset_for_users` method
In the process of working on dc87872 (#1803), we provided a command to be run remotely using `-c` and single quotes. In the end, the commit used double quotes, but we've now found the single quotes are necessary to make this script run successfully on certain machines
For future reference, we were able to debug this by running the script on the server: we attempted to run the script normally, but with the method call that removes temp files (and all other irrelevant methods) commented out, then ssh-ed onto the server and ran it manually
> Use single quotes in password reset script

- lib/tasks/reports.rake
This tweaks the approved Report-uploading Rake task to ignore reports with a `nil` value for `financial_year` or `financial_quarter` as these fail validations when we try to call `#rows` on them when creating the CSV file. 
We don't actually offer a CSV file for these kinds of reports, which were created from historical data from before RODA existed.
I've tested this locally with 2 organisations after fetching prod data, and all seems to be working as expected.
Run this on staging
> (2800) Don't upload reports with no financial year or financial quarter

- CHANGELOG.md
- config/routes.rb
Adds Sidekiq UI
This will allow us to view the result of scheduled jobs in the service more easily. This is particularly useful now we're about to run the report uploading script
This is accessible at `/sidekiq` but only for logged in "service owner" users.
> (2813) Add Sidekiq web UI

- app/views/reports_state/approve/complete.html.haml
As requested by BEIS, this removes a sentence that's fairly redundant, given who approved reports within the organisation
> (2815) Remove sentence from report approved confirmation

- CHANGELOG.md
- Upload the report CSV to S3 when the report is approved
- For approved reports, provide download of stored report CSV file instead of generating it from live data
- Fix/improve various commenting edge cases:
- Show useful error when trying to remove the body from an existing comment
- Show the RODA identifier when adding/editing a comment on an activity without a title
- Include breadcrumbs when the form is re-rendered after failing to create/update a comment
- Report approved emails sent to BEIS users include a reminder that the report is going to be uploaded
- Send a notification email to the report approver if the report upload fails
- The latest generated spending breakdown CSVs can be downloaded from the Exports page
- Spending breakdown email notification has a link to the Exports …
> Release 129

- .env.test
- app/jobs/report_export_uploader_job.rb
- app/jobs/spending_breakdown_job.rb
- config/environments/test.rb
- spec/features/users_can_approve_a_report_spec.rb
- spec/features/users_can_export_spending_breakdown_spec.rb
- spec/jobs/report_export_uploader_job_spec.rb
- spec/jobs/spending_breakdown_job_spec.rb
These are a couple of spots we missed when upgrading to Ruby 3, as the language has now changed the way it handles keyword arguments.
I've updated the feature tests here to use less mocking so we can check the result of the methods that are actually called, so that this will hopefully be caught in future. I've mocked responses to S3 in the test environment here too.
> (2820) Fix incorrectly-passed CSV arguments

- CHANGELOG.md
- app/views/shared/reports/_grouped_table.html.haml
- app/views/shared/reports/_table.html.haml
- app/views/shared/reports/_table_header.html.haml
- spec/features/users_can_view_reports_spec.rb
For BEIS users, the organisation reports table included a column heading of "Organisation", but there was no data for this column, meaning all data were offset one column from their headings
This makes it so that the organisation appears only for BEIS users at `/reports`, where the reports table covers multiple organisations. In all other cases - i.e. for PO users at `/reports` and for both PO and BEIS users at the organisation reports path - we leave the organisation out
---
The feature specs for viewing reports only seem to touch `/reports`, not `/organisations/:organisation_id/reports`, and don't appear to test column headings. Is it worth adding some tests for this, or is it too much detail for feature tests?
> (2807) Fix organisation reports table for BEIS users

- doc/deleting-things-from-production.md
Tiny change - Fix documentation query
Pluck doesn't work on single records, we can access `id` directly instead.
> Fix documentation query

- CHANGELOG.md
- app/services/activity/roda_identifier_generator.rb
- app/services/activity_defaults.rb
- spec/factories/activity.rb
- spec/services/activity/import_spec.rb
- spec/services/activity/roda_identifier_generator_spec.rb
The changes in 46e5f29 meant that non-ODA activities added via the UI are prefixed "NODA-". This change was implemented in the `ActivityUpdater` service, which is not touched when creating activities via the importer. Projects and third-party projects created via the importer would be prefixed "NODA-" through including their parent's identifier in their own, however new level B imported activities would not
This rectifies that by amending the RODA identifier generator to include "NODA-" when passed `is_non_oda: false` via
`ActivityDefaults#generate_roda_identifier` (or the activity factory)
> (2809) Prefix non-ODA programmes with NODA in import

- CHANGELOG.md
- app/models/activity.rb
- app/views/shared/activities/_activity.html.haml
- spec/models/activity_spec.rb
This prevents the activity details tab from including a link to edit the `is_oda` field, while retaining the link to add this for ISPF activities where the field is `nil`
The card also mentioned preventing this via bulk upload, but we don't have an `is_oda` column in the bulk upload template - this is handled by separate templates uploaded via separate forms. We have measures in place to ensure we don't do anything when there's a mismatch between the ODA type of the template and the form, but in any case the importer's activity updater doesn't modify `is_oda`
> (2740) Prevent editing `is_oda` via UI

- app/controllers/reports_controller.rb
In our base controller, we use Pundit’s mechanism for alerting us if we forget to authorize any controller actions. Collective controller actions such as index are checked for the use of `policy_scope`.
The reports index doesn’t call the policy scope, so we see this error in our server logs:
`Pundit::PolicyScopingNotPerformedError (ReportsController)`
We can skip the policy scope check, because permissions are checked against the user’s organisation.
N/A
> Skip Pundit’s policy scope verification on index

- CHANGELOG.md
- app/services/forecast/import.rb
- app/services/forecast_history.rb
- spec/services/forecast/import_spec.rb
- spec/services/forecast_history_spec.rb
- Fix the display of successfully uploaded forecasts for the cases when:
- the original forecast is deleted
- the imported values were already in the report
> (2787) (2819) Successfully uploaded summary table fixes

- CHANGELOG.md
- app/services/activity_defaults.rb
- spec/services/activity_defaults_spec.rb
Currently, we generate an IATI identifier for all activities.
However, we have had some feedback that this is confusing, and the IATI
identifier should be absent for non-ODA activities in the CSV download.
Only generate IATI identifiers for ODA activities. Add some coverage for the
`is_oda` and `transparency_identifier` attributes of the activity defaults.
We don't have any ISPF activities in production, so there aren't any existing
identifiers that need to be hidden.
> Only generate IATI identifiers for ODA activities

- CHANGELOG.md
- app/controllers/activity_forms_controller.rb
- app/presenters/activity_presenter.rb
- app/views/activity_forms/purpose.html.haml
- config/locales/models/activity.en.yml
- spec/presenters/activity_presenter_spec.rb
The purpose step of the activity form includes a note on both the title and description fields about truncation of data when published to Statistics in International Development. Non-ODA activities are not published to this, so the note is irrelevant and confusing in that context. This therefore hides the note when accessing the step on a non-ODA activity
> (2801) Hide SID truncation note on non-ODA activities

- CHANGELOG.md
- app/views/shared/activities/_activity.html.haml
- spec/views/shared/activities/activity_spec.rb
Non-ODA activities are not reported to IATI, therefore the IATI identifier and "Include in IATI export?" fields are irrelevant and confusing when looking at the activity details tab for such activities. This removes them in this context
> (2802) Hide fields irrelevant to non-ODA activities

- CHANGELOG.md
- script/training_db_sync.rb
**Note:** we weren't able to reproduce the error after playing around with the training DB sync script, so we've reverted this to draft for now. We can revisit it if and when the login issues reapper
Hopefully a fix for the login issues after running the training DB sync
Shall we try testing this before merging, if the timing (for a training data refresh) is okay with BEIS?
> (2746) Clear sessions during training DB sync

- CHANGELOG.md
- app/models/activity.rb
- app/presenters/activity_csv_presenter.rb
- app/presenters/activity_presenter.rb
- app/services/activity/updater.rb
- app/services/activity_defaults.rb
- db/migrate/20230227114720_make_activity_oda_eligibility_nullable.rb
- db/schema.rb
- spec/features/beis_users_can_create_a_programme_level_activity_spec.rb
- spec/features/users_can_create_a_project_level_activity_spec.rb
- spec/features/users_can_create_a_third_party_project_level_activity_spec.rb
- spec/models/activity_spec.rb
- spec/presenters/activity_csv_presenter_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/services/activity_defaults_spec.rb
> I did a lot of thinking about where to place the nullifying of the attributes. I ended up putting them in a before_save > callback. Happy to hear any better ideas. My thinking:
> 1. They can't go in the ActivityDefaults class because that is only applied to new activities. We don't want to apply this class to existing activities because it has some new activity only logic.
> 2. We could create a new NonOdaDefaults class, but then we have to be careful to apply it everywhere + it won't actually do much, it will only set some attributes to nil.
> 3. Even though the Activity class is large, I think there is stuff that is less-related than this that could be moved into another class potentially.
> 4. I've nullified the non-persisted defaults here, so it's nice that they are in the same …
> (2826) Make ODA-only fields blank for non-ODA activities

- CHANGELOG.md
- app/policies/activity_policy.rb
- app/views/shared/activities/_activity.html.haml
- app/views/shared/activities/_activity_summary.html.haml
- spec/features/beis_users_can_create_a_programme_level_activity_spec.rb
- spec/features/beis_users_can_upload_level_b_activities_spec.rb
- spec/features/users_can_create_a_project_level_activity_spec.rb
- spec/features/users_can_create_a_third_party_project_level_activity_spec.rb
- spec/features/users_can_upload_activities_spec.rb
- spec/policies/activity_policy_spec.rb
- spec/support/activity_form.rb
- spec/views/shared/activities/activity_spec.rb
We want to disable the linked activities feature for now, to be re-enabled in
future. We have had some feedback that linking is confusing to POs while
there's no ODA funds being spent.
This hides the linked activities feature in the wizard unless the feature flag
is active.
We want to disable the linked activities feature for now, to be re-enabled in
future. We have had some feedback that linking is confusing to POs while
there's no ODA funds being spent.
This hides the linked activities row on the describe page and summary unless
the feature flag is active.
> (2805) Add global feature flag for linked activities

- CHANGELOG.md
- app/controllers/activity_forms_controller.rb
- app/views/activity_forms/purpose.html.haml
Currently, when the purpose step is invalid, the view is re-rendered without
an instance of ActivityPresenter, leading to an error.
This moves the instantiation of the presenter to the view so that it is
available for both steps.
> (2844) Fix missing presenter when step is invalid

- CHANGELOG.md
- db/data/20230220095332_set_transaction_date_on_commitments.rb
- db/migrate/20230220094559_add_transaction_date_to_commitments.rb
- db/schema.rb
*Part 1 of 2*: We'll be running the migration script before merging the second PR #2030 which will update the codebase to reference the new field
This adds a `transaction_date` field to commitments that will be used instead of the Financial Year and Quarter, as well as a script that will populate this value from the current Financial Year and Quarter for existing Commitments.
New activities will, in future, use the planned start date or actual start date for their transaction date.
> [2831a] Add transaction date to commitments

- CHANGELOG.md
- Remove heading for unpopulated organisation column in organisation reports table for BEIS users
- Prevent child ODA activities being created on non-ODA parents and vice-versa via the bulk upload
- Prefix imported non-ODA programmes "NODA-"
- Prevent editing ODA type via the UI
- Fix the display of successfully uploaded forecasts for the cases when:
- the original forecast is deleted
- the imported values were already in the report
- Omit legacy fields for ISPF activities on the "details" page
- Remove legacy fields from ISPF reports
- Only generate IATI identifiers for ODA activities
- Remove reference to truncating data published to Statistics in International Development for non-ODA activities
- Hide IATI identifier and "Include in IATI XML export?" fields on activity details tab for …
> Release 131

- CHANGELOG.md
- app/models/commitment.rb
- app/presenters/commitment_presenter.rb
- app/services/commitment/import.rb
- app/views/shared/commitment/_table.html.haml
- app/views/shared/xml/_commitment.xml.haml
- db/migrate/20230301135404_remove_financial_year_and_financial_quarter_from_commitments.rb
- db/schema.rb
- doc/import-commitments.md
- spec/factories/commitment.rb
- spec/features/users_can_view_commitment_values_spec.rb
- spec/fixtures/csv/commitments/invalid.csv
- spec/fixtures/csv/commitments/valid.csv
- spec/models/commitment_spec.rb
- spec/presenters/commitment_presenter_spec.rb
- spec/services/commitment/import_spec.rb
- spec/views/shared/xml/commitment_spec.rb
*Part 2 of 2*: Updates references to Financial Year & Financial Quarter to use new `transaction_date` field once it's been populated by the script introduced in #2047.
This PR refactors a few aspects of the Commitment model and the script used to import them:
- Updates the Commitment importer so no date fields are required. The `transaction_date` will be inferred from an Activity's `planned_start_date` if it exists, then the `actual_start_date`. If neither is present for any reason (as appears to be the case with some of our data despite validations), we fall back on the date the activity was created.
- Uses the new `transaction_date` field to display the Commitment figure on an Activity's financial details tab (see screenshot)
- Removes `financial_year` and `financial_quarter` from …
> [2831b] Refactor Commitment model and importer

- CHANGELOG.md
- app/controllers/activity_forms_controller.rb
- app/helpers/commitment_helper.rb
- app/models/activity.rb
- app/models/commitment.rb
- app/presenters/activity_presenter.rb
- app/services/activity/updater.rb
- app/services/commitment/import.rb
- app/views/activity_forms/commitment.html.haml
- app/views/shared/activities/_activity.html.haml
- config/locales/default.en.yml
- config/locales/models/activity.en.yml
- spec/controllers/activity_forms_controller_spec.rb
- spec/factories/activity.rb
- spec/features/beis_users_can_create_a_programme_level_activity_spec.rb
- spec/features/users_can_create_a_project_level_activity_spec.rb
- spec/features/users_can_create_a_third_party_project_level_activity_spec.rb
- spec/helpers/commitment_helper_spec.rb
- spec/presenters/activity_presenter_spec.rb
- spec/services/activity/updater_spec.rb
- spec/services/commitment/import_spec.rb
- spec/support/activity_form.rb
**Note: currently based off unmerged branch in #2030 so for the purposes of reviewing this, start at [90c8352](https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/2040/commits/90c8352e2b5d561c2124b821d97245c87d64c9a8)**
Adds new Original Commitment Figure page to the new activity journey. This is optional at levels B and C but required at level D.
> [2827] Collect original commitment figure in new Activity form

- CHANGELOG.md
- app/views/users/_form.html.haml
- spec/features/beis_users_can_invite_new_users_spec.rb
Remove the mobile number reset field from the new user form
> (2792) Remove MFA from new user form

- CHANGELOG.md
- app/views/organisations/_table.html.haml
The `ul` element has the role `tablist`. The specification says that it must “own” `tab` elements.[1] We’ve chosen to give the links inside `li` the role `tab`, rather than give `li` elements `tab` role.
Even though an “owned element” is defined as “any DOM descendant of the element”, Axe tools raises a critical issue: “Element has children which are not allowed” for the `ul` with role `tablist`, and “Required ARIA parent role not present: tablist“ for the `a` elements with role `tab`, suggesting that it was expecting direct child/parent elements rather than going through the intermediate `li` element.
Elsewhere we fixed this by giving the `li` elements presentational roles
This also fixes 4 serious issues for the `li` elements: "List item does not have a \<ul\>, \<ol\> parent element …
> List items in tab list links are presentational

- CHANGELOG.md
- app/views/activities/comments.html.haml
- app/views/activities/historical_events.html.haml
- app/views/activities/uploads/new.html.haml
- app/views/adjustments/show.html.haml
- app/views/devise/sessions/new.html.haml
- app/views/devise/sessions/otp_attempt.html.haml
- app/views/level_b/activities/uploads/new.html.haml
- app/views/level_b/activities/uploads/update.html.haml
- app/views/level_b/budgets/uploads/create.html.haml
- app/views/level_b/budgets/uploads/new.html.haml
- app/views/pages/cookie_statement.html.haml
- app/views/public/visitors/index.html.haml
- app/views/shared/activities/_activity.html.haml
- app/views/shared/activities/_activity_summary.html.haml
- app/views/shared/activities/uploads/_activities_table.html.haml
- app/views/shared/adjustments/_table.html.haml
- app/views/shared/reports/_table_budgets.html.haml
- app/views/shared/transfers/_index.html.haml
- app/views/users/_form.html.haml
- config/locales/models/report.en.yml
Add `govuk-link` class to:
- Links in the sign-in journey
- "Back to home" links on level B activities and budgets upload pages
- "View activity" link on report pages
- "Back to report" link on activities upload page
- Edit budget link within reports
- Forecasts upload guidance
- Link to report in activity comments view and change history view
- Links to the activity and the report in the adjustments view
- Link to edit a transfer
- Cookie statement page
- New organisation link in user form
> (2822) Add govuk-link class where missing

- app/controllers/activities/uploads_controller.rb
- app/controllers/level_b/activities/uploads_controller.rb
- app/views/shared/activities/uploads/_upload_form.html.haml
- spec/controllers/activities/uploads_controller_spec.rb
- spec/controllers/level_b/activities/uploads_controller_spec.rb
- spec/features/beis_users_can_upload_level_b_activities_spec.rb
- spec/features/users_can_upload_activities_spec.rb
This adds the type to the IDs for the `input` and `div.govuk-hint` elements, the `for` attribute of the `label` element, and the `aria-describedby` attribute of the `input` element, in order to address critical accessibility issues highlighted by axe DevTools
Replaces #2059
> (2851) Make activity upload form IDs unique

- app/views/shared/reports/_table_row.html.haml
- spec/features/users_can_view_reports_spec.rb
For BEIS users, /reports has two tabs. On each tab, there is a heading column for organisation names. The `th` elements use the organisation's ID as their ID, but this is duplicated for each tab, which is an accessibility issue. This adds the tab heading/report status grouping ("current"/"approved") to the ID in order to create unique IDs
> (2852) Make organisation IDs unique at `/reports`

- CHANGELOG.md
- app/models/iati/xml_download.rb
- spec/features/beis_users_can_download_exports_spec.rb
- spec/models/iati/xml_download_spec.rb
The link to download an IATI export for an organisationfund/level combination of activities is shown if any activities exist for that combination. However, when preparing the XML, activities are only included if publishable to IATI (based on an activity's `publish_to_iati` attribute). This means links can be generated for exports that will contain no activities, which is invalid. This makes it so that a link is only shown if publishable activities exist for the given combination
These screenshots are taken from AMS local data, which may be out of sync with production
> (2833) Only show IATI export with publishable activities

- CHANGELOG.md
- app/controllers/concerns/activities/breadcrumbed.rb
In the UI form for adding activities, before the activity has a title, there's a link in the breadcrumbs without any text in it, which makes it unnoticeable to most users and also an accessibility issue
In `Activities::Breadcrumbed` we already have a method for providing fallback text of "Untitled activity" where an activity doesn't have a title, but we weren't using this under particular conditions. This makes it so that we use it in all conditions, which fixes the issue
> (2857) Provide text for untitled activity link

- CHANGELOG.md
- app/controllers/activity_forms_controller.rb
- app/policies/activity_policy.rb
- app/views/shared/activities/_activity.html.haml
- spec/controllers/activity_forms_controller_spec.rb
- spec/features/users_can_edit_an_activity_spec.rb
- spec/policies/activity_policy_spec.rb
- spec/views/shared/activities/activity_spec.rb
We now allow BEIS users to add and edit an original commitment figure at all levels below Fund level.
Partner organisations can only add an original commitment figure at levels C and D (mandatory). Once it's been set, it can no longer be edited - they'll need to ask the BEIS team to do this for them.
> [2839] Allow BEIS users to edit original commitment figure

- app/views/activity_forms/covid19_related.html.haml
- app/views/activity_forms/fund_pillar.html.haml
- app/views/activity_forms/gcrf_challenge_area.html.haml
- app/views/activity_forms/gdi.html.haml
- app/views/activity_forms/oda_eligibility.html.haml
- app/views/activity_forms/programme_status.html.haml
- app/views/activity_forms/sector.html.haml
- app/views/activity_forms/sector_category.html.haml
On various pages that used `f.govuk_collection_radio_buttons`, we were also using `f.hidden_field`, but this is included by default with `f.govuk_collection_radio_buttons`[1]. This led to a redundant hidden field being created with the same ID as the radio button collection, which is an accessibility issue. This removes the duplicate hidden fields from relevant pages, fixing the issue
[1] https://www.rubydoc.info/gems/govuk_design_system_formbuilder/GOVUKDesignSystemFormBuilder
> (2858) Remove duplicate hidden fields on radio collections

- app/services/activity/import.rb
- spec/services/activity/import_spec.rb
Before this, any inclusion of the Commitment in the upload template would cause the bulk upload to fail. We believe all users should be able to at least initially set a Commitment on an existing activity if it doesn't exist so they can upload historical data all in one go.
If there's already a commitment, we render an error message to let users know they'll need to edit this via the user interface.
[Trello card](https://trello.com/c/6oiOPlMW/2871-allow-ocf-to-be-set-when-updating-existing-activities-via-bulk-upload-as-well-as-creating)
> (2871) Allow setting new commitment on existing activity via bulk upload

- CHANGELOG.md
- app/controllers/actuals/uploads_controller.rb
- app/services/actual/import.rb
- app/views/actuals/uploads/new.html.haml
- app/views/actuals/uploads/update.html.haml
- app/views/reports/_actuals_upload.html.haml
- app/views/shared/_warning_text.html.haml
- config/locales/models/actual.en.yml
- spec/features/users_can_upload_actuals_spec.rb
- spec/features/users_can_view_reports_spec.rb
> (2500b) Signpost adding actual comments on their own

- app/controllers/activity_forms_controller.rb
- app/services/activity/updater.rb
- spec/controllers/activity_forms_controller_spec.rb
- spec/services/activity/updater_spec.rb
- Only builds a new Commitment on the Activity when rendering the "edit" page if one has not already been set on the Activity, showing the previous value to be edited.
- Prevents OCF being overwritten as `nil` when failing to save after a validation error by rolling back when `save!` raises an error.
> (2873) Prepopulate OCF when editing & prevent overwriting with `nil` when saving fails

- CHANGELOG.md
- app/views/activities/uploads/new.html.haml
- app/views/activities/uploads/update.html.haml
- app/views/actuals/uploads/new.html.haml
- app/views/actuals/uploads/update.html.haml
- app/views/forecasts/uploads/new.html.haml
- app/views/forecasts/uploads/update.html.haml
- config/locales/models/activity.en.yml
- config/locales/models/actual.en.yml
- config/locales/models/forecast.en.yml
- spec/features/users_can_upload_actuals_spec.rb
- spec/features/users_can_upload_forecasts_spec.rb
- Add "Back to report" links at all stages of the actuals and forecasts upload journeys
> (2865) Consistent "Back to report" navigation in upload to report journeys

- .github/workflows/deploy.yml
- .github/workflows/trigger_rebase.yml
The `set-output` command is deprecated, and causes warnings to be thrown when used. Github plan to fully disable it on 31st May 2023 [1].
The suggested replacement approach is to use the `$GITHUB_OUTPUT` environment file, which is available by default.
(h/t @RobjS for the fix)
[1] https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
N/A
> (2778) Use $GITHUB_OUTPUT instead of set-output command

- CHANGELOG.md
- app/controllers/budgets_controller.rb
- app/views/budgets/edit.html.haml
- app/views/budgets/new.html.haml
- app/views/shared/budgets/_table.html.haml
- config/locales/models/budget.en.yml
- spec/features/beis_users_can_upload_level_b_budgets_spec.rb
- spec/features/users_can_edit_a_budget_spec.rb
> Follows from https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/2056
> Various content/design changes to align the budgets area with the [prototype](https://roda-design-ideas-production.up.railway.app/#sprint-12)
Table headers shouldn't be empty for accessibility reasons.
This adds an "Action" heading to the budget table on the financials tab.
The most recent prototype has shifted the "Type" column to after the
"Revisions" column.
This also uses the translations where they were accidentally missed in the
past.
The prototype has some text showing the current budget on the edit page.
The prototype shows the financial year that the budget is for in the heading.
The prototype shows a £ symbol prefix on the budget amount input.
> (2861) Tidy up budgets

- CHANGELOG.md
- app/controllers/activity_forms_controller.rb
- app/services/activity/import/converter.rb
- app/services/activity/import/creator.rb
- app/services/activity/updater.rb
- config/locales/models/activity.en.yml
- spec/controllers/activity_forms_controller_spec.rb
- spec/features/beis_users_can_upload_level_b_activities_spec.rb
- spec/services/activity/import_spec.rb
- spec/services/activity/updater_spec.rb
This PR refactors a couple of things before making it possible for users to enter commas in the Original Commitment Figure form field:
1. Validation errors are now handled at the `Commitment` level, rather than its parent `Activity` which allow us to validate the Commitment itself _before_ relying on ActiveRecord's `save!` populating errors from the model level. This has required a slight change in the `ActivityFormsController` to catch these.
1. We no longer use the `build_commitment` method to create a new Commitment in the `Updater` class, but create the Commitment in isolation before linking it to an Activity to line up more closely with the approach taken for creating a `Budget`. It didn't feel necessary to extract this logic into its own `*Creator`-type class just yet as we only …
> (2867) Allow users to enter commas when submitting an original commitment figure

- CHANGELOG.md
- app/services/activity/import/updater.rb
- config/locales/models/activity.en.yml
- spec/features/beis_users_can_upload_level_b_activities_spec.rb
- spec/services/activity/import_level_b_spec.rb
- spec/services/activity/import_spec.rb
The bulk upload now presents the user with an error when they try to upload a CSV with a fund activity's RODA identifier in the "RODA ID" column.
This PR also fixes a small bug where the wrong Activity column was being used for an activity that wasn't found.
> (2855) Prevent updating of funds via the bulk upload

- CHANGELOG.md
- app/controllers/activities_controller.rb
- app/helpers/activity_helper.rb
- app/policies/activity_policy.rb
- app/policies/project_policy.rb
- app/views/activities/children.html.haml
- app/views/activities/details.html.haml
- app/views/activities/financials.html.haml
- spec/controllers/activities_controller_spec.rb
- spec/helpers/activity_helper_spec.rb
- spec/policies/activity_policy_spec.rb
- spec/policies/project_policy_spec.rb
- spec/policies/third_party_project_policy_spec.rb
- Ensure non-BEIS users cannot download activities as XML
N/A
> (2880) Ensure user is authorised to download activity XML

- CHANGELOG.md
- app/helpers/form_helper.rb
- app/models/activity.rb
- spec/helpers/form_helper_spec.rb
- spec/models/activity_spec.rb
> Pivoted a couple of times on this. I have another branch where I add validation that matches the exact options `validates :sector_category, presence: true, inclusion: {in: ->(activity) { activity.sector_category_radio_options.map(&:code) }}, on: :sector_category_step` instead of `validates :sector_category, presence: true, inclusion: {in: Codelist.new(type: "sector_category").values_for("code")}, on: :sector_category_step`, but it invalidates 35 Activities and I don't want us to have to deal with that. I think from a security perspective this should be fine? 
The results of a recent pen test raised that various attributes of an Activity
can be set to arbitrary values.
This adds inclusion validation for the attributes.
Validation is kept loose where we use codelists, we only check …
> (2878) Add inclusion validators to Activity attributes

- spec/controllers/activity_comments_controller_spec.rb
- spec/controllers/actuals/history_uploads_controller_spec.rb
- spec/controllers/exports/organisations_controller_spec.rb
- spec/controllers/exports_controller_spec.rb
- spec/controllers/implementing_organisations_controller_spec.rb
- spec/controllers/level_b/activities/uploads_controller_spec.rb
- spec/controllers/pages_controller_spec.rb
- spec/controllers/report_comments_controller_spec.rb
- spec/features/users_can_activate_reports_spec.rb
- spec/features/users_can_approve_a_report_spec.rb
- spec/features/users_can_edit_a_forecast_spec.rb
- spec/features/users_can_export_spending_breakdown_spec.rb
- spec/features/users_can_mark_a_report_in_review_spec.rb
- spec/features/users_can_submit_a_report_spec.rb
- spec/features/users_can_view_reports_spec.rb
- spec/requests/domain_redirect_spec.rb
- spec/requests/errors_spec.rb
- spec/requests/host_urls_are_whitelisted_spec.rb
- spec/support/shared_examples/transfer_controller.rb
Previously, there was a lack of consistent syntax/helper method usage when testing the HTTP status of a controller response or page. This cleans things up by using the `have_http_status` matcher in combination with a status symbol[1]. It also makes the `it` descriptions more consistent when referencing status codes
[1] https://github.com/rails/rails/blob/v4.0.0/guides/source/layouts_and_rendering.md#the-status-option
> Tidy up HTTP status assertions

- CHANGELOG.md
- spec/helpers/codelist_helper_spec.rb
- vendor/data/codelists/BEIS/tags.yml
We have been asked to add an additional ISPF tag for `Previously reported under Newton Fund`.
> (2901) Add ISPF tag for `Previously reported under Newton Fund`

- app/views/budgets/edit.html.haml
- app/views/budgets/revisions.html.haml
- app/views/shared/budgets/_current_budget.html.haml
- spec/features/users_can_edit_a_budget_spec.rb
The revisions page shows the current budget as the most recent revision. However, the prototype also shows the current budget as a standalone element to match the edit page.
> Add the current budget to the revisions page

- CHANGELOG.md
- app/controllers/budgets_controller.rb
- app/views/layouts/_messages.html.haml
- config/locales/models/budget.en.yml
- spec/features/users_can_edit_a_budget_spec.rb
Currently, the success messages use a modified error summary component, with a
green border and green text.
Ideally, we shouldn't be using this component for this purpose, but for now it can be
improved by making the text black instead of green.
The success message when a Budget is updated current shows "Budget successfully
updated".
We want this to be more specific, so the message will now include the financial
year and the value. E.g., "Budget successfully updated. Current budget of FY
2015-2016 is now £7.00"
|Before|After|
|-|-|
|<img width="1169" alt="image" src="https://user-images.githubusercontent.com/47089130/227957406-2a81afe5-9451-416f-a342-68d3f92c6266.png">|<img width="1211" alt="image" src="https://user-images.githubusercontent.com/47089130/227956710-18d28645-9437-4f55-b658-f2 …
> (2905) Budget edit success message

- CHANGELOG.md
- app/controllers/activities_controller.rb
- app/models/activity.rb
- app/policies/activity_policy.rb
- app/views/activities/_deleted_activity_notification_banner.html.haml
- app/views/activities/confirm_destroy.html.haml
- app/views/activities/index.html.haml
- app/views/activities/index_beis.html.haml
- app/views/reports_state/mark_qa_completed/confirm.html.haml
- app/views/reports_state/request_changes/confirm.html.haml
- app/views/reports_state/review/confirm.html.haml
- app/views/shared/activities/_activity_summary.html.haml
- config/locales/default.en.yml
- config/locales/models/activity.en.yml
- config/locales/models/report.en.yml
- config/routes.rb
- spec/controllers/activities_controller_spec.rb
- spec/features/users_can_delete_an_activity_spec.rb
- spec/features/users_can_mark_a_report_as_awaiting_changes_spec.rb
- spec/features/users_can_mark_a_report_as_qa_completed_spec.rb
- spec/features/users_can_mark_a_report_in_review_spec.rb
- spec/models/activity_spec.rb
- spec/policies/activity_policy_spec.rb
- Allow BEIS users to delete untitled activities
- Signpost PO users on how to get untitled activities deleted
https://user-images.githubusercontent.com/40244233/227240995-dbe4a35a-b81b-46f6-ac55-764c4ea78b03.mov
> (2516) Untitled activity deletion

- lib/tasks/annual_fund_impact_metrics_activities.rake
- spec/lib/tasks/annual_fund_impact_metrics_activities_spec.rb
We want to be able to generate a CSV of activities that will be used to
pre-populate an annual collaborative spreadsheet of fund impact metrics.
This task will be used to capture a snapshot of activities once a year in
July.
The CSV will be created in the `tmp` folder. We have documentation describing
how to download files when connected remotely to an instance of the application.
> (2744) Add task to generate a CSV of Activities for annual fund impact metrics

- CHANGELOG.md
- app/views/activities/show.xml.haml
- app/views/exports/organisations/show.xml.haml
- config/application.rb
- script/training_db_sync.rb
- spec/features/beis_users_can_upload_level_b_activities_spec.rb
- spec/features/beis_users_can_upload_level_b_budgets_spec.rb
- spec/features/users_can_sign_in_spec.rb
- spec/features/users_can_upload_activities_spec.rb
Set TimeZone to London
This change was motivated by one of our tests using `Time.now` (BST) clashing with ActiveRecord storing times as UTC and failing.
Although [this article](https://thoughtbot.com/blog/its-about-time-zones) advises against setting a global timezone and recommends allowing users to set their own, this is a larger change than we have capacity (and need?) for at the moment.
We believe that all users should be accessing the site from a UK timezone, so this shouldn't change what they see.
Noticeable places this will change will be visible are:
- The approval time on a Report
- The time an export was uploaded to S3
Before this change, these would be one hour behind BST as they call `Time.current` which uses the app's time zone which defaulted to UTC, rather than the running …
> [2907] Set local time zone of app to London

- app/models/activity.rb
- spec/features/users_can_delete_an_activity_spec.rb
This ensures the remaining activity in a linked pair has its linked activity ID reset if its link is deleted. It's a precaution to avoid any errors based on assumptions that having a linked activity ID means that a linked activity exists in the database
> (2911) Explictly unlink activities before deleting

- CHANGELOG.md
- app/views/shared/_navigation.html.haml
- config/initializers/devise.rb
- spec/features/users_can_sign_out_spec.rb
Rails uses JavaScript to intercept requests from links that are given a
`method`, which allows us to use links for methods including DELETE. When
JavaScript is disabled, this falls back to a GET request.
Currently, this means that users see an error page when attempting to sign out
with JavaScript disabled, as Devise is expecting a DELETE request.
Devise allows us to specify the method used to sign out, so we can update this
to GET.
> (2903) Make sure users can sign out if JavaScript is disabled

- CHANGELOG.md
- app/controllers/actuals/uploads_controller.rb
- app/services/actual/import.rb
- spec/features/users_can_upload_actuals_spec.rb
- spec/services/actual/import_spec.rb
The actuals/refunds upload template is prepopulated with rows for all the activities to which you can add values. Previously, if you didn't want to provide values for all activities (e.g. if you just wanted to add values for one activity), you would have to remove all the remaining rows, since the default values are invalid
This makes it so that if there's at least one valid row and the only errors are default value errors, the valid row is imported and the invalid rows are ignored/discarded. This saves users the effort of manually deleting rows they don't care about
Rows with other errors will still prevent the import from completing, and the actual: zero, refund: blank error will still show if there are other errors and/or no valid rows
The `has_only_default_value_errors?` method relies …
> (2909) Allow valid actual/refund without deleting invalid rows

- CHANGELOG.md
- app/controllers/organisations_controller.rb
- app/policies/organisation_policy.rb
- app/views/organisations/_partner_org_tabs.html.haml
- app/views/organisations/_service_owner_tabs.html.haml
- app/views/organisations/_table.html.haml
- app/views/organisations/index.html.haml
- app/views/reports/_activities_upload.html.haml
- config/locales/models/activity.en.yml
- spec/features/organisation_show_page_spec.rb
- spec/features/users_can_view_implementing_organisations_spec.rb
- spec/features/users_can_view_reports_spec.rb
- spec/features/users_can_view_the_site_navigation_spec.rb
- spec/policies/organisation_policy_spec.rb
- Allow partner organisation users to list the implementing organisations
- Add guidance about finding implementing organisation names on the report activities tab
> (2883) Expose implementing organisations to partner org users

- CHANGELOG.md
- lib/tasks/annual_fund_impact_metrics_activities.rake
- spec/lib/tasks/annual_fund_impact_metrics_activities_spec.rb
Currently, the programme status for Activities in the annual fund impact
metrics CSV is the value from the database, which is a snake case string.
> (2920) Use locales for programme status on Activities download

- lib/tasks/annual_fund_impact_metrics_activities.rake
- spec/lib/tasks/annual_fund_impact_metrics_activities_spec.rb
We have confirmation that funds should not be included in the annual fund
impact metrics CSV.
We want to add a "level" column to the annual fund impact metrics CSV, to that
the activities can be easily sorted.
> Metrics CSV - level updates 

- CHANGELOG.md
- Exclude planned activities from annual fund impact metrics CSV
- Allow partner organisation users to list the implementing organisations
- Add guidance about finding implementing organisation names on the report activities tab
- Show a validation error when a Budget is edited with a comment but without changing the value
- Fix bug where current value was incorrect when editing a Budget with an invalid value
- Use locales for the programme status of the activities in the annual fund impact metrics CSV
> Release 134

- db/data/20230612081755_set_correct_receiving_organisations.rb
RODA reported 9 actuals with incorrectly set 'receiving organisations'. The client was unable to correct these themselves, as they are set on reports that are already approved. This PR creates a script to run in production that:
- Finds the actual by its `actual ID`
- Changes the existing receiving organisation name to the correct one
- Sets the organisation type to 'Academic' (80)
The actuals in question and their correct details are available in the spreadsheet 'RODA corrections - Q2 22-23' linked from the [Zendesk ticket](https://dxw.zendesk.com/agent/tickets/18138).
The receiving organisation is not shown in the spreadsheet generated by downloading a report. Therefore, once this script has been run in production, we will inspect the IATI xml report format to verify that the intended …
> Fix incorrect receiving orgs

- db/data/20230614151054_correct_partner_org_identifiers.rb
There are two activities with incorrect partner org identifiers that need amending, as reported by the client in [this ticket.](https://dxw.zendesk.com/agent/tickets/17993) 
This script finds each activity by its existing (incorrect) partner org identifier, and replaces the partner org identifier on the activity with the correct one.
> Adds script to change partner org identifiers

- db/data/20230718131711_import_ukri_level_d_budgets.rb
A large number of budgets for level D activities need to be added - it is not possible to do this currently via the bulk upload interface. 
This PR adds a re-usable script to upload budgets that cannot be handled by the client via bulk upload.
When this PR has been merged, we will need to make a deployment to production. Once the release has been made, the csv with the required budgets needs to be uploaded to GPaas; we can then run the script in production.
> Adds script to upload multiple level D budgets. 

- CHANGELOG.md
- app/services/export/s3_downloader.rb
- app/services/export/s3_uploader.rb
- spec/services/export/s3_downloader_spec.rb
- spec/services/export/s3_uploader_config_spec.rb
- spec/services/export/s3_uploader_spec.rb
- Support s3 access via ECS credentials, with the bucket name set as an environment variable
N/A
> (2938) Change how the app accesses s3 storage

- CHANGELOG.md
- Support s3 access via ECS credentials, with the bucket name set as an environment variable
This release prepares the application for the platform migration off of GOV.UK PaaS and onto DSIT's own hosting infrastructure.
> Release 138

- CHANGELOG.md
- app/controllers/activities_controller.rb
- app/controllers/exports/organisations_controller.rb
- app/controllers/exports_controller.rb
- app/controllers/reports_controller.rb
- app/models/iati/xml_download.rb
- app/services/activity/grouped_activities_fetcher.rb
- app/services/activity_search.rb
- app/services/report/grouped_reports_fetcher.rb
- app/services/report/organisation_reports_fetcher.rb
- app/views/level_b/activities/uploads/new.html.haml
- config/initializers/rollout.rb
- spec/controllers/exports/organisations_controller_spec.rb
- spec/controllers/exports_controller_spec.rb
- spec/features/beis_users_can_create_a_programme_level_activity_spec.rb
- spec/features/beis_users_can_create_a_report_spec.rb
- spec/features/beis_users_can_upload_level_b_activities_spec.rb
- spec/features/users_can_view_activities_spec.rb
- spec/models/iati/xml_download_spec.rb
- spec/rollout_spec.rb
- spec/services/activity_search_spec.rb
- spec/services/report/grouped_reports_fetcher_spec.rb
- spec/services/report/organisation_reports_fetcher_spec.rb
The ISPF is now live, meaning we no longer need a mode that hides ISPF funds from users. 
Trello: ticket [2943](https://trello.com/c/NTyNjH3d/2943-remove-the-ispf-hiding-feature-flag)
This PR removes the Rollout handled flag to exclude ISPF. All switches in the code triggered by the hide ISPF flag have been removed, along with now-redundant tests associated with that flag.
> Removes ispf_fund_in_stealth_mode

- CHANGELOG.md
- db/migrate/20231030124418_add_is_non_oda_to_report.rb
- db/schema.rb
Reports for ISPF need to be marked as ODA or non_ODA, to allow us to have two simultaneous open reports for ISPF.
In this PR, an is_non_oda boolean is added to the report model. Additionally, having verified with DSIT that all existing ISPF reports are non-ODA, the migration sets the is_non_oda value for existing ISPF reports to true.
- [ x] Is a changelog entry required? An entry should always be made in `CHANGELOG.md`, unless this PR is a small tweak which has no impact outside the development team.
> Add migration to add is_non_oda column to reports

- CHANGELOG.md
- app/models/report.rb
- db/migrate/20231030201831_enforce_one_editable_report_per_series_by_oda_type.rb
- db/schema.rb
- spec/models/report_spec.rb
Amend the report validation (enforced as Rails model validation and as database unique index) to take into account the ODA type of the report.
This allows non-ISPF reports (whose `is_non_oda` value is `nil`) to function as usual, and it allows ISPF to have one ODA and one non-ODA report editable at the same time for each partner organisation.
One can't really "edit" an index, which is why we're removing it and recreating it with the desired columns and attributes. See prior art at https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/1416/files#diff-6b33599697c95e38ad112ef133d058e26095bf7c68334fd0cf433547bebd4317 and https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/768/files
The index should be created without errors, …
> Amend report validation to include is_non_oda

- app/policies/project_policy.rb
- app/policies/third_party_project_policy.rb
- spec/policies/activity_policy_spec.rb
- spec/policies/project_policy_spec.rb
- spec/policies/third_party_project_policy_spec.rb
- `ProjectPolicy` now inherits from `ActivityPolicy`
- project and 3rd party project specs do not test redundant scenarios that are already tested in activity policy spec
- misleading specs have been removed
This is a step towards unifying all the activity related policies. Activities do not use an inheritance model for the different levels (fund, programme, project, third-party project), so in time we have ended up defining the policies in the activity policy.
The separate policies are now mainly used for:
- scopes; it may be possible to gather them under the activity policy umbrella, but this is outside the scope (pun unintended) of the current work, unless we are going to be working on those areas;
- "headless" invocations (using the policy without a record, e.g. `policy(:project)`) …
> (2945) Clean up project and third-party project policies

- CHANGELOG.md
- app/models/report.rb
- db/migrate/20231107133740_add_is_oda_to_reports.rb
- db/migrate/20231107141900_enforce_one_editable_report_per_series_by_oda_type.rb
- db/schema.rb
- spec/models/report_spec.rb
- Add `is_oda` attribute to reports and populate it to `false` for all existing ISPF reports
- Amend report validation to permit two editable reports per fund and organisation, as long as they have different ODA types
N/A
> (2948)(2946) Add `is_oda` to reports and report uniqueness validation

- CHANGELOG.md
- app/models/report.rb
- db/migrate/20231107133740_add_is_oda_to_reports.rb
- db/migrate/20231107141900_enforce_one_editable_report_per_series_by_oda_type.rb
- db/schema.rb
- spec/models/report_spec.rb
Add is_oda attribute to reports and populate it to false for all existing ISPF reports
Amend report validation to permit two editable reports per fund and organisation, as long as they have different ODA types
N/A
> 2948 2946 add is oda to reports

- CHANGELOG.md
- app/models/report.rb
- spec/models/report_spec.rb
- Amend the check for a pre-existing later report to take ODA type into account
N/A
> (2960) Amend pre-existing report check

- app/models/report.rb
- app/services/activity/projects_for_report_finder.rb
- spec/models/report_spec.rb
- spec/services/activity/projects_for_report_finder_spec.rb
- Update the query that retrieves the report to take into account the ODA type (`is_oda`) of the activity.
- Update projects for report finder to filter activities by ODA type.
N/A
> (2947) (2966) Update report - activity finders

- CHANGELOG.md
- app/models/report.rb
- config/locales/models/report.en.yml
- spec/models/report_spec.rb
For ISPF reports, the error message is now more specific about which type of report (ODA or non-ODA) already exists and is not approved.
No change for non-ISPF reports.
Note: there is no way to specify ODA/non-ODA through the UI at the moment. This functionality will be added in future PRs.
> Error message has ODA type of report when relevant

- CHANGELOG.md
- app/presenters/report_presenter.rb
- app/services/report/grouped_reports_fetcher.rb
- app/services/report/organisation_reports_fetcher.rb
- app/views/reports/index.html.haml
- app/views/shared/reports/_table_row.html.haml
- config/locales/models/report.en.yml
- spec/presenters/report_presenter_spec.rb
- spec/services/report/grouped_reports_fetcher_spec.rb
- spec/services/report/organisation_reports_fetcher_spec.rb
- Show ODA/non-ODA alongside the fund short name on the reports table for ISPF
- Order the reports by fund, ODA type, and financial period
> (2949) Expose the ODA/non-ODA type of reports in the report views

- CHANGELOG.md
- app/services/export/report.rb
- spec/services/export/report_spec.rb
- Fix the logic that generates actuals and variance rows for reports, to avoid inserting a spurious column for reports that have forecasts but no actuals
In certain circumstances, such as when a report has forecasts but no actual spend, there is an extra column for the data that is not matched to a header.
The reason the extra column shows up is due to the data structures used for the actuals and variance, which will always return a hash with keys and values, even if the values are not meaningful (empty arrays or zero values).
We cannot simply filter out empty arrays or zero values, because they can be meaningful in other contexts, such as when there are some nil or zero values in some quarters, but they are surrounded by quarters with non-zero values, so we have to include them.
The …
> Fix the mismatch between headers and rows

- .pryrc
- CHANGELOG.md
- app/helpers/application_helper.rb
- spec/helpers/application_helper_spec.rb
- Show environment banner and email prefix on the `dev` domain
The banner will look similar to the development banner, but saying "dev" instead of "development".
> Show environment banner and email prefix for the newly added dev domain

- CHANGELOG.md
- Remove ispf_fund_in_stealth_mode that hides ISPF funds from users
- Add `is_oda` attribute to reports and populate it to `false` for all existing ISPF reports
- Amend report validation to permit two editable reports per fund and organisation, as long as they have different ODA types
- Amend the check for a pre-existing later report to take ODA type into account
- Error message shown when attempting to create a report while an unapproved one for the same fund, org, and ODA type exists includes the ODA type where relevant
- Show ODA/non-ODA alongside the fund short name on the reports table for ISPF
- Fix the logic that generates actuals and variance rows for reports, to avoid inserting a spurious column for reports that have forecasts but no actuals
- Show environment banner and email …
> Release 139

- CHANGELOG.md
- app/models/activity.rb
- app/models/report.rb
- spec/features/users_can_upload_actuals_spec.rb
- spec/models/activity_spec.rb
- spec/models/report_spec.rb
- Remove the `oda_eligibility` criterion from `reportable` scope
Applying the ODA eligibility criteria globally, by including it in the definition of `reportable` activities, is not correct in the global context: ISPF non-ODA activities are reportable, as long as they have the relevant `programme_status`.
Instead, we will apply the ODA eligibility criteria on a report basis, as the report defines what it means for activities to be reportable within its purview.
For example, only projects and third-party projects are currently relevant for reporting, and it is the report's responsiblity to invoke the service object that applies the activity level criteria.
(This is not to say that we couldn't rethink these responsibilities, but in the current state, it's not much of a stretch to move this …
> Apply ODA eligibility criteria within report

- CHANGELOG.md
- Dockerfile
The nodesource.com setup scripts are deprecated.
Here we update the Dockerfile to use the new recommended installation.
We've moved both Node and Yarn installation into APT as we consider
them 'system' layer tools which install the packages on which the
application depends.
We've exposed the `NODE_MAJOR` version as a build argument which
defaults to 16, the current version in use by the application.
https://trello.com/c/RaVyNflr
> (2941) Update Node and Yarn installation

- CHANGELOG.md
- app/controllers/reports_controller.rb
- app/models/report.rb
- app/views/reports/new.html.haml
- config/locales/models/report.en.yml
- spec/controllers/activities/uploads_controller_spec.rb
- spec/factories/activity.rb
- spec/features/beis_users_can_create_a_report_spec.rb
- spec/features/users_can_create_a_project_level_activity_spec.rb
- spec/features/users_can_create_a_third_party_project_level_activity_spec.rb
- spec/features/users_can_manage_implementing_organisations_spec.rb
- spec/features/users_can_upload_activities_spec.rb
- spec/models/report_spec.rb
- spec/policies/activity_policy_spec.rb
- spec/requests/activity_forms_spec.rb
- spec/services/activity/import_spec.rb
- spec/services/export/report_spec.rb
- spec/views/shared/activities/activity_spec.rb
- Allow ISPF reports to be created as ODA or non-ODA
- Ensure that non-ISPF reports do not get a value set for `is_oda` (for historical reasons, the app relies on non-ISPF reports and activities not having an `is_oda` value set)
- Validate that the value of `is_oda` is set for ISPF reports
- Reorder the fields on the new report form per design
> (2952) New ISPF reports are created as ODA or non-ODA

- CHANGELOG.md
- app/presenters/report_presenter.rb
- app/views/reports/_form.html.haml
- app/views/reports/_summary.html.haml
- app/views/shared/reports/_table_row.html.haml
- config/locales/default.en.yml
- config/locales/models/report.en.yml
- spec/features/beis_users_can_edit_a_report_spec.rb
- spec/features/users_can_view_reports_spec.rb
- spec/presenters/report_presenter_spec.rb
The introduction of the International Science Partnership Fund led to a state where reports contain either ODA activities or non-ODA activities - an important distinction for users.
This works displays the 'ODA state' on the report show view and report edit form.
The decisions was made for two versions of this:
- on the show page, for the ISPF fund reports, the ODA state is shown, for all other funds the row is not shown in the summary
- on the edit page, for the ISPF fund reports, the ODA state is appended to the fund name, for all other funds nothing is shown
(See screenshots below)
As we already have a way to present the fund short name with the ODA state appended, we followed this pattern and then renamed the original method to be clear about the behaviour of each.
We are currently in …
> (2974) Show ODA state on ISPF reports

- spec/spec_helper.rb
We use Simplecov as part of Coveralls to generate a code coverage
percentage and a bar which we hold ourselves to (98%).
https://coveralls.io/
https://github.com/simplecov-ruby/simplecov
Unfortunately, Simplecov looks to mis-configured so our coverage report
may not have been as accurate as we would have liked!
By configuring Simplecov explicitally for Rails, we get a more accurate
report (the spec files themselves for example are no longer included
which were heavily skewing our result).
In order to continue to reach our goal of 98% coverage we have more
work to do or some decisions to make:
For now we are ignoring low coverage in some specific files and all the
tasks, these are common items to skip, but we should make a decision
about where to take these.
We've heavily commented the …
> (2986) Fix the coverage calculation

- CHANGELOG.md
- app/controllers/activities/uploads_controller.rb
- app/models/csv_file_upload.rb
- app/models/report.rb
- app/presenters/report_presenter.rb
- app/views/activities/uploads/_fund_section.html.haml
- app/views/activities/uploads/new.html.haml
- app/views/activities/uploads/update.html.haml
- spec/controllers/activities/uploads_controller_spec.rb
- spec/presenters/report_presenter_spec.rb
- Upload templates for ISPF reports use the ODA type of the report
> (2982) ISPF reports templates are split between ODA and non-ODA

- CHANGELOG.md
- app/models/export/activity_actuals_columns.rb
- spec/models/export/activity_actuals_columns_spec.rb
- spec/services/export/report_spec.rb
The total actuals is the sum of the 'actuals net' columns in the report,
of which there can be multiple..
Here we keep a total of the actual net values as it is calculated for each
financial quarter and add it to the columns for the current row if
appropriate.
Because the ActivityActualsColumns class also provides data for the
'spending breakdown' we have to check that a report is being generated
and only include the total actuals column if that is the case.
Most changes here relate to the addition of the extra column, the
ActivityActualsColumns adds `n` number of financial quarters and then
adds the total actuals to the end, some of this code has to rely on the
position of the values i.e the column number which has been altered by
this work.
We could not see another approach for this …
> (2927) Add total actuals to report export

- CHANGELOG.md
- app/services/activity_defaults.rb
- spec/services/activity_defaults_spec.rb
- Fix originating report finder in ActivityDefaults to take into account the ODA type of the activity
ActivityDefaults is responsible for setting a number of attributes for an activity that can be inferred from data the app already has.
One of these is the originating report, which is the currently active report for the fund and organisation of the activity.
Now that ISPF reports are split between ODA and non-ODA, the originating report finder needs to take into account the ODA type of the activity, and correctly find the corresponding report.
We forgot to update this finder in https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/2203
N/A
> (2991) Identify originating report by using is_oda value

- config/initializers/sidekiq.rb
WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`
N/A
> Fix sidekiq deprecation warnings

- CHANGELOG.md
- app/models/export/activity_commitment_column.rb
- app/services/export/report.rb
- spec/models/export/activity_commitment_column_spec.rb
- spec/services/export/report_spec.rb
We want to show the original commitment value for an activity in the report csv export.
The value is entered by a user and is optional, when there is no value we show a blank value as zero could imply there was explicitally £0 of commitment, which may be missleading.
After spending time in the spec for the report export, we refactored the helpers to make the spec more approachable.
We also came across a redundant method, which we removed.
https://trello.com/c/7TbEQrNO
> (2928) Outgoing commitment value in report csv export

- .github/workflows/ci.yml
- Gemfile
- Gemfile.lock
- docker-compose.test.yml
- spec/spec_helper.rb
Our Coveralls reports have not worked for some time:
https://coveralls.io/jobs/132270209
This work fixes that by updating how we send the data to Coveralls. In summary:
- drop the coveralls gem
- update simplecov gem
- add a new formatter
- expose the coverage report in the GitHub action runner
- run the Coveralls GitHub action
> Fix: Test coverage sent to Coveralls

- CHANGELOG.md
- app/models/export/activity_iati_column.rb
- app/services/export/report.rb
- spec/models/export/activity_iati_column_spec.rb
- spec/services/export/report_spec.rb
This work adds the `publish_to_iati` from `Activity` value in the report csv export.
- The value is true by default 
- The value is shown as one of 'Yes' or 'No'
- The column comes at the very end of the columns in the csv table
https://trello.com/c/c4GFG0UW
> (2929) Published to IATI value in report csv

- CHANGELOG.md
2023-11-28
[Full changelog][140]
- Remove the `oda_eligibility` criterion from `reportable` scope, and apply it on a report by report basis, so we don't exclude ISPF non-ODA activities from ISPF non-ODA reports
- Update how Node and Yarn are installed inside the application container
- Allow ISPF reports to be created as ODA or non-ODA
- Ensure that non-ISPF reports do not get a value set for `is_oda` (for historical reasons, the app relies on non-ISPF reports and activities not having an `is_oda` value set)
- Validate that the value of `is_oda` is set for ISPF reports
- Reorder the fields on the new report form per design
- Show if a report for ISPF is ODA or non-ODA on the report show view
- Show if a report for ISPF is ODA or non-ODA on the report edit form
- Upload templates for ISPF …
> Release 140

- CHANGELOG.md
- app/models/activity.rb
- app/services/iati/activity_scope_service.rb
- app/views/shared/xml/_activity.xml.haml
- spec/features/beis_users_can_view_an_activity_as_xml_spec.rb
- spec/models/activity_spec.rb
- spec/services/iati/activity_scope_service_spec.rb
- spec/views/shared/xml/activity_spec.rb
The 'scope' of the activity is an IATI metric that we want to include for publishing. Like many IATI metrics, it is up to DSIT to interpret as they see. Here the logic is:
- national when the acitivity benefits a single country
- regional when the activity benefits multiple countries
- mulit-national when the activity benefits multiple countries across multiple regions
No other scope value were deemed necessary for DSIT.
With the business logic clear, we went ahead and added a service object to calculate it - the decision is covered in the commit.
Once we can calculate the scope we then show it in the IATI xml download that is published.
We have run a sample xml file through the IATI validator which raised no new errors, although there are errors, they are pre-existing. …
> (2932) Add IATI Scope to xml

- CHANGELOG.md
- app/views/matched_efforts/_form.html.haml
- spec/features/users_can_create_a_matched_effort_spec.rb
- spec/features/users_can_edit_a_matched_effort_spec.rb
The new matched effort form was missing it's error summary:
https://design-system.service.gov.uk/components/error-summary/
This adds it in and confirms its presence in the specs.
https://trello.com/c/GaiuFcnt
> (2977) Fix: missing error summary on matched effort form

- app/models/activity.rb
- app/models/fund.rb
- app/models/report.rb
- spec/models/fund_spec.rb
- spec/views/exports/organisations/show_spec.rb
- Remove specs for ISPF in stealth mode
- Remove unused scopes and methods `not_ispf`
N/A
> (2965) Clean up leftovers from "ISPF in stealth mode" feature flag

- CHANGELOG.md
- app/services/export/report.rb
- spec/services/export/report_spec.rb
- ISPF report CSVs now include the ODA type, to make it easier for users to distinguish between them.
N/A
> (2997) Include ODA type in ISPF report export filenames

- config/routes.rb
- spec/requests/health_check_spec.rb
The AWS health check endpoint has been configured to look for the route `health-check` instead of `health_check`.
Rather than asking them to reconfigure it, we will accept that both versions (with dash and with underscore) are common, and provide an alias for the route, so that it responds to both requests.
N/A
> Alias health_check so it responds to health-check

- spec/factories/organisation.rb
- spec/support/faker.rb
- Use Faker's `unique` feature to guarantee unique strings for the `iati_reference` and `beis_organisation_reference` in the organisation factory.
We have seen the test suite fail with an intermittent failure, unrelated to actual code failure, caused by the organisation created failing the uniqueness check for its `iati_reference`:
```
ActiveRecord::RecordInvalid:
Validation failed: Iati reference Iati reference has already been taken
```
E.g. https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/actions/runs/6978961311/job/18991313569
We suspect this intermittent failure is caused by Faker's pseudo-random generator accidentally producing the same string within the same spec. The IATI reference and BEIS organisation reference are more susceptible to this, because …
> (2967) Generate unique references in organisation factory

- doc/0_index_of_contents.md
- doc/authentication.md
- spec/features/users_can_sign_in_spec.rb
There are two quite different changes here:
The first tightens the time control around the user signing in and the spec storing the OTP for comparing later.
The second makes the OTP always correct, decoupling the spec from the OTP entirely.
I've documented what I learnt along wth the changes to the acutal specs.
I found that the OTP seems to last 5 mintutes and 30 seconds, even though it is configured to 5 miniutes. I've added a spec that demonstrates the odd extra 30 seconds and encourage you to have a play with the specs and see what you think and let me know.
I am confident the end result here will stop the flaking, but other folks tastes may vary so I am leaving this draft for now.
Appreciate any other views on this spec flaking, there is an example CI run linked in the commit, but …
> (2995) Fix: flaky sign in spec

- CHANGELOG.md
- app/views/shared/activities/_budgets.html.haml
- config/locales/models/activity.en.yml
- spec/features/users_can_create_a_budget_spec.rb
- spec/features/users_can_view_budgets_on_an_activity_page_spec.rb
- Display the budgets headings as "Activity budgets" for level C and D activities on the Financials tab
> (3009) Budgets as "Activity budgets" for levels C and D

- CHANGELOG.md
- app/models/import/csv/financial.rb
- spec/models/import/csv/financial_spec.rb
To try and simplify our approach to importing from csv files this
Import::Csv::Financial class is a basic wrapper for a financial value
that is to be imported from csv.
Our philosophy when importing from csv is that a financial value is to expect:
- a positive number
- a negatvie number
- zero
- any kind of blank space
- invalid
- some kind of financial formatting e.g. 10,000.00
Here, invalid means
> We could not convert the supplied string to a BigDecimal.
This implementation treats a `0` and an empty cell the same,
which makes the upstream import code more approachable as we can
assume everything will be `0`.
We resue the existing `ConvertFinancialValue` service object to do the
actual conversion, dealing with an errors as described above - we chose
this approach over changing the …
> (2931/1) Model a financial value from a csv

- CHANGELOG.md
- spec/helpers/codelist_helper_spec.rb
- vendor/data/codelists/BEIS/tags.yml
This PR picks the relevant commit from [PR 2289](https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/2289) and applies them straight to main. 
We are doing this to be able to release this work quickly for the client, without releasing other commits currently sitting in develop.
-------
DSIT asked to have the following activity tag added:
code: 8
description: Strategic Allocation Pot (SAP)
This was on dxw support ticket #19080
> HOTFIX: Add new activity tag

- CHANGELOG.md
- spec/helpers/codelist_helper_spec.rb
- vendor/data/codelists/BEIS/tags.yml
DSIT asked to have the following activity tag added:
code: 8
description: Strategic Allocation Pot (SAP)
This was on dxw support ticket [#19080](https://dxw.zendesk.com/agent/tickets/19080)
https://trello.com/c/DxhGtLdQ
> (3008) Add new activity tag

- CHANGELOG.md
- app/models/import/csv/activity_actual_refund_comment/row.rb
- config/locales/import/csv/actiity_actual_refund_comment/errors.en.yml
- spec/models/import/csv/activity_actual_refund_comment/row_spec.rb
Now we have a reliable model of a financial value in a csv import, we can move onto the rest of the data in a row.
This is the Actual, Refund and Commnet csv row model, it is responsible for providing a reliable interface to import a row of data that result in a new Actual, Refund or Comment and will form the base of a new importer.
The motivation here is to allow users to provide a comment in the upload when there is no actual or refund to attach that comment to - instead the comment is attached directly to the activity the row represents - this is a common user feature request that would commonly be used to explain the lack of actual or refunds in a report.
We wanted to approach this like the 'form object' design pattern, it is a standin for a model that validates in a specific context, …
> (2931/2) Model csv actual refund comment row from csv

- CHANGELOG.md
- app/models/import/csv/activity_actual_refund_comment/row.rb
- config/locales/import/csv/actiity_actual_refund_comment/errors.en.yml
- spec/models/import/csv/activity_actual_refund_comment/row_spec.rb
Actuals value must never be negative, here we add the validation to
the `Import::Csv::ActivityActualRefundComment::Row`.
https://trello.com/c/lBZkYq5c
> CSV import actuals cannot be negative

- CHANGELOG.md
- app/controllers/exports_controller.rb
- app/policies/export_policy.rb
- app/services/export/continuing_activities.rb
- app/views/exports/index.html.haml
- config/routes.rb
- spec/services/export/continuing_activities_spec.rb
The first step in updating activities with the new transparency identifier: producing a list of activities that fulfill the conditions to continue, from the old GB-GOV-13 identifier corresponding to BEIS, to the new GB-GOV-26 identifier corresponding to DSIT.
The list will need to be signed off by DSIT.
If the synchronous request proves to be too much with production amounts of data, we'll go back to the more complex async option drafted in https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/2301
> Export a CSV of all continuing activities

- CHANGELOG.md
- app/models/import/csv/activity_actual_refund_comment/skipped_row.rb
- app/services/import/csv/activity_actual_refund_comment/row_service.rb
- config/locales/import/csv/actiity_actual_refund_comment/errors.en.yml
- spec/models/import/csv/activity_actual_refund_comment/row_spec.rb
- spec/models/import/csv/activity_actual_refund_comment/skipped_row_spec.rb
- spec/rails_helper.rb
- spec/services/import/csv/activity_actual_refund_comment/row_service_spec.rb
- spec/support/csv_import_helpers.rb
In #2293 we introduced a model of a row that contains Actual, Refund or Activity comment data for importing.
Here we add a service that can turn one of these row objects into actual objects in the application database.
Given a appropriate `CSV::Row` this service will with return the resulting object that was added or false, a row can be skipped, see below.
This is the point at which we will attempt to locate the `Activity` to associate the record with. We also check that the activity is authorised for the report and user.
In the current import implementation (that this work intends to replace) a row cannot be skipped i.e. a row cannot result in no data being created, this was seen by users as a drawback, they want to include rows that have no result. To support this change, we introduce a …
> (2931/3) Actual, Refund or Comment row import service

- app/controllers/exports_controller.rb
- app/services/export/continuing_activities.rb
- app/views/exports/index.html.haml
- config/routes.rb
To help DSIT with confirming the lists of activities that will and won't need to be updated with the new transparency identifier, allow them to export a list of the activities that are assumed to not continue under GB-GOV-26.
The reason we have used the criteria of elimination rather than a new standalone query is that this is how the migration is likely to look like in practice: activities that fulfill the continuation criteria will be updated, and all other activities will be left as they are.
Non-ODA activities are excluded from both, because they are not concerned with transparency reporting to begin with.
> Download a list of non-continuing ODA activities

- app/services/export/continuing_activities.rb
In order to make the list usable for Dan, order the non-continuing activities by the same criteria as the continuing ones: partner org name and RODA identifier.
> (3006) Order non-continuing activities by org and RODA ID

- CHANGELOG.md
- app/controllers/actuals/uploads_controller.rb
- app/models/import/row_error.rb
- config/locales/import/csv/actiity_actual_refund_comment/errors.en.yml
- spec/controllers/actuals/uploads_controller_spec.rb
- spec/features/import/users_can_upload_actuals_refunds_and_actvitiy_comments_spec.rb
- spec/models/import/row_error_spec.rb
This work allows us to switch between the old Actual and Refund importer (`Actual::Import`) and the new Acutal, Refund and Activity comment importer.
The goal here is to test the importer with DSIT in development or staging so they are confident it does everything they want.
Once we are happy, we will come back and update the UI to make the most of the new importer.
> (2931/5) Feature flag for new import service

- spec/factories/activity.rb
The purpose of this change is to make the factory more realistic, to avoid it being a source of confusion as to how the transparency identifier is generated in RODA.
N/A
> (3027) Update the factory to use current rules

- CHANGELOG.md
- config/application.rb
Exclude health check requests from host authorisation, to allow the AWS deploy pipeline to proceed faster. Currently health check requests are denied by the host auth process, because the IPs are not in the DOMAIN or ADDITIONAL_HOSTNAMES env vars.
We don't have a canonical list of the IPs, nor do we have easy access to the env vars (these particular env vars live in task definitions, not in ParameterStore).
https://api.rubyonrails.org/classes/ActionDispatch/HostAuthorization.html
N/A
> (3021) Exclude health check requests from host auth

- CHANGELOG.md
- app/models/organisation.rb
- config/locales/models/actual.en.yml
- config/locales/models/organisation.en.yml
- db/migrate/20240111133813_change_beis_to_dsit.rb
- db/schema.rb
- db/seeds/organisations.yml
- doc/activity-identifiers.md
- spec/features/beis_users_can_create_a_programme_level_activity_spec.rb
- spec/models/organisation_spec.rb
- Change the transparency identifier and names for the DSIT organisations (DSIT and DSIT Finance)
> (3005) Change DSIT organisations' IATI references and names

- CHANGELOG.md
- db/migrate/20240115183402_change_transparency_identifier.rb
- db/schema.rb
For activities that will be continuing under DSIT:
- change their transparency identifier to replace the string "GB-GOV-13" with "GB-GOV-26"; e.g. `GB-GOV-13-ISPF-UKSA-AH2TS7K-SPB9U87` becomes `GB-GOV-26-ISPF-UKSA-AH2TS7K-SPB9U87`
- change the `providing_organisation_reference` for all their actuals, from "GB-GOV-13" to "GB-GOV-26"
- change the `providing_organisation_reference` for all their forecasts, from "GB-GOV-13" to "GB-GOV-26"
This type of data change would be better suited for a data migration or a rake task, but both of those would require access to the application console in the production environment.
> (3007) Change transparency identifier

- CHANGELOG.md
- app/models/organisation.rb
- spec/models/organisation_spec.rb
To facilitate the transition between the service owner being identified by the old IATI reference `GB-GOV-13` and being identified by the new IATI reference `GB-GOV-26`, allow both identifiers to be used.
This will prevent user permissions from being lost during the short interval between the code being deployed and the migration being run.
N/A
> Allow service owner to be identified by both IDs

- CHANGELOG.md
- Support both the new and the old actual importer, allowing switching between
them with a feature flag
- Exclude health check requests from host authorisation
- Remove the feature flag for ODA bulk upload
- Allow service owner to be identified by both IDs during the transition between BEIS and DSIT
> Release 143

- CHANGELOG.md
- app/models/organisation.rb
- config/locales/models/actual.en.yml
- config/locales/models/organisation.en.yml
- db/data/20240123152048_change_beis_to_dsit.rb
- db/seeds/organisations.yml
- doc/activity-identifiers.md
- spec/features/beis_users_can_create_a_programme_level_activity_spec.rb
- spec/models/organisation_spec.rb
- Change the transparency identifier and names for the DSIT organisations (DSIT and DSIT Finance)
> (3005) Update service owner organisation

- CHANGELOG.md
- lib/tasks/continuing_activities_actuals_and_forecasts.rake
- Add a rake task to change the transparency identifier for activities that will continue under DSIT, and the providing org reference for their actual spend and forecasts
N/A
> Proper data migration

- CHANGELOG.md
- app/controllers/actuals/uploads_controller.rb
- app/models/import/csv/imported_row.rb
- app/services/import/csv/activity_actual_refund_comment/file_service.rb
- app/views/actuals/uploads/_actuals.html.haml
- app/views/actuals/uploads/_comments.html.haml
- app/views/actuals/uploads/_refunds.html.haml
- app/views/actuals/uploads/_skipped.html.haml
- app/views/actuals/uploads/update.html.haml
- spec/controllers/actuals/uploads_controller_spec.rb
- spec/features/import/users_can_upload_actuals_refunds_and_activity_comments_spec.rb
- spec/models/import/csv/imported_row_spec.rb
- spec/services/import/csv/activity_actual_refund_comment/file_service_spec.rb
Now that we have done some testing on the new importer with the DSIT team, we can be more confident to update the view. Whilst the existing view shows a combination of imported Actuals and Refunds, the new view split each type into it's own table:
- Actuals
- Refunds
- Activity comments
- Skipped rows
Skipped rows have quite a different shape to the other types, to help users identify which rows in their file were skipped we introduce the concept of a `ImportedRow`. This lets us store the resulting object along with the row number that sourced it, this is very much the same approach we take for any errrors.
https://trello.com/c/a6CvTA01
> (3023) View updates for new importer

- CHANGELOG.md
- app/models/activity.rb
- app/views/shared/xml/_activity.xml.haml
- spec/features/beis_users_can_view_an_activity_as_xml_spec.rb
- spec/models/activity_spec.rb
- Use an activity's `transparency_identifier` as `iati-identifier` in XML exports, and the `previous_identifier`, if it exists, as `other-identifier`
N/A
> (3019) Change what identifier is used as iati-identifier in XMLs

- CHANGELOG.md
- Change the transparency identifier and names for the DSIT organisations (DSIT and DSIT Finance)
- Add a rake task to change the transparency identifier for activities that will continue under DSIT, and the providing org reference for their actual spend and forecasts
- model a simple imported row so that users can see which row in the csv import
were skipped
- the Activity actual, refund and comment upload success view now shows the
imported actuals, refunds, activity comments and skipped rows
- Use an activity's `transparency_identifier` as `iati-identifier` in XML exports, and the `previous_identifier`, if it exists, as `other-identifier`
> Release 144

- CHANGELOG.md
- config/locales/views/iati_xml.en.yml
Certain details (organisation name, email, address) have not been updated in the config for IATI xml since the switch from BEIS to DSIT. 
This PR updates the required fields with the new details, as per [this](https://dxw.zendesk.com/agent/tickets/19873) support ticket. 
**NOTE:** this PR depends on [PR 2363](https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/2363). 2363 bumps the Ruby version being used from 3.0.6 to 3.1.2. The commits in this PR are rebased over 2363, and should probably again be rebased over develop once 2363 is merged. **HOLD MERGE** of this PR until 2363 is merged.
> Update iati xml details for DSIT

- CHANGELOG.md
- Bump Ruby version from 3.0.6 to 3.1.2
- Update details in IATI xml yaml to reflect switch from BEIS to DSIT
> release 146

- .github/workflows/ci.yml
- README.md
- db/data/20240919000000_change_partner_org_ids.rb
- doc/architecture/decisions/0003-use-dotenv-for-managing-environment-variables.md
- script/bootstrap
- script/cibuild
- script/setup
See Zendesk 20045 in which we are requested to change the `Activity#partner_organisation_identifier` for 100 activities.
These IDs are not used internally so there's no data integrity issue within the RODA application.
We do however, log if:
- this change will result in there being another activity with the same Partner Org ID and the same parent, as this is not permitted ordinarily, see [Activity model][] and note below
- the given Activity's current `partner_organisation_identifier` does not match the ID listed in our spreadsheet of changes
Our data migration must be run with with either `--dry-run` or `--live-run` e.g.
```sh
rails runner db/data/20240919000000_change_partner_org_ids.rb --dry-run`
```
In the `--dry-run` case we print out all the logging but hold back on making the …
> Ops: update 100 Activities' PO ID with data migration

- db/data/20240919000000_change_partner_org_ids.rb
In this PR we tweak the data to be changed in `db/data/20240919000000_change_partner_org_ids.rb`
See https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/2367
Following a review of validation errors identified when running the migration in `--dry-run` mode, 6 activities are to be excluded. Their RODA IDs:
- `GCRF-BA-R5FBZXE-73R7B48-9TK4WUY`
- `GCRF-BA-R5FBZXE-73R7B48-Z3FC2LP`
- `GCRF-BA-R5FBZXE-73R7B48-RFPMJX3`
- `GCRF-BA-R5FBZXE-73R7B48-6GG5YVE`
- `GCRF-BA-R5FBZXE-73R7B48-HXBLEK9`
- `GCRF-BA-R5FBZXE-73R7B48-RM5XQA5`
In the case of 6 of the 100 activites in the list of 100 for editing, it turned out that the change in
`Activity#partner_organisation_identifier` would violate a uniqueness control on this field. The validation rule specifies that two …
> Remove 6 of 100 activities to have PO Org ID edited

- app/jobs/spending_breakdown_job.rb
- app/mailers/download_link_mailer.rb
- spec/jobs/spending_breakdown_job_spec.rb
- spec/mailers/download_link_mailer_spec.rb
When we attempted to update to a new version of Ruby, this Mailer
stopped working.
We are not sure why, but switching to positional arguments resolves the
issue, UserMailer uses positional arguments so we assume that this is
acceptable.
Making this refactor opens the door to update Ruby.
> Refactor DownloadLinkMailer

- CHANGELOG.md
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/shared/users/_table.html.haml
- app/views/users/index.html.haml
- config/locales/models/user.en.yml
- config/routes.rb
- spec/controllers/users_controller_spec.rb
- spec/features/beis_users_can_edit_a_user_spec.rb
- spec/features/beis_users_can_view_other_users_spec.rb
- spec/models/user_spec.rb
- spec/requests/user_spec.rb
This PR separates out the /users page into /users/active and /users/inactive with a tabbed view.
> Separate /users page into active and inactive users

- .github/workflows/ci_checks.yml
When updating CI we missed this step. We are not sure anyone actually
uses the Coveralls site, but we where sending it so should continue to.
https://coveralls.io/github/UKGovernmentBEIS/beis-report-official-development-assistance
> Send coverage to Coveralls

- Dockerfile
- README.md
We recently switched off asset compilation in environments other than
production.
In production, we thought the environment variables required for asset
compilation would be present, when we deployed the change to the
development environment, it turned out that was not the case (we have
no direct control over how the infrastructure is configured).
Returning these stand in variables allows the assets to be compiled, the
variables are not used in the running container and this is how we
approached this issue before the change.
> Fix: Asset compilation

- app/views/shared/xml/_activity.xml.haml
- db/data/20241114082139_fix_hybrid_beis_dsit_identifier.rb
- db/migrate/20241114114012_add_hybrid_beis_dsit_activity.rb
- db/schema.rb
- spec/db/data/20241114082139_fix_hybrid_beis_dsit_identifier_spec.rb
- spec/views/shared/xml/activity_spec.rb
This data migration fixes the data in the application that was
previously updated in error.
We previously updated the `transparency_identifier` which should be
immutable. This data migration reverts that change.
We then set the new `hybrid_beis_dsit_activity` which makes the
application display 'previous reporting organisation' info in the IATI
xml.
A 'hybrid activity' is one that was started under BEIS but continued
under DSIT and so has to show:
- the previous reporting organisation
- retain the old IATI identifier
There can never be new 'hybrid activities'.
Instructions for running this data migration are in the file.
> Data migration for IATI and other identifiers

- CHANGELOG.md
- Remove Spring from development
- Switch to the Zeitwerk autoloader
- Use Rails 6.1 default configuration
> Release 154

- CHANGELOG.md
- app/models/current.rb
- app/models/user.rb
- db/migrate/20241204220209_create_join_table_organisations_users.rb
- db/schema.rb
- doc/architecture/decisions/0038-users-may-belong-to-multiple-organisations.md
- spec/models/user_spec.rb
This creates a `has_and_belongs_to_many` join table relationship between organisations and users, allowing a user to belong to `additional_organisations` and paves the way to allowing a user to set their `organisation` to be a `Current.user_organisation` and thus view data for that organisation instead of their own "real" organisation.
This should change nothing about the existing functionality of the site and will be entirely invisible to end users. (The next phase will include front-end changes which *will* allow selected users to switch their current organisation.)
Helper methods on the `User` model to navigate this relationship include `primary_organisation` (to retrieve the user's actual `organisation`, which is necessarily overwritten), `all_organisations` (the union of …
> Allow users to have additional organisations

- CHANGELOG.md
- db/data/20241203084616_fix_dsit_beis_forecasts.rb
- spec/db/data/20241203084616_fix_dsit_beis_forecasts_spec.rb
The name of the providing organisation does not match the reference
number in a lot of cases, which we assume happened when BEIS became
DSIT.
This migration fixes that.
Let me explain why this looks 'unusual':
The Forecast model is protected against direct access, for background
see our docs:
https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/blob/develop/doc/forecasts-and-versioning.md
In this instance the data is simply incorrect, the reference 'GB-GOV-26'
should be named 'DEPARTMENT FOR SCIENCE, INNOVATION AND TECHNOLOGY' and
nothing else. We are not creating new or deleting old Forecast and so
should not upset the versioning.
As we are correcting data we have to touch a lot of Forecasts and the
protection makes this interesting!
For the actual data …
> Fix planned disbursement providing organisation

- CHANGELOG.md
- app/controllers/application_controller.rb
- app/controllers/users/organisation_session_controller.rb
- app/models/user.rb
- app/views/layouts/application.html.haml
- app/views/shared/_navigation.html.haml
- app/views/shared/_organisation_switcher.html.haml
- config/locales/views/organisation_switcher.en.yml
- config/routes.rb
- spec/controllers/activities_controller_spec.rb
- spec/controllers/application_controller_spec.rb
- spec/controllers/organisation_session_controller.rb
- spec/features/users_can_edit_a_comment_spec.rb
- spec/features/users_can_switch_organisation_spec.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
- spec/views/shared/navigation_spec.rb
We have a new front-end component, a dropdown menu organisation switcher, which will be displayed for a user with a non-zero number of `addtional_organisations` and will allow them to switch their organisation. (There is no functionality currently to populate a given user's `additional_organisations` - this would need to be done manually. By default a user will have zero `additional_organisations` and this component will be hidden.)
Once switched, the user will see reports, exports, and activities for that organisation. They can switch back to their original organisation in the same way.
We store the user's switched organisation in the session as `current_user_organisation`, and we also write this into `Current.user_organisation` so we can easily access it in the `User` model where we …
> Front-end work for allowing users to switch organisations

- CHANGELOG.md
- app/views/layouts/application.html.haml
This meta tag is used to set the colour that you see when the browser
'bounces':
https://webkit.org/blog/11989/new-webkit-features-in-safari-15/
it is currently set to `blue` which is pretty distracting!
In the current GOV.UK front end it is set to `#0b0c0c` so we do the
same:
https://design-system.service.gov.uk/styles/page-template/
> Set theme colour

- CHANGELOG.md
- app/controllers/users_controller.rb
- app/models/user.rb
- app/services/update_user.rb
- db/migrate/20241212115356_add_user_anonymisation.rb
- db/schema.rb
- spec/factories/user.rb
- spec/features/users_can_sign_in_spec.rb
- spec/mailers/report_mailer_spec.rb
- spec/models/user_spec.rb
- spec/services/report/send_state_change_emails_spec.rb
This is the work to start to allow us to anonymise users - our version of 'deletion'. We decided not to delete users as we want to retain the history of 'who did what when'. DSIT have decided  that a user who has been deactivated for 5 years can be anonymised, which will remove all personally identifiable information (PII) from a user in the application.
To do so we will need to store when a user was deactivated so we can either anonymise ourselves or let admin users do so.
This first step introduces two date and time fields to user:
- deactivated_at
- anonymised_at
We are taking the `updated_at` timestamp as our best guess at the deactivated_at date and time of existing users as we assume a deactivated user last activity will be the deactivation of their account.
As the state of the user …
> Prepare user model for anonymisation

- app/controllers/users_controller.rb
- app/models/user.rb
- spec/features/beis_users_can_view_other_users_spec.rb
- spec/models/user_spec.rb
We recently added the length of time a user has been deactivated for on
the deactivated user index, the ordering on this did not work as
expected, this work fixes that and takes the time to refactor how we
approach this.
We create two scopes for use in the views, we've gone for scopes as we
can test those in isolation.
As we have the ordering tested on the scopes, we deleted the old feature
spec that tested the order of the user list.
We kept the call to `policy_scope(User)` although we think it is just
equivalent to `all` as there is no scope so it is inherited.
> Refactor user scopes

- spec/requests/health_check_spec.rb
Mild fix for a spec that would fail in dev if you had any unprocessed Sidekiq detritus from other projects. Benefit for devs only, no need for CHANGELOG stuff
None
Sometimes specs would fail if you had unprocessed enqueued sidekiq stuffs
They no longer fail
> Fix flaky healthcheck spec

- CHANGELOG.md
- app/controllers/users_controller.rb
- app/javascript/application.js
- app/javascript/src/edit-user-additional-organisations.js
- app/models/user.rb
- app/services/create_user.rb
- app/services/update_user.rb
- app/views/users/_form.html.haml
- app/views/users/show.html.haml
- config/locales/models/user.en.yml
- spec/features/beis_users_can_edit_a_user_spec.rb
- spec/features/beis_users_can_invite_new_users_spec.rb
- spec/models/user_spec.rb
- spec/services/create_user_spec.rb
- spec/services/update_user_spec.rb
We now have the ability to add additional organisations from the app itself via the create/edit user forms.
This replaces the radio list of BEIS + partner organisations with a dropdown, for the primary organisation, and also adds a checkbox list of partner organisations for the additional organisations. Appropriate explanatory hint text is also provided.
We also have a sprinkling of JavaScript to enhance the form such that a user's additional organisation selections cannot include their primary organisation. As a safeguard for users who do not have JavaScript enabled, we have validation in the model for this too.
> Administrative interface for user additional organisations

- CHANGELOG.md
- app/controllers/users_controller.rb
- app/helpers/form_helper.rb
- app/policies/user_policy.rb
- app/views/users/_form.html.haml
- app/views/users/deactivate.html.haml
- app/views/users/reactivate.html.haml
- config/locales/models/user.en.yml
- config/routes.rb
- spec/features/beis_users_can_edit_a_user_spec.rb
Here we move the deactivate/reactivate a user functionality into a separate pair of pages, with explanatory and confirmatory text on each page. We continue using the same `update` method on the Users controller and just pass the active state through.
> Change deactivate/reactivate interactions

- CHANGELOG.md
- app/views/shared/users/_active_table.html.haml
- app/views/shared/users/_deactivated_table.html.haml
- spec/features/users_can_switch_organisation_spec.rb
This fixes an issue where if an admin user switches their organisation, the user list view shows the switched organisation rather than each user's actual organisation. We include a test to reflect that this behaviour is now correct.
> Fix admin user switching issue

- config/brakeman.ignore
We'll be upgrading Rails to 7.1.x shortly so let's temporarily disable the EOLRails warning in Brakeman, and re-enable it when we're updating to Rails 7.1.x.
> Brakeman is complaining about our EOL version of Rails 7.0.8.7.

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- app/jobs/anonymise_deactivated_users_job.rb
- config/routes.rb
- config/sidekiq.yml
- doc/architecture/decisions/0040-use-sidekiq-scheduler-for-scheduled-jobs.md
- spec/config/sidekiq_scheduler_spec.rb
- spec/jobs/anonymise_deactivated_users_job_spec.rb
- spec/support/sidekiq.rb
This gives us a simple background job which anonymises users who have been deactivated for more than 5 years. We introduce the sidekiq-scheduler gem for the purpose of scheduling jobs in a cron-like manner.
(Also worth noting that the sidekiq_scheduler_spec basically just checks for typos in the Sidekiq schedule config, in case we ever need to tweak that again or add additional jobs.)
> Anonymise users background job

- app/services/export/activities_level_b.rb
- config/environments/test.rb
- spec/controllers/exports_controller_spec.rb
- spec/features/beis_users_can_download_exports_spec.rb
- spec/services/export/activities_level_b_spec.rb
Note that these are separate changes to the budget window changes, which are opened in a [separate card](https://trello.com/c/FGbAceUU/3116-for-each-remaining-fund-show-historical-budgets-when-they-exist)
- Fix IATI identifier coming through as GB-GOV-26 only
- Separate comments by "|"
- For GCRF, remove "ODA or Non-ODA", "ISPF ODA partner countries",  
"ISPF themes", "Tags"
- For GCRF, add "GCRF Strategic Area", "GCRF Challenge Area"
- For ISPF, add "ISPF non-ODA partner countries"
- For Newton, remove "ODA or Non-ODA", "ISPF ODA partner countries", 
"ISPF themes", and "Tags"
- For Newton, add "Newton Fund Country Partner Organisations", 
"Newton Fund Pillar"
- For Other ODA, remove "ODA or Non-ODA", "ISPF ODA partner countries", 
"ISPF themes", "Tags"
> Level B reporting fixes

- app/services/export/activities_level_b.rb
- spec/features/beis_users_can_download_exports_spec.rb
- spec/services/export/activities_level_b_spec.rb
This was always set to DSIT, because we'd been choosing
`activity.organisation.name`
instead of
`activity.extending_organisation.name`.
"Extending" here is a synonym for "partner"!
> Level B export: fix partner org name

- CHANGELOG.md
- app/helpers/activity_helper.rb
- app/views/shared/xml/_activity.xml.haml
- spec/features/beis_users_can_view_an_activity_as_xml_spec.rb
- spec/helpers/activity_helper_spec.rb
Due to a change in DSIT policy, activities where multiple benefiting countries have been reported should only display the associated region of those countries. We use the existing `Activity#benefitting_region` method in the IATI XML now rather than iterating over the benefitting countries and assigning percentages.
We also patch up the specs where previously we were expecting multiple countries to be shown in the XML.
> Changes to how benefitting countries are displayed in IATI XML

- CHANGELOG.md
- Migrate to Rails 7.1 defaults
- Update IATI XML export benefitting countries into single region
> Release 169

- CHANGELOG.md
- app/helpers/activity_helper.rb
- app/views/shared/xml/_activity.xml.haml
- spec/features/beis_users_can_view_an_activity_as_xml_spec.rb
- spec/helpers/activity_helper_spec.rb
This fix slightly undoes the previous work on IATI XML country export where we merged `benefitting_countries` into one region; we were overzealous in that work, in that cases where there was only one benefitting country should have remained as they were previously, ie. rendered in the XML as a single country rather than a region.
> Fix IATI XML country export where there is only one benefitting country

- config/environments/development.rb
We *should* do this in dev, but can't at present because of
```
AbstractController::ActionNotFound at /home
The index action could not be found for the :verify_policy_scoped
callback on HomeController, but it is listed in the controller's
:only option.
```
In order to turn it on in dev, we need to do a bit of review/refactoring around when callbacks are called. At present, we allow them to fail silently when not applicable. This isn't a behaviour Rails 7.1 and up encourages, but we're on our last day of our last sprint and can't fix this now.
> Turn off Rails 7.1 callback checks in dev

- CHANGELOG.md
- app/validators/date_within_boundaries_validator.rb
- spec/features/beis_users_can_edit_a_report_spec.rb
- spec/validators/date_within_boundaries_validator_spec.rb
Ticket [20715](https://dxw.zendesk.com/agent/tickets/20715) flagged two activity start dates that did not pass validation as they were more than 17 years in the past. 
We agreed with the client to add 10 years to this validation range, ie. to allow planned and actual activity start dates up to 27 years in the past. This will allow the resolution of this ticket, and also help to support the service as it matures and is more likely to need historical activity records added that exceed the previous 17 year limit.
> Alter the maximum age of an activity start date

- CHANGELOG.md
- Remove the supporting code for the one-off data migration related to the new DSIT transparency identifier (rake task and continuing/non-continuing activities exports)
- Alter date boundary to allow activity start dates 27 years in the past
- Upgrade nokogiri from 1.18.2 to 1.18.4
- Upgrade json from 2.10.1 to 2.10.2
- Upgrade rack from 2.2.11 to 2.2.13
> Release 174

- package.json
This reverts commit 4d564a91a28a2ca8825594149b72210413be9961.
We have identified this commit as causing problems with yarn installing sass at build time
[Release 174 ](https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/releases/tag/release-174)is currently failing to deploy in production. The build step of the AWS pipeline that manages the deployment of new changes is failing, meaning the deploy step is never triggered. The docker build is failing because yarn is unable to install sass. 
Our investigation of the causes of this failure has identified this previously unreleased commit as causing the problem with the sass installation. At this time we do not know what aspect of the changes introduced here has caused the problem. We have unreleased code that must …
> Revert "Move build-time packages to devDependencies"

- app/javascript/application.js
@rails/ujs is used to transform links to enable deletes. It creates a hidden
form and submits the request as a POST request with a hidden field
_method=delete.
A recent change means this is not working, users therefore cannot perform
important actions.
Calling `start` isn't supposed to be necessary, but seems to fix the issue.
We may need to do a review of these links to see if we can use an improved
method vs Rails UJS.
> Fix rails ujs links not working

- CHANGELOG.md
- app/controllers/activity_redactions_controller.rb
- spec/features/users_can_edit_an_activity_spec.rb
Changing the publish to IATI status of an activity now no longer also changes the status of the child activity
Ticket [20719](https://dxw.zendesk.com/agent/tickets/20719) requested that Level C and D activities have their 'publish to IATI' status decoupled. That is, if a parent activity is set to 'publish: yes', this should _not_ automatically also publish its child activities. This change was requested as it is not always desirable for every child activity of a parent to be published, or to be published at the same time as the parent. 
Previously, the update function of the activity_redactions_controller bundled two updates together, an update to the activity, and to any child activities found for that activity. This PR removes the references to child activities, updating the publish to …
> Decouples published to IATI status between parent and child activities

- CHANGELOG.md
Release 177
- Decouples the publish to IATI status of parent and child activities
> Release 177

- CHANGELOG.md
- Loosen restrictions on editing activity budgets (those associated with projects and third-party projects).
Previously, (1) there had to be a currently-editable report associated with the same organisation and fund, and (2) the budget had to be associated with that report. This removes the second requirement, allowing budgets associated with previously-approved reports can still be edited provided they meet the first requirement
- In case an existing budget has no associated report, associate it with the
current editable report when attempting to update, making the budget valid
> Release 178

- CHANGELOG.md
- doc/support/download_activities_for_annual_impact_metrics.md
- lib/tasks/annual_fund_impact_metrics_activities.rake
- spec/factories/activity.rb
- spec/lib/tasks/annual_fund_impact_metrics_activities_spec.rb
This updates the KPI-exporting script with latest requirements
- Only select activities with actuals from 2021,2022,2023,2024
- Remove restriction for only including Actuals in past 2 years
- Add "Fund" column to specify which fund an activity belongs to
- Export Level C activities for specified organisations, otherwise only
export Level D activities.
- Generate a CSV file for each organisation
It also refactors the tests slightly to make them (I hope) more readable.
> Update KPI-exporting script to meet new requirements

- lib/tasks/annual_fund_impact_metrics_activities.rake
- spec/lib/tasks/annual_fund_impact_metrics_activities_spec.rb
Ignores case when looking up Level C-reporting orgs in KPI script.
This rake task was failing to produce the expected output on production as some Organisations have upper case names.
Alternatively, we could resolve this with an ID, but we're unsure whether identifiers are consistent across environments.
In a perfect world, we'd allow users at DSIT to specify in the UI whether or not an Organisation reports at Level C or D e.g. with a checkbox, but this is a larger piece of work.
> Handle case insensitivity in kpi script
