UKGovernmentBEIS/beis-report-official-development-assistance

.env.test
.travis.yml
config/initializers/assets.rb
doc/architecture/decisions/0005-use-travis-for-ci.md
spec/features/visitors/home_page_spec.rb

- Use Travis as BEIS's tool of choice
- We have no platform to deploy to so this only runs tests on pull requests and pushes. Soon we will be able to configure it to deploy on pushes to master and develop to GPaaS

Use Travis for continuous integration

---

.travis.yml

Deploy to heroku `beis-roda-staging` app after a successful build on the `develop` branch

Add deploy step to travis build

---

README.md

Mention the Heroku staging environment in the README

Mention the Heroku staging environment in the README

---

CHANGELOG.md
README.md
doc/adr/0002-use-a-changelog-for-tracking-changes-in-a-release.md

Trello: https://trello.com/c/aabjqNFM/46-create-a-changelog
Add a blank CHANGELOG.md and details of how to use it in README

Add a CHANGELOG.md and reference it in the README

---

doc/architecture/decisions/0007-use-a-changelog-for-tracking-changes-in-a-release.md

This ADR was created in `/doc/adr/` in error, it should be in
`/doc/architecture/decisions`

Move Changelog ADR to the correct place

---

app/controllers/application_controller.rb
app/controllers/dashboards_controller.rb
app/controllers/visitors_controller.rb
spec/features/users_can_sign_in_spec.rb
spec/features/users_can_sign_out_spec.rb
spec/support/authentication_helpers.rb

Temporarily revert commit d40fb6f which has broken Auth0
Will be superseded by https://github.com/UKGovernmentBEIS/beis-report-overseas-development-assistance/pull/28

Revert auth0 changes

---

CHANGELOG.md
README.md
config/locales/en.yml
package-lock.json
package.json
spec/features/public/visitors/home_page_spec.rb

- Switch from "Overseas" to "Official" after spotting the mistake when setting up GPaaS today.

Correct name of the service

---

app/controllers/staff/funds_controller.rb
app/presenters/transaction_presenter.rb
app/views/staff/funds/show.html.haml
app/views/staff/shared/transactions/_table.html.haml
config/application.rb
config/locales/codelists/2_03/iati.en.yml
spec/presenters/transaction_presenter_spec.rb

https://trello.com/c/XBWmcFaf/130-add-a-transactionpresenter-to-tidy-up-transaction-display
Add a TransactionPresenter to streamline the display of Transactions in the fund#show page.

(130) Add a TransactionPresenter to tidy up transaction display

---

CHANGELOG.md
app/controllers/staff/organisations_controller.rb
app/views/staff/organisations/_form.html.haml
app/views/staff/organisations/edit.html.haml
app/views/staff/organisations/new.html.haml
app/views/staff/organisations/show.html.haml
config/locales/en.yml
config/locales/models_and_forms.en.yml
config/routes.rb
spec/features/staff/users_can_edit_an_organisation_spec.rb

- refactor org new form away from simple form
- refactor org new form into a reusable partial
- new org edit form

56 users can edit an organisation

---

CHANGELOG.md
app/controllers/staff/transactions_controller.rb
app/views/staff/shared/transactions/_table.html.haml
app/views/staff/transactions/_form.html.haml
app/views/staff/transactions/edit.html.haml
app/views/staff/transactions/new.html.haml
config/locales/en.yml
config/locales/models_and_forms.en.yml
config/routes.rb
spec/features/staff/users_can_edit_a_transaction_spec.rb

Trello: https://trello.com/c/FQXbKkVH/100-edit-transactions-on-a-fund
* Edit transactions associated to a fund.
* Refactor Transaction#new view to use a re-usable Transaction create/edit form

(100) Edit transactions

---

.travis.yml
Dockerfile
README.md
doc/architecture/decisions/0013-travis-only-tests-with-docker-containers.md

* reduce every build time from 17 minutes down to 4 by reducing the number of bundles from 3 to 1, and adding parrelisation to the remaining bundle
* the [dxw tech team have a decision whereby we think it is best to test in CI with docker images](https://github.com/dxw/tech-team-rfcs/blob/master/rfc-013-use-docker-to-deploy-and-run-applications-in-containers.md) where we are using Docker images in live environments 
* add a build status badge to the top of our readme

(163) Travis tests the application using Docker

---

app/views/staff/activity_forms/_wrapper.html.haml
app/views/staff/transactions/new.html.haml

Removed paragraphs form the back links that might cause styling issues
No changes

remove paragraph elements from back links

---

CHANGELOG.md
db/migrate/20200116172705_add_service_owner_to_organisations.rb
db/schema.rb
spec/models/organisation_spec.rb

We only imagine this to be done very infrequently by a developer in the console, so there is no UI for this.
co-authored-by: Tom <tomhipkin@gmail.com>

Provide a way to flag an organisation as BEIS

---

spec/spec_helper.rb

This is a re-submission of @leeky PR #144 after the remodelling work. Nothing changed.

(chore) re introduce coveralls running locally

---

config/locales/en.yml

Quick one I spotted that got missed on programme.

(fix) Update programme translation

---

spec/models/transaction_spec.rb

This will make it easier to read and know what test coverage a method has as well as knowing where to add new tests.
I was looking into money/currency validations and found this when testing locally. Though I didn't implement anything this is probably worth contributing to make it easier for the next person.

Refactor transaction unit tests to group them by method

---

doc/console-access.md

- document the steps I had to use to seed the database of our new production environment so that we can follow these steps next time

Document how we can get console access on GPaaS

---

deploy-terraform.sh

Also make it safer by using {} and ""

Use TRAVIS_BUILD_NUMBER not TRAVIS_BUILD

---

README.md
doc/deployment-process.md

Inspired by https://crown-commercial-service.github.io/ReportMI-service-manual/#/deployments?id=production which adds steps to the pull request model of creating releases and updating the change log.
Change logs are a a decision we've already made as dxw to track project progress https://github.com/dxw/tech-team-rfcs/blob/master/rfc-019-use-changelogs-to-track-changes.md.
This is the process used in release-1 as it was better to have some structure around the changelog. I'd like to use this pull request to check what we want to do and if there are any learnings and improvements we can make.

Document deployment steps for production and staging

---

README.md

Update to the Readme before we turn off Heroku.

Update staging and production URLS after the move from Heroku

---

config/locales/models_and_forms.en.yml

Fix typo - `refrence` -> `reference`

Fix typo in the word "reference"

---

.travis.yml
Dockerfile
README.md
app/views/layouts/application.html.haml
docker-compose.test.yml
docker-entrypoint.sh
spec/features/public/visitors/javascript_detection_spec.rb
spec/support/capybara.rb
spec/support/omniauth.rb
travis-docker-push.sh

The goal of this work was to introduce the ability for the team to test JavaScript features in the test suite.
The approach is a standard one, we use [Capybara](https://github.com/teamcapybara/capybara#drivers) and pass `js: true`  to any specs that need to test JS behaviour. This relies on there being a web broweser and selenium driver available for use.
I've opted to use Firefox and Geckodriver (instead of Chrome and chrome driver) for no other reason that it is the default, if we feel strongly, switching the browser and driver should be relatively straight forward.
In local development you will need to have both Firefox and Geckodriver installed, a simple way to achieve this is in the readme as part of this work. A way to bypass the JS test is also documented for developers who may …

(507) Setup JavaScript testing environment

---

app/views/staff/transactions/_form.html.haml
config/locales/en.yml
config/locales/models_and_forms.en.yml

Changed content for transaction:
- title
- reference
- description
- date
This is what it should look like from the content mockup. Please check this before merging. Thanks!

Updated transaction content

---

doc/console-access.md

In https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/296
the location of the app inside the docker container was changed from /srv to
/app, but the docs were not updated to reflect this.

Update app location in docs

---

db/seeds/activity.rb
db/seeds/organisations.yml
spec/factories/activity.rb
spec/features/staff/users_can_manage_extending_organisation_spec.rb

Trello: https://trello.com/c/czIkj4tW
While working on a different feature, I noticed our seeds file does not create activities that pass the IATI validator, as they were missing important bits of information in regards to extending organisations and reference numbers.
This PR introduces some changes to the activity seeds file, where now all the activities created will pass the IATI public validator. In addition to a fund, I have created two programmes that belong to the fund, and one project that belongs to one of the programme. This should help us to test the app faster, since we do not have to create programmes manually every time.
Other changes in this PR are fixes needed in order to seed the database with valid data. One change is an incorrect reference number in one of the …

(509) Seeds file to create valid activities

---

CHANGELOG.md
app/views/public/visitors/index.html.haml
config/locales/en.yml

User tested and content designed for the start page see:
https://trello.com/c/iHrP48FW

(566) Add start page content

---

config/locales/models_and_forms.en.yml

This was recommended by the external content review

Removed a full stop after CRS codes

---

config/locales/en.yml

Needed a question mark as it was asking the user a question

Added a ? to the focus area category stage

---

config/locales/models_and_forms.en.yml
spec/support/form_helpers.rb

Deleted a full stop after a link to the IATI descriptions

Removed a stray full stop

---

config/locales/models_and_forms.en.yml

Wrote out SME in the sector category helper text

Wrote SME in full in helper text

---

CHANGELOG.md
db/data/20200529093420_ingest_uksa_iati_data.rb
db/data_schema.rb

- ~~this is blocked until the following data migration has been run https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/blob/develop/db/data/20200521165254_add_iati_ids_to_existing_uksa_data.rb through a production deploy~~ this has now happened https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/434
- run the task to automatically ingest historic data from UKSA
- use of the fixture as the source - IATI data has not been changed or added to by BEIS in the last 6 months. The fixture we've used for testing was also used to set up the pentest environment which has had it's data verified by Dan https://dxw.slack.com/archives/CN0H2L066/p1590769465039200
- this task will fail if there is no organisation with the `iati-reference` for …

Script the ingesting of UKSA IATI data onto production environments

---

config/locales/models/budget.en.yml

Changed "Status" to "Budget status" to be consistent with "Budget type"
Changed "Value" to "Budget amount"

Changed "status" title and "value" title

---

config/locales/models/user.en.yml

Changed title from "Active?" to "What is the user's status?"
Deleted some of the hint text so it's now "Deactivated users cannot login"

Changed title and hint text

---

db/data/20200622145847_delete_unwanted_activities_2.rb
db/data_schema.rb

Trello: https://trello.com/c/Ow0W9ZMP/743-remove-three-unneeded-activities-from-production
Remove 3 unwanted & unfinished activities from production

(743) Remove 3 unwanted activities from production

---

config/locales/models/transaction.en.yml

Changed "Value" to "Transaction amount" as recommended in the content review

Changed "Value" to "Transaction amount"

---

config/locales/models/activity.en.yml

Changed "Your unique identifier" to "Enter your unique identifier" recommended in the content review.

Changed unique identifier title

---

CHANGELOG.md
app/assets/stylesheets/application.css.scss

The application uses a lot of horizontal space so it makes sense to
increase the width of the layout from the standard 960px to a larger
value.
Once we enter a public beta phase we can always tweak the value based on
user analytics.

Increase application layout width

---

CHANGELOG.md
app/controllers/public/accessibility_statement_controller.rb
app/views/layouts/application.html.haml
app/views/public/accessibility_statement/index.html.haml
config/locales/views/accessibility_statement.en.yml
config/locales/views/footer.en.yml
config/routes.rb
spec/features/user_can_view_static_pages_spec.rb

Content provided and confirmed by BEIS.
https://docs.google.com/document/d/1hd059DAlgpSOP2K0cckciaG8-P4yZvOOCERbj7nd3ek/edit#heading=h.jt6s7di0pvrz
Added 'opens in a new window' in-line with links in the main application.

(696) Add accessibility statement

---

config/locales/models/activity.en.yml

A small content change that fell through the gaps.

(content) Update the label of the identifier step

---

CHANGELOG.md
app/views/staff/activities/financials.html.haml

To be consistent with other activity levels.

(fix) Move budgets on the progrmame financials tab

---

config/locales/models/transaction.en.yml

This has been changed on the table view and this should match.

(content) Update label on transaction edit

---

config/locales/models/budget.en.yml

To be consistent with other parts of the services, changed this to "Budget amount"

Changed "Value" to "Budget amount"

---

CHANGELOG.md
app/controllers/staff/activity_forms_controller.rb

There is more potential for refactoring here as the controller action remains lengthy. I do however feel there is enough value here to merit proposing it already. I can see value in improved readability which means we can be more confident in adding or changing steps and in removing the _many_ database saves. Let me know what you think!
* massively reduce the number of times we hit the database by using `assign_attributes` instead of `update`. The former does not hit the database as the latter does [1]
* `render_wizard` continues to be responsible for trying to save the object and controlling what to render based on success or failure. This wasn't clear to me until I read the gem documentation [2] so I added a comment for future readers to make it clear where the save was happening
* …

(796) Refactor ActivityFormController#Update action

---

db/data/20200722154738_migrate_uksa_gcrf_mappings.rb

Second attempt at making MigrateUksaGcrfMappings more tolerant

---

config/locales/models/transaction.en.yml

Changed "Type" to "Transaction type" and removed the hint text as it's a drop down menu so there's less need for hint text.

Merged the transaction type hint text with the title

---

config/locales/models/activity.en.yml

The content review recommended using "add" over "create" on the call to action buttons so I changed this to "add activity" instead of "create activity"

Changed "create activity" button to "add activity"

---

config/locales/models/organisation.en.yml

Changed the call to action button from "create organisation" to "add organisation"

Changed "create organisation" to "add organisation"

---

config/locales/models/user.en.yml

Changed the call to action button from "Create user" to "Add user" as recommended in the content review

Changed "Create user" button to "Add user"

---

app/views/shared/_google_tag_manager_body.html.haml
app/views/shared/_google_tag_manager_head.html.haml
spec/support/capybara.rb

Speed up test suite by not loading Google Tag Manager code over the internet.

(904) Skip Google Tag Manager during tests

---

CHANGELOG.md
app/views/staff/extending_organisations/edit.html.haml
config/locales/models/activity.en.yml

This was identified during a content review.

(841) Update content for Extending organisation

---

config/locales/models/activity.en.yml

To be consistent with the other buttons and the content review

Changed button from "Create activity" to "Add activity"

---

config/locales/models/activity.en.yml

Updated the activity details summary page with recommendations from the content review
Changed "Focus area" to "Economic/societal area" to be consistent with the question field
Changed "Flow" to "Flow type" for the same reason
I realise that this makes the titles longer on this page so if this doesn't work then feel free to not to approve this PR

Changed "Focus area" and "Flow" on activity details

---

app/controllers/staff/transaction_uploads_controller.rb
app/models/activity.rb
app/services/import_transactions.rb
app/views/staff/activity_forms/roda_identifier.html.haml
app/views/staff/shared/activities/_activity.html.haml
db/seeds/activity.rb
spec/features/staff/users_can_edit_an_activity_spec.rb
spec/features/staff/users_can_upload_transactions.rb
spec/models/activity_spec.rb
spec/services/import_transactions_spec.rb

This is refactoring triggered by a conversation I had with @lozette, to make it clearer how one should get the RODA identifier for an activity.

Add Activity#roda_identifier

---

app/services/ingest_csv.rb
app/services/ingest_csv_row.rb
spec/fixtures/csv/transactions.csv
spec/services/ingest_csv_row_spec.rb
spec/services/ingest_csv_spec.rb

Given a CSV with the following columns, find an activity (determined by `delivery_partner_identifier`) and either create or update an associated transaction keyed off the `description` field:
- delivery_partner_identifier
- description
- transaction_type
- date
- currency
- value
- receiving_organisation_name
- receiving_organisation_type
- receiving_organisation_reference

(986) Ingest financials from CSV

---

CHANGELOG.md
app/views/shared/_navigation.html.haml

It was 🐞’n me and there was a card.

(861) Sign out link not active on Users page

---

Brewfile
CHANGELOG.md
Gemfile
Gemfile.lock
Procfile
README.md
doc/architecture/decisions/0024-use-scripts-to-rule-them-all.md
lib/tasks/shellcheck.rake
script/bootstrap
script/console
script/server
script/setup
script/test
script/update

This adds scripts using the [Scripts to Rule Them All](https://github.com/github/scripts-to-rule-them-all) pattern to make it easier to get started with the app.

Add scripts to rule them all

---

CHANGELOG.md
app/helpers/codelist_helper.rb
config/locales/models/activity.en.yml
spec/factories/activity.rb
spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
spec/helpers/codelist_helper_spec.rb
spec/support/form_helpers.rb

https://trello.com/c/B6JVmnyT/1112-update-aid-type
https://trello.com/c/DS4wCbIn/868-update-aid-type-radio-buttons
- Remove unused aid types.
- Replace the hints in the aid type form with shorter, more accessible copy.
- Rename the aid activity with more user-friendly text

(1112) Update aid type

---

CHANGELOG.md
app/controllers/staff/activity_forms_controller.rb
app/models/activity.rb
app/presenters/activity_presenter.rb
app/services/ingest_csv.rb
app/services/ingest_iati_activities.rb
app/views/staff/activity_forms/fstc_applies.html.haml
app/views/staff/shared/activities/_activity.html.haml
config/locales/models/activity.en.yml
db/migrate/20201106110954_add_fstc_applies_to_activity.rb
db/schema.rb
spec/factories/activity.rb
spec/features/staff/users_can_create_a_fund_level_activity_spec.rb
spec/features/staff/users_can_edit_an_activity_spec.rb
spec/models/activity_spec.rb
spec/presenters/activity_presenter_spec.rb
spec/support/form_helpers.rb

This adds a new field to report free standing technical cooperation. Some of this could be gleaned from the aid type further down the line, but this is probably good enough for now.

I can report free standing technical cooperation

---

CHANGELOG.md
spec/helpers/codelist_helper_spec.rb
vendor/data/codelists/IATI/2_03/activity/sector.yml

Trello: https://trello.com/c/iiuQNo4c
We are seeing sector codes that are not in our codelist, since we added the codelist last year we need to update it now.
This PR introduces the latest DAC 5 digit sector code list from IATI, in which new sectors have been added and others have been modified.

(1319) Updated sector codelist

---

CHANGELOG.md
config/locales/models/activity.en.yml

Trello: https://trello.com/c/f1neWj0q
The hint text for the FSTC form step on the Activity journey has been modified to be in line with the radio options available.

(1337) Hint text for `fstc` modified

---

README.md

This was missed off from #814, and badges are important 👍

Change CI Badge to Github actions

---

CHANGELOG.md
app/controllers/staff/planned_disbursements_controller.rb
app/models/report.rb
app/services/export_activity_to_csv.rb
lib/financial_period.rb
spec/lib/financial_period_spec.rb
spec/models/report_spec.rb
spec/rails_helper.rb
spec/services/export_activity_to_csv_spec.rb
spec/support/time_helpers.rb
spec/support/time_travel_helpers.rb

(1334) Add previous quarter's actuals to CSV export

---

.github/workflows/deploy.yml

I got the syntax wrong. Looking at the docs, this should work now.

Fix deploy conditionals

---

README.md
doc/deployment-process.md
doc/manage-environment-variables.md
terraform/README.md

There's still a few mentions of Travis sneaking around

Update CI-related docs

---

app/controllers/staff/activity_forms_controller.rb
app/services/activity/updater.rb

The ActivityFormsController has a lot of repetition and makes the controller quite large. I've factored all the update actions into a lean(er) class that accepts the activity and the specific step, then works out which parameters to fetch and apply, as well as any extra steps that need to be performed. I haven't bothered with any unit tests for this class, which does make me a little anxious, but I think it's fine, as this is all covered by feature tests.

(1403) Refactor ActivityFormsController

---

.rspec
script/test
spec/features/public/visitors/home_page_spec.rb
spec/features/staff/organisation_show_page_spec.rb
spec/lib/tasks/import_activities_spec.rb
spec/lib/tasks/invalid_activities_spec.rb
spec/spec_helper.rb
spec/views/staff/shared/message_spec.rb

- Restore `progress` style formatting outside of CI when running whole suite
- `script/test` no longer creates unused `test` user
- Disable [monkey patching](https://rspec.info/blog/2014/05/notable-changes-in-rspec-3/#zero-monkey-patching-mode)

Some RSpec tweaks

---

doc/database-backup-and-restore.md

Over time we've developed a quicker, simpler and more robust way to do
this.

(chore) Update docs for copying production data to local

---

CHANGELOG.md
app/views/public/visitors/index.html.haml
app/views/staff/activity_forms/_wrapper.html.haml
app/views/staff/reports_state/submit/complete.html.haml
app/views/staff/reports_state/submit/confirm.html.haml
app/views/staff/transaction_uploads/new.html.haml
config/locales/views/start.en.yml

Update the service with links to relevant support guidance. **Please note that I wrote the text surrounding the additional links, so it probably would benefit from being double-checked by a content designer.**

(1428) Add relevant guidance links to different parts of  RODA

---

doc/architecture/decisions/0029-application-text-encoding.md

We thought it would be valuable to included an ADR arround the issues we faced and the learnings we took from the text encoding work we had to do recently.
This is also in the decision log 
https://docs.google.com/spreadsheets/d/1BW12sa9_5N4lAt-ITODO2KPzAxd9b2umZOrRtdeg2_s/edit#gid=1451037787

(1497) Add ADR for text and encoding

---

CHANGELOG.md
app/assets/stylesheets/partials/_forms.css.scss
app/controllers/staff/planned_disbursement_uploads_controller.rb
app/controllers/staff/transaction_uploads_controller.rb
app/views/staff/planned_disbursement_uploads/_upload_form.html.haml
app/views/staff/planned_disbursement_uploads/new.html.haml
app/views/staff/planned_disbursement_uploads/update.html.haml
app/views/staff/transaction_uploads/_upload_form.html.haml
app/views/staff/transaction_uploads/new.html.haml
app/views/staff/transaction_uploads/update.html.haml
config/locales/models/planned_disbursement.en.yml
config/locales/models/transaction.en.yml
db/seeds/activity.rb

- The CSV template download links for actuals and forecasts are more prominent (from button style to link style, and given a medium heading size)
- The new upload page for actuals and forecasts includes a modified version of the upload form, where the label is styled to be visually the same weight as the CSV download link
- The error report page for actuals and forecasts has different copy (label and hint) for the upload form (compared to the initial upload page)

(1451) Upload financial data journey

---

CHANGELOG.md
app/helpers/codelist_helper.rb
app/views/staff/shared/activities/_activity.html.haml
spec/features/staff/beis_users_can_create_a_fund_level_activity_spec.rb
spec/features/staff/beis_users_can_create_a_programme_level_activity_spec.rb
spec/helpers/codelist_helper_spec.rb
spec/models/codelist_spec.rb
spec/support/form_helpers.rb
vendor/data/codelists/IATI/2_03/activity/sector.yml
vendor/data/codelists/IATI/2_03/activity/sector_category.yml

Code lists change over time and the reason for storing them as vendor data is to allow the team to replace the old list with the new one with minimal effort.
The sector codes where updated in Feb 2021 so we want to offer the new values for Q4 reporting.
The first commit replaces the sector code and sector category code lists.
The second commit addresses an interesting problem that relates, full story in the commit messages.

(1536) Update sector codes

---

terraform/README.md

This updates `terraform/README.md` to accurately reflect what we did to deploy to `pentest` most recently, correcting some mistakes and filling in some missing details that might not be obvious to people who've not done this process before.

Update terraform docs

---

CHANGELOG.md
app/controllers/staff/activity_forms_controller.rb
app/controllers/staff/reports_controller.rb
app/models/activity.rb
app/views/staff/shared/activities/_activity.html.haml
spec/controllers/staff/activity_forms_controller_spec.rb
spec/features/staff/users_can_edit_an_activity_spec.rb
spec/models/activity_spec.rb
spec/presenters/activity_presenter_spec.rb
spec/services/activities/import_from_csv_spec.rb
spec/support/form_helpers.rb

- GCRF Strategic area is collected at level C and D

(1625) GCRF Strategic area is collected at level C and D

---

CHANGELOG.md
app/views/staff/activity_forms/purpose.html.haml
config/locales/models/activity.en.yml

Add supporting hint text about the soft limits to title and description

Add supporting hint text to title and description

---

spec/features/staff/users_can_create_a_budget_spec.rb
vendor/data/codelists/BEIS/budget_type.yml

Fix typos in budget types

---

doc/glossary.md

I’ve focused on differences between code language and domain language.
For the domain language we have the growing data dictionary on ZenDesk, which I suggest we don’t duplicate. Same for the various acronyms that are public knowledge.

(1607) Add glossary of terms for internal use

---

CHANGELOG.md

- Allow forecasts to have negative values
- Add links to Guidance for all Activity fields that have guidance

Release 45

---

doc/glossary.md

Add SID to the glossary, expand upon budget, and attempt to define transfer.

Expand the glossary

---

CHANGELOG.md

- Link to the Service performance Zendesk article in the footer
- Add functionality to search for activities by identifiers and title
- Record providing organisation for budgets
- Migrate to Webpacker for compiling JavaScript
- Show activities in an collapsable and expandable tree view table

Release 47

---

CHANGELOG.md
app/views/staff/activity_forms/sector_category.html.haml

- Replace the broken sector code hint link with an easier to maintain BEIS Zendesk link

Replace broken hint link with BEIS Zendesk link

---

doc/deleting-things-from-production.md

- Document the process of deleting activities

Document the process of deleting activities

---

CHANGELOG.md
app/views/public/visitors/index.html.haml

Also move the Matched Effort Provider entry to unreleased, as it's not yet released

(1756) Update the request an account link

---

doc/importing-new-delivery-partner-data.md

We now require Reports to be present when importing Activity data for levels C and D, so I've moved the Reports documentation higher up, as well as tweaking some of the wording to be more generic and applicable to any time we do onboarding, not just Q3 2020

Update import documentation

---

app/views/layouts/application.html.haml
config/locales/models/activity.en.yml

- Remove dodgy / invisible characters

Remove invisible characters

---

doc/background-jobs.md

Adds some documentation about debugging Sidekiq via a Rails console running on the "worker" instance.

Add documentation on Sidekiq debugging

---

.github/workflows/deploy.yml

- Fix the step that invokes the deploy notification script.

Fix script name

---

doc/activity-identifiers.md

We recently added a new, auto generated RODA identifier and want to
document this change.

Update the activity identifier documentation

---

config/locales/models/organisation.en.yml
spec/models/organisation_spec.rb

The existing error message was misleading

Update Organisation format error message

---

db/schema.rb

- Fixes the schema, which got broken by what looks like a merge conflict resolution gone left

(2113) Schema has borked reports refunds

---

config/locales/models/transaction.en.yml

- Fix a typo
- Remove the button styling from a link
- Rephrase the link text so it integrates more naturally in the paragraph

(2045) Fix guidance for uploading actuals

---

.github/workflows/trigger_rebase.yml

The JQ query I added in #1306 wasn't quite right. This PR should fix it

Fix JQ query to get the first PR number

---

README.md
doc/email-notifications.md

I wanted to see the emails the applicaiton sends so I looked for our
docs on the subject, as there weremn't any, I wrote this up as a
starter.

Email notification documentation

---

CHANGELOG.md

- BEIS users can export the external income per organisation per fund

Release 72

---

db/migrate/20210907123425_add_timestamps_to_budgets.rb
db/schema.rb

- Add timestamps to the budgets table

(2157) Add timestamps to the budgets table

---

CHANGELOG.md
app/assets/stylesheets/partials/_table.scss

- Force word wrapping in error value cells

(2160) Force word wrapping in error value cells

---

doc/benefitting_countries_and_regions.md

Add developed docs for benefitting countries, regions and geography history.
https://trello.com/c/PXhke6Dd

(2084) Chore: Document geography

---

CHANGELOG.md

2021-09-21
- BEIS users have a link to delivery partners reports on the homepage
- Show the activity summary on all activity tabs
- Delivery Partner can post an adjustment to an historic
financial period
- Users can export budget data

Release 74

---

spec/controllers/staff/activities_controller_spec.rb
spec/controllers/staff/activity_uploads_controller_spec.rb
spec/features/staff/users_can_view_an_activity_as_xml_spec.rb
spec/models/iati/xml_download_spec.rb

- Rephrase specifications to reflect current reality

(2186) Ensure the region logic is clearly described by the IATI export specs

---

CHANGELOG.md
db/data/20210927103536_fix_coherence_and_impact_code.rb
spec/models/activity_spec.rb
vendor/data/codelists/BEIS/gcrf_strategic_area.yml

- Fix the GCRF strategic area code for Coherence and Impact
**Includes a data migration to fix the almost 300 existing activities with the wrong code.**

Fix Coherence and Impact GCRF strategic area code

---

doc/exports.md

Here it is! The final PR for this work! 
To help developers and anybody else understand this feature, some brief guidance around it.
I was not 100% sure how to pitch this, but I am confident we we learn as we write more docs and can come back and improve.

(2158) Chore: Spending breakdown export developer doc

---

doc/0_index_of_contents.md
doc/support_tasks/create_new_report.md

When a new delivery partner joins BEIS ODA reporting a developer is
required to carry out this process.

(2218) Chore: Document creating a new report

---

CHANGELOG.md
app/models/activity.rb
app/views/staff/reports/_tab.html.haml
app/views/staff/reports/activities.html.haml
app/views/staff/reports/budgets.html.haml
app/views/staff/reports/variance.html.haml
app/views/staff/shared/reports/_tabs.html.haml
config/locales/models/report.en.yml
spec/features/staff/users_can_create_a_comment_spec.rb
spec/features/staff/users_can_view_actuals_within_report_spec.rb
spec/features/staff/users_can_view_reports_spec.rb
spec/models/activity_spec.rb
spec/support/comment_form.rb
spec/support/report_page.rb

Include adjustments of type `Actual` in the variance calclulation.
Also moves some content to the locales.
https://trello.com/c/FX0NPZux

(2196) Feature: include adjustments in calculation of variance

---

CHANGELOG.md

- Consolidate links to commnents on the report, variance tab

Release 79

---

app/services/export/spending_breakdown.rb
spec/services/export/spending_breakdown_spec.rb

Nmber 8️⃣ in the series!
Now that the forecast columns behaviour has it's own class
(Export::ActivityForecastColumns from #1437) the spending breakdown report can be
generated using it.
This frees the spending breakdown export itself to only deal with
collating the requirements with which to build the export, but not
actually do the work.
I've also used the in-line fixtures seen elsewhere in the `Export` classes
to make the spec more readable.

(2246) refactor: spending breakdown export uses new forecast column

---

app/models/export/activity_link_column.rb
spec/models/export/activity_link_column_spec.rb

Returns a column of links to activities in the application for use in
exports.
Not yet used in the applicaiton but it is coming…

(2246) feature: activity link column

---

CHANGELOG.md
app/presenters/activity_csv_presenter.rb
config/locales/models/activity.en.yml
spec/presenters/activity_csv_presenter_spec.rb

The ActivityCsvPresenter was not rendering this in a useful way and the
locale was incorrect.

Fix: Free standing technical cooperation in report

---

.github/workflows/deploy.yml
CHANGELOG.md

Adds Ghost Inspector tests to the GitHub action deploy workflow

Ghost Inspector GitHub action

---

.github/workflows/deploy.yml

* Use `suite` instead of `test` for the ghost inspector execution

Fix Ghost Inspector action

---

doc/architecture/decisions/0033-move-towards-more-continuous-delivery.md

As per proposed ADR. Please let me know what you think.

Proposed decision to release code more flexibly

---

spec/models/export/activity_actuals_columns_spec.rb

Caught this whilst looking at something else.

Fix typo in expectation

---

CHANGELOG.md
doc/0_index_of_contents.md
doc/logging.md

Logging documentation

---

CHANGELOG.md
script/bootstrap
script/setup

* Ensures Apple Command Line tools are installed
* Ensures ruby-build is up to date
* Launches postgres and redis containers

Fix setup script

---

CHANGELOG.md

- Refactor setting of implementing organisations to use
unique organisations through new join table

Release 92

---

CHANGELOG.md

- BEIS users can add and edit implementing organisations

release-93

---

README.md
doc/database-backup-and-restore.md

There's probably a lot of discussion that can be had about exactly what should be documented where, but here is a first attempt at getting the challenges we faced today in getting a local environment set up documented.

Add additional local setup steps to README

---

app/mailers/user_mailer.rb
app/models/user.rb
app/views/devise/passwords/edit.html.haml
app/views/devise/passwords/new.html.haml
app/views/devise/sessions/new.html.haml
app/views/user_mailer/reset_password_instructions.text.erb
config/initializers/devise.rb
spec/features/staff/users_can_reset_password_spec.rb

- Allow users to reset their password
- Use GOV.UK Notify mailer

(2379) Resetting user password

---

app/controllers/staff/users_controller.rb
app/mailers/user_mailer.rb
app/services/create_user.rb
spec/factories/user.rb
spec/features/staff/beis_users_can_invite_new_users_spec.rb
spec/services/create_user_spec.rb
spec/support/custom_email_matchers.rb

- Admins can invite users
- Users receive the welcome email with a link to reset their password

(2377) Admin invites a user

---

app/views/staff/activity_uploads/new.html.haml

http://localhost:3000/reports/23a9d595-5c6a-40bb-831e-3354d797cde3/activity_upload/new

Fix unstyled text

---

doc/deployment-process.md

Tidy up some markdown formatting issues and a couple of sentences that didn't quite read smoothly the first time.

Minor improvements to deployment docs

---

CHANGELOG.md

- Add 'Other ODA' fund
- Change the HTML title tag of the Users page to be Users, not Home
- Prevent server errors when a mobile number is invalid
- Fix bug where comments on actuals were not being included in activity
comments

Release 101

---

spec/features/staff/users_can_create_an_external_income_spec.rb
spec/services/export/report_spec.rb

Fix two fragile tests which broke over the weekend, when the financial year changed.

Fix: fragile tests breaking on change of financial year

---

CHANGELOG.md

- Remove 33 ineligible countries from RODA configuration

Release 107

---

CHANGELOG.md

release 109

---

CHANGELOG.md

- Do not parse arbitary text in oda_eligibilities or programme_status as being 0.
https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/1695

Release 110

---

CHANGELOG.md

- Blank Implementing Organisations fields leave the current Implementing Organisations list unchanged

Release 112

---

CHANGELOG.md

release 115

---

CHANGELOG.md
app/controllers/staff/activity_forms_controller.rb
app/models/activity.rb
app/models/export/activity_attributes_order.rb
app/services/activities/import_from_csv.rb
app/services/report/export.rb
app/views/staff/activity_forms/uk_dp_named_contact.html.haml
app/views/staff/activity_forms/uk_po_named_contact.html.haml
app/views/staff/shared/activities/_activity.html.haml
config/locales/models/activity.en.yml
db/migrate/20220913155750_rename_uk_dp_named_contact_to_uk_po_named_contact.rb
db/schema.rb
spec/factories/activity.rb
spec/features/staff/users_can_create_a_project_level_activity_spec.rb
spec/features/staff/users_can_create_a_third_party_project_level_activity_spec.rb
spec/features/staff/users_can_edit_an_activity_spec.rb
spec/models/activity_spec.rb
spec/models/export/activity_attributes_order_spec.rb
spec/services/activities/import_from_csv_spec.rb
spec/support/activity_form.rb
spec/views/staff/shared/activities/activity_spec.rb
vendor/data/guidance.yml

- Replace code references to `uk_dp_named_contact` with `uk_po_named_contact`, including database migration

(2560) Rename `uk_dp_named_contact` to `uk_po_named_contact`

---

spec/controllers/staff/activities/uploads_controller_spec.rb
spec/controllers/staff/level_b/activities/uploads_controller_spec.rb

- Rename importer in spec descriptions

Rename importer in spec descriptions

---

CHANGELOG.md

- Rename `master` branch to `main`

Release 119

---

spec/fixtures/csv/valid_level_b_budgets_upload.csv

The columns in the budgets template have changed (two removed, one moved) since the test fixture (CSV) was created. This brings it in sync to avoid confusion about the columns for future devs

(2636) Sync budgets fixture with template

---

app/controllers/exports/organisations_controller.rb
app/controllers/exports_controller.rb
app/controllers/reports_controller.rb
app/views/exports/index.html.haml
app/views/exports/organisations/show.html.haml
app/views/reports/new.html.haml
spec/views/exports/organisations/show_spec.rb

- Use an instance variable, set in the controller, instead of iterating through all the existing funds in the views
N/A

(2624) Refactor fetching funds

---

CHANGELOG.md

- Improve error message when trying to create child activities on incomplete parent activities

Release 120

---

.github/dependabot.yml

- Configure dependabot to update Actions workflows
N/A

Configure dependabot to update Actions workflows

---

db/schema.rb

"This was generated with Postgres v14.5. It's been changing for a while, and I'd like to check this into the main codebase. We're due to add some new fields for ISPF and I'd like to not muddy the water with these changes.
The one thing I'm a bit confused about here is the removal of the index on `email` which happened automatically." - George
@CristinaRO would you be able to check this out locally, run `script/server` and see if the schema changes at all?

Commit `db/schema` to codebase

---

CHANGELOG.md
app/controllers/activity_forms_controller.rb
app/helpers/codelist_helper.rb
app/models/activity.rb
app/presenters/activity_presenter.rb
app/views/activity_forms/ispf_theme.html.haml
app/views/shared/activities/_activity.html.haml
config/locales/models/activity.en.yml
db/migrate/20221026162057_add_ispf_theme_to_activities.rb
db/schema.rb
db/seeds/activity.rb
spec/controllers/activity_forms_controller_spec.rb
spec/factories/activity.rb
spec/features/beis_users_can_create_a_programme_level_activity_spec.rb
spec/helpers/codelist_helper_spec.rb
spec/presenters/activity_presenter_spec.rb
spec/support/activity_form.rb
vendor/data/codelists/BEIS/ispf_theme.yml

Adds Level B ISPR theme to the Activity model and to the UI multi-step form

(2671) Add Level B ISPF theme form step

---

CHANGELOG.md

- Configure Rollout and Rollout UI gems to allow BEIS users to manage feature flags
- Allow comments on Level B activities from BEIS users
- Add comments column to Level B activities bulk upload template
- Add Level B activity comments to budget exports
- Strip leading/trailing whitespace and line breaks from comments in reports and exports

Release 121

---

doc/deployment-process.md

Use examples to make the release process code even more transparent, e.g. that:
`git tag release-X [merge-commit-for-release]`
should be interpolated like: `git tag release-120 e1156bfd2cf45a0281808edb8342055407c0f253`
and not: `git tag release-120 [merge-commit-for-release]`
nor: `git tag release-X e1156bfd2cf45a0281808edb8342055407c0f253`
nor: `git tag release-X [merge-commit-for-release]`
Also leave out spacing in list consistently - makes auto-numbering easier

Clarify production release process

---

spec/services/actual/import_spec.rb

[hoping this is the intended outcome for this ticket!]
Previously this spec test checked an attribute of the first and second elements in a collection (Active Record Relation), however it was identified that the order of the collection cannot always be guaranteed, therefore the tests need to be adaptable enough to deal with the collection being randomly ordered
This moves away from testing specific expectations on the nth element of the collection, and instead tests that the collection as a whole contains the expected values for the given attribute/association (comment)

(2618) Non-deterministic actuals spec

---

CHANGELOG.md
app/services/activity/import.rb
app/views/level_b/activities/uploads/_fund_section.html.haml
app/views/level_b/activities/uploads/new.html.haml
config/activity_csv_columns.yml
config/locales/models/activity.en.yml
spec/controllers/level_b/activities/uploads_controller_spec.rb
spec/features/beis_users_can_upload_level_b_activities_spec.rb
spec/fixtures/csv/valid_level_b_ispf_non_oda_activities_upload.csv
spec/services/activity/import_spec.rb

Add CSV template download and upload/import for Level B ISPF non-ODA activities

(2644) Add new CSV upload for Level B ISPF non-ODA

---

CHANGELOG.md

- Add ISPF ODA and non-ODA activity bulk uploads - templates will only be visible when the ISPF feature flag is disabled

Release 123

---

CHANGELOG.md
app/models/export/activity_tags_column.rb
app/services/export/report.rb
app/services/export/spending_breakdown.rb
spec/models/export/activity_tags_column_spec.rb
spec/services/export/report_spec.rb
spec/services/export/spending_breakdown_spec.rb

(2685) Include tags in spending breakdown and report exports

---

CHANGELOG.md
app/controllers/reports_controller.rb
app/controllers/reports_state_controller.rb
app/helpers/report_helper.rb
app/jobs/report_export_uploader_job.rb
app/services/export/s3_downloader.rb
app/views/reports/_download.haml
config/routes.rb
db/migrate/20230109155421_add_export_url_to_report.rb
db/migrate/20230110151834_rename_export_url_to_export_filename.rb
db/schema.rb
spec/features/users_can_approve_a_report_spec.rb
spec/features/users_can_view_reports_spec.rb
spec/helpers/report_helper_spec.rb
spec/jobs/report_export_uploader_job_spec.rb

- Upload the report CSV to S3 when the report is approved
N/A

(2709) Upload report CSV to s3 on approval

---

terraform/app.tf

- Give RODA applications access to S3 bucket
N/A

(2709) Give RODA apps access to the S3 bucket

---

terraform/app.tf

- Fixes permissions for app
N/A

Fix app permissions

---

CHANGELOG.md
config/locales/models/activity.en.yml

This question was asked in a yes/no way, but it's an optional multi-select checkbox question. This updates the wording to fit

(2769) Update tags question

---

CHANGELOG.md

- Add page titles for home and activities pages (useful for Google Analytics reporting and accessibility); make page titles and headings consistent on activity form pages
- Update level C/D IATI exports to provide a quarterly summary of all transactions combined (actuals, adjustments and refunds), not just actuals
- Update tags question wording to make more sense for multiple choice

Update CHANGELOG for Release 127

---

CHANGELOG.md
app/controllers/reports_controller.rb
app/controllers/reports_state_controller.rb
app/helpers/report_helper.rb
app/jobs/report_export_uploader_job.rb
app/presenters/report_presenter.rb
app/services/export/s3_downloader.rb
app/views/reports/_download.haml
app/views/reports/_summary.html.haml
config/locales/default.en.yml
config/locales/models/report.en.yml
config/routes.rb
db/migrate/20230116171600_add_export_filename_to_report.rb
db/migrate/20230116173500_add_approved_at_and_uploaded_at_to_reports.rb
db/schema.rb
spec/features/users_can_approve_a_report_spec.rb
spec/features/users_can_view_reports_spec.rb
spec/helpers/report_helper_spec.rb
spec/jobs/report_export_uploader_job_spec.rb
terraform/app.tf
terraform/s3-export-download-bucket.tf

Feature: reports uploaded to s3

---

terraform/app.tf
terraform/s3-export-download-bucket.tf

- create a new private S3 bucket for someone to deploy to staging
- bind the bucket to the app

Add new S3 bucket for private use

---

CHANGELOG.md
vendor/data/codelists/BEIS/ispf_oda_partner_countries.yml

Change Vietnam to Viet Nam in ISPF partner countries. This is a request from BEIS to bring the data in line with official standards

(2726) Change Vietnam to Viet Nam

---

CHANGELOG.md

- Allow ISPF non-ODA partner countries on ODA activities
- Change "Vietnam" to "Viet Nam" in ISPF ODA partner countries
- Prefix the RODA identifiers of all non-ODA activities with "NODA-"

Release 128

---

app/views/reports_state/mark_qa_completed/complete.html.haml
config/locales/models/report.en.yml

As requested by BEIS:
- Update "Mark as completed" to "QA complete"
- Remove redundant final sentence on complete view (not relevant to audience)

(2810) Update QA complete text

---

CHANGELOG.md

Release 130

---

config/locales/models/activity.en.yml

Update label and hint for original comment figure form step.
|Before|After|
|--|--|
|<img width="628" alt="image" src="https://user-images.githubusercontent.com/47089130/224058976-01588f8d-73ac-4f72-8b55-50f1587ce79b.png">|<img width="649" alt="image" src="https://user-images.githubusercontent.com/47089130/224058830-987ab9a6-c648-4d1a-bd47-fa3ff7c953c5.png">|

(2856) Update label and hint for original comment figure form step

---

CHANGELOG.md

The recent change to the new user form was to remove the mobile number reset field, not a password reset field (there wasn't one)

Correct changelog entry

---

spec/features/users_can_edit_a_budget_spec.rb

This spec is flaky in CI.
I'm not sure why, but sometimes when time travelling, the user gets signed
out, and the next assertion fails.
This re-authenticates the user after time travelling. It also freezes the time
in the correct before block, as previously it was accidentally part of a different
context.

 Fix flaky time travel spec

---

CHANGELOG.md

- Fix changelog order (convention; dev experience)
- Tidy up (errors)
- Reformat headings and links (style)
You can view the updated changelog in GitHub style here: https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/blob/tidy-changelog/CHANGELOG.md
[...]
- [heh] Is a changelog entry required? An entry should always be made in `CHANGELOG.md`, unless this PR is a small tweak which has no impact outside the development team.

(2889) Tidy changelog

---

CHANGELOG.md
config/locales/models/activity.en.yml

- Add more information to the form guidance on the original commitment figure step

(2897) Add more guidance to the OCF step

---

doc/support_tasks/download_activities_for_annual_impact_metrics.md

Document activities download for annual impact metrics

(2894) Document activities download for annual impact metrics

---

CHANGELOG.md

- Add script to change incorrect receiving organisations for 9 actuals that had been incorrectly set on upload

Release 135 

---

CHANGELOG.md

Changelog updated for release 136 with:
- Add script to change incorrect partner organisation identifiers on 2 activities

release 136 

---

CHANGELOG.md

Release 137
- Add script to upload multiple budgets while bypassing report validation

Release 137

---

script/training_db_sync.rb

We currently use a script to periodically [sync production data to the training environment](https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/blob/develop/doc/support_tasks/training_db_sync.md) for DSIT testing. 
This script does not break when errors are thrown while running commands with Ruby module Open3.
This PR changes the error handling in the script to check for errors present in stderr. This allows us to capture any such errors, and raise an exception if any are present. If errors are present in stderr while capturing data from source; copying data; or loading data to the destination, the script will delete sessions and tempfiles before exiting.

Change error handling in CmdRunner to handle stderr errors

---

Gemfile
Gemfile.lock
doc/0_index_of_contents.md
doc/background-jobs.md

- Upgrade sidekiq to a non-vulnerable version
N/A

(2825) Upgrade sidekiq

---

CHANGELOG.md

- The IATI activity scope is calculated based on the benefitting countries and included in the IATI XML download as applicable
- The error summary is now shown correctly when adding new matched effort in the application
- The filenames for ISPF report CSVs now include the ODA type

Release 141

---

db/seeds/organisations.rb

The currency codes are all capitals, this incorrect seed value tripped
me up, so let's fix it.
https://trello.com/c/IcuVvsCV

Fix organisation currency seed value

---

app/services/export/continuing_activities.rb

- Add fund and programme info to export
- Order by RODA ID instead of status
N/A

Add fund and programme info to export

---

CHANGELOG.md

- Display the budgets headings as "Activity budgets" for level C and D activities on the Financials tab
- Model a financial value from a CSV file
- Add a new Activity tag, Strategic Allocation Pot (SAP), code 8
- Model a single row of CSV data that contains actual, refund and activity comments
- The new actual, refund and activity importer no longer accepts negative actual values
- Provide a CSV download of all activities that are likely to continue under DSIT and will need the new DSIT transparency identifier
- Add a service that can import a single row of CSV that contains either a Actual, Refund or Activity Comment
- When importing an Activity, Refund or Activity comment, the result can now be a row that was skipped
- Add a service that can import a single row of CSV that contains …

Release 142

---

CHANGELOG.md
app/views/activities/uploads/new.html.haml
app/views/level_b/activities/uploads/new.html.haml
spec/controllers/activities/uploads_controller_spec.rb
spec/controllers/level_b/activities/uploads_controller_spec.rb
spec/features/beis_users_can_upload_level_b_activities_spec.rb
spec/features/users_can_upload_activities_spec.rb

- Remove the feature flag for ODA bulk upload

(3014) Remove ODA bulk upload feature flag

---

CHANGELOG.md

- Configure rack-attack to prevent brute force login attacks

Release 145

---

CHANGELOG.md

- Add Rails script to update 100 PO IDs
- Remove Docker cache
- Update 'docker-compose' command to 'docker compose'

Release 147

---

CHANGELOG.md

- Adjust data migration to update 100 PO Org IDs

Release 148

---

CHANGELOG.md

- Rails version updated to 6.1.7.10

Release 149

---

CHANGELOG.md

- Separate out users into tabbed view of active and inactive

Release 150

---

CHANGELOG.md

Release 151

---

CHANGELOG.md

Release 152

---

README.md
doc/console-access.md
doc/deployment-process.md
doc/hosting.md
doc/logging.md

We've learnt lots about how the application is hosted and how to
interact with it, this starts to document what we have learnt.

Update documentation for hosting

---

README.md

Update the readme CI checks badge for the new CI workflow.

Update CI checks badge

---

README.md
doc/feature-flags.md

Document feature flags

---

CHANGELOG.md

Release 153

---

doc/background-jobs.md

Update the background jobs documentation.

Update background jobs docs

---

CHANGELOG.md

- Migration (and logic) to allow users to belong to multiple organisations
- Data migration to fix forecasts with incorrect providing organisation name

Release 155

---

CHANGELOG.md
app/views/report_mailer/_footer.text.erb
app/views/report_mailer/_submitted_partner_organisation.text.erb
app/views/report_mailer/activated.text.erb
app/views/report_mailer/awaiting_changes.text.erb
app/views/user_mailer/first_time_devise_reset_password_instructions.text.erb

Switching BEIS to DSIT in the mailer content.

Update mailer content

---

CHANGELOG.md

- Fixed: the welcome email is now sent to new users correctly
- Some instances of 'BEIS' have been replaced with 'DSIT'

Release 156

---

CHANGELOG.md

- Theme colour has changed from blue to a black
- The date and time a user is deactivated is now stored

Release 158

---

CHANGELOG.md

Release 159

---

CHANGELOG.md

- Admin interface to enable additional organisations

Release 160

---

CHANGELOG.md

- Split out deactivate/reactivate functionality into separate pages with confirmatory text
- Upgrade the remaining 11 config options to Rails 7.0 defaults

Release 161 changes

---

app/controllers/activities_controller.rb
app/services/activity/tab.rb
app/views/activities/children.html.haml
app/views/activities/comments.html.haml
app/views/activities/details.html.haml
app/views/activities/financials.html.haml
app/views/activities/historical_events.html.haml
app/views/activities/other_funding.html.haml
app/views/activities/transfers.html.haml
app/views/shared/activities/_tab_nav_item.html.haml
spec/views/shared/activities/tab_nav_item_spec.rb

Errors such as
```
DEPRECATION WARNING: Passing instance variables to `render` is
deprecated.
In Rails 7.1, @activities, @activity, @current_user, @implementing_organisation_presenters, and @tab_name will be ignored.
(called from block (2 levels) in show at /Users/russ/dev/roda/app/controllers/activities_controller.rb:52)
```
block us from going to Rails 7.1. 
Our offences are confined to places where we've used `Activity::Tab`.
This class sends a message to itself in order to set a list of
`@instance_variables` for the given tab. The `ActivitiesController` then
uses `Activity::Tab#locals` to copy a hash of all the instance variables
in the instance of the `Tab` with keys like
`{ :@tab_name => 'financials', :https://github.com/actuals => [...] }`
to the locals of the template that is …

3076 Clear Rails 7.1 deprecation warnings

---

CHANGELOG.md

- Fixed: users list view shows correct organisation after admin user has switched organisation

Release 162

---

CHANGELOG.md

- Add functionality to anonymise a user

Release 163

---

CHANGELOG.md
README.md

This fixes a few documentation formatting problems.

Minor documentation issues

---

doc/architecture/decisions/0039-anonymise-users-instead-of-deleting-them.md

This ADR describes the rationale behind our anonymisation (rather than deletion) of inactive users.

User anonymisation ADR

---

CHANGELOG.md

- Fix: duplicate countries allowed on import
- Export level B activities per fund (controlled by Rollout)

Release 164 changelog

---

CHANGELOG.md

- Upgrade Devise two factor gem from 4.x to 5.x

Release 165

---

CHANGELOG.md

- Fix Level B activities export organisation name

Release 167

---

CHANGELOG.md

- Upgrade to Rails 7.1 with 7.0 defaults

Release 168

---

CHANGELOG.md
app/services/export/activities_level_b.rb
spec/controllers/exports_controller_spec.rb
spec/features/beis_users_can_download_exports_spec.rb
spec/services/export/activities_level_b_spec.rb

Level B Exports: dynamic budget columns

---

CHANGELOG.md

- Fix IATI XML export countries where there is only one benefitting country
- Level B export dynamic budget columns

Release 170

---

CHANGELOG.md

- Show a warning when a user not from DSIT/ODA Management is being assigned to DSIT

Release 171

---

app/views/exports/index.html.haml
spec/features/beis_users_can_download_exports_spec.rb

Remove Rollout check for Level B exports functionality

---

CHANGELOG.md

- Upgrade to Rails 8.0.1
- Upgrade to Ruby 3.4.1

Release 173

---

CHANGELOG.md

- Fix a bug with deleting actuals

Release 176

---

CHANGELOG.md

- Update govuk-frontend from v3.11.0 to v5.11.0

Release 179

---

CHANGELOG.md

- Update KPI exporting rake task with new requirements

Release 181

---

CHANGELOG.md

Release 182
